### ISSUE TITLE
I cannot set the responseType in the HttpRequestConfig

### ISSUE THREAD

**Issue by blaart** [SAP/cloud-sdk-js#1000]
When using my internet destination, I want to use other response types than 'json' (for instance to retrieve an image). For now I cannot override this setting as it is no part of the HttpRequestConfig. It is however a setting in the AxiosRequestConfig...

I now need to do this:
    const axiosRequest = await buildAxiosRequestConfig({destinationName: destination, jwt: token}, config);
    axiosRequest.responseType = 'arraybuffer';
    const result = await axios.request(axiosRequest);

**Comment by marikaner** [comment]
Hey @blaart,

thank you for your feedback. We have recently talked about allowing this configuration as well. It is good to know, that there is an actual need for this. We will most probably implement this, but it might take a bit until we get to it. We would still have to discuss the API design on this.

Are you trying to use this in an OData client or are you using `executeHttpRequest` directly?

**Comment by blaart** [comment]
Hi @marikaner,

No problem, I have a workaround.. I'm using this with a direct http call/destination (not OData).

**Comment by FrankEssenberger** [comment]
I will close the issue since we have a backlog item to do this in the future and you can work around it currently.
