### ISSUE TITLE
start Workflow Instance from fiori Elements App via Event Handler

### ISSUE THREAD

**Issue by SnarkWay** [SAP/cloud-sdk-js#1017]
Dear all,

I am currently trying to call a workflow instance via an event handler js file within a fiori elements standard list report app in Business Appliaction Studio.
Therefore I have been following the approach below. Whenever an entity 'Books' was saved a new workflow instance 'test' which I created should be created/started --> screenshot 1
the destination with the URL API I have created manually in the destinations within my SCP cockpit -->  screenshot 2

screenshot 1
![call workflow instance](https://user-images.githubusercontent.com/15323595/108365208-3aa9cf00-71f7-11eb-834b-81bcb79bec78.JPG)

screenshot 2
![workflow destination](https://user-images.githubusercontent.com/15323595/108363323-1220d580-71f5-11eb-9327-5a62998d8e6b.JPG)

the package json file has been updated by the workflow destination
![package json](https://user-images.githubusercontent.com/15323595/108363351-1e0c9780-71f5-11eb-93f1-8a302a6190b8.JPG)

the error appearing once saving an entity of 'Books' is as follows:

![error](https://user-images.githubusercontent.com/15323595/108366313-81e48f80-71f8-11eb-8c2f-90f4830d5866.JPG)

Can you help out here? how do I call the workflow instances correctly?

Best Regards
Max

**Comment by jjtang1985** [comment]
Hi @SnarkWay ,

From the error message, I guess there might be some issue related to the `baseURL` configuration. However, I'm not the expert of the `@sap/cds-runtime` component (CAP).

Please find more information about CAP [here](https://cap.cloud.sap/docs/about/).
Please find the CAP support channel [here](https://cap.cloud.sap/docs/resources/).

I'm going to close this issue.
Please reopen in case you have further questions.

**Comment by artemkovalyov** [comment]
@SnarkWay, if you'd prefer having a library for Workflow API instead of implementing it yourself via CAP - we're going to release it by the end of this quarter. The error message you see is because CAP uses the SDK as a transitive dependency and most likely not causing your problem. With the planned SDK client calling Workflow service should be a relevantly easy feat.
