### ISSUE TITLE
Retrieve Backend Annotation

### ISSUE THREAD

**Issue by FlorianFechterTCon** [SAP/cloud-sdk-js#1024]
Hey SAP Cloud SDK Developer / Experts,

I would be happy to know if there is a simple way to read the annotations, we have defined in the SAP OnPremise backend, using the SAP Cloud SDK (JavaScript Version). So without having to build the queries ourselves. 
Unfortunately I could not find any information or examples online, and we would like to be able to reuse at least the labels we have created.
I am sorry if I missed the information within the documentation.

Best Regards 
Florian

**Comment by artemkovalyov** [comment]
Hi @FlorianFechterTCon,

You're always welcome with questions :) We're happy to help to the best of our knowledge!

For this one, can you explain a bit more what you mean by annotations?
A good example, specification, or code snippet would be the best way to make sure we share the same understanding of the problem/question. This helps us a lot with good answers.

P.S.: Our [latest docs are always here](https://sap.github.io/cloud-sdk/docs/js/getting-started) and we update them frequently with valuable info and answers to frequently asked questions.

**Comment by FrankEssenberger** [comment]
Hello @FlorianFechterTCon,

one quick update. In case the information is accessible via an OData API we have generated many clients already (All the ones you find on the API hub and you can download them via npm. If the API is not on the api hub you can generate the client easily on your own:

https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-odata-client

Best
Frank

**Comment by FlorianFechterTCon** [comment]
Hey guys,

thank you for your fast replies.
I meant the annotations that can be defined in the Abap classes like "...MPC_EXT" or in the CDS views. 
And which are then stored / delivered with the metadata.
Example:
`<edmx:Edmx xmlns:edmx="http://schemas.microsoft.com/ado/2007/06/edmx"
    xmlns:m="http://schemas.microsoft.com/ado/2007/08/dataservices/metadata"
    xmlns:sap="http://www.sap.com/Protocols/SAPData" Version="1.0">
    <edmx:Reference xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx"
        Uri="http://sap/opu/odata/IWFND/CATALOGSERVICE;v=2/Vocabularies(TechnicalName='%2FIWBEP%2FVOC_COMMON',Version='0001',SAP__Origin='LOCAL')/$value">
        <edmx:Include Namespace="com.sap.vocabularies.Common.v1" Alias="Common" />
    </edmx:Reference>
    <edmx:DataServices m:DataServiceVersion="2.0">
        <Schema xmlns="http://schemas.microsoft.com/ado/2008/09/edm" Namespace="CAT.API_PCQM_SRV" xml:lang="de"
            sap:schema-version="1">
            <EntityType Name="Operation" sap:content-version="1">
                <Key>
                    <PropertyRef Name="InspLotNumber" />
                    <PropertyRef Name="InspOperationNumber" />
                </Key>
                <Property Name="InspLotNumber" Type="Edm.String" Nullable="false" MaxLength="12" sap:unicode="false"
                    sap:label="Prüflos" sap:creatable="false" sap:updatable="false" />
                <Property Name="InspOperationNumber" Type="Edm.String" Nullable="false" MaxLength="4"
                    sap:unicode="false" sap:label="Vorgang" sap:creatable="false" sap:updatable="false" />
                <Property Name="Plant" Type="Edm.String" MaxLength="4" sap:unicode="false" sap:label="Werk"
                    sap:creatable="false" sap:updatable="false" />
                ...
            </EntityType>
            ...
            **<Annotations xmlns="http://docs.oasis-open.org/odata/ns/edm"
                Target="CAT.API_PCQM_SRV.Operation/InspLotNumber">
                <Annotation Term="Common.Heading" String="Inspection Lot" />
                <Annotation Term="Common.Label" String="Inspection Lot" />
            </Annotations>
            <Annotations xmlns="http://docs.oasis-open.org/odata/ns/edm"
                Target="CAT.API_PCQM_SRV.Operation/InspOperationNumber">
                <Annotation Term="Common.Heading" String="Oprn No" />
                <Annotation Term="Common.Label" String="Oprn No" />
            </Annotations>
            <Annotations xmlns="http://docs.oasis-open.org/odata/ns/edm" Target="CAT.API_PCQM_SRV.Operation/Plant">
                <Annotation Term="Common.Heading" String="Plant" />
                <Annotation Term="Common.Label" String="Plant" />
            </Annotations>**
            ...
        </Schema>
    </edmx:DataServices>
</edmx:Edmx>`
I took a look at the links you posted but I'm still not clear how I should / can access this information.
After generating and using the OData Client, is there a special API like "getAnnotations" or "getAnnotationsForEntitySet".
E.g. in order to set Column Labels or things like that.

From UI5 I remember that you can simply execute "getProperty" with a certain syntax and get information like this.
"{Category/##com.sap.vocabularies.Common.v1.Label/String}" (https://blogs.sap.com/2018/07/24/how-to-leverage-vocabulary-based-annotations-in-sapui5-applications/)

Thank you for your patience.

Best Regards
Florian

**Comment by FrankEssenberger** [comment]
Hi Florian,

now I got what you mean. So the annotations are part of the service metatdate (.edmx) file. I see a lot of them in the spec files :-).  Unfortunately we do not consider them in the parsing process so in the client the information is gone. 
So this is of course bad news for you, but I would like to collect some more information, because we are always happy to include feature if we know there is customer demand.

So if I read the example right, you have an `Operation` entity type with three properties where one of them is `InspLotNumber` which has two annotations:

```
 <Annotation Term="Common.Heading" String="Inspection Lot" />
  <Annotation Term="Common.Label" String="Inspection Lot" />
```

For you it would be nice if the generated client would have something like: `Operation.InspLotNumber.getAnnotation()` which would return some list of key value mapping of the two annotations above.

Right?

Best
Frank

**Comment by FlorianFechterTCon** [comment]
Hey @FrankEssenberger,

I had thought of something like that, yes.
But I can also imagine very well that the annotations can change more often. Therefore it would be quite good if they are always loaded dynamically.  But I can understand that we have more possibilities with the "Generic OData client" at this point.

Thank you for the response and I would be very happy if we have a standard solution for this problem in the future.

Best Regards
Florian

**Comment by FrankEssenberger** [comment]
Since we generate the clients for each release in other words new metadata file I guess we could stay up to date. Also you can always regenerate the client manually if needed. I will create a back log item for this. I do not know how fast this will be supported but if more user request it, it will get quicker.

**Comment by FrankEssenberger** [comment]
> always loaded dynamically. But I can understand that we have more possibilities with the "Generic OData client" at this point.

What do you mean by generic OData client?

**Comment by nexzgg** [comment]
@FrankEssenberger,
i think he means that https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client but for JavaScript.

**Comment by nexzgg** [comment]
And, i would also be very enthusiastic about a standard solution for reading annotations :)

**Comment by FrankEssenberger** [comment]
ah ok. So I will create a backlog item with a first task to create a ADR for the potential API. I will link this issue and it would be great if you could give some feedback if the ideas we have go in the right direction and bring you the value and functionality you need.

**Comment by FrankEssenberger** [comment]
I created the item and we will involve you in the next steps. Since we are currently focussing on other topics it could take a while until we can tackle this feature.
