### ISSUE TITLE
Double URL encoding in batch request

### ISSUE THREAD

**Issue by ja-ne** [SAP/cloud-sdk-js#1129]
Hello sap/cloud-sdk-js,

**Describe the bug**
A GET request wrapped in a batch request seems to be URL encoded twice.

**To Reproduce**
1. Perform a batch request containing a GET request which filters for a text containing a character that needs URL encoding, for example a whitespace.
2. Given an entity exists that matches the filter it is not found.

**Expected behavior**
The entity is found.

**Used Versions:**
 - node version 14.15.4
 - npm version 6.14.10
 - SAP Cloud SDK version 1.39.0

**Code Examples**
```
const destination = getDestinationFromSomewhere();
const request = Entity.requestBuilder()
	.getAll()
	.filter(Entity.SOMEPROPERTY.equals('Hello World'));
const result = await batch(request).execute(destination);
```

This is the payload which gets generated for the batch request:
```
--batch_<id>
Content-Type: application/http
Content-Transfer-Encoding: binary

GET /sap/opu/odata/sap/SERVICENAME/Entity?$format=json&$filter=(SomeProperty eq 'Hello%2520World') HTTP/1.1
Content-Type: application/json
Accept: application/json


--batch_<id>
```
The whitespace in 'Hello World' is URL encoded twice.

Could you please have a look at this?

Thanks in advance.

**Comment by jjtang1985** [comment]
Hi @ja-ne ,

Thanks for reporting.
I can reproduce the same issue.

I created a backlog item and will let you know the updates.

Best regards,
Junjie

**Comment by ja-ne** [comment]
Hi @jjtang1985,
thanks for your support.

**Comment by artemkovalyov** [comment]
Hi @ja-ne, what's the urgency on your side so that we can prioritize the fix. cc @jjtang1985 @FrankEssenberger

**Comment by ja-ne** [comment]
Hi @artemkovalyov,

it causes a bug for which a workaround would be some implementation effort but not impossible. I'd place it between https://github.com/SAP/cloud-sdk-js/issues/1102 (highest prio) and https://github.com/SAP/cloud-sdk-js/issues/1055 (lowest prio).

**Comment by FrankEssenberger** [comment]
Hello @ja-ne,

we made a fix for the issue. Should be solved so I am closing the issue. Will be released in 1.41.0 or already in the canary version.

Best
Frank

**Comment by jjtang1985** [comment]
The [1.41.0](https://github.com/SAP/cloud-sdk-js/releases/tag/v1.41.0) is available.

**Comment by ja-ne** [comment]
Thanks for the fix. I was now able to test it and it works as expected, sorry for the delay. But it may be related to another problem: https://github.com/SAP/cloud-sdk-js/issues/1226
