### ISSUE TITLE
OnPrem Connectivity Error

### ISSUE THREAD

**Issue by FrankEssenberger** [SAP/cloud-sdk-js#1198]
A customer gets a 401 when trying to connect to an onPrem system using the SDK:

https://itsm.services.sap/now/workspace/agent/record/sn_customerservice_case/397a4434db27ac90de430a9bd39619de

**Comment by FrankEssenberger** [comment]
We have to adjust our log statements. The customers get confused especially by:
- Could not receive destination from service binding.
- Unable to match a specific XSUAA service instance to the given JWT. The following XSUAA instances are bound: na-8b149770-5dee-4c73-9f05-e7a8e7e71dc8!t23499. The following one will be selected: na-8b149770-5dee-4c73-9f05-e7a8e7e71dc8!t23499. This might produce errors in other parts of the system!
- Unable to create \"SAP-Connectivity-Authentication\" header: no JWT found on the current request.\n    Continuing without header. Connecting to on-premise systems
may not be possible."," -> If you are basic this is not critical

**Comment by gregorwolf** [comment]
Seems that I can replicate exactly the same issue with my sample project [](https://github.com/gregorwolf/HTML5UserAPIforCF/) where I've implemented a call to the /sap/bc/ping and /sap/public/ping service in [srv/express.js#L52](https://github.com/gregorwolf/HTML5UserAPIforCF/blob/main/srv/express.js#L52). The output is:

> Failed to build HTTP request for destination: failed to build headers! Root Cause: Principal propagation was selected in destination, but no SAP-Connectivity-Authentication bearer header was added by connectivity service.

Using exactly the same destination via the proxy created by the approuter  in [approuter/xs-app.json#L28](https://github.com/gregorwolf/HTML5UserAPIforCF/blob/main/approuter/xs-app.json#L28) works just fine. I hope that this issue is solved quickly.

**Comment by jjtang1985** [comment]
Hi @FrankEssenberger , as the original author has not replied for long time, perhaps we can continue the discussion with Gregor here.

**Comment by gregorwolf** [comment]
Hi @jjtang1985 ,

I was just able to fix my issue. I provided ony the Destination. Now I've changed my code in [srv/express.js#L17](https://github.com/gregorwolf/HTML5UserAPIforCF/blob/main/srv/express.js#L17) to provide [DestinationNameAndJwt](https://sap.github.io/cloud-sdk/api/1.41.0/interfaces/sap_cloud_sdk_core.destinationnameandjwt). Maybe that can help also the customer from @FrankEssenberger with the simmilar issue?

Best Regards
Gregor

**Comment by jjtang1985** [comment]
Hi @gregorwolf ,

thanks for sharing your fix, which should help all the OnPrem users.

Indeed, without providing JWT, it won't work as the error says `Unable to create "SAP-Connectivity-Authentication" header: no JWT found on the current request`.

Best regards,
Junjie

**Comment by FrankEssenberger** [comment]
Also from my side thanks at @gregorwolf .

I asked the customer, how he executed the call: via destination or JWT, what was the auth type (because for basic it would of cause work without a JWT, because no users needs to be propagated). Since I did not get any response for almost two month I close this issue.
