### ISSUE TITLE
Could not set destination context: Invalid URL with double url

### ISSUE THREAD

**Issue by blaart** [SAP/cloud-sdk-js#1225]
Hi I'm facing the following error in our production system:
Could not set destination context: Invalid URL: http://api-contentserver:443http://api-contentserver:443/cs/llisapi.dll/api/v1/auth

It is not consequent so sometimes it works, sometimes not. It concerns an Onpremise destination with BA. Note the double mentioned url here. 

we are using v1.37.0 there, so my question is: is this probably a sdk issue (which maybe fixed in newer version) or should I look somewhere else?

**Comment by FrankEssenberger** [comment]
Hello blaart,

sorry to hear that you have an issue in a productive environment. So from an SDK side we never make calls to a `api-contentserver` with this `dll` in the path. Also we have not touched the destination related modules in the last releases to fix something. At which point in the stack does this error appear?

My initial guess would be that this is a response from the destination-service which tries to resolve some auth flow and fails. This would also explain why it works sometimes (destination service ok) and sometimes it fails.  What is the authorization type of the destination? If you switch to some simple thing like basic auth does the error disappear? If so this would be a clear indication that it is the destination service.

Best
Frank

**Comment by blaart** [comment]
Hi Frank, thanks for your swift response. 
The api-contentserver is the url that is configured in the destination. As I cannot reproduce this in a test environment it is hard to say where in the stack this takes place. I'm using Basic Auth as auth type. But I was also thinking of the destination service maybe going wrong somewhere. Not sure, will dive deeper into this. Thanks.

**Comment by FrankEssenberger** [comment]
Ah ok, I thought a bit if we manipulate the URL received from the service. But we actually just [parse the destination](https://github.com/SAP/cloud-sdk-js/blob/37209ba61c5bc5af8cf3c952b9b2e325fb39afc1/packages/core/src/connectivity/scp-cf/destination/destination.ts#L38).

So I think the SDK is not changing this but it is the service providing this as a response. You could use the [fetchDestinations](https://github.com/SAP/cloud-sdk-js/blob/37209ba61c5bc5af8cf3c952b9b2e325fb39afc1/packages/core/src/connectivity/scp-cf/destination/destination-service.ts#L68) method directly as a test in your code and log, what is returned by the service and see what is in the URL field.

I hope you can sort out the this flaky issue.

**Comment by blaart** [comment]
Never mind this, we use an apm module for elastic logging. The logging of that module fooled us.
