### ISSUE TITLE
Split `@sap-cloud-sdk/core`

### ISSUE THREAD

**Issue by jjtang1985** [SAP/cloud-sdk-js#1242]
We received some feedbacks from email about the size of the dependency  `@sap-cloud-sdk/core`.
Some users use `executeHttpRequest` and do not need e.g, the type-safe client related functionalities from the `@sap-cloud-sdk/core`.
In addition, most likely, users do not need both OData version 2 and OData version 4 support.
Therefore, we might consider splitting the core package into multiple packages for different use cases.

**Comment by florian-richter** [comment]
This was completed with the release of version 2 of the SAP Cloud SDK
