### ISSUE TITLE
Support on "OAuth2JWTBearer" Authentication

### ISSUE THREAD

**Issue by shumagundam** [SAP/cloud-sdk-js#1245]
Hi,

I am having a similar issue as the post describe below:
https://answers.sap.com/questions/13195320/unable-to-call-external-service-sap-workflow-servi.html?childToView=13192516#answer-13192516

My main question: 
Is the cloud sdk currently able to handle authentication automatically or do we still need to rely on axios or other third-party nodejs module to connect to workflow serivce?

My Errors:
When I deployed my project to the cloud foundry, I am getting this error message below
<img width="576" alt="Screen Shot 2021-04-27 at 7 17 01 AM" src="https://user-images.githubusercontent.com/13772323/116232788-937e7200-a728-11eb-8a0e-f5c6cc93e749.png">

Below are my files:
cat-services.js
"<img width="495" alt="Screen Shot 2021-04-27 at 7 18 58 AM" src="https://user-images.githubusercontent.com/13772323/116233048-d8a2a400-a728-11eb-8f5d-122c3c8ab0e0.png">"

<img width="625" alt="Screen Shot 2021-04-27 at 7 20 49 AM" src="https://user-images.githubusercontent.com/13772323/116233293-1c95a900-a729-11eb-9b05-a47ed4c958ba.png">

<img width="1285" alt="Screen Shot 2021-04-27 at 7 25 13 AM" src="https://user-images.githubusercontent.com/13772323/116233764-b8271980-a729-11eb-9590-7fd95f9d092d.png">

**Comment by artemkovalyov** [comment]
Hi @shumagundam,

`cds.connect.to('workflow_trial')` doesn't look like Cloud SDK to me but instead more like CAP.

The good news is we're releasing a type-safe client for OpenAPI services this or coming week. It's going to be integrated with our Connectivity feature which means you'll have auth working out of the box.

We'll also release a certified client library for the SAP Workflow which would be available on NPM. I'll ask colleagues if we can give you a canary version to try it out.

@FrankEssenberger @jjtang1985, from your experience, can auth be simplified in the example below? Or should we wait for a released client?

**Comment by jjtang1985** [comment]
Hi @shumagundam ,

Unfortunately, the `OAuth2JWTBearer` auth type is not supported by the SAP Cloud SDK for the time being. (@artemkovalyov )
Would it be ok to switch to some other auth types?
Here is a list of [supported authentication type](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#authentication-and-json-web-token-retrieval) when using the SDK.

Let's assume you can switch to some other supported auth type, then you can use our type-safe client, which will handle the authentication flow under the hood.

Having a certified client library is nice, which is pre-generated and released by SAP to reduce your effort of the the generation.
As this might take a while (we plan to release the client in May, which is not guaranteed), I recommend you can generate your own client for now.
Here is the [document](https://sap.github.io/cloud-sdk/docs/js/features/openapi/generate-openapi-client) about the generation. Please use the `canary` version of the generator and be aware, currently the generator is still under beta version and the GA will be released soon.
When you successfully generate your own type-safe client, here is the [document](https://sap.github.io/cloud-sdk/docs/js/features/openapi/execute-openapi-request) about how should you execute a request.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
@shumagundam 

if you have to use the auth type `OAuth2JWTBearer`, could you please create a separate ticket as a [feature request](https://github.com/SAP/cloud-sdk-js/issues/new/choose)?

**Comment by FrankEssenberger** [comment]
Just for the colleague who will work on this. Here is thw point where a additional block is needed: 
https://github.com/SAP/cloud-sdk-js/blob/9636132d149b16b866042c9b136e336820bd2ba0/packages/core/src/connectivity/scp-cf/destination/destination-from-service.ts#L101
I have not looked into the `OAuth2JWTBearer` flow but I would assume that the destination service should do all the work and potentially it would already work if you call the `addOAuthSamlAuth` method also for the `JWTBearer` case. The important this is anyhow not the implementation which is small but to properly include the flow in our E2E tests.

**Comment by shumagundam** [comment]
Hi all,

Thanks for the sending me the documentation and recommendation. I think we can switch to different types of authentication.

Regarding the type-safe client, it looks like there is a JAVA version.  https://sap.github.io/cloud-sdk/docs/java/features/rest/clients/scp-workflow-rest-api/ Can you confirm?

Regards,
Jonas

From: Junjie Tang ***@***.***>
Reply-To: SAP/cloud-sdk-js ***@***.***>
Date: Wednesday, April 28, 2021 at 3:07 AM
To: SAP/cloud-sdk-js ***@***.***>
Cc: "Wang, Jonas" ***@***.***>, Mention ***@***.***>
Subject: Re: [SAP/cloud-sdk-js] Support on "OAuth2JWTBearer" Authentication (#1245)


Hi @shumagundam<https://github.com/shumagundam> ,

Unfortunately, the OAuth2JWTBearer auth type is not supported by the SAP Cloud SDK for the time being. ***@***.***<https://github.com/artemkovalyov> )
Would it be ok to switch to some other auth types?
Here is a list of supported authentication type<https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#authentication-and-json-web-token-retrieval> when using the SDK.

Let's assume you can switch to some other supported auth type, then you can use our type-safe client, which will handle the authentication flow under the hood.

Having a certified client library is nice, which is pre-generated and released by SAP to reduce your effort of the the generation.
As this might take a while (we plan to release the client in May, which is not guaranteed), I recommend you can generate your own client for now.
Here is the document<https://sap.github.io/cloud-sdk/docs/js/features/openapi/generate-openapi-client> about the generation. Please use the canary version of the generator and be aware, currently the generator is still under beta version and the GA will be released soon.
When you successfully generate your own type-safe client, here is the document<https://sap.github.io/cloud-sdk/docs/js/features/openapi/execute-openapi-request> about how should you execute a request.

Best regards,
Junjie

**Comment by artemkovalyov** [comment]
@shumagundam , yes, we have a Java client released already. YOu can try it out if you want. Soon there will be a JS client as well. I believe in 2-3 weeks or so.

**Comment by jjtang1985** [comment]
Hi @shumagundam ,

we have released [1.47.0](https://github.com/SAP/cloud-sdk-js/releases/tag/v1.47.0), that contains the new feature about this auth type.

I'll close this ticket and please reopen if you have questions.

BR,
Junjie
