### ISSUE TITLE
Describe differences to @sap_oss/odata-library?

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk-js#1298]
Hello SAP Cloud SDK Team,

today I've discovered the [@sap_oss/odata-library](https://github.com/SAP/odata-library) project and filed the issue [How is this project related to SAP Cloud SDK for JavaScript? #31](https://github.com/SAP/odata-library/issues/31). Maybe someone from the team should also add their thoughs. And maybe it would be worth mentioning somewhere the differences between the projects. Maybe @mnezerka can join this discussion to do the same on the side of @sap_oss/odata-library.

Best Regards
Gregor

**Comment by marikaner** [comment]
Hey @gregorwolf,

thank you for pointing that out. We were in contact with the colleagues some time ago when the OData library was still an internal project.

There are a few key differences between the SAP Cloud SDK and the OData library:
* As @mnezerka pointed out, the OData library operates dynamically on the metadata file of a service and creates on an on-the-fly client. The SDK generates a file-based client from the metadata file and does not use it at runtime.
* The clients generated by the SDK are typed (TypeScript), while the on-the-fly clients of the OData library are written in JavaScript.
* The SDK clients can handle requests against any URL, while the API was designed with the intention to build applications on SAP BTP leveraging the concept of [destinations](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination).  With the OData library, you have more control over the requests that are made, but you have to take care of connectivity and authentication / authorization on your own.

I hope that completes the picture. We will take this up into our documentation as well.

**Comment by marikaner** [comment]
Hey Gregor, better late than never - we now added a note to our [official documentation](https://sap.github.io/cloud-sdk/docs/js/overview-cloud-sdk-for-javascript#difference-to-sap-odata-library). Thanks again for pointing that out.

**Comment by gregorwolf** [comment]
LGTM
