### ISSUE TITLE
Add functionality to override HTTP method (for OData update requests)

### ISSUE THREAD

**Issue by lennart-m** [SAP/cloud-sdk-js#1323]
Hi!

I use the cloud SDK to read/write data in SAP SuccessFactors.

---

**Is your feature request related to a problem? Please describe.**
I have a problem updating entities using MERGE/PATCH. The remote system does not seem to accept HTTP PATCH, and HTTP MERGE does not work in Node.js / in the Cloud SDK as this is not a valid method. The remote system also does not support MERGE inside a batch request.
It seems I cannot modify an entity other than replacing it (using HTTP PUT via `UpdateRequestBuilder.replaceWholeEntityWithPut`)

**Describe the solution you'd like**
It would be great if it were possible to manually override the HTTP method using a `setCustomHttpMethod` method on the request builder. In my case I found that the remote system supports POSTing to a single entity (addressed via key), and setting the header `X-Http-Method` to the desired HTTP method (full example below).

A new method `setCustomHttpMethod`, in combination with the already existing method `MethodRequestBuilder.addCustomHeaders` would give me full control to tell the system how to interpret my request.

**Describe alternatives you've considered**
I can't really come up with a better solution :-)

**Additional context**
This is a working HTTP request to the remote system:
```http
POST https://mysystem/odata/v2/cust_request('999')
Accept: application/json
Content-Type: application/json
X-Http-Method: MERGE

{
    "cust_Status": "APPROVED"
}
```
Usually the POST to an addressed entity would not be supported. But together with the HTTP header setting the method to MERGE, this is request that gets properly handled.

---

Thanks a lot!

Lennart

**Comment by jjtang1985** [comment]
Hi @lennart-m ,

could you please take a look at my questions?

Thank you.

**Comment by lennart-m** [comment]
Hi Junjie,

Sorry for the delayed reply.

You understood my request correctly.

I don't have a fixed time line for this request. I am currently working on an application that will probably go live within a few months but for now it's okay for me to be able to replace entities via PUT.
However, PUT is semantically not really the correct method, so it would be more fitting to PATCH/MERGE.

This change would also be of great help for future applications that consume external OData services that don't support PATCH, e.g. SAP SuccessFactors.

Sincerely,

Lennart

**Comment by jjtang1985** [comment]
Hi @lennart-m ,

thanks for answering my questions.
For SuccessFactors, we definitely need to work on it so you don't have to use `PUT`, the backlog item is created.

@artem-smotrakov , FYI.

Best regards,
Junjie

**Comment by lennart-m** [comment]
Hi @jjtang1985 

Can you estimate when this issue might be fixed? There is no high urgency but during the last months I found that not being able to properly `PATCH` data in SuccessFactors does require quite a lot of extra work; all entities need to be read before they can be updated, resulting in extra traffic and reduced performance as all fields always have to be transmitted.

Do you accept community contributions? I don't want to promise anything but I might try to approach this issue myself if I find some spare time.

Thanks a lot,

Lennart

**Comment by jjtang1985** [comment]
Hi @lennart-m , 

Thank you for updating.

With the current 2.0 development, I'm afraid we will not touch it for this quarter.
Please let me know if the urgency is changed so we can re-prioritize it.
@artemkovalyov 

>Do you accept community contributions?

Sure, this is more than welcome. Please feel free to do so.

Best regards,
Junjie

**Comment by ZhongpinWang** [comment]
Hi @lennart-m ,

We implemented the overwrite behaviour and merged it in the last week. The canary versions for `[@sap-cloud-sdk/odata-common](https://www.npmjs.com/package/@sap-cloud-sdk/odata-common)`, [@sap-cloud-sdk/http-client](https://www.npmjs.com/package/@sap-cloud-sdk/http-client) and [@sap-cloud-sdk/openapi](https://www.npmjs.com/package/@sap-cloud-sdk/openapi) are published. We will release the new version soon as well.

A simple example could be:

```typescript
const { myEntityApi } = myEntityService();
myEntityApi
  .requestBuilder()
  .getAll()
  .addCustomRequestConfiguration({ method: 'YOUR-METHOD' });
```

In this case, the default http method `GET` will be overwritten by `YOUR-METHOD`. Feel free to try it out.

If you find any problems or have any questions regarding this issue, please re-open the issue and let us know. Thank you.

Best regards,
Zhongpin
