### ISSUE TITLE
Is adding support to send mail via an (OnPremise) SMTP destination in the scope of the Cloud SDK?

### ISSUE THREAD

**Issue by gregorwolf** [SAP/cloud-sdk-js#1372]
Hello SAP Cloud SDK Team,

in the blogpost [Connect to an On Premise Mail Server from SAP BTP Cloud Foundry](https://blogs.sap.com/2021/05/07/connect-to-an-on-premise-mail-server-from-sap-btp-cloud-foundry/) 
[Niklas Miroll](https://people.sap.com/miroll) / @niklas1375 describes how he used Java to send an E-Mail via an On Premise Mail Server. He also described the issues that he faced using Node.JS. 

My question is now is adding support to send mail via an (OnPremise) SMTP destination in the scope of the Cloud SDK?

If not I would go ahead and try to enhance the [sap-cf-mailer](https://github.com/jowavp/sap-cf-mailer/) project.

Best regards
Gregor

**Comment by artemkovalyov** [comment]
Hi @gregorwolf,

Thanks for a good question.

It's really an edgy topic and with the current plans, it would hardly make it to the SDK if there's no huge demand for it. I noted to check this in more details but I think enhancing `sap-cf-mailer` is the way to go for now

I'll be closing this if you have any other questions feel free to re-open an issue or create a new one.

**Comment by gregorwolf** [comment]
Interresting to read in [The Advent of SAP Cloud SDK for JavaScript Version 3](https://blogs.sap.com/2022/12/12/the-advent-of-sap-cloud-sdk-for-javascript-version-3/) that already in the Cloud SDK for JavaScript v2 the mail feature is experimental and will become productive with v3.
