### ISSUE TITLE
SlsPrcgConditionRecord.builder().fromJson(jsonObj)

### ISSUE THREAD

**Issue by MykillZ** [SAP/cloud-sdk-js#1440]
**Describe the bug**

When a json object should be converted to a sdk entity we get following error.
`momentInstance.unix is not a function` .

**Expected behavior**
An object with javascript Date type should be converted by `SlsPrcgConditionRecord.builder().fromJson(jsonObj)` to a `moment` type.

**Used Versions:**
@sap/cds: 5.3.1
@sap/cds-compiler: 2.4.4
@sap/cds-dk: 4.3.1
@sap/cds-foss: 2.3.1
@sap/cds-odata-v2-adapter-proxy: 1.7.6
@sap/cloud-sdk-op-vdm-business-partner-service: 1.26.0
@sap/cloud-sdk-op-vdm-sales-pricing-condition-record-service: 1.26.0
@sap/cloud-sdk-op-vdm-sales-pricing-condition-type-service: 1.26.0
@sap/hana-client: 2.9.23
Node.js: v14.17.3

**Comment by jjtang1985** [comment]
Hi @MykillZ ,

thanks for approaching us.

Could you please provide an example of the `jsonObj` mentioned, so one can reproduce the same error?

Best regards,
Junjie

**Comment by MykillZ** [comment]
As written in the following test https://github.com/SAP/cloud-sdk-js/blob/7e581600c4759b738abc53b4019e53cc8dce80db/packages/core/src/odata-common/entity-builder.spec.ts#L44 . The function expects dates of the type moment. 

Maybe a text about the supported complex type in this section might help. 

https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v2-type-safe-client-for-javascript-typescript#build-an-entity-from-a-json-representation
