### ISSUE TITLE
Dash in HTTP_PROXY host breaks proxy configuration

### ISSUE THREAD

**Issue by johenning** [SAP/cloud-sdk-js#1464]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `@sap-cloud-sdk/core@1.47.0` for the project I'm working on.

When setting `HTTP_PROXY` or `HTTPS_PROXY` to e.g. `http://service-name:8080`, the dash is not considered part of the host, but instead lands inside the `port`. Effectively deactivating the proxy configuration entirely.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/proxy-util.js b/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/proxy-util.js
index 67a6f98..d01d8d7 100644
--- a/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/proxy-util.js
+++ b/node_modules/@sap-cloud-sdk/core/dist/connectivity/scp-cf/proxy-util.js
@@ -151,7 +151,7 @@ var addHost = function (groups) { return function (proxyConfiguration) {
  * @returns Configuration with default values or undefined if the parsing failed.
  */
 function parseProxyEnv(proxyEnvValue) {
-    var regex = /(?<protocolWithDelimiter>(?<protocol>^.+):\/\/)?(?<userPwdWithDelimeter>(?<user>.+):(?<pwd>.+)@)?(?<hostAndPort>(?<host>[\w.]+):?(?<port>.+)?)/;
+    var regex = /(?<protocolWithDelimiter>(?<protocol>^.+):\/\/)?(?<userPwdWithDelimeter>(?<user>.+):(?<pwd>.+)@)?(?<hostAndPort>(?<host>[\w.-]+):?(?<port>.+)?)/;
     var parsed = regex.exec(proxyEnvValue);
     if (parsed === null || parsed === void 0 ? void 0 : parsed.groups) {
         var groups = parsed.groups;
```

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

**Comment by marikaner** [comment]
Hey @johenning,

thank you for letting us know. We will fix this as soon as possible!

**Comment by marikaner** [comment]
I fixed this on a PR. The fix will be published with the next release.

**Comment by FrankEssenberger** [comment]
@johenning thanks for always investigating and identifying the issue.
