### ISSUE TITLE
Empty space in join method causes wrong filter query generation

### ISSUE THREAD

**Issue by cezaryrk** [SAP/cloud-sdk-js#1485]
Line: 
https://github.com/SAP/cloud-sdk-js/blob/7e581600c4759b738abc53b4019e53cc8dce80db/packages/core/src/odata-common/uri-conversion/get-filter.ts#L190

Example Code:
```
StudyModule
      .requestBuilder()
      .getAll()
      .filter(filterFunctions.startsWith(StudyModule.CODE, 'M_'))
...
```
Generates the following filter query, which is wrong:
```
http://localhost:4200/StudyModule?$format=json&$filter=(startswith(Code%2C%20%27M_%27))
```
and causes the following error message:
```
{
"error": {
"code": "400",
"message": "Expected a uri token of kinds 'QualifiedName, ODataIdentifier' in '(startswith(Code, 'M_'))' at position 18"
}
}
```

The correct request should be (without the space as %20):
```
http://localhost:4200/StudyModule?$format=json&$filter=(startswith(Code%2C%27M_%27))
```

**Comment by florian-richter** [comment]
Hi @cezaryrk 

Thanks for opening this issue and providing a fix. Would you like to open a pull request (given credit directly to you) or should I replicate the fix in a local branch?

Please let me know until tomorrow, otherwise I will go with the local branch so we can roll out a fix ASAP.

Best regards
Florian

**Comment by cezaryrk** [comment]
Hi Florian, 

I will provide a pull request ASAP.

Best regards
Robert Kania from TU Berlin ;)

**Comment by florian-richter** [comment]
@cezaryrk are you using ODATAv4 or v2? Can you share what library you are using as your ODATA backend?

I checked the [ODATAv2 spec](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/) (search for `4.5. Filter System Query Option ($filter)`) and the examples all show a space. In [ODATAv4](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#_Toc31360986) it is shown without spaces.

Neither spec seems to require the use or lack of a space, so your PR should not introduce breaking changes for anyone and hopefully fix your specific case.

**Comment by cezaryrk** [comment]
Thx, we using the OData V4 specification, which for development is providen by the default startup of CDS Services by calling
"npx cds watch src/service". 

like in the documentation https://cap.cloud.sap/docs/node.js/cds-serve
