### ISSUE TITLE
Build error happened with @sap-cloud-sdk/core@1.48.0

### ISSUE THREAD

**Issue by zjhua2002** [SAP/cloud-sdk-js#1536]
Hello Colleagues,

The [baf-date-time releasev13 pipelines](https://gkex4.jaas-gcp.cloud.sap.corp/job/baf-date-and-time/job/releasev13/110/console) are failed : Build error happened with @sap-cloud-sdk/core@1.48.0(refer to log info section below).

Could you Please help to fix the issue?

**To Reproduce**

1. Set up in local machine
git clone git@github.wdf.sap.corp:BIG/baf-date-and-time.git
2. Execute
npm install
npm run build
3. See error

**Expected behavior**
build successfully without errors. Previously we can build successfully with @sap-cloud-sdk/core@1.31.0

**Screenshots**
n/a

**Used Versions:**
$ node -v
v14.16.0
- node version via `node -v`
- npm version via `npm -v`
- SAP Cloud SDK version you used as dependency
1.48.0

**Code Examples**
n/a

**Log file**
08:15:05  node_modules/@sap-cloud-sdk/core/dist/odata-common/selectable/enum-field.d.ts(51,50): error TS1110: Type expected.
08:15:05  npm ERR! code ELIFECYCLE
08:15:05  npm ERR! errno 2
08:15:05  npm ERR! @sap/baf-date-and-time@13.3.7 build: `tsc`
08:15:05  npm ERR! Exit status 2
08:15:05  npm ERR! 
08:15:05  npm ERR! Failed at the @sap/baf-date-and-time@13.3.7 build script.
08:15:05  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
08:15:05  
08:15:05  npm ERR! A complete log of this run can be found in:
08:15:05  npm ERR!     /home/node/.npm/_logs/2021-08-23T02_45_04_202Z-debug.log

**Additional context**
n/a

**Comment by FrankEssenberger** [comment]
Hi @zjhua2002,

since we just released version 1.48.0 I wonder if this brought in the error. Could you perhaps fix the SDK version to the previous release and check if the error persists? This would help cornering the root cause.

Best
Frank

**Comment by jjtang1985** [comment]
Hi @zjhua2002 ,

I guess this error `error TS1110: Type expected` occurs typically because of an old `typescript` version.
Could you please try version `4.1.5` or newer version of `typescript` and see whether this will fix the issue?

Best regards,
Junjie

**Comment by zjhua2002** [comment]
Hello @jjtang1985 

Thanks for your tips. After I changed my typescript to higher version, now it works fine now. Thanks.

Best regards,
Peyton Zhong
