### ISSUE TITLE
oData v2 Client orderBy Escaping Issue

### ISSUE THREAD

**Issue by schw4be** [SAP/cloud-sdk-js#1575]
Hi there,

a simple oData v2 Call with orderby runs in the following error:

`TypeError [ERR_UNESCAPED_CHARACTERS]: Request path contains unescaped characters
    at new ClientRequest (_http_client.js:151:13)
    at Object.request (https.js:313:10)`

This is the sample code:

`        return await MyEntity.requestBuilder().getAll().filter(MyEntity.Field.equals(someValue)
        ).orderBy(desc(MyEntity.ID)).top(1).execute({
            url: api_url,
            username: api_user,
            password: api_pwd,
        });
    }`

The build URI looks like this:
`odata/v2/MyEntity/MyEntity?$format=json&$filter=(Field%20eq%20'VALUE')&$orderby=Id desc&$top=1
`
SDK Version used: 1.48.1

I think the unescaped "**id desc**" causes the issue.

**Comment by jjtang1985** [comment]
Hi @schw4be ,

thanks for reaching out.

I can reproduce the issue and we will work on it soon.

Thank you.

**Comment by jjtang1985** [comment]
Hi @schw4be ,

I fixed the encoding bug.
Please try `canary` version and let me know whether it solves your issue.

Thank you.

**Comment by schw4be** [comment]
Hey @jjtang1985,
looks good! Thank you very much for the quick fix :)
Greetings
