### ISSUE TITLE
Guidance on CloudSDK Caching of Destination Service Requests using SAP CAP

### ISSUE THREAD

**Issue by JohannesRu** [SAP/cloud-sdk-js#1584]
Hello colleagues,

We are part of SAP Graph - using the CAP framework [https://cap.cloud.sap/docs/node.js/] as the main framework for our app.
CAP uses the CloudSDK under the hood. The setup is working great for us so far.

We are testing our solution now against higher work load. Our app is doing well, however, Destination service is refusing to talk to us with increasing load. The actual business system is fine. 
We noticed that **for each and every request, CloudSDK reaches out to destination service to get latest  /instanceDestinations as well as /subaccountDestinations.**

These requests are subject to hardly any change in the usual customer setup. Even with higher limitation rates from Destination service side - the 2 calls are redundant most of the time and if we use cached responses we can significantly improve the performance of our software.

Here you can find the logs of our app.
`
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/instanceDestinations 
Accessing URL: GET https://destination-configuration.cfapps.sap.hana.ondemand.com/destination-configuration/v1/subaccountDestinations 
Accessing URL: GET https://sandbox.api.sap.com/s4hanacloud/sap/opu/odata/sap/API_BUSINESS_PARTNER /A_BusinessPartner?$select=BusinessPartner
`

We are calling the Business System with the following CAP command
`srv.tx(req).run(query)`

CAP calls CloudSDK using the following
`_cloudSdkCore.executeHttpRequest(...args)` commands.

Do you see any possibility for the **three of us to come up with a best-practice?** 
**Business System requests we don't want to cache, Destination Service Requests however would be great to cache**

**Comment by jjtang1985** [comment]
Hi @JohannesRu ,

Thank you for raising this up.

We have a BLI for supporting cache configuration in the `executeHttpRequest`.

Here is another related issue(https://github.com/SAP/cloud-sdk-js/issues/1262), where you can find this [comment](https://github.com/SAP/cloud-sdk-js/issues/1262#issuecomment-847617430), that shows  you can use this example for getting destination with cache `getDestination('destinationName', { useCache: true })` and use the destination later on.

The CAP colleague Johannes was also aware this and replied [this](https://github.com/SAP/cloud-sdk-js/issues/1262#issuecomment-848508851).

I'm not sure whether CAP is able to support the approach mentioned above or not.

From the SDK perspective, we definitely can extend the `executeHttpRequest` with the cache feature like the function `getDestination`.

@artemkovalyov , let's discuss the priority.
@JohannesRu , feel free to push @artemkovalyov ;)

Best regards,
Junjie

**Comment by JohannesRu** [comment]
Hey @jjtang1985 ,
Thanks for the quick response.
We are using the workaround proposed by Johannes V. now. 
Works for us. I can imagine more customers will appreciate this possibility also when using CAP so I believe making this part of the actual CAP SDK makes sense.

Again, thanks for the quick help.
 Johannes
