### ISSUE TITLE
Error while generating odata client programatically

### ISSUE THREAD

**Issue by Penna123** [SAP/cloud-sdk-js#1599]
**Describe the bug**
Error: Cannot find module '@sap/edm-converters/lib/edmToCsn/lib/main' which is coming from file @sap-cloud-sdk\generator\dist\service\csn.js:41:15)

**To Reproduce**

1. Set up ...  : We have included @sap-cloud-sdk\generator as part of our project
2. Execute ...: Generated the client programtically as mentioned in https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-odata-client#generate-a-client-programmatically 
3. Confirm ...
4. See error : We have removed dist folder and re-ran the application, after which getting error
Error: Cannot find module '@sap/edm-converters/lib/edmToCsn/lib/main' 
which is coming from file @sap-cloud-sdk\generator\dist\service\csn.js:41:15)

**Expected behavior**
It should not throw any error and work fine

**Screenshots**
none

**Used Versions:**

- node version via `node -v` : v15.0.1
- npm version via `npm -v`: 7.0.3
- SAP Cloud SDK version you used as dependency: "@sap-cloud-sdk/core": "^1.48.1",
- generator also latest one

**Impact / Priority** : its impacting our development 

Impact: e.g. Blocked

Timeline: e.g. Go-Live is in 6 weeks

**Additional context**

**Comment by deekshas8** [comment]
Hi @Penna123 ,

`@sap/edm-converters` is installed as a dependency of `@sap-cloud-sdk\generator` package. The error occurs when the dependency is missing in `node_modules`.

You can try to delete the `node_modules` folder and install all dependencies again. Another option would be to run `npm ci` if you have a `package-lock.json` to install all dependencies with a clean slate.

Please let me know if you were able to resolve your issue.

**Comment by marikaner** [comment]
Hey @Penna123,

were you able to resolve your issue?

**Comment by Penna123** [comment]
Hi 
This is working after deleting node_modules folder and building again.
Thanks!!
Leela
