### ISSUE TITLE
Type error when filtering an `Edm.DateTimeOffset` field

### ISSUE THREAD

**Issue by lennart-m** [SAP/cloud-sdk-js#1612]
Hi! We're using the cloud SDK to perform OData communication with a SuccessFactors OData v2 service.

**Describe the bug**
The TypeScript typings do not allow filtering an OData field of type `Edm.DateTimeOffset`. The only allowed value is the string `'Edm.DateTimeOffset'`, or `null` literal.
However, it works when manually casting the value.

**To Reproduce**

1. Generate the OData client for a v2 OData service that has an entity with `Edm.DateTimeOffset` property.
2. Create a filter on the property (e.g. `equals(moment())`)
3. See TypeScript error about method `EdmTypeField<User, "Edm.DateTimeOffset", true, true>.equals` only accepting parameter of type `"Edm.DateTimeOffset" | null`

This also affects other filter methods like `greaterThan` etc.

**Expected behavior**
It should be able to filter using actual values.

**Screenshots**
Type error:
![image](https://user-images.githubusercontent.com/20302675/134149400-2b8911db-6d82-413e-9dbd-676463c275f3.png)

Effective typing of the equals function:
![image](https://user-images.githubusercontent.com/20302675/134156123-00205d3a-85e7-4155-a927-7e43b527a0d8.png)

**Used Versions:**

- node version via `node -v`: `12.20.0`
- npm version via `npm -v`: `7.5.3`
- SAP Cloud SDK version you used as dependency: `^1.49.0`

**Code Examples**
This code throws an OData error although filtering should be possible.
```
import { OrderableEdmTypeField } from "@sap-cloud-sdk/core";
import moment from "moment";
import { User } from "./ext/gen/user";

User.LAST_MODIFIED_DATE_TIME.equals(moment());
```

**Impact / Priority**

This is only a TypeScript error. When making TypeScript accept this value (e.g. explicit cast to `any`) it works fine. So there is a workaround.

---

Thanks a lot!
Lennart

**Comment by deekshas8** [comment]
Hi @lennart-m ,

Thanks for bringing this to our attention. I was able to reproduce it. I have added this item to our backlog.
As you mentioned that you have a workaround, I will mark this as medium priority.

Regards.

**Comment by deekshas8** [comment]
Hi @lennart-m,

I fixed the bug. Please try the `canary` version and a new stable version will be released soon.
I'll close the ticket. Please reopen if necessary.

Thank you.
