### ISSUE TITLE
Improve logging output format based on actual binding of Application Logging service or some env property

### ISSUE THREAD

**Issue by piejanssens** [SAP/cloud-sdk-js#1666]
From the [documentation](https://github.com/SAP/cloud-sdk/blame/main/docs/js/features/logging.mdx#L117):

_If VCAP_SERVICE variables are present in the environment variables the kibana format is used, because the SAP Cloud SDK assumes your application is running on Cloud Foundry._

It appears to do just that, only having any VCAP_SERVICE in the environment variables is too broad. When developing locally, most of the time there will be some VCAP_SERVICE set, not because it's running in CF, but because they are being set through default-env.json or otherwise to hook into CF services from the local runtime.

This means at the moment Cloud SDK is very often wrongfully assuming it's running in CF, when it's not.

Proposal: check for both the presence of the Application Logging service in VCAP_SERVICE or the explicit configuration of requesting Kibana specific formatting output through the presence of an environment variable. For example `features.kibana_formatter=true` which is also [used for CAP](https://cap.cloud.sap/docs/node.js/cds-log#cds-log-ootb-formatting-kibana).

**Comment by gregorwolf** [comment]
Thank you @piejanssens that you've already filed this issue. In [How to turn off excessive logging from CDS NodeJS app?](https://answers.sap.com/questions/13512730/how-to-turn-off-excessive-logging-from-cds-nodejs.html) this was also discussed. CC @deekshas8

**Comment by jjtang1985** [comment]
Hi @piejanssens ,

We implemented the feature about a month ago and the stable version was released.
Please try version `2.5.0`.
Here you can find the updated [doc](https://sap.github.io/cloud-sdk/docs/js/features/logging#what-happens-under-the-hood) regarding the log format.

Please reopen, if you have questions.

Best,
Junjie
