### ISSUE TITLE
The OData generated client has no way to add the new dependent entity if it is defined in the EDMX as not creatable

### ISSUE THREAD

**Issue by yurecz** [SAP/cloud-sdk-js#1667]
Hello,

I need to add the new dependent entity to the root entity. In the EDMX file the dependent entity is flagged as not creatable:

`
<EntityContainer Name="cds_lmd_route_Entities" m:IsDefaultEntityContainer="true">
                <EntitySet Name="Route" EntityType="cds_lmd_route.RouteType" /> //Root
                <EntitySet Name="CustomerVisit" EntityType="cds_lmd_route.CustomerVisitType" sap:creatable="false"> //Child
 </EntityContainer>
`
According to the documentation: https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v2-type-safe-client-for-javascript-typescript#create-as-child-of
It can be done like this: 

`
CustomerVisit.requestBuilder()
  .create(visit)
  .asChildOf(
    route,
    Route.TO_CUSTOMER_VISIT
  )
  .execute(myDestination)
`
The problem is that the OData client-generated coding does not have **create** method.
So it is not clear how to add a new entity to the root.

Used workaround:
manually change the EDMX file to make entity CustomerVisit creatable:
`
<EntityContainer Name="cds_lmd_route_Entities" m:IsDefaultEntityContainer="true">
                <EntitySet Name="Route" EntityType="cds_lmd_route.RouteType" /> //Root
                <EntitySet Name="CustomerVisit" EntityType="cds_lmd_route.CustomerVisitType" sap:creatable="true"> //Child
 </EntityContainer>
`
Regenerate the OData client and it works.

Still very inconvenient always to remember that you need to change the EDMX file to make it work.

**Comment by marikaner** [comment]
Hey @yurecz,

you're opening up a very interesting point here. We currently do not support annotations yet. This might be the first step to a solution. Do you have any documentation that would allow us to learn about the rules of those?
The reason I am asking is, that I would like to understand whether this is the case for all SAP system or only yours, whether this is a rule or a convention to better design an API around this.

For now, I have to admit that you probably will have to keep adding the "sap:creatable" attribute.

**Comment by yurecz** [comment]
Hello marikaner,

I think we should first understand if the service definition generated by the SAP RAP(EDMX) conforms to the OData V2 specification regarding creating the sub-entities.
Two options are possible:
1. RAP BO conforms, when we need simply fix it in the Cloud SDK
2. RAP BO does conform when I open the SAP internal incident for RAP colleagues to properly generate the service definition and this issue can be closed.
Do you know the source to be checked for the OData specification? I am not familiar with this topic.

Best regards,
Yuri

**Comment by marikaner** [comment]
Hey @yurecz,

I found some more details on [annotations](https://github.com/oasis-tcs/odata-vocabularies/blob/main/vocabularies/Org.OData.Capabilities.V1.md).
I would like to implement this, however this is a bigger chunk and will definitely take a lot of time until it will be available for you. I hope for now you can work with the workaround.

**Comment by jjtang1985** [comment]
Due to the current priority, we won't work on this.
