### ISSUE TITLE
Configure Service Credentials for CloudSDK [Node.js]

### ISSUE THREAD

**Issue by uwe-klinger** [SAP/cloud-sdk-js#1726]
**Is your feature request related to a problem? Please describe.**

Currently, CloudSDK retrieves the `xsuaa` and `destination` service credentials from `VCAP_SERVICES` variable (using `xsenv`). This variable isn't available in non Cloud Foundry environments. The alternative configuration supported by `xsenv` using a special path syntax is also not desired in any case. 

**Describe the solution you'd like**

CAP allows configuration of credentials in its configuration. 

e.g.:

```js
{
  "requires": {
     "uaa": {
        "kind": "xsuaa",
        "credentials": {
            ...
         }
      }
   }
```

It is desired to either pass over the service credentials to CloudSDK or register a callback to return the credentials:

```js
const sdk = require("@sap-cloud-sdk/core");
sdk.setServiceCredentials( { 
  "xsuaa": { "uri": ... },
  "destination": { "uri": ... }
})
```

or:

```js

const services = { 
  "xsuaa": { "uri": ... },
  "destination": { "uri": ... }
};

const sdk = require("@sap-cloud-sdk/core");
sdk.setServiceCredentialProvider( service => services[service] );
})
```

...so that CAP credentials can be handed over to CloudSDK.

**Describe alternatives you've considered**

see above

**Impact / Priority**

To be discussed via phone :-)

**Additional context**

N/A

**Comment by florian-richter** [comment]
Summary what has been discussed offline: 
- We will reach out to XSENV for some improvements that would help resolve the issue of providing credentials
- We will provide a method to create named destinations as part of the version 2 of the SAP Cloud SDK

**Comment by marikaner** [comment]
@uwe-klinger As we have reviewed `registerDestination` together and we/you are still in contact with xsenv, this issue can be closed. Let us know if you need further support on this.
