### ISSUE TITLE
Error logs while parsing batch `DELETE` responses

### ISSUE THREAD

**Issue by lennart-m** [SAP/cloud-sdk-js#1732]
Hi, I use the cloud SDK to read/write data in SAP SuccessFactors.

---

**Describe the bug**
When executing an OData `DELETE` within a `$batch` request the cloud SDK outputs a log message about failure in response parsing.
```json
{
  "message": "Could not parse response body. Invalid JSON. Original Error: SyntaxError: Unexpected token C in JSON at position 0",
  "level": "error",
  "custom_fields": {
    "package": "core",
    "messageContext": "batch-response-parser"
  },
  "logger": "sap-cloud-sdk-logger",
  "timestamp": "2021-10-25T13:36:14.538Z",
  "msg": "Could not parse response body. Invalid JSON. Original Error: SyntaxError: Unexpected token C in JSON at position 0",
  "written_ts": 1635168974538,
  "written_at": "2021-10-25T13:36:14.538Z"
}
```

**To Reproduce**

1. Generate OData client for some SF OData Service
2. Use the cloud SDK to execute a `DELETE` within a `batch` request
4. See error below

**Expected behavior**
There should not be any error message. An OData `DELETE` request's response should not be parsed.

**Used Versions:**

- node version via `node -v`: 12.22.7
- npm version via `npm -v`: 6.14.15
- SAP Cloud SDK version you used as dependency: 1.50.0

**Code Examples**
Request body:
```
--batch_c9713710-a62c-4b98-8db3-f7d696a3662c
Content-Type: multipart/mixed; boundary=changeset_605e191b-b487-4d26-b76b-963e10fc74a3

--changeset_605e191b-b487-4d26-b76b-963e10fc74a3
Content-Type: application/http
Content-Transfer-Encoding: binary

DELETE https://myserver.sapsf.eu:443/odata/v2/cust_entity/cust_entity(Id=1L) HTTP/1.1
Content-Type: application/json
Accept: application/json



--changeset_605e191b-b487-4d26-b76b-963e10fc74a3--
--batch_c9713710-a62c-4b98-8db3-f7d696a3662c--
```

Response body:
```
--batch_89b52e20-aee8-46c8-8fda-a74b4684191b
Content-Type: multipart/mixed; boundary=changeset_3ff17c33-5fcf-4b0a-ab17-84917374e43e

--changeset_3ff17c33-5fcf-4b0a-ab17-84917374e43e
Content-Type: application/http
Content-Transfer-Encoding: binary

HTTP/1.1 200 OK
DataServiceVersion: 1.0
Content-Length: 0



--changeset_3ff17c33-5fcf-4b0a-ab17-84917374e43e--

--batch_89b52e20-aee8-46c8-8fda-a74b4684191b--
```

**Impact / Priority**

I don't exactly know when release will be. There is no high urgency as this is just a log error.

Also there is a workaround: set level of logger `batch-response-parser` to `off` (although this level is not allowed but the typings, it is still a valid winston level).

**Additional context**
The fact that SuccessFactors responds to `DELETE` requests with code `200` matches the OData v2 specification:
https://www.odata.org/documentation/odata-version-2-0/operations/#:~:text=If%20the%20operation%20executed%20successfully%20servers%20should%20return%20200%20(OK)%20with%20no%20response%20body.

> _2.8 Deleting Entries_
> Entries are deleted by executing an HTTP DELETE request against a URI that points at the Entry. If the operation executed successfully servers should return 200 (OK) with no response body.

---

Thanks a lot!
Lennart

**Comment by deekshas8** [comment]
Hi @lennart-m ,
We have fixed the issue, you can try in the `canary` version. A new stable version should be released sometime soon.
I'll close the ticket for now. Please reopen if necessary.
Regards.
