### ISSUE TITLE
getDestination fails to lookup destination in provider account 

### ISSUE THREAD

**Issue by dinurp** [SAP/cloud-sdk-js#1806]
**Describe the bug**

API [```getDestination```](https://sap.github.io/cloud-sdk/api/1.52.0/modules/sap_cloud_sdk_core#getDestination) fails to lookup destination from the provider account when accessed in the context of a user from subscriber account. This is the case even with option ```selectionStrategy: DestinationSelectionStrategies.alwaysProvider``` set. This case fails for authentication types ```OAuth2JWTBearer``` and ```OAuth2ClientCredentials```. It works for authentication type ```OAuth2UserTokenExchange```.  It appears from the log that the destination is found in all these cases in provider account, but when sdk requests for credentials, it requests this from subscriber account. 

**To Reproduce**

1. Set up 2 multitenant applications (A and B) in BTP, one (called A) with dependency to destination service
2. Create a basic nodejs app with dependency to cloud SDK. For example with [CAP](https://cap.cloud.sap/docs/get-started/#) ```cds init flights --add nodejs``` 
3. Subscribe the app A and B from another account.
4. Grant authorization to a user to the apps (A and B)  in subscriber account. 
5. Grant authorization to a user (can be the same) to the apps (A and B) n provider account.
6. Create a destination for app B in provider account, example given below. Credentials in the destination are from a key created for the xsuaa for app B.  
7. Configure the destination for authentication type ```OAuth2ClientCredentials```. 
8. Extract the service credentials for the app A to a file ```default-env.json```
9. Set environment variable ```access_token``` with value as jwt token for the user in subscriber account
10.  Use ```getDestination``` to lookup the destination using the jwt token and service credentials for app A. Example see the script given in code examples.

**Expected behavior**

API ```getDestination``` should return the destination configured in provider account.

**Used Versions:**

- node version via `node -v`
v14.18.1
- npm version via `npm -v`
7.16.0
- SAP Cloud SDK version you used as dependency
-  npm ls @sap-cloud-sdk/core
flights@1.0.0 C:\Work\cap-mtx-project
└─┬ @sap/cds@5.6.2
  └── @sap-cloud-sdk/core@1.52.0

**Code Examples**

The following script was used for the tests. Logs from different runs of this is attached. See next section.
To support the script you need ```default-env.json``` from the deployed multitenant app. 
You also need supply environment variable ```access-token``` with the jwt token for an authorized user from provider account and subscriber account, one at a time. I had these in an ```.env``` file  

``` javascript
const _debug = require("debug")("test:log"); 
const _debugOptions = require("util").inspect.defaultOptions;
function debug(msg,depth=0){
    oldDepth = _debugOptions.depth
    _debugOptions.depth = depth
    _debug(msg);
    _debugOptions.depth = oldDepth
} 
require("debug").enable("test:log")
debug("starting")

const sdk = require("@sap-cloud-sdk/core");
require("@sap/xsenv").loadEnv();
require("dotenv").config();

require("@sap-cloud-sdk/util").setGlobalLogLevel("debug")
let dest = "CAP-Incidents"; 
let options= {userJwt:process.env.access_token, selectionStrategy: sdk.DestinationSelectionStrategies.alwaysProvider};

// what is the subdomain of the user access token?
debug({ "userJwt-Subdomain": sdk.decodeJwt(options.userJwt).ext_attr.zdn },2);


sdk.getDestination(dest,options).then(d => {
    debug(d,1) 
}).catch(e => {
    debug()
    debug({
        "status":e.rootCause.response.status,
        "message": e.rootCause.response.data,
        "path": e.rootCause.request.path,
        "headers": e.rootCause.request.getHeaderNames(),
       // what is the subdomain of the request for destination?
        "Authorization-Subdomain": sdk.decodeJwt(e.rootCause.request.getHeader("Authorization").split(" ")[1]).ext_attr.zdn
    },3);
});
```

Exported destination configuration looked like:
```
#
#Mon Nov 15 11:10:22 UTC 2021
Name=CAP-Incidents
ProxyType=Internet
Type=HTTP

URL=https\://112XXXc5trial-dev-cds-mtx-project-srv.cfapps.eu10.hana.ondemand.com

Authentication=OAuth2ClientCredentials

tokenServiceURLType=Common
tokenServiceURL=https\://authentication.eu10.hana.ondemand.com/oauth/token

clientId=-- removed ---
clientSecret=<< Existing password/certificate removed on export >>
```
**Log file**

Attached log file [err-log.txt](https://github.com/SAP/cloud-sdk-js/files/7539631/err-log.txt) has logs for the following runs:
- access_token from subscriber, authentication: 'OAuth2UserTokenExchange' 
- access_token from provider, authentication: 'OAuth2UserTokenExchange' 
- access_token from subscriber, authentication: 'OAuth2JWTBearer' 
- access_token from provider, authentication: 'OAuth2JWTBearer' 
- access_token from subscriber, authentication: 'OAuth2ClientCredentials' 
- access_token from provider, authentication: 'OAuth2ClientCredentials' 

In the log:
- subscriber sub-domain is ```112XXXc5trial-c1```
- provider sub-domain is ```112XXXc5trial```

**Impact / Priority**

This is forcing us to configure the destination in subscriber accounts leading to effort in creating these, potential leak of credentials specified and high effort in key rotation. 
Timeline: GTM is planned for December 2021. First go live expected in 2022.

**Additional context**
This was discovered in the context of a CAP multi-tenant app development. We have 2 micro services, one needs to call the other.

**Comment by jjtang1985** [comment]
Hi @dinurp ,

Thanks for raising this up.

I have some questions when reading the description and also created an architectural diagram [here](https://github.com/SAP/cloud-sdk-js/files/7545785/issue-1806.drawio.txt) for better communication. It would also be great if you can fix the diagram (if I'm wrong) and we can communicate based on that. I renamed the drawio file to txt extension for uploading limits.

Please find my questions below:

In general, where did you execute the code snippets? I assume local machine as you copy the service credential, which should not be the case for CF?

> Create a basic nodejs app with dependency to cloud SDK. For example with CAP cds init flights --add nodejs

I assume this is a new app, so I mark it as test application C, which has the code snippets provided. Am I wrong?

> Set up 2 multitenant applications (A and B) in BTP, one (called A) with dependency to destination service.
> Create a destination for app B in provider account, example given below. 

The destination is created in the provider account, where B is deployed. However, previously, you only mentioned A binds the destination service. Are A and B deployed with the same subaccount?

> Set environment variable access_token with value as jwt token for the user in subscriber account

Which user are you talking about? A user of Application C?

Thank you very much.

I'm looking forward to your reply.

Best regards,
Junjie

**Comment by FrankEssenberger** [comment]
BLI created. Link to private repo visible for internal colleagues.

**Comment by FrankEssenberger** [comment]
Should also be fixed by this PR: https://github.com/SAP/cloud-sdk-js/pull/1867.

**Comment by FrankEssenberger** [comment]
version 1.53.0 is released, which should fix the issue.

**Comment by FrankEssenberger** [comment]
I close the issue to keep our board tidy. If you experience problems please reopen or open a new issue.

**Comment by dinurp** [comment]
Works great. Thanks.
