### ISSUE TITLE
@sap/xsenv cannot be installed with node v16

### ISSUE THREAD

**Issue by Sytten** [SAP/cloud-sdk-js#1877]
**Describe the bug**
There is an engine check in `@sap/xsenv` that prevents installation of this module when using the current node version (v16).

**To Reproduce**

1. Use node v16
2. yarn install
3. See the error

**Expected behavior**
Allowed to install the package with the current LTS of node.

**Comment by tomfrenken** [comment]
Hey @Sytten

Thanks for reporting this bug to us.
I was able to replicate the bug and will check with the xsenv colleagues if/when it is possible to support node v16.

**Comment by tomfrenken** [comment]
After checking with the xsenv colleagues it looks like it will take some time until node16 is supported, I would recommend using node 14 for now

**Comment by florian-richter** [comment]
@Sytten I agree that this should be supported, but as a workaround you could use the `--ignore-engines` until `@sap/xsenv` is updated accordingly. Given that this is not directly a SAP Cloud SDK issue and there is a workaround, I would like to close the issue. Feel free to reopen if you disagree.
