### ISSUE TITLE
Batch request with no generated client

### ISSUE THREAD

**Issue by crazio** [SAP/cloud-sdk-js#2023]
Dear Cloud-SDK team,

We created our own OData v2 service in SAP Gateway and now we want to call some OData actions via batch request from our cloud service.
We don't use Typescript and we don't have generated client for our service. When we had a look at some SAP Cloud SDK client (for instance `@sap/cloud-sdk-vdm-business-partner-service`) we noticed that it has `batch` function, but core package `@sap-cloud-sdk/core` doesn't have this function, so seems like it won't be so easy for us.
I see that core package has classes like `ODataBatchRequestBuilder`, so probably we can handle our needs with it? Can you, please, share if we can use this class and probably give some small hint how to use it in our case?

Thanks a lot!

**Comment by florian-richter** [comment]
If you have a custom service without a pre-generated client, you should use our generator `@sap-cloud-sdk/generator` to create a custom client. Using this client you should be able to create batch requests against your service. 

We strongly recommend TypeScript where possible, but generated clients (and all the other packages we provide) can be used to 100% with JavaScript. 

Here some helpful links from our documentation: 
- [Generate an OData client](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-odata-client)
- [Execute an OData v2 (batch) request](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v2-type-safe-client-for-javascript-typescript#batch-requests)
- [Execute an OData v4 (batch) request](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v4-type-safe-client-for-javascript-typescript#batch-requests)

I will close the ticket as I hope the documentation will help you create the batch requests. If you have further issues, feel free to reopen or create a new issue.
