### ISSUE TITLE
Support destinations from service bindings out of the box: saas-registry & service-manager

### ISSUE THREAD

**Issue by PhilipMugglestone** [SAP/cloud-sdk-js#2060]
Hello Cloud SDK team,

Could you consider supporting the following BTP services as destinations from service bindings via environment variables out of the box so that the generic HTTP client can be used with them?
- saas-registry
- service-manager

Two other services are already supported out of the box - see doc [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#service-binding-environment-variables).

It would be great to also support the saas-registry and service-manager services which are typically bound to a given app deployed to BTP. It makes little sense to manually create destinations for them as full details including credentials are already defined in environment variables.

Both suggested services have REST APIs - am currently using axios but this is significantly more verbose than executeHttpRequest.

Thanks,
Philip

**Comment by marikaner** [comment]
Hey @PhilipMugglestone,

that sounds interesting. Could you share some details on your use case and how you would imagine this? This would help us discussing requirements for such a feature.

**Comment by PhilipMugglestone** [comment]
Hi @marikaner,

Sure. Many SAP partners create multi-tenant SaaS apps deployed in BTP for their customers. The saas-registry and service-manager APIs can play a key role in these apps. It's possible to use them via axios (or similar) but it would be more elegant to use executeHttpRequest of SAP Cloud SDK. There's no need to create BTP destinations here as the credentials etc. are all provided to the app at runtime.

From a personal perspective, we have a Yeoman [generator](https://github.com/saphanaacademy/generator-saphanaacademy-saas) that helps partners kick-start their SaaS projects and to demonstrate best practice for ongoing development so I'd like to show use of executeHttpRequest rather than axios. See the generator code [here](https://github.com/saphanaacademy/generator-saphanaacademy-saas/blob/master/generators/app/templates/srv/library.js). CF API (getCFInfo function etc.) is already accessed via cloud sdk but saas-registry (getSubscriptions) & service-manager (createSMInstance etc.) are not.

Thanks,

Philip
SAP HANA Academy

**Comment by marikaner** [comment]
Hey @PhilipMugglestone ,

thank you. Based on the code that you generate, I take away that features you would like to have would be:
1. getting subscriptions from the SAAS registry
2. creating, getting, and deleting service manager instances using the service manager service

I will create a feature request for this in our backlog and discuss this with the team. If we have further questions we will come back to you. Feel free to add requirements to the list above.

**Comment by PhilipMugglestone** [comment]
Hi @marikaner ,
Thanks however the intention is more general and the focus is OAuth2 authentication. The feature request is about making it easy to use executeHttpRequest against REST services that are available in environment variables via service bindings so not actually defined as destinations in BTP. This nis already possible except when those REST services require an access token obtained via OAuth2ClientCredentials - as is the case for service-manager and saas-registry. It's the process of obtaining the access token when there isn't a "real" destination defined in BTP that seems to be missing from Cloud SDK. That or simply an clear example of how to do this today.

**Comment by FrankEssenberger** [comment]
@PhilipMugglestone we have a first PR: #2633.
Perhaps you can say if this is what you had in mind.

**Comment by saphanaacademy** [comment]
@FrankEssenberger thanks yes this is exactly what I had in mind apart from the fact that the service manager service is not supported? for saas-registry it looks good.

**Comment by FrankEssenberger** [comment]
ok I will try to quickly add the service manager service. If I have problem creating/binding the service I may come back to you.

**Comment by FrankEssenberger** [comment]
Added the service manager.

**Comment by FrankEssenberger** [comment]
The PR is merged and a new `canary` release should be available in a few minutes. Is it ok to close the issue and you reopen it or create a new one in case something is not working?

**Comment by saphanaacademy** [comment]
I've been able to test and everything is working as expected. Can already see it in action for the saas-registry service [here](https://github.com/saphanaacademy/generator-saphanaacademy-saas/blob/master/generators/app/templates/srv/library.js) (line 23). Thanks so much!

**Comment by saphanaacademy** [comment]
Hi,

All good in Cloud Foundry environment however doesn't appear to be working for saas-registry in Kyma environment.

Instead of using VCAP_SERVICES we define volume mounts eg:
```
          volumeMounts:
            - name: app8-uaa
              mountPath: "/etc/secrets/sapcp/xsuaa/app8-uaa"
              readOnly: true
            - name: app8-registry
              mountPath: "/etc/secrets/sapcp/saas-registry/app8-registry"
              readOnly: true
```
So
```
        let res = await httpClient.executeHttpRequest({ destinationName: 'app8-registry' }, {
            method: 'GET',
            url: '/saas-manager/v1/application/subscriptions'
        });
```
Returns: `"Failed to resolve the destination 'name: app8-registry'." `

For info, the following code returns the service bindings OK:
```
const xsenv = require('@sap/xsenv');
const services = xsenv.getServices({
    uaa: { label: 'xsuaa' },
    registry: { label: 'saas-registry' }
});
```
 
Thanks.

**Comment by FrankEssenberger** [comment]
I had a quick look and it seems that we do not use the `xsenv` in the code everywhere. If you follow the [load service](https://github.com/SAP/cloud-sdk-js/blob/3bff42e1aa498baec330a11c5d3af9e1122cbae2/packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts#L53) you come to a place where we look at the `VCAP_SERVICE` by [hand](https://github.com/SAP/cloud-sdk-js/blob/3bff42e1aa498baec330a11c5d3af9e1122cbae2/packages/connectivity/src/scp-cf/environment-accessor.ts#L143). I guess this should be delegated to the library. Otherwise it can not work right? For my understanding in Kyma there is not VCAP env?

If my understanding is right I would open an issue in our backlog to remove all the missed `VCAP` acceses.

**Comment by FrankEssenberger** [comment]
Backlog item is created. We will come back once it is fixed.

**Comment by tomfrenken** [comment]
Hey @saphanaacademy,

we've just realized a fix for the bug, it will be available either by using our latest canary version or with our next release.

**Comment by saphanaacademy** [comment]
Working nicely in v2.8.0. Thankyou!
