### ISSUE TITLE
Function executeHttpRequest(destination, requestConfig) does not pick up global proxy settings

### ISSUE THREAD

**Issue by shardul-sonar-sap** [SAP/cloud-sdk-js#2061]
**Describe the bug**
I am trying to use the function `executeHttpRequest(destination, requestConfig)` in cloud sdk's js library to fetch a destination `$metadata`. We are using a proxy to our configuration-server(component which uses cloud-sdk for fetching destinations) so all the requests must go to the proxy. 

This is how we have configured it on our cluster : 
```
HTTP_PROXY=some.url
HTTPS_PROXY=some.url
```
Based on the [documentation](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/proxy), I would expect the cloud sdk functions to pick up the global proxy settings automatically in case the proxy type is Internet , and for On-Premise case to ignore the proxy settings.

For some reason this does not seem to happen, and the request below is being directly sent to the actual destination configured in BTP instead of our proxy : 
```
class CloudSdkHttpRequestConfig {
  public headers: Record<string, string> | undefined;
  public params: Record<string, string> | undefined;
  public method: HttpMethods;

  public constructor(
    headers: Record<string, string> | undefined,
    params: Record<string, string> | undefined,
    method: HttpMethods = HttpMethods.Get
  ) {
    this.headers = headers;
    this.params = params;
    this.method = method;
  }
}

const requestConfig = new  new CloudSdkHttpRequestConfig(
    headers,
    { "sap-documentation": "all" },
    HttpMethods.Get
  );
cloudSdk.executeHttpRequest(destination, requestConfig);
```
We are currently doing a work-around for this : 
```
class CloudSdkHttpRequestConfig {
  public headers: Record<string, string> | undefined;
  public params: Record<string, string> | undefined;
  public method: HttpMethods;
  public httpAgent?: any;
  public httpsAgent?: any;

  public constructor(
    headers: Record<string, string> | undefined,
    params: Record<string, string> | undefined,
    method: HttpMethods = HttpMethods.Get,
    ifNotOnPremiseSystem = true
  ) {
    this.headers = headers;
    this.params = params;
    this.method = method;
    // setting proxy (hoverfly) for calls to fetch metadata
    // should not be set if the call is to on-prem system
    if (ifNotOnPremiseSystem && HTTP_PROXY) {
      this.httpAgent = new HttpsProxyAgent(HTTP_PROXY);
      this.httpsAgent = new HttpsProxyAgent(HTTP_PROXY);
    }
  }
}
```
But I would expect that it works out of the box and not in this way. 

**To Reproduce**

1. Set up cloud sdk on any new or existing typescript or javascript project and then call the function `executeHttpRequest(destination, config)`. 
2. Set up HTTP_PROXY and HTTPS_PROXY env variables for a URL and then check if the request to fetch the destination is redirected via the PROXY server or not. 

**Expected behavior**
The `HTTP_PROXY` and `HTTPS_PROXY` should be recognised and for the function `executeHttpRequest`

**Used Versions:**
- node version via `node -v` : v14.15.1
- npm version via `npm -v` : 6.14.8
- SAP Cloud SDK version you used as dependency : 1.53.1

**Impact / Priority**
Currently affecting some developments for our testing environment. 

Affected development phase: **Development** 

Impact: Inconvenience 

**Additional context**

**Comment by FrankEssenberger** [comment]
Hi @shardul-sonar-sap ,

you are 100% correct and the SDK should pickup the proxy and put it to the agents [see here](https://github.com/SAP/cloud-sdk-js/blob/23474a60b382d8d6e806a5c5c26281b999e36223/packages/core/src/http-agent/proxy-util.ts#L237). However, this seems not to work and I wonder why.

The proxy configuration is part of the destination object which is either fetched by the SDK for you or you have built it manually. Only if the SDK fetches the desintaion it will add the proxy.  So in your example what is the `destination`? If it is a fetched destination it should contain a proxyConfiguration property - can you check?. If you build the destination manually you can use the [addProxyConfiguration](https://github.com/SAP/cloud-sdk-js/blob/23474a60b382d8d6e806a5c5c26281b999e36223/packages/core/src/http-agent/proxy-util.ts#L184) method to add the proxy config.

If you fetched the destination and the config is still missing, perhaps the value of the env does matter the [pattern](https://github.com/SAP/cloud-sdk-js/blob/23474a60b382d8d6e806a5c5c26281b999e36223/packages/core/src/http-agent/proxy-util.ts#L141) we use to extract the proxy config, buth then you should also see a log statement.

Best 
Frank

**Comment by FrankEssenberger** [comment]
I have been in contact with the colleagues and the reason the proxy was not considered was the use of the `fetchDestination` method directly. This is done on purpose in their environment, because they do not have the destination service bindings accessible for `xsenv`. They will try to call the `addProxyConfigurationInternet()` to add the proxy to the destination, which should work.

Please comment on this issue if this solved your case.

**Comment by shardul-sonar-sap** [comment]
@FrankEssenberger : 
Thanks for taking a look in the issue. I also had a chat with the colleague already. 
So the confusion was because we use `fetchDestination` function. 

My assumption was that the `executeHttpRequest()` should have automatically pick up the proxy configurations, because the name of the function suggests that it should execute an http request. But due to the `internet` and `onprem` this makes slightly complex. 

Anyway you can mark this bug as resolved. If we need anything else we will contact you again thanks :)
