### ISSUE TITLE
"s4-hana-cloud" service binding does not work without xsuaa binding

### ISSUE THREAD

**Issue by johannes-vogel** [SAP/cloud-sdk-js#2102]
Hi,

I am Johannes from the CAP team and we observed the following problem when adapting your new version:

**Problem description**

Within our tests, we set up the VCAP_SERVICES env variable manually and only add an entry for "s4-hana-cloud".
With cloud sdk version 2.0.0, the tests do not work anymore, because this PR #2062 requires to always have (mock) a binding to a XSUAA instance.

The new cache depends on jwt token/ if not present on the provider token which is tried to be fetched from XSUAA binding.
Within our tests, we neither provide a jwt token or XSUAA binding.

Is that done on purpose and we should adapt our tests or is this a problem on your side? 
With version 1.x it was not required.

**To Reproduce**

```js
process.env.VCAP_SERVICES = JSON.stringify({
  's4-hana-cloud': [
    {
      label: 's4-hana-cloud',
      plan: 'api-access',
      name: 'd',
      tags: ['s4-hana-cloud'],
      instance_name: 'd',
      binding_name: null,
      credentials: { url: 'xxx' },
      syslog_drain_url: null,
      volume_mounts: []
    }
  ]
})

const sdk = require('@sap-cloud-sdk/connectivity')
sdk.getDestination({ destinationName: 'd' })
```

**Comment by jjtang1985** [comment]
Thanks for raising this up.
I guess this [line](https://github.com/SAP/cloud-sdk-js/blob/3181cb6b896f014c9ae0941915d27659a2690c8a/packages/connectivity/src/scp-cf/destination/destination-from-registration.ts#L121) checks the xsuaa binding, which is newly introduced for the cache key.

**Comment by marikaner** [comment]
Hey @johannes-vogel, I can see that it is inconvenient, if you have to mock the xsuaa binding. Currently you would have to do that even if you provide a JWT. We will change this, so that either one of the options is enough.

However, we have generally decided to make the isolation strategies more strict, so that there is no "NoIsolation" and no "User" isolation. The ratio is, that in production you should use tenant isolation at least.

I would recommend to send a dummy token in your case.
Does that help?

**Comment by jjtang1985** [comment]
> Currently you would have to do that even if you provide a JWT. We will change this, so that either one of the options is enough.

I created PR:https://github.com/SAP/cloud-sdk-js/pull/2110 for this.

**Comment by johannes-vogel** [comment]
@marikaner Thanks for explaining.
In our tests it is simpler to mock the xsuaa binding instead of providing the jwt token on each request.
