### ISSUE TITLE
Destinations with provided JWT - audience mismatch

### ISSUE THREAD

**Issue by nocheintobi** [SAP/cloud-sdk-js#2211]
After having upgraded to sap-cloud-sdk 2.1.0 combined with VDMs in version 2.0.0, accessing destinations via the VDMs does not work anymore when providing a JWT fetched from the destination service. 
When being in an XSUAA context without fetching the DestinationService access token, access works fine (which is done when doing calls from UI in a Business User's tenant scope).

The JWT fetched from the DestinationService for a certain subscribed tenant contains the clientId of the DestinationService subscription within its audience property (`aud`). 
When using that, as follows:

```js
someWhitelistedApi.requestBuilder()
    .getAll()
    .top(1)
    .select(someWhitelistedApi.schema.SOME_PROPERTY)
    .execute({destinationName: "MyDest", jwt: destinationJwtForTenant, useCache: true});
```

you get the following error:

ErrorWithCause: Could not find a destination with name "MyDest"! Unable to execute request.
     at /home/vcap/deps/0/node_modules/@sap-cloud-sdk/odata-common/dist/request-builder/request-builder-base.js:108:23
     at processTicksAndRejections (internal/process/task_queues.js:97:5)
     at async /home/vcap/app/dist/app.service.js:117:32
     at async Promise.all (index 1)
     at async AppService.healthcheck (/home/vcap/app/dist/app.service.js:115:16)
     at async AppController.triggerHealthCheck (/home/vcap/app/dist/app.controller.js:24:16)
     at async /home/vcap/deps/0/node_modules/@nestjs/core/router/router-execution-context.js:46:28
     at async /home/vcap/deps/0/node_modules/@nestjs/core/router/router-proxy.js:9:17
 Caused by:
 Error: Jwt token with audience: [
   **'sb-clonexxxxxxxxxxxxxxxxxxxxxx|destination-xsappname!bxxx'**,
   'uaa'
 ] is not issued for these clientIds: [** 'sb-myApp!t0815', 'myApp!t0815' **].
     at returnError (/home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:254:25)
     at /home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:306:36
     at TokenInfo.<anonymous> (/home/vcap/deps/0/node_modules/@sap/xssec/lib/tokeninfo.js:140:24)
     at /home/vcap/deps/0/node_modules/jsonwebtoken/verify.js:223:12
     at /home/vcap/deps/0/node_modules/@sap/xssec/lib/verificationkey.js:111:24
     at /home/vcap/deps/0/node_modules/@sap/xssec/lib/keycache.js:230:24
     at _requestToNetworkAXIOS (/home/vcap/deps/0/node_modules/@sap/xssec/lib/requests.js:52:13)
     at processTicksAndRejections (internal/process/task_queues.js:97:5) {
   cause: Error: Jwt token with audience: [
    **'sb-clonexxxxxxxxxxxxxxxxxxxxxx|destination-xsappname!bxxx'**,
     'uaa'
   ] is not issued for these clientIds: [ ** 'sb-myApp!t0815', 'myApp!t0815' ** ].
       at returnError (/home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:254:25)
       at /home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:306:36
       at TokenInfo.<anonymous> (/home/vcap/deps/0/node_modules/@sap/xssec/lib/tokeninfo.js:140:24)
       at /home/vcap/deps/0/node_modules/jsonwebtoken/verify.js:223:12
       at /home/vcap/deps/0/node_modules/@sap/xssec/lib/verificationkey.js:111:24
       at /home/vcap/deps/0/node_modules/@sap/xssec/lib/keycache.js:230:24
       at _requestToNetworkAXIOS (/home/vcap/deps/0/node_modules/@sap/xssec/lib/requests.js:52:13)
       at processTicksAndRejections (internal/process/task_queues.js:97:5) {
     statuscode: 401

With previous SDK versions, that worked properly, I guess the `aud` property of the JWT hadn't been checked before.

Working with provided JWTs per tenant is neccessary when doing API calls from outside the UI, e.g. a healthcheck, that performs a Ping to all subscribed tenants' destination.

**Used Versions:**
- node version: 14.18.2
- npm version: 6.14.15
- SAP Cloud SDK version: 2.1.0
- whitelisted VDMs (e.g. @sap/cloud-sdk-vdm-material-planning-data-service): 2.0.0

**Comment by nocheintobi** [comment]
Found out, that it‘s working when setting ˋiasToXsuaaTokenExchangeˋ to ˋfalseˋ.
Got it working by trial and error, since the docs didn‘t give any hints.
Maybe adding this information to the migration guide to cloud sdk 2.0+ would be helpful…?

**Comment by FrankEssenberger** [comment]
Hi @nocheintobi,

sorry that you had to reengineer our code to find a solution.  Your intuition is correct that we switched to a library `@ap/xssex` in version 2.0 of the SDK to do some token exchange for IAS token if needed and also doing the verification which is more strict. 

For cases when you do not have a user context and want to get destinations from other tenants on behalf of your application you can also use the `iss` property instead of a JWT:

https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination#destination-lookup-without-a-json-web-token

With this option the SDK will fetch a destination service token for the given tenant for your. You have to be careful not to make some mistakes regarding isolation of data.

I will adjust the migration guide. Is it ok if I close this issue?

Best
Frank

**Comment by nocheintobi** [comment]
Hi Frank, 
thank you for reply! I'm fine with closing the issue and appreciate the resulting task :) ...
Tobi
