### ISSUE TITLE
setGlobalLogLevel, setLogLevel, muteLoggers don't work

### ISSUE THREAD

**Issue by brodo** [SAP/cloud-sdk-js#2237]
**Describe the bug**
`setGlobalLogLevel`, `setLogLevel` and  `muteLoggers` don't change the logging behaviour.

**To Reproduce**

1. use `setGlobalLogLevel`, `setLogLevel` or `muteLoggers` to get fewer log messages
2. `Execute executeHttpRequest`
3. See a lot of 'info'-level log messages

**Expected behavior**
It should only show the appropriate log messages

**Used Versions:**

- node version via `node -v`: v16.14.0
- npm version via `npm -v`: 8.3.1
- SAP Cloud SDK version you used as dependency: "@sap-cloud-sdk/core": "^1.54.0", "@sap-cloud-sdk/util": "^2.1.0"

**Impact / Priority**

This makes the logs harder to read during development.

Affected development phase: Development
Impact: Inconvenience, I

**Comment by nocheintobi** [comment]
Hi brodo,
`@sap-cloud-sdk/core` should be removed as it has been split into different modules, on of such is `@sap-cloud-sdk/util`. After having fixed the imports, you should be able to influence logging behavior as it was before.
What I have seen after updating is, that some messages appeared e.g. for loggers in destination context, that should have been muted by a less detailed log level but appeared anyway. It seems, that messageContexts win over loggers in precedence - so you might need to modify the log level for some messageContexts in addition.
`register-destination` messageContext for example is one of those candidates, that appeared in the logs also their logger was set to error-level.

**Comment by FrankEssenberger** [comment]
Good morning,

@nocheintobi is right and you have a mix of version 1 and version 2 of the SDK. We recommend to use the latest version and do not use core but the smaller pacakges like `connectivity` or `OData` depending on you use case. Here is a [migration guide](https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-2) in case you have already some code in the old version. The breaking changes are not so large.
I will create a backlog item about the log level issue. If you set one specific logger to `error` and do not touch the level on the messageContext this should block it. 

Best
Frank

**Comment by FrankEssenberger** [comment]
@nocheintobi could you perhaps give the steps to reproduce the behavior with the logger?

**Comment by brodo** [comment]
Thanks a lot @nocheintobi @FrankEssenberger for helping so quickly! It worked, but I still have a very verbose error output when an error happens. I'll open another issue for that though.

**Comment by nocheintobi** [comment]
@FrankEssenberger, I noticed it for the following messageContexts - all of which are logged via the `sap-cloud-sdk-logger`:
* `jwt`
* `register-destination`
* `env-destination-accessor`
* `destination-accessor-vcap`
* `destination-accessor-service`
* `proxy-util` (will only show up when using destination service instance instead of `destinations` env variable)

The following snippet will show when adding proper configuration to VCAP_SERVICES and filling in an existing destination name:

```
process.env.VCAP_SERVICES = `{"xsuaa": [...], "destination": [...]}`;

const { getDestination } = require("@sap-cloud-sdk/connectivity");
const { setLogLevel } = require("@sap-cloud-sdk/util");

setLogLevel('error', 'sap-cloud-sdk-logger');
// setLogLevel('error', 'proxy-util');
// setLogLevel('error', 'destination-accessor-service');
// setLogLevel('error', 'env-destination-accessor');
// setLogLevel('error', 'jwt');
// setLogLevel('error', 'register-destination');

(async() => await getDestination("<ValidDestinationName>")) ();
```
