### ISSUE TITLE
Can openapi-generator  generate code in JS ?

### ISSUE THREAD

**Issue by I501000** [SAP/cloud-sdk-js#2271]
Can openapi-generator  generate code in JS ?  In the document , openapi-generator generates code in TS .

**Comment by I501000** [comment]
Resolved. Just add parameter  -t

**Comment by jjtang1985** [comment]
Hi @I501000 ,

Thank you for sharing your experience;)

To add a link to the documentation, [here](https://sap.github.io/cloud-sdk/docs/js/features/openapi/generate-openapi-client#options) you can all the options of the generator including `-t`, that does the transpiration.

I'll close this ticket.
