### ISSUE TITLE
Support for AbortController

### ISSUE THREAD

**Issue by manjunath-satyamurthy** [SAP/cloud-sdk-js#2287]
**Is your feature request related to a problem? Please describe.**
At SAPGRAPH we use the destination service to fetch metadata for several destinations (potentially thousands) and based on certain conditions it would be nice to be able to abort all the triggered requests.

**Describe the solution you'd like**
Seemingly from node version 15 and above there is native support for  [AbortController](https://developer.mozilla.org/en-US/docs/Web/API/AbortController). And `axios` from version 0.22.0 and above also started to support abortController.

Please enable the following apis to accept an abort signal which could then be passed to the underlying axios requests.
[`getDestination`, `executeHttp`, `executeHttpRequest`, `fetchDestination`, `fetchSubaccountDestinations`, ...]

**Impact / Priority**
Optimization / Medium

**Comment by jjtang1985** [comment]
@manjunath-satyamurthy ,

We are working on the next [major version](https://github.com/SAP/cloud-sdk-js/discussions/3197), where we will switch to node 18 as the minimal node runtime.

With this, the major blocker of this feature request will not be there anymore, so we can starting considering this use case.

Now, I have a question.
> At SAPGRAPH we use the destination service to fetch metadata for several destinations (potentially thousands) and based on certain conditions it would be nice to be able to abort all the triggered requests.

Which requests do you want to abort?
When executing an http request via the SAP Cloud SDK (sdk [doc](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/http-client#executehttprequest)), the SDK does 2 jobs for you in general:
1. fetch destinations (in your case, it will consume the destination service) just like the `getDestination()` API
2. execute the http request against the fetched destination

I feel you are talking about `1` (fetching destinations), so you can stop fetching the rest of the destinations, based on certain conditions.

Could you please confirm?

Best regards,
Junjie

**Comment by manjunath-satyamurthy** [comment]
Hi @jjtang1985 . Good to know this can be supported in near future.
Regarding your question -
I think it would be better if we can pass the `AbortController` for both the scenarios

**Comment by jjtang1985** [comment]
Unfortunately, we have no plan for working on the AbortController due to other priorities.
