### ISSUE TITLE
Using V4 javascript version, how to set the content type to application/json;IEEE754Compatible=true'

### ISSUE THREAD

**Issue by yurecz** [SAP/cloud-sdk-js#2291]
1. Using the V4 OData service client for javascript with the ABAP backend
2. Trying to pass the numeric fields using the new BigNumber('33') constructor in the oData create request
3. Receive the exception on the ABAP side that the server cannot parse the value '33'
4. Debug in ABAP, see that the server expected the flag IEEE754Compatible=true set in the content-type request header.

Question: How to set the content-type header to change it from:
         application/json
to the:
         application/json;IEEE754Compatible=true
?

**Comment by jjtang1985** [comment]
Hi @yurecz,

Thank you for reaching out.

You can use "set custom request headers" and here is the [documentation](https://sap.github.io/cloud-sdk/docs/js/features/odata/execute-odata-request#setting-custom-request-headers).
Please choose SDK version used by switching the tab and here is the minimal example:
```ts
.addCustomHeaders({
 'content-type': 'application/json;IEEE754Compatible=true'
});
```

Please let me know, if it works or not.

**Comment by yurecz** [comment]
@jjtang1985 Thank you very much. Yes, it works.

Best regards,
Yuri

**Comment by yurecz** [comment]
Information for the people using the generated client together with the S/4HANA ABAP server:
using this coding:
```
.addCustomHeaders({
 'content-type': 'application/json;IEEE754Compatible=true'
});
```
will only work for the simple requests, if you want to create the subentities using the generated client, you will need to pass the IEEE754Compatible flag via the customer query parameters for the `$format`:
```
.addCustomQueryParameters({ 
 '$format': 'application/json;IEEE754Compatible=true' 
})
```

**Comment by texttechne** [comment]
Hi @yurecz,
these were really helpful notes for me to understand this functionality. Just reading the spec was only confusing. So, first of all, thanks!

Maybe I can give back ;-)
There seems to exist the following distinction: requesting data in IEEE754 format and declaring the format of a request or response payload:
* you use the `$format` query param or the `Accept` header param to request IEEE754 compatibility (see [spec](https://docs.oasis-open.org/odata/odata-json-format/v4.01/odata-json-format-v4.01.html#sec_RequestingtheJSONFormat))
* when posting / updating / patching you are required to set the `Content-Type` header (see [spec]) to specify the format of the payload
* whatever JSON you receive after having requested the format correctly, the response will have the `Content-Type` header set to the IEEE754 format

Best Regards
