### ISSUE TITLE
Strongly increased memory consumption/waste since V2

### ISSUE THREAD

**Issue by nocheintobi** [SAP/cloud-sdk-js#2312]
After having upgraded to Cloud SDK V2 and the corresponding VDMs, the memory consumption has increased, which can cause apps deployed to CloudFoundry to crash where they would have worked pretty well with SDK v1.
In an export scenario where I fetch data in buckets from the SAP system, combine those and then pass the complete result as CSV to an endpoint, I compared using SDK/VDMs in V1.x to Version 2 (the VDM-APIs used here are mainly the ones from `@sap/cloud-sdk-vdm-material-planning-data-service`). The very same data was exported, the same machine and runtime was used. In both variants, the export took about 25 seconds, so no big difference in performance.
The memory consumption looks as follows:
Before V2 upgrade
<img width="724" alt="before-v2" src="https://user-images.githubusercontent.com/11714327/160782491-d386364c-e20d-4e92-82c9-b2b6d86347b5.png">

After V2 upgrade
<img width="722" alt="after-v2" src="https://user-images.githubusercontent.com/11714327/160782485-c9dff707-1f62-4423-b883-757677c1208d.png">

The heap consumption has a peak which is more than twice as high for V2 (600 MB) as it was in V1 (220 MB).
External memory usage and ArrayBuffers show slightly higher values but the rate is not as significant as for the heap.
Also a memory leak doesn't apply in my mind as the garbage collector cleans up properly. Only the short-term heap usage seems to be a wasteful.

**Used Versions:**
- node version: 14.18.2 (both scenarios)
- npm version: 6.14.15 (both scenarios)
- SAP Cloud SDK version: 1.54.0 / 2.1.0
- VDM versions: 1.28.2 / 2.0.0

**Comment by jjtang1985** [comment]
Hi @nocheintobi ,

Thank you very much for SDK V2 adoption and raising this up.

Could you please share some code snippets/examples about your use case, so we can also reproduce?
Also, how big is the CSV file you want to export?

Best regards,
Junjie

**Comment by nocheintobi** [comment]
Hi @jjtang1985 ,
I prepared the two minimalistic snippets that show the difference in heap consumption.
I used a plant where we have about 350 materials and about 60000 SupplyDemandItems for all those materials together.
For simplicity, I left out anything that concerns CSV and field limitation via $select.
As you might guess, you'll need to add a destination in line 1 of each example ;-) 
Here the V1-Sample code:
```js
const DESTINATION = {...};
const { or } = require("@sap-cloud-sdk/core");
const {MrpMaterial, SupplyDemandItems} = require("@sap/cloud-sdk-vdm-material-planning-data-service")

let itemsCount = 0;
/* Fetch data via VDM */
async function fetch(plant, skip, top) {
    // const result = [];
    const materials = await MrpMaterial.requestBuilder().getAll().filter(MrpMaterial.MRP_PLANT.equals(plant)).skip(skip).top(top).execute(DESTINATION);
    const items = await SupplyDemandItems.requestBuilder().getAll().filter(SupplyDemandItems.MRP_PLANT.equals(plant), or(...materials.map(m => SupplyDemandItems.MATERIAL.equals(m.material)))).execute(DESTINATION);
    itemsCount += items.length;
    return materials.map(m => {return {plant: m.mrpPlant, material: m.material, items: items.filter(i => i.material === m.material)}});
}

// monitor heap
const interval = setInterval(() => 
    console.log(`HEAP used: ${Math.round(process.memoryUsage().heapUsed/1024/1024)} MB, items received: ${itemsCount}`), 1000);

(async() => {
    const PLANT = "1010";
    const count = (await MrpMaterial.requestBuilder().getAll().filter(MrpMaterial.MRP_PLANT.equals(PLANT)).select(MrpMaterial.MATERIAL).execute(DESTINATION)).length;
    const tasks = [];
    const pageSize = 30;
    for(let i = 0; i < count; i+=pageSize) {
        tasks.push(fetch(PLANT, i, pageSize));
    }
    const allData = [].concat(...await(Promise.all(tasks)));
    console.log("Total Size: " + JSON.stringify(allData).length);
    console.log(`Materials: ${count}, items: ${itemsCount}`);
    setTimeout(() => {clearInterval(interval)}, 10000);
})();
```

and here the V2 sample code:
```js
const DESTINATION = {...};

const { or } = require("@sap-cloud-sdk/odata-common");
const VDM = require("@sap/cloud-sdk-vdm-material-planning-data-service")

const materialApi = VDM.materialPlanningDataService().mrpMaterialApi;
const itemsApi = VDM.materialPlanningDataService().supplyDemandItemsApi;
const MATERIAL = materialApi.schema;
const ITEM = itemsApi.schema;
let itemsCount = 0;

async function fetch(plant, skip, top) {
    const result = [];
    const materials = await materialApi.requestBuilder().getAll().filter(MATERIAL.MRP_PLANT.equals(plant)).skip(skip).top(top).execute(DESTINATION);
    const items = await itemsApi.requestBuilder().getAll().filter(ITEM.MRP_PLANT.equals(plant), or(...materials.map(m => ITEM.MATERIAL.equals(m.material)))).execute(DESTINATION);
    itemsCount += items.length;
    return materials.map(m => {return {plant: m.mrpPlant, material: m.material, items: items.filter(i => i.material === m.material)}});
}
// monitor heap
const interval = setInterval(() => 
    console.log(`HEAP used: ${Math.round(process.memoryUsage().heapUsed/1024/1024)} MB, items received: ${itemsCount}`), 1000);

(async() => {
    const PLANT = "1010";
    const count = (await materialApi.requestBuilder().getAll().filter(MATERIAL.MRP_PLANT.equals(PLANT)).select(MATERIAL.MATERIAL).execute(DESTINATION)).length;
    const tasks = [];
    const pageSize = 30;
    for(let i = 0; i < count; i+=pageSize) {
        tasks.push(fetch(PLANT, i, pageSize));
    }
    const allData = [].concat(...await(Promise.all(tasks)));
    console.log("Total Size: " + JSON.stringify(allData).length);
    setTimeout(() => {clearInterval(interval)}, 10000);
})();
```
[mem-results.md](https://github.com/SAP/cloud-sdk-js/files/8379567/mem-results.md) shows the results on my machine.
For this reduced samples, the difference in heap usage is not as big as in my real code, but still significant. If neccessary, I can enhance the sample - just let me know...

Thanks for your support! 
Tobi

**Comment by jjtang1985** [comment]
Hi @nocheintobi ,

Thank you for your detailed answer.
I'll investigate and let you know.

BR,
Junjie

**Comment by nocheintobi** [comment]
A **temporary workaround** for those who are facing similar problems until the issue has been fixed might be one of the following:
* Start node with `--optimize-for-size` to reduce the overall memory footprint of your application
* Start node with `--expose-gc` and run `global.gc()` between huge fetches (might be handy in batch jobs)
* Try the combination of both
Both will potentially slow down your application, `--optimize-for-size` possibly everywhere and the garbage collector whenever you're executing it.

**Comment by jjtang1985** [comment]
Hi @nocheintobi ,

I'm looking into it.
It seems, the deserialisation is quite heavy especially when running the `execute` in a loop and also the number of entity is big.

To give you an overview, the `execute` method you used contains two parts:
1. build and execute the request and get an response from your destination server. You can also replace your `execute` with `executeRaw` to achieve so. ([doc](https://sap.github.io/cloud-sdk/docs/js/features/odata/execute-odata-request#getting-the-raw-response-and-the-original-request))
2. deserialize the original response and build entities.

Therefore, as a workaround, you can git rid of the derserializer by:
1. switch to `executeRaw`
1. pick payload of the response body (`response.data`)
1. pick the entity collection of the response (`response.data.d.results`)
1. iterate the collection
1. merge `materials` and `item` like you did before, but you need know the property keys, which can be found in the schema (e.g., `materialApi.schema`)

If you do so, please let me know, whether the memory usage is reduced significantly. (I like the graphs very much 😃 )

I'll let you know further updates.

**Comment by nocheintobi** [comment]
Hi @jjtang1985,
I gave it a try using executeRaw in my provided example and can confirm that memory consumption reduces heavily. Where my previous V2 sample consumed >800MB, using executeRaw took about 250MB at the peak.

Are there plans for optimizing the deserialization? If so, I'd prefer sticking to execute and working with the given types instead of switching the app code to using executeRaw...

**Comment by nocheintobi** [comment]
Hi @jjtang1985,
after generating the client with sdk version `2.2.1-20220407123656.0`, the memory consumption of the test scenario reduced to about 450MB (+/-25MB). 
So now we have:
<img width="357" alt="comparison" src="https://user-images.githubusercontent.com/11714327/162399350-e75b8de2-3024-4a50-9ae5-79127f845a46.png">

So half-way done ;-)

I additionally tested with the node flags I mentioned earlier, `--optimze-for-size` only reduced the peak slightly (about 420MB) and the garbage collector brought me back into the range I reached with V1... So the main part of the increased memory consumption seems to be caused by dereferenced objects on the heap...

I'm still available for further tests if needed.

**Comment by jjtang1985** [comment]
Hi @nocheintobi ,

Thank you very much for providing a nice graph for comparison.

I created a mock server that has:
- TestEntity50Col, an entity that has 50 columns (60K elements)
- TestEntity100Col, an entity that has 100 columns (350 elements)

I tried to reproduce the issue, but it shows the same level of memory usage.

So far, still one part I was not able to mock, as my server could not handle 60000 (items) / 30 (page size) = 2000 requests in parallel.
But I don't think the number is relevant, as the memory usage for 1, 10, 100, 200 requests is direct proportional.

It would be great, if you can support further.
Please install the node module 'node-memwatch-new' for memory check, then wrap your test code like below, so we can understand better:
```
  var memwatch = require('node-memwatch-new');
  var hd = new memwatch.HeapDiff();
  // put your test code here
  var diff = hd.end();
  console.log(JSON.stringify(diff.change.details.filter(e => e.size.includes('mb'))));
```
Please do it for both version 1 and canary so we can compare.
The output should look like:
```json
[
  {"what":"Native","size_bytes":18360133,"size":"17.51 mb","+":425,"-":132},
  {"what":"Number","size_bytes":1608096,"size":"1.53 mb","+":100572,"-":66},
  {"what":"Object","size_bytes":4371432,"size":"4.17 mb","+":10841,"-":82},
  {"what":"String","size_bytes":8244528,"size":"7.86 mb","+":201124,"-":2014}
]
```

**Comment by jjtang1985** [comment]
@nocheintobi ,

Thank you very much for your detailed reports 👍 

We will plan a stable release for SDK cores (@sap-cloud-sdk/*) hopefully next week, including the generator.
However, as I said, the vdm release `@sap/cloud-sdk-vdm-material-planning-data-service` was planned at the end of May.
Let's see whether we can make a new one before that.
@marikaner , FYI.

Thank you very much once again for reporting this with professional approaches.
We really appreciate it 😃 

Best regards,
Junjie
