### ISSUE TITLE
@sap-cloud-sdk/core version 2 and above not available on npm?

### ISSUE THREAD

**Issue by risapisa** [SAP/cloud-sdk-js#2342]
Hi colleagues,

Is there a reason why @sap-cloud-sdk/core only has up to version 1.54.0 available on npm? https://www.npmjs.com/package/@sap-cloud-sdk/core

**Comment by jjtang1985** [comment]
Hi @risapisa ,

Thank you for raising this up.

Please check [how to place sdk core](https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-2#replace-core-imports), as we split the SDK core package to smaller modules.

The complete upgrade guide can be found [here](https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-2).

Best regards,
Junjie

**Comment by jjtang1985** [comment]
I'll close it.
Please reopen, if you have further questions.
