### ISSUE TITLE
Generated VDM does not contain orderable functions (e.g. 'asc' / 'desc')

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-sdk-js#2367]
**Describe the bug**
I updated a VDM, generated with "@sap-cloud-generator@1.52.0", to follow and use the SAP Cloud SDK v2 by using generator 2.2.0
This was working like a charm and I generated a new package with the outcomes.

Then I installed the new package in my application and started to 'update' my requests to follow the new SDK requirements.
The first request already got me to that point, to start deep-diving the `dist` folders by searching for 'asc' and 'desc' functions to be able to order my request. 
Unfortunately, I am not able find both functions as outcomes form "@sap-cloud-sdk/odata-common". They are defined with /order/orderable.ts, and getting exported there. But on the index.ts "orderable" isn't available for me to get imported.

**To Reproduce**

1. Generate a VDM and import it
2. Use the outcoming API and set up your requestBuilder:

            // get entries from logDataStore
            const { logDataStoreApi } = generatedVDM.dataLayerLogstoreService();
            const logEntries = await logDataStoreApi
                                    .requestBuilder()
                                    .getAll()
                                    .filter(
                                        logDataStoreApi.schema.STATUS.equals('NEW'),
                                        logDataStoreApi.schema.TARGET.equals('LOGABC')
                                    )
                                    .orderBy(asc(logDataStoreApi.schema.CREATED_AT))
                                    .top(top)
                                    .execute(mySecretDestination);

Try to use functions "asc" or "desc" within the "orderBy" function. Both functions are not available.

**Expected behavior**
I can import them with 
`import { asc, desc } from '@sap-cloud-sdk/odata-common'`

**Used Versions:**
- node version 14.17.6
- npm version 8.1.1
- SAP Cloud SDK: @sap-cloud-sdk/generator: 2.2.0

**Comment by jjtang1985** [comment]
Hi @drvup ,

Thank you for raising up.
I think this is a bug.
Please use the following workaround:

```
import { asc } from '@sap-cloud-sdk/odata-common/internal';
```

**Comment by FrankEssenberger** [comment]
Also as a update we now order using `asc` per default: https://github.com/SAP/cloud-sdk-js/pull/2877
