### ISSUE TITLE
Purchase order SDK not support item selection .

### ISSUE THREAD

**Issue by I501000** [SAP/cloud-sdk-js#2419]
**Describe the bug**
The following code worked 👍 

const {purchaseOrderService} =require('@sap/cloud-sdk-vdm-purchase-order-service');
const {purchaseOrderApi, purchaseOrderItemApi} = purchaseOrderService();

function getPurchaseOrders(req) {
    
    return purchaseOrderApi.requestBuilder()
    .getAll()
    .top(1)
    .filter(purchaseOrderApi.schema.PURCHASE_ORDER.equals(req.body.purchaseOrder))
    .select(
        purchaseOrderApi.schema.PURCHASE_ORDER,
        purchaseOrderApi.schema.PURCHASE_ORDER_DATE,
        purchaseOrderApi.schema.PURCHASING_ORGANIZATION,
        purchaseOrderApi.schema.PURCHASING_GROUP,
        purchaseOrderApi.schema.COMPANY_CODE
        )
    .execute({
        destinationName: 'O5P',
        JWT: retrieveJwt(req)
    });
}
The following code does not work, but it should work ,it is a bug 

const {purchaseOrderService} =require('@sap/cloud-sdk-vdm-purchase-order-service');
const {purchaseOrderApi, purchaseOrderItemApi} = purchaseOrderService();

function getPurchaseOrders(req) {
    
    return purchaseOrderApi.requestBuilder()
    .getAll()
    .top(1)
    .filter(purchaseOrderApi.schema.PURCHASE_ORDER.equals(req.body.purchaseOrder))
    .select(
        purchaseOrderApi.schema.PURCHASE_ORDER,
        purchaseOrderApi.schema.PURCHASE_ORDER_DATE,
        purchaseOrderApi.schema.PURCHASING_ORGANIZATION,
        purchaseOrderApi.schema.PURCHASING_GROUP,
        purchaseOrderApi.schema.COMPANY_CODE,
        purchaseOrderApi.schema.TO_ITEM
        .select(purchaseOrderItemApi.schema.MATERIAL,purchaseOrderItemApi.schema.STORAGE_LOCATION)
        )
    .execute({
        destinationName: 'O5P',
        JWT: retrieveJwt(req)
    });
}

**To Reproduce**

1. Set up ...
2. Execute ...
3. Confirm ...

**Expected behavior**

**Screenshots**

**Used Versions:**

- node version via `node -v`
- npm version via `npm -v`
- SAP Cloud SDK version you used as dependency

**Code Examples**
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information.

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**

Affected development phase: e.g. Getting Started, Development, Release, Production

Impact: e.g. No Impact, Inconvenience, Impaired, Blocked

Timeline: e.g. Go-Live is in 12 weeks.

**Additional context**

**Comment by jjtang1985** [comment]
Hi @I501000 ,

Thank you for raising up.

Please check my code snippets below, which should work, where `TO_PURCHASE_ORDER_ITEM` should be used instead of `TO_ITEM`.
```
const service = purchaseOrderService();
const { purchaseOrderApi, purchaseOrderItemApi } = service;
purchaseOrderApi.requestBuilder().getAll().select(
  purchaseOrderApi.schema.ADDRESS_CITY_NAME,
  purchaseOrderApi.schema.TO_PURCHASE_ORDER_ITEM.select(
    purchaseOrderItemApi.schema.MATERIAL,
    purchaseOrderItemApi.schema.STORAGE_LOCATION,
  )
);
```

If it does not, please share the error message.

Also, does the auto completion work with your IDE, when typing `purchaseOrderApi.schema.ADDRESS_CITY_NAME` and `purchaseOrderApi.schema.TO_PURCHASE_ORDER_ITEM`? It should help find the property names.

Best,
Junjie

**Comment by I501000** [comment]
Found the reason, change the code like the following:

function getPurchaseOrders(req) {
   return purchaseOrderApi.requestBuilder().getByKey(req.body.purchaseOrder)
   .select( purchaseOrderApi.schema.PURCHASE_ORDER,
            purchaseOrderApi.schema.PURCHASE_ORDER_DATE,
            purchaseOrderApi.schema.PURCHASING_ORGANIZATION,
            purchaseOrderApi.schema.PURCHASING_GROUP,
            purchaseOrderApi.schema.COMPANY_CODE,
            purchaseOrderApi.schema.TO_PURCHASE_ORDER_ITEM.select(purchaseOrderItemApi.schema.ALL_FIELDS)
            )
            .execute({
        destinationName: 'O5P',
        JWT: retrieveJwt(req)
    });

**Comment by I501000** [comment]
Hi, [jjtang1985]
Thanks!
Another question is for material document creation. The following is the code . But there is no meth for execute in destination . Do you know how ?

materialDocumentHeaderApi.entityBuilder().fromJson(req.body)

**Comment by I501000** [comment]
Found the document , thanks!

const { businessPartnerApi, businessPartnerAddressApi } =
 businessPartnerService();
const businessPartner = businessPartnerApi
 .entityBuilder()
 .firstName('John')
 .lastName('Doe')
 .businessPartnerCategory('1')
 .toBusinessPartnerAddress([
    businessPartnerAddressApi
      .entityBuilder()
      .country('DE')
      .postalCode('14469')
      .cityName('Potsdam')
      .streetName('Konrad-Zuse-Ring')
      .houseNumber('10')
      .build()
 ])
 .build();

// execute the create request
businessPartnerApi
 .requestBuilder()
 .create(businessPartner)
 .execute(myDestination);

**Comment by jjtang1985** [comment]
Hi @I501000 ,

I'm not sure about the about the `materialDocumentHeaderApi`.

To create an entity, here is the [doc](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v2-type-safe-client-for-javascript-typescript#create-request-builder).

**Comment by jjtang1985** [comment]
I'll close this issue. Feel free to reopen, if you have further questions.
