### ISSUE TITLE
High severity whitesource vulnerability

### ISSUE THREAD

**Issue by krishraheja** [SAP/cloud-sdk-js#2448]
Hi support,

I am getting high severity whitesource vulnerability for axios 0.21.4 in @sap-cloud-sdk/core 1.54.0. Please see the impact analysis below:

![image](https://user-images.githubusercontent.com/53295200/166883737-44e153e7-eb56-4106-81de-21529e61e6f9.png)

Request you to please provide a fix for this vulnerability.

Best Regards
Krishan

**Comment by jjtang1985** [comment]
Hi @krishraheja ,

Thanks for raising up.
Are you using our (pre-generated clients) vdm or only the sdk core? (Or could you please list all the sdk dependencies you are using?)

Could you please try version `1.54.1`?

By the way, we have released version 2 since the beginning of the year and version 1 will be deprecated in the near future.

FYI, @marikaner.

BR,
Junjie

**Comment by krishraheja** [comment]
Hi Junjie,

Thanks for your prompt reply.

We are only using core library @sap-cloud-sdk/core. As per your suggestion, I was checking for 1.54.1 version, but it not available in npmjs. is that already pushed or should I wait to reflect it there.

Best Regards
Krishan

**Comment by tomfrenken** [comment]
Hey @krishraheja 

1.54.1 is available here (since 3 months) https://www.npmjs.com/package/@sap-cloud-sdk/core/v/1.54.1, e.g. with this command:

```
npm i @sap-cloud-sdk/core@1.54.1
```

Hope that helps

Best,
Tom

**Comment by krishraheja** [comment]
Hi @tomfrenken @jjtang1985 

It's strange that I can't see 1.54.1 in npmjs but when I added this version in package.json, it has resolved my issue. Also not sure in my package.json I had added it like  "@sap-cloud-sdk/core": "^1.54.0" then it should have picked 1.54.1 automatically.

Thanks a lot for your support. 

Appreciate your good work!

Best Regards
Krishan

**Comment by jjtang1985** [comment]
Hi @krishraheja ,

there was a tag issue with the `@sap-cloud-sdk/core` package.
Before, `^1.54.0` pointed to `1.54.0`, but now it points to `1.54.1`.

Best regards,
Junjie

**Comment by krishraheja** [comment]
Hi @jjtang1985 

Yes now it is showing exact 1.54.1 version. Thanks for your support.

Best Regards
Krishan
