### ISSUE TITLE
POST formData with executeHttpRequest

### ISSUE THREAD

**Issue by nocin** [SAP/cloud-sdk-js#2450]
Hi Cloud SDK Team,

**Describe the bug**
I already posted a question in the CAP Forum a few months ago which explains what I'm trying to archive and also what I tried so far. 
[https://answers.sap.com/questions/13551972/posting-formdata-to-external-rest-api.html](https://answers.sap.com/questions/13551972/posting-formdata-to-external-rest-api.html)

I have an API which I try to post a file to using formData. I can successfully use the API via Postman or using fetch.
Then I tried the same using CDS and now also directly using executeHttpRequest.

**To Reproduce**
Unfortunately I have no public API which I can provide for testing.

**Expected behavior**
Of course the API should accept my formData query send via executeHttpRequest. :-)
The API Endpoint converts the file and the content-type of the response is for example:
`Content-Type: multipart/mixed;boundary=Boundary_682_1571866230_1651741380254`
As already said, this works fine using fetch (see my posted question) and the problem seems to be on the sending side.

**Used Versions:**
- node version via `node -v`
v14.17.6
- npm version via `npm -v`
6.14.15
- SAP Cloud SDK version you used as dependency
1.54.0

**Code Examples**

Using CDS:
```
    const myAPI= await cds.connect.to('myDestination')
    const health = await myAPI.get("/health") 
    console.log(">>> Health ", health.status) // a GET request works fine

    try {
        const imageBuffer = fs.readFileSync('./tux.png')
        const form = new FormData()
        form.append('file', imageBuffer, {
            contentType: 'text/plain',
            name: 'file',
            filename: 'tux.png'
        })
        const response = await myAPI.send({
            method: 'POST',
            path: '/my/api/path',
            data: form
         })
    } catch (err) {
        console.log("Error message: " + err.message) //Error during request to remote service: Request failed with status code 404
    }
```

Using executeHttpRequest:

```
 const health = await executeHttpRequest(
        { destinationName: 'myDestination' },
        { method: 'get', url: '/health', params: {} }
 )
 console.log(">>> Health ", health.data.status) // a GET request works fine

 try {
        const imageBuffer = fs.readFileSync('./tux.png')
        const form = new FormData()
        form.append('file', imageBuffer, {
            contentType: 'text/plain',
            name: 'file',
            filename: 'tux.png'
        })

        const response = await executeHttpRequest(
            { destinationName: 'myDestination' },
            { method: 'post', url: '/my/api/path', headers: { 'Content-Type': 'multipart/form-data', 'Accept': '*/*', 'Content-Length': imageBuffer.length }, data: form }
        )
        console.log(response.data)
    } catch (err) {
        console.log("Error message: " + err.message) //Request failed with status code 404
    }
```

Tried adding different headers, without success.
One thing to note, using Postman the Content-Type always includes the boundary, e.g.:
`Content-Type: multipart/form-data; boundary=--------------------------817648025188283885837797`
I tried adding it manually while debugging, but also no success.

**Log file**
Error message always returned: "Request failed with status code 404"
From wiki:
> The 404 or Not Found error message is a HTTP standard response code indicating that the client was able to communicate with the server, but the server could not find what was requested. so, your code is OK, but server cannot find resource you are looking for. Double check if your url is correct.

It defnitly can reach the API enpoint as it returns a Payara error message (the endpoint service runs on a Payara Server):

> '<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"><html xmlns="http://www.w3.org/1999/xhtml"><head><title>Payara Server  5.2021.3 #badassfish - Error report</title><style type="text/css"></style> </head><body><h1>HTTP Status 404 - Not Found</h1><hr/><p><b>type</b> Status report</p><p><b>message</b>Not Found</p><p><b>description</b>The requested resource is not available.</p><hr/><h3>Payara Server  5.2021.3 #badassfish</h3></body></html>'

Unfortunaltely until now I didn't had the chance to check on Payara server side, if anything and what exacly arrives at the endpoint. It seems that the request is not correct when send to the endpoint.

best regads
Nico

**Comment by marikaner** [comment]
@nocin The two issues you linked in your comment seem to be resolved now. Is this sill an issue for you?
