### ISSUE TITLE
Allow user-supplied cache implementation

### ISSUE THREAD

**Issue by johenning** [SAP/cloud-sdk-js#2474]
**Is your feature request related to a problem? Please describe.**
In our usecase at SAP Graph we have multiple k8 pods for a single tenant when scaling out. Each of these pods accesses destinations via the CloudSDK with `{ useCache: true}`, but of course this only means that *each* pod caches the destinations it accesses.
As is typical, we delegate requests to theses pods via round-robin, which ensures an evenly distributed load. But is also ensures that for successive calls to the same system, every call will be as expensive as the first one, because they will always land at a pod that does not have its cache filled, until all pods have been called once.

Instead of this, we would like to have a cache instance that can be shared between the pods. Our technology of choice is redis.

**Describe the solution you'd like**
Looking at the current implementation my suggestion would be this:
* Allow user to supply a custom cache adapter that gets instantiated instead of the builtin one here: https://github.com/SAP/cloud-sdk-js/blob/630a3789e14857ae053b50f59e4eb7f4460a7972/packages/connectivity/src/scp-cf/destination/destination-cache.ts#L150
* This custom cache must implement the same interface as: https://github.com/SAP/cloud-sdk-js/blob/35502853b6ac6c3f1faabbe3b11e7d646beb36ee/packages/connectivity/src/scp-cf/cache.ts#L34
* Change this cache interface to use promises
  * As any network-connected cache will be accessed via asynchronous functions, its not possible to build an adapter for the current synchronous interface

**Describe alternatives you've considered**
* Alternatively, if the CloudSDK would support redis as a cache directly, that would of course be the optimal solution for us, but I suspect the approach outlined above is more realistic

**Impact / Priority**
* Right now we have our own cache implementation around `getDestination` and do not use the built-in cache anymore, but we would prefer to have a more official and stable solution. I would thus say its medium priority

Affected development phase: Production

Impact: Inconvenience / Impaired

**Comment by marikaner** [comment]
Hey @johenning, we have a ticket to create an ADR for this very soon. Given your input I assume this won't be anything complicated. We will share it with you for feedback once it is done.

**Comment by deekshas8** [comment]
Hi @johenning,

The PR #2527  was merged and the changes are available in the `canary` version
A new stable version should be released soon.

I'll close the ticket. Please reopen if you face any issues.
