### ISSUE TITLE
Update OData request does not send to the backend the UoM via PATCH

### ISSUE THREAD

**Issue by yurecz** [SAP/cloud-sdk-js#2526]
**Describe the bug**
OData service provider: ABAP RAP

In the OData entity, the quantity fields need to be changed. Trying to do it with the following code via PATCH request:

```
loadProposalProduct.quantity = new BigNumber(10)
loadProposalProduct = await execute(LoadProposalProduct.requestBuilder().update(loadProposalProduct))
```

The backend server sends me the error message that the unit of measure should be provided.
Debugging ABAP I see that the OData request to the ABAP server does not contain the value of the UoM as a result the ABAP server is complaining.
It happens because even though the quantity value is changed the UoM of the quantity field is not changed and not added to the OData request.

**Expected behavior**
It should be the option to specify in the PUT request the additional fields which need to be passed to the OData request even if their value is not changed.
Another option would be to analyze the OData EDMX for the SAP specific annotation:       
            
 ```
<Annotations Target="SAP__self.LoadProposalProduct_Type/Quantity">
                <Annotation Term="SAP__common.FieldControl" EnumMember="SAP__common.FieldControlType/Mandatory" />
                <Annotation Term="SAP__measures.Unit" Path="QuantityUnit" />
                <Annotation Term="SAP__common.Label" String="Quantity" />
                <Annotation Term="SAP__common.QuickInfo" String="Quantity field, 15 characters" />
</Annotations>
```

and based on this add the value on the fly to the OData request -> this option is probably less interesting as it requires SAP-specific coding.

**Used Versions:**
        "@sap-cloud-sdk/core": "^1.54.1",
        "@sap-cloud-sdk/test-util": "^1.54.1",
        "@sap-cloud-sdk/util": "^1.54.1",

**Impact / Priority**
Cannot use PATCH request o update the entity set
**Workaround**
To make things work, I switched to the PUT version of the update OData request:

```
loadProposalProduct.quantity = new BigNumber(10)
loadProposalProduct = await execute(
            LoadProposalProduct.requestBuilder().update(loadProposalProduct).replaceWholeEntityWithPut()
        )
```

The drawback here is that the complete entity needs to be fetched from the server when changing the quantity and then sent the PUT request back.
It is very inefficient.

**Comment by yurecz** [comment]
Hello Junjie,

        The OData client is generated by myself.
The EDMX file is the following: 

Best regards,
Yuri
[LMDVisitListAPI.zip](https://github.com/SAP/cloud-sdk-js/files/8823711/LMDVisitListAPI.zip)

**Comment by jjtang1985** [comment]
Hi @yurecz ,

Have you tried my example?
Did it work for you?

Best regards,
Junjie

**Comment by yurecz** [comment]
Hello @jjtang1985,

Many thanks, yes, it works.

Best regards,
Yuri
