### ISSUE TITLE
sap-cloud-sdk/generator - issue by compiling typescript files

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-sdk-js#2571]
**Describe the bug**
Dear SAP Cloud SDK team,

I started to update applications to reflect your Cloud SDK v2 changes and therefore I am generating new VDM packages.
By updating one of our VDM-Packages I am able to generate the updated service and all related files within. By compiling afterwards I do get some failures I am not able to solve.

_Example:_

```
src/sdk-vdm-services/data-loader-layer-service/RawDataStoreApi.ts:51:5 - error TS2322: Type 'EntityBuilderType<RawDataStore<DeSerializersT>, any>' is not assignable to type 'EntityBuilderType<RawDataStore<DeSerializersT>, DeSerializersT>'.
  Type 'EntityBuilderType<RawDataStore<DeSerializersT>, any>' is not assignable to type '{ entity: (value: DeserializedType<DeSerializersT, "Edm.String">) => EntityBuilderType<RawDataStore<DeSerializersT>, DeSerializersT>; ... 10 more ...; content: (value: DeserializedType<...> | ... 1 more ... | undefined) => EntityBuilderType<...>; }'.
    Property 'entity' is protected in type '{ entity: (value: DeserializedType<DeSerializersT, "Edm.String">) => EntityBuilderType<RawDataStore<DeSerializersT>, any>; ... 10 more ...; content: (value: DeserializedType<...> | ... 1 more ... | undefined) => EntityBuilderType<...>; } & EntityBuilder<...>' but public in type '{ entity: (value: DeserializedType<DeSerializersT, "Edm.String">) => EntityBuilderType<RawDataStore<DeSerializersT>, DeSerializersT>; ... 10 more ...; content: (value: DeserializedType<...> | ... 1 more ... | undefined) => EntityBuilderType<...>; }'.

return entityBuilder(this);
```

**To Reproduce**
Due to data-policy reason I am not allowed to post anything to public (on gitHub) belonging to the customer I work for. This was done within OSS 428328 / 2022, following existing SLAs.

**Expected behavior**
I am able to generate javascript compiled files by the generated typescript files (of the SAP Cloud SDK generator).

**Used Versions:**
- node version v14.17.6
- npm version 8.1,1
- SAP Cloud SDK version 2.5.0

**Code Examples**
That's how I generate the VDM with the generator:

```
import { generate } from '@sap-cloud-sdk/generator';
[...]

/**
 * Creation procedure
 * @description Iterates at folder-array and generates VDM-Services
 */
const outputDir = 'src/sdk-vdm-services';
for (const edmxFolder of edmxFolderCollection) {
    const inputDir = 'edmxFiles/' + edmxFolder.folderName;

    // Create your project datastructure with all sourcefiles based on your options
    let generatorConfig = {
        forceOverwrite: true, // update existing files
        generateJs: false,
        useSwagger: false,
        writeReadme: false,
        clearOutputDir: true,
        generateNpmrc: false, 
        generateTypedocJson: false,
        generatePackageJson: false,
        generateCSN: false,
        sdkAfterVersionScript: false,
        s4hanaCloud: false
    };
    // generate your project, you can also redefine options
    try {
        generate({
            ...generatorConfig,
            inputDir,
            outputDir
        });
    } catch (error) {
        console.log(error);
    }
};
```

**Impact / Priority**
Due to not compilable typescript files, we're not able to continue with SAP Cloud SDK v2 upgrade and within, we're not fulfilling the SLA with SAP as the SAP Cloud SDK v2 is no longer maintained. 

Kind Regards,
Cedric

**Comment by jjtang1985** [comment]
Hi @drvup ,

Thank you for creating an GH issue.
As mentioned, we created a backlog item.
We will update you, once it's fixed.

Best,
Junjie

**Comment by FrankEssenberger** [comment]
Hi @drvup,

we meged the PR hopefully fixing the issue. The reason was that the service contained a entity name `Entity` which was causing problems in v2 where we also introduced a private field name `entity`.

The [PR](https://github.com/SAP/cloud-sdk-js/pull/2577) is already merged and you should see a new `canary` version on npm in a few minutes. You can install this version and try if it is working? We do releases every two weeks so the changes should become available in the stable version soon as well.

Best
Frank

**Comment by FrankEssenberger** [comment]
Relates to: https://github.com/SAP/cloud-sdk-js/pull/2577
