### ISSUE TITLE
Feature Request: Out-of-the-box token fetching when using code generated with the openapi-generator for talking to BTP reuse services

### ISSUE THREAD

**Issue by mr-flannery** [SAP/cloud-sdk-js#2596]
**Is your feature request related to a problem? Please describe.**

During tenant onboarding, we want to create a destination in the tenant's subaccount. We tried to implement this by using the  `openapi-generator` to generate code for the destination service. In order to make it work, we had to fetch the auth token for talking to the destination service ourselves. 

It would be more convenient if the SDK did that for me out-of-the-box.

**Describe the solution you'd like**

I have already spent some thoughts and boundary conditions and possible solutions, though my list is very likely not exhaustive.

Currently, there are two options to fetch the token:
1. Do it yourself
2. Reuse the destination service's token fetching capabilities.

Doing it myself is possible, but inconvenient.

Reusing the destination service's token fetching capabilities is fine if the the target system is maintained as a destination anyway (e.g. SAP Successfactors). However, for reuse services, this isn't something I'd typically do since they're already in my `VCAP_SERVICES`. The destination service is an awkward example, so feel free to mentally substitute it by a different service.

My best guess for a solution currently is instead of passing a `DestinationOrFetchOption` to the `execute` function, it should be possible to specify service credentials instead (e.g. by service type, label, instance name, etc., or even a combination of these; I guess similar to how `xsenv` structures its input). The SDK should then be able to fetch a token with the information from the service binding and construct a destination that it can use for the actual request.

Of course, this should be tenant-aware, i.e. it should be possible for me to specify on behalf of which tenant I want to execute the request (looking at our specific scenario, even without a full user JWT!). 

Additional complexity could come from some service bindings being maintained via the service manager instead of via `VCAP_SERVICES` / volume mounts directly.

**Describe alternatives you've considered**

We have a workaround, so all good.

**Impact / Priority**

Inconvenience, no timeline.

**Additional context**

Are you aware of the `tokenServiceURL.headers.<header-key>` (and analogous) properties? (See [docs](https://help.sap.com/docs/CP_CONNECTIVITY/cca91383641e40ffbe03bdc78f00f681/4e1d742a3d45472d83b411e141729795.html)). This did not help us with our problem, but at least judging from the type definition/autocomplete, it looks like the SDK does not explicitly support these yet.

**Comment by FrankEssenberger** [comment]
Hi @mr-flannery,

thank you for opening a feature request. I agree the current API is not really nice if you want to consume BTP service via the SDK using a generated clients, because you do not have a destination for that and also you do not want to have a destination, because it is sort of `static` information.

However, I am also a bit afraid to add more and more options to the `DestinationOrFetchOption`. Just that I get it 100% correct. You have the destination properties like `url` and only need the token for a given service. Could you perhaps reuse  the [serviceToken](https://github.com/SAP/cloud-sdk-js/blob/0675ee3bc76d48d6d64db5cac078affd69e8e555/packages/connectivity/src/scp-cf/token-accessor.ts#L26) to get a token for the BTP service you want to call and assemble a destination from there?

I know that the destination object with its `auth`property is not nice to use. Perhaps it makes sense to include some helper method in the SDK to do that for you for the BTP services. I have to discuss this with the team. 

Best
Frank

**Comment by mr-flannery** [comment]
Hey @FrankEssenberger,

> Could you perhaps reuse the [serviceToken](https://github.com/SAP/cloud-sdk-js/blob/0675ee3bc76d48d6d64db5cac078affd69e8e555/packages/connectivity/src/scp-cf/token-accessor.ts#L26) to get a token for the BTP service you want to call and assemble a destination from there?

I mentally filed that under "doing it myself", but yes, that should work as well.

> Just that I get it 100% correct. You have the destination properties like url and only need the token for a given service.

Almost. Taking a binding for the destination service as example:

```
{
   "binding_guid": "2e1f2f11-a7fd-4cb2-8699-589c42669fb6",
   "binding_name": null,
   "credentials": {
    "clientid": "<redacted>",
    "clientsecret": "<redacted>",
    "credential-type": "binding-secret",
    "identityzone": "cpaxref-provider",
    "instanceid": "e351ccda-512c-4833-9cf2-e4a48889506a",
    "tenantid": "2311cb3a-ea84-448f-a3c5-6e4b8f3f2928",
    "tenantmode": "dedicated",
    "uaadomain": "authentication.sap.hana.ondemand.com",
    "uri": "https://destination-configuration.cfapps.sap.hana.ondemand.com",
    "url": "https://cpaxref-provider.authentication.sap.hana.ondemand.com",
    "verificationkey": "-----BEGIN PUBLIC KEY-----\nMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAud3C00gz1ugiCLfr/uiH\nUuS1sGp1atHHN2piTnBs1JjGLdEnJMHUrvL9YmCAbEWJHGCGZXqweQwtpjNglQb0\n/feG8d+dhKzHop4a4IXtYUBUwU6VrySddBO4KdBzV64zzfVjSXHaLK0zkXcLOuJQ\n/hKhM4oMVMlyzaDkO7gF8jz1Re7NZ30jLOPAdRZSWsdtZh/rVOPQRu479PlTmADx\nNsCfa0NVGrpEZOrcLbVDOSt4PUBSUZXC0rJofVS3YcCNntXbD87IbScc6RxBR0tb\nSiV6IMcAVoQ2ma/jGsIsCzk9l3qYKXmyX2Mzzp1bQZicXkLfYLcnUQkUXrrnbTAp\nqQIDAQAB\n-----END PUBLIC KEY-----",
    "xsappname": "clonee351ccda512c48339cf2e4a48889506a!b19550|destination-xsappname!b433"
   },
   "instance_guid": "e351ccda-512c-4833-9cf2-e4a48889506a",
   "instance_name": "crm-destination",
   "label": "destination",
   "name": "crm-destination",
   "plan": "lite",
   "provider": null,
   "syslog_drain_url": null,
   "tags": [
    "destination",
    "conn",
    "connsvc"
   ],
   "volume_mounts": []
}
```

I would expect to get the baseURL, the token URL and the credentials from the service binding, the tenant context (subdomain/zoneId) from the user (e.g. passed as parameter to the `execute` function) and the rest from the generated code (API path, params, body, etc.).

> However, I am also a bit afraid to add more and more options to the `DestinationOrFetchOption`.

On the hand I can relate to that, this type has always felt pretty unwieldy. On the other hand I don't really see a way around that, at least not without breaking changes to the API. Maybe the type hint would be slightly more helpful if you got rid of the `DestinationOrFetchOption` type and just typed the function with an inline union type (e.g. `Destination | DestinationFetchOptions | ServiceBindingDescriptor`).

Currently in my vscode it looks like this:
![image](https://user-images.githubusercontent.com/3228218/174630734-8c6541da-6d08-4a00-b388-d04007a3c01c.png)

My hope would be that an explicit union type would also be displayed there and would therefore better convey what options a user has here.

Also I forgot to mention it in my original description, but I think my suggestion isn't much different from #2060 . We may even have the same problem.

Best,
Dennis

**Comment by FrankEssenberger** [comment]
Ah to see this in line with #2060 is a clever idea. Some of the service bindings have explicit destinations defined, but one could extend this to also create destinations for all bound services.

We already adjusted the code that the `transformFn` to handle the transformation form the binding to the destination is async so that token exchange can be performed in there: https://github.com/SAP/cloud-sdk-js/pull/2551.

We would then just need more reasonable default [transformFn](https://github.com/SAP/cloud-sdk-js/blob/615174a84789b041cd9299b22f6dd198c13488c2/packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts#L121) and in case you need something different/special you can extend/reimplement the existing method.

**Comment by mr-flannery** [comment]
> We would then just need more reasonable default [transformFn](https://github.com/SAP/cloud-sdk-js/blob/615174a84789b041cd9299b22f6dd198c13488c2/packages/connectivity/src/scp-cf/destination/destination-from-vcap.ts#L121) and in case you need something different/special you can extend/reimplement the existing method.

This is pretty important, I think. My understanding of the [Open Service Broker spec](https://github.com/openservicebrokerapi/servicebroker/blob/master/spec.md#response-6) is that service bindings _must_ contain a `credentials` object (they call it "hash", I understand that as "HashMap" or what Ruby calls a [Hash](https://ruby-doc.org/core-3.1.2/Hash.html), i.e. an object), but the concrete format is up to the provider. And I can think of at least one example (MDI) that differs from most other services.

**Comment by FrankEssenberger** [comment]
I create a backlog item and also add some bullet points and linking the two feature requests.

**Comment by mr-flannery** [comment]
Oh hey, wasn't aware you'd be tackling this issue so quickly! I took a look at the PR, I'm unsure about what the consumption would look like exactly. Is this integrated into the generated API clients so that the following magically works:

```
await new DestinationService().operation().execute("my-destination-service-binding");
```

Or am I expected to to the translation from the service binding name to the destination myself:

```
await new DestinationService().operation().execute(destinationFromServiceBinding("my-destination-service-binding"));
```

**Comment by FrankEssenberger** [comment]
The first one where `my-destination-service-binding` is the name of the service binding.  Your case is really a brain twister because you want to call the destination service :-) but it will behave the same for any other service like `business-logging`, `workflow` etc.

**Comment by mr-flannery** [comment]
Nice! Do you want feedback before merging/releasing this feature? I can't make any statements regarding timelines right now, but I'd like to try this out rather soon, have to check with the team.

**Comment by FrankEssenberger** [comment]
we can also do a quick review from our side merge it and you check out the `canary` release and give us feedback from your experience.

**Comment by FrankEssenberger** [comment]
@mr-flannery PR is merged. New `canary` version should be available in a few minutes. Is it ok to close the issue for now and you reopen it when something is not working?

**Comment by mr-flannery** [comment]
Since the requested feature has been delivered and the other issues are tracked in different tickets, I'm fine with closing this issue.

**Comment by FrankEssenberger** [comment]
Thanks for keeping track of our tickets.
