### ISSUE TITLE
Generated oData v2 VDM: DeSerializing of requests with sub-sub-selects not working as expected

### ISSUE THREAD

**Issue by drvup** [SAP/cloud-sdk-js#2606]
**Describe the bug**
I am using a generated Virtual Data Model to call an onPremise system oData v2 API and to fetch Customer data. It's all working and I am able to interact and establish a connection.
As soon as I am adding .select() statements, having sub-sub-selects, the data is coming from ERP (like expected) but the deSerializing isn't working anymore. The sub-sub-select entity and its properties are coming up as customFields instead.

**To Reproduce**
The following call is showing the sub-sub-select statement:
   ```
 const haystack2 = await customerSetApi.requestBuilder().getAll()
    .top(1)
    .select(customerSetApi.schema.ALL_FIELDS,            
        customerSetApi.schema.TO_CUSTOMER_CONTACT.select(customerContactSetApi.schema.ALL_FIELDS),
        customerSetApi.schema.TO_CUSTOMER_SALES.select(customerSalesSetApi.schema.ALL_FIELDS),
        customerSetApi.schema.TO_CUSTOMER_SALES.select(customerSalesSetApi.schema.TO_CUSTOMER_SALES_PARTNER.select(customerSalesPartnerSetApi.schema.ALL_FIELDS)),
        customerSetApi.schema.TO_CUSTOMER_SALES.select(customerSalesSetApi.schema.TO_CUSTOMER_SALES_MULTI_LANGUAGE.select(customerSalesMultiLanguageSetApi.schema.ALL_FIELDS)))
    .execute({ destinationName: config.get('DESTINATIONS.CLOUDCONNECTOR'), useCache: true })           
    console.log('Using default deSerializer this should be feasible as well: ')
    console.log(haystack2[0].toCustomerSales[0].toCustomerSalesPartner[0]);
```

**Expected behavior**
I do expect the deSerializing of the oData v2 response will be provided for sub-sub-selects in the same way it's done for selects and sub-selects.
The data of "TO_CUSTOMER_CONTACT" and also for "TO_CUSTOMER_SALES" is getting deSerialized like expected, it's just the sub-sub-selects who are missing and do appear as customFields  :(

**Screenshots**
The first screenshot shows that the data is available and the request is working. Not deSerialized, it's all fine and the json contains all selected data, within sub-sub-selects:
![CusomterSalesPartner_data_existing](https://user-images.githubusercontent.com/9018930/175311852-3a0ef45a-8f5e-486b-a51b-ab255625cfde.png)

The deSerialized approach shows you the sub-sub-selected data isn't going to be deSerialized like expected, but added as customFields instead:
![CustomerSalesPartner_as_customField](https://user-images.githubusercontent.com/9018930/175311883-1b13b1dd-04af-4d81-9703-604ec2eb766c.png)

**Used Versions:**

- node version 14.17.6
- npm version 8.1.1
- SAP Cloud SDK version: "@sap-cloud-sdk/generator": "^2.5.0"

**Impact / Priority**

This is blocking default capabilities and within our planed migration to SAP Cloud SDK v2. 
Timeline of project: Go Live end of july.

Do not hesitate to ask more details or schedule a short session to get a deep-dive about it. Thanks and Kind regards,
Cedric

**Comment by drvup** [comment]
FYI: Corresponding OSS Incident: 466600 / 2022

**Comment by jjtang1985** [comment]
Hi @drvup ,

Thanks for raising up.

We use the first response JSON and call the deserialisation function.
If the second object does not contain the expected value, most likely the deserialisation function is relevant.

Unfortunately, I could not reproduce by using this [PR](#2607), where I added a test and it passed.

Perhaps it's an edge case that is related to the specification file.
Would you like to share your specification file and the json response from the `executeRaw` so we can debug further?

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @drvup ,

Thanks for sharing the data and I can reproduce the issue.
I'll create a bug ticket and we'll update you here later.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @drvup,

Thank you very much for your feedback.
Sure, we'll update our documentation page;)

Best regards,
Junjie
