### ISSUE TITLE
Error when generating an oData client

### ISSUE THREAD

**Issue by strahilg** [SAP/cloud-sdk-js#2650]
Hi,

When I want to generate an oData client from a service metadata specification I am getting the following error:

```
ERROR    (generator-cli): ErrorWithCause: Generation of services failed.
    at /home/user/.node_modules_global/lib/node_modules/@sap-cloud-sdk/generator/dist/generator-cli.js:22:18
Caused by:
Error: Compilation Errors:
/home/user/projects/GeneratedODataClients/BatchRequest.ts:2:10 - error TS2305: Module '"@sap-cloud-sdk/util"' has no exported member 'transformVariadicArgumentToArray'.
    at transpileDirectory (/home/user/.node_modules_global/lib/node_modules/@sap-cloud-sdk/generator/node_modules/@sap-cloud-sdk/generator-common/dist/compiler.js:35:15)
    at async Promise.all (index 0)
    at async generate (/home/user/.node_modules_global/lib/node_modules/@sap-cloud-sdk/generator/dist/generator.js:57:13)
```

I installed the `@sap-cloud-sdk/generator` globally and also installed the `@sap-cloud-sdk/odata-v2` package in my project.

Note: For Development environment I am using SAP Business Application Studio.

**Comment by jjtang1985** [comment]
Hi @strahilg ,

Thank you for raising up.

Could you please share the versions of all the SDK modules like the `generator` and `odata-v2`.
Also, if you are using CAP, please also share the version.

Thank you.

**Comment by strahilg** [comment]
Hi @jjtang1985 ,

The `@sap-cloud-sdk/generator` version is 2.5.0, the `odata-v2` version is also 2.5.0.
Maybe some more details globally I have the following modules:

```
+-- @sap-cloud-sdk/generator@2.5.0
+-- @sap-cloud-sdk/openapi-generator@1.48.1
+-- @sap/cds-dk@4.7.2 
```

and in the project:

```
+-- @sap-cloud-sdk/core@1.54.2
+-- @sap-cloud-sdk/odata-v2@2.5.0
+-- @sap/cds@5.9.2
+-- @sap/cds-odata-v2-adapter-proxy@1.9.0
+-- @sap/hdi-deploy@4.4.1
+-- @sap/ux-specification@1.96.9
+-- @sap/xsenv@3.3.2
+-- @sap/xssec@3.2.13
```

**Comment by marikaner** [comment]
Hey @strahilg, we improved our documentation on this a bit. We recommend to use the generator as a local dependency, because when transpiling global dependencies are not considered. We investigated this last week and found that you can work around this by either installing `@types/node` locally or generating TypeScript code and transpiling on your own.
I think the easiest option will however be to just install the generator as a local dev dependency.

Would that work for you?

**Comment by FrankEssenberger** [comment]
Since we have not heard back for a while I will close this issue for now. Feel free to reopen if needed.

Best
Frank

**Comment by jmsrpp** [comment]
Just confirming that the fix by @marikaner worked for me. Installing ```@types/node``` locally allowed me to generate the client.

**Comment by strahilg** [comment]
Hi all, Sorry for the late reply. Yes now everything is working
