### ISSUE TITLE
Forward key+cert for mTLS Support

### ISSUE THREAD

**Issue by EchoSierra** [SAP/cloud-sdk-js#2667]
**Problem Description**
We need to use mTLS for service-to-service communication and therefore need to provide key and certificate, what is currently not possible with the cloud-sdk-js.

**Describe the solution you'd like**
We need the possibility to provide key+cert when calling/executing http request. It would be great if we could provide this e.g. in the options (options currently only supports the csrf-token).

**Describe alternatives you've considered**
We already tried setting the https agent on the destination directly, but noticed that this is not used in the http call.

**Impact / Priority**
We can't authenticate our service-to-service calls.

Affected development phase: Development

Impact: Blocked

Timeline: Go-Live is planned for 09-2022.

**Comment by marikaner** [comment]
Hey @EchoSierra,

do I understand correctly, that you basically need to use client certificate authentication? Are you aware, that you could configure this in the destination service? (Checkout this guide on [trust and key stores](https://sap.github.io/cloud-sdk/docs/js/guides/trust-and-key-stores#keystore-configuration)).

In case I am not understanding your issue correctly or you cannot use the destination service. Can you show an example what you are trying to achieve and what is not working? If you use an HTTP call, you need to add your certificate on the `httpAgent`, not the `httpsAgent`.

**Comment by EchoSierra** [comment]
Closing the issue as it became apparent the problem was caused by another component. Cloud-sdk is working as expected.
