### ISSUE TITLE
Client generator throwing multiple errors

### ISSUE THREAD

**Issue by szymarcus** [SAP/cloud-sdk-js#2774]
**Describe the bug**
On generating a new client from an .edmx file I am getting multiple missing type errors although I have installed the generator as local dependency.

The files that were generated in the outputdir does seem to be correct though.

**To Reproduce**
 `npx generate-odata-client --inputDir service-specs/ --outputDir generatedService --clearOutputDir`

**Expected behavior**
No errors should ne thrown 

**Used Versions:**

- node version via `node -v`: 18.1.0
- npm version via `npm -v`: 8.8.0
- SAP Cloud SDK version you used as dependency: "@sap-cloud-sdk/generator": "^2.7.1"

**Comment by tomfrenken** [comment]
Hey @szymarcus, thanks for reaching out to us.

Since the errors seem to be compilation errors, this has most likely to do with your `tsconfig.json`.

However, since you appear to use typescript anyways, you can set the `--generateJs false` flag.

**Comment by szymarcus** [comment]
Hey @tomfrenken thanks a lot for your quick answer. I now disabled the js generation and just compile the ts files myself within the build step.

**Comment by tomfrenken** [comment]
Glad it worked 👍
