### ISSUE TITLE
Error handling: How can I parse error responses payload?

### ISSUE THREAD

**Issue by ELMORABITYounes** [SAP/cloud-sdk-js#2779]
Right now when an API responds with an error, the SDK throws an error of type `ErrorWithCause`, but this error does not provide access to the payload of the response and the status code.

What I need is to have access to the response payload and status even if the server responds with an error just like the case in Axios, I tried using the `executeRaw` method instead of `execute`, as it was mentioned in the documentation that it provides access to the response payload and status, but it is not working for error responses and it behaves the same as the `execute` method.

Is there a way to configure the SDK to return the payload and status in the thrown errors? or to configure `executeRaw` to return all responses as `HttpResponse` so we can have access to the status and the payload of the response even in case of an error response, just like what is currently possible in [axios](https://pipedream.com/community/t/faq-how-do-i-stop-axios-from-throwing-an-error-on-4xx-5xx-requests/923) ?

Any help would be very much appreciated, thank you!

**NB**: I am using **OData v2 Type-safe Client API**.

**Comment by jjtang1985** [comment]
Hi @ELMORABITYounes ,

Thanks for approaching us.

The [executeRaw](https://github.com/SAP/cloud-sdk-js/blob/main/packages/odata-common/src/request-builder/get-request-builder-base.ts#L66) calls this [function](https://github.com/SAP/cloud-sdk-js/blob/main/packages/odata-common/src/request/odata-request.ts#L224) and gives your original response from the server, without any modifications.

However, I guess there is something wrong with the request, so an error occurs, then the SDK will catch the error and re-throw it [here](https://github.com/SAP/cloud-sdk-js/blob/main/packages/odata-common/src/request/odata-request.ts#L233). The `ErrorWithCause` is build [here](https://github.com/SAP/cloud-sdk-js/blob/0d4f8d7af327226b969f5e013774b36b1f76e113/packages/odata-common/src/request/odata-request.ts#L287) and the original error is stored as part of the stack [here](https://github.com/SAP/cloud-sdk-js/blob/0d4f8d7af327226b969f5e013774b36b1f76e113/packages/util/src/error-with-cause.ts#L19)

Therefore, please catch the `ErrorWithCause` and check the stack key of it, which should contain both status code and the response body.

Let me know, if it works.
Best regards,
Junjie

**Comment by ELMORABITYounes** [comment]
Hello @jjtang1985,

Thank you for your response.

The problem is that this stack you mentioned is a string that is built from a lot of [information](https://github.com/SAP/cloud-sdk-js/blob/056f21ad963fa4de037b541d75723e4d7e68f2c6/packages/util/src/error-with-cause.ts#L30), which - I think - makes it not possible to parse the error response data returned from the server.

The implementation you referenced is from the main branch, but I am currently using this version [v1.44.0](https://github.com/SAP/cloud-sdk-js/blob/v1.44.0/packages/core/src/odata-common/request/odata-request.ts), though there are some changes in the last version the response data is still concatenated in the stack string. 

It would have been easier if the Axios response [data](https://github.com/SAP/cloud-sdk-js/blob/056f21ad963fa4de037b541d75723e4d7e68f2c6/packages/util/src/error-with-cause.ts#L29) was added as a property to the error instead of concatenating it with the stack property, and this way the user would have full access and control over the response data.

Here is one example of the error thrown when the server responds with an error:
`
{
  "cause": {
    "cause": {
      "config": {
         "XXX": "XXXX"
      },
      "message": "Request failed with status code 400",
      "name": "Error",
      "stack": "Error: Request failed with status code 400\n at createError (/var/task/index.js:28637:19)\n at settle (/var/task/index.js:28653:16)\n at IncomingMessage.handleStreamEnd (/var/task/index.js:29254:15)\n at IncomingMessage.emit (events.js:412:35)\n at IncomingMessage.emit (domain.js:475:12)\n at endReadableNT (internal/streams/readable.js:1333:12)\n at processTicksAndRejections (internal/process/task_queues.js:82:21)",
      "status": 400
    },
    "name": "ErrorWithCause"
  },
  "name": "ErrorWithCause",
  "stack": "ErrorWithCause: OData get by key request failed!\n at new ErrorWithCause2 (/var/task/index.js:14100:28)\n at /var/task/index.js:51432:21\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at async Object.checkIfCustomerExists (/var/task/index.js:75458:27)\n at async handler_default (/var/task/index.js:75579:5)\n at async Runtime.exports.handler (/var/task/index.js:75629:5)\nCaused by:\nErrorWithCause: get request to https://XXXXXX failed! Error getting address informations for customer (XXXXXXX)\n{\"code\":\"SY/530\",\"message\":{\"lang\":\"de\",\"value\":\" Error getting address informations for customer (XXXXXX)\"},\"innererror\":{\"transactionid\":\"XXXXXXXXX\",\"timestamp\":\"20220818071450.7140140\",\"Error_Resolution\":{\"SAP_Transaction\":\"Run transaction /IWFND/ERROR_LOG on SAP NW Gateway hub system and search for entries with the timestamp above for more details\",\"SAP_Note\":\"See SAP Note 1797736 for error analysis (https://service.sap.com/sap/support/notes/1797736)\"},\"errordetails\":[{\"code\":\"/IWBEP/CX_MGW_BUSI_EXCEPTION\",\"message\":\" Error getting address informations for customer (XXXXX)\",\"propertyref\":\"\",\"severity\":\"error\"}]}}\n at new ErrorWithCause2 (/var/task/index.js:14100:28)\n at constructError (/var/task/index.js:48283:16)\n at /var/task/index.js:48255:25\n at runMicrotasks (<anonymous>)\n at processTicksAndRejections (internal/process/task_queues.js:95:5)\n at async Object.checkIfCustomerExists (/var/task/index.js:75458:27)\n at async handler_default (/var/task/index.js:75579:5)\n at async Runtime.exports.handler (/var/task/index.js:75629:5)\nCaused by:\nError: Request failed with status code 400\n at createError (/var/task/index.js:28637:19)\n at settle (/var/task/index.js:28653:16)\n at IncomingMessage.handleStreamEnd (/var/task/index.js:29254:15)\n at IncomingMessage.emit (events.js:412:35)\n at IncomingMessage.emit (domain.js:475:12)\n at endReadableNT (internal/streams/readable.js:1333:12)\n at processTicksAndRejections (internal/process/task_queues.js:82:21)"
}
`

I think with this kind of error it is not easy to access the response data or parse it.

Thank you

**Comment by jjtang1985** [comment]
Hi @ELMORABITYounes ,

Thanks for the detailed description.

First of all, the version 1 (odata clients and sdk core modules) is deprecated and the best practice is to upgrade to version 2.
Here is the [upgrade guide](https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-2).
You'll get our support if you face any questions and create issues here.

Back to your request.
The `stack` is used for printing purposes.
If you need the original Axios response data, please use the [rootCause](https://github.com/SAP/cloud-sdk-js/blob/main/packages/util/src/error-with-cause.ts#L42).

Please check my screenshot below as an example:
<img width="807" alt="Screenshot 2022-09-01 at 10 17 47" src="https://user-images.githubusercontent.com/33489572/187868957-65b0c628-b56b-45be-846f-82414f881bea.png">

I guess the logic of the `rootCause` has not been toughed from your version to the latest.

Let me know if it works.

BR,
Junjie

**Comment by ELMORABITYounes** [comment]
Hello @jjtang1985,

Unfortunately, the `rootCause` in the version I am working with seems different than what you have shown, so probably that was changed in the recent versions and we will consider upgrading to the last version.

Thank you for your support!
