### ISSUE TITLE
How to read destination URL property in Java script ( CAP NodeJS application ) deployed on Cloud Foundry ?

### ISSUE THREAD

**Issue by murthyvsap** [SAP/cloud-sdk-js#2838]
How to read destination URL property in Java script ( CAP NodeJS application ) deployed on Cloud Foundry ? 

could you please provide us JAVA script code snippet / sample , which will enable us to read the destination property like URL .

Details :  destination in subscriber sub-account "byd-url" and we want to read the property "URL" 
![image](https://user-images.githubusercontent.com/44488642/188478957-eeb13078-d958-49d6-b045-d1de58fb53e7.png)

**Comment by marikaner** [comment]
Hey @murthyvsap,

we will upgrade our samples to cover this. In the mean time use [`retrieveJwt`](https://sap.github.io/cloud-sdk/api/2.7.0/functions/sap_cloud_sdk_connectivity.retrieveJwt) and [`getDestination`](https://sap.github.io/cloud-sdk/api/2.7.0/functions/sap_cloud_sdk_connectivity.getDestination) to achieve what you need.

Sample code:
```ts
async function requestHandler(req) {
  const destination = getDestination({ jwt: retrieveJwt(req) });
}
```

Additionally you could change the isolation and selection strategy. By default the SDK uses tenant + user isolation and selects subscriber destinations first.

Hope that helps.

**Comment by murthyvsap** [comment]
Hi @marikaner 

good morning :-)  , thanks a lot for the extended help and support :-) 

the suggesion to use could sdk reuse functions [retrieveJwt](https://sap.github.io/cloud-sdk/api/2.7.0/functions/sap_cloud_sdk_connectivity.retrieveJwt) and [getDestination](https://sap.github.io/cloud-sdk/api/2.7.0/functions/sap_cloud_sdk_connectivity.getDestination) helped us to resolve the issue.

steps we followed:
**Step 1**:  import the reusable function of cloud sdk 

- const { getDestination, retrieveJwt } = require("@sap-cloud-sdk/connectivity"); 
- add the dependency in package.json "@sap-cloud-sdk/connectivity": "^2.8.0"

![image](https://user-images.githubusercontent.com/44488642/188851310-9cdaf65c-0ec9-4480-9c9b-4f18228b6857.png)

![image](https://user-images.githubusercontent.com/44488642/188851383-c044c2de-41dd-4d9a-9859-fe3aab54453d.png)

**Step 2**:  create an reusable function 

- create async function  as shown below 
`` 
// Reuse function to get the ERP URL
async function getDestinationURL(req, destinationName) {
    let destinationURL;
    try{
        // read the destination details using cloud SDK reusable getDestination function
        const destination = await getDestination({ destinationName: destinationName, jwt: retrieveJwt(req) });
        
        if(destination){
            console.log("ERP destination URL : " + destination.url);        
            destinationURL = destination.url;
        }
        else{
            // In case if the remote system detination URL is blank , then use the defualt URL ( to make sure to generate the URL for project)
            destinationURL = "https://myXXXXXX-sso.businessbydesign.cloud.sap"; 
            console.log("ERP default destination URL : " + destinationURL);   
        }
        
    }catch (error) {
        req.error(error);
    }
    return destinationURL;    
}



regards
murthy

**Comment by marikaner** [comment]
Happy it worked for you!
