### ISSUE TITLE
call to on-prem destination using ca, cert and key on custom https.Agent

### ISSUE THREAD

**Issue by vobu** [SAP/cloud-sdk-js#2865]
Hi,

we want to query an on-prem destination that expects 3 keys for authorization purposes.
For this, we're using the `requestConfig` option from `executeHttpRequest` (`@sap-cloud-sdk/http-client`) subsequently :
```js
const { executeHttpRequest } = require("@sap-cloud-sdk/http-client")
//...
const destinationOptions = {
  destinationName: "XXX"
}
const requestConfig = {
  url,
  method: "GET",
  httpsAgent: new https.Agent({
    ca: fs.readFileSync(caFile, { encoding: "utf-8" }),
    cert: fs.readFileSync(certFile, { encoding: "utf-8" }),
    key: fs.readFileSync(keyFile, { encoding: "utf-8" }),
    rejectUnauthorized: false // don't die on self-signed certs
  })
}
//...
const httpRequestOptions = {
  fetchCsrfToken: false
}
await executeHttpRequest(destinationOptions, requestConfig, httpRequestOptions)
```
However, the call is never issued as the cloud sdk fails with the error:
`ErrorWithCause: Failed to build headers`

Are we doing the request correctly as outlined above?

Thanks in advance for any pointers!

env: (app is running on BTP, cf)
- @sap-cloud-sdk/http-client: 2.8.0
- node 16.16.0
- Nodejs Buildpack version 1.7.72

**Comment by vobu** [comment]
sooo, found the culprit: 

```
File: packages/connectivity/src/scp-cf/authorization-header.ts
173:       'OnPremise connections are not possible with NoAuthentication. Please select a supported authentication method e.g. PrincipalPropagation or BasicAuthentication.'
```

Allowing on-prem connectivity via a destination w/o auth is an entirely different discussion 😸 
But what's certain is that the above error message doesn't bubble up correctly to 

```
File: packages/http-client/src/http-client.ts
428:     throw new ErrorWithCause('Failed to build headers.', error);
```

**Comment by jjtang1985** [comment]
Hi @vobu ,

Thanks for sharing the solution 👍 

> BTW: this is another prime example of Open Source FTW! 💪
Because I was able to further investigate the error myself w/o having to jump obstacles through official support channels from the very beginning.
Thanks for publishing the Cloud SDK as Open Source software 👊

Exactly, that's the idea of open source and a big thank you for your contribution to the community 😄 

I created a backlog item for your finding, let's see whether we can improve the logger.

**Comment by jjtang1985** [comment]
I'll close this ticket as it's done.
The following improvement ticket will be refined soon.
