### ISSUE TITLE
Support for many-to-many associations

### ISSUE THREAD

**Issue by jmsrpp** [SAP/cloud-sdk-js#2999]
**Is your feature request related to a problem? Please describe.**

I am currently unable to create an association using a $links segment for a many-to-many association, using the [API Proxy](https://api.sap.com/api/APIPortal_APIProxy_CF/resource) and [API Product](https://api.sap.com/api/APIPortal_Product_CF/resource) resources of SAP API Management. It requires a POST to the $batch endpoint of the service (there are some examples in the Batch Requests section of the API Proxy resource on API Business Hub). 

**Describe the solution you'd like**

I would like to be able to build the correct URL using [asChildOf](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v2-type-safe-client-for-javascript-typescript#create-as-child-of), as it allows me to address the specific record and not the entire entity (e.g. /APIProducts('Federated_API') vs. /APIProducts). However, asChildOf requires me to pass the navigation field (e.g. apiProxiesApi.schema.API_PRODUCTS), which does not include the required $links segment.

Ideally, SAP Cloud SDK would identify this is a many-to-many association from the model metadata and automatically build the URL:

<NavigationProperty Name="apiProducts" Relationship="apiportal.APIProxy_APIProduct_Many_Many0" FromRole="APIProxy" ToRole="APIProduct"></NavigationProperty> 

However, it would also be acceptable to pass this leading segment as an additional property to the asChildOf method as a workaround.

**Describe alternatives you've considered**
I have tried many combinations of asChildOf, appendPath, Deep Create, etc. without any luck. My only other recourse is to use an external library but I would lose the benefits of destination support and the conciseness of the fluent API.

**Impact / Priority**

Affected development phase: Release

Impact: Blocked

Timeline: Release scheduled for Q4 2022

**Additional context**
This is part of a code sample showing customers how to federate API documentation between different gateways (both SAP and Non-SAP) for a unified API catalog. It reacts to an inbound event, fetches the Open API spec programmatically from another provider, and creates a Remote API in SAP API Management.

Here is a complete sample payload for the batch call:

```
--batch_b2fe-fc86-d733
Content-Type: multipart/mixed; boundary=changeset_dbf2-c5bb-a344

--changeset_dbf2-c5bb-a344
Content-Type: application/http
Content-Transfer-Encoding: binary

PUT APIProducts(name='SimplifiedS4HANAProducts') HTTP/1.1
x-csrf-token: d776c7a92458b493-_X7FJI30ncQz7nl3UV0xvW856cU
Accept-Language: en
Accept: application/json
MaxDataServiceVersion: 2.0
DataServiceVersion: 2.0
Content-Type: application/json
Content-Length: 249

{"name":"SimplifiedS4HANAProducts","title":"Simplified S/4HANA Product API","scope":"","description":"<p></p>","version":"1","status_code":"PUBLISHED","isRestricted":false,"isPublished":true,"quotaCount":-99,"quotaInterval":-99,"quotaTimeUnit":null}
--changeset_dbf2-c5bb-a344
Content-Type: application/http
Content-Transfer-Encoding: binary

POST APIProducts(name='SimplifiedS4HANAProducts')/$links/apiProxies HTTP/1.1
x-csrf-token: d776c7a92458b493-_X7FJI30ncQz7nl3UV0xvW856cU
Accept-Language: en
Accept: application/json
MaxDataServiceVersion: 2.0
DataServiceVersion: 2.0
Content-Type: application/json
Content-Length: 32

{"uri":"APIProxies('Ping_CPI')"}
--changeset_dbf2-c5bb-a344
Content-Type: application/http
Content-Transfer-Encoding: binary

POST APIProxies(name='Ping_CPI')/$links/apiProducts HTTP/1.1
x-csrf-token: d776c7a92458b493-_X7FJI30ncQz7nl3UV0xvW856cU
Accept-Language: en
Accept: application/json
MaxDataServiceVersion: 2.0
DataServiceVersion: 2.0
Content-Type: application/json
Content-Length: 49

{"uri":"APIProducts('SimplifiedS4HANAProducts')"}
--changeset_dbf2-c5bb-a344--

--batch_b2fe-fc86-d733--
```

**Comment by marikaner** [comment]
Hey @jmsrpp, in fact, we currently do not support this. We will try to come up with a solution, but I cannot promise that we will implement and release this future in Q4 2022. We will also discuss workarounds and will come back to you as soon as possible.

**Comment by jmsrpp** [comment]
Hey @marikaner - Thanks a lot for responding to me. I understand and appreciate you discussing within the team. Feel free to reach me directly if you need any additional clarification or examples.

**Comment by jjtang1985** [comment]
Dear @jmsrpp ,

Thank you very much for raising up in our OS repo.

I created a PR for adding more tests [here](https://github.com/SAP/cloud-sdk-js/pull/3016) for using `appendPath`:
- with create requests
- with batch requests 

These tests are good examples for your use case.
It would be great if you can try and share your feedback.

> Timeline: Release scheduled for Q4 2022

Regarding your time line, to be very honest, we are working on the next major version update.
I guess it's not realistic to completely support this feature with our typed client, before your deadline.

We are working on aligning an ADR, though, so the future plan will be clarified.

Let me know, if you have any questions.

**Comment by jmsrpp** [comment]
Hi @jjtang1985 ,

Thanks for your efforts and for the sample. As mentioned to @marikaner, I understand the timeline constraints but wanted to be transparent about our previous plans. I reviewed the changes and have 2 questions:

1. How can I address creation of the link as a child entity, as follows? In this case I need to append the parent entity, which I was currently using asChildOf to generate. This prohibits me from appending /$links and /apiProducts as I need to specify the relationship field (e.g. apiProxiesApi.schema.API_PRODUCTS)
**APIProxies(name='Ping_CPI')/$links/apiProducts**
2. What is .stringProperty method of the entity builder? I could not find it in the documentation.

**Comment by jmsrpp** [comment]
Hi @jjtang1985 @marikaner - Thanks for the follow up on this issue. I was able to get it working as it seems appendPath can be used to append anything and not just paths. I eliminated asChildOf and added something like:

.appendPath(`(name='Federated_API')`, '/$links', '/apiProxies');

or

.appendPath(`(name='${proxyName}')`, '/$links', '/apiProducts');

to the requestBuilder() calls for each entity. I also had to add 'as any' to the create() and changeset() calls to prevent compilation errors. Even though it is less than ideal, I can utilize this as a workaround in Q4 while you finalize an ADR and plan for type-safe support in the future.

**Comment by jjtang1985** [comment]
Hi @jmsrpp ,

Awesome.
I'm happy to see it's working with the workaround.
Thanks for sharing your examples.

To answer your question:
> What is .stringProperty method of the entity builder? I could not find it in the documentation.

The `stringProperty` is just a normal property of our test entity like any known properties of `ApiProxies` defined in the specification file in your case.

I'll leave this ticket open and update later.

**Comment by jjtang1985** [comment]
Hi @jmsrpp, 

> I can utilize this as a workaround in Q4 while you finalize an ADR and plan for type-safe support in the future.

We had an internal alignment regarding this.
The "productive" would be using an "untyped"/"generic" OData client, which will hopefully be started early next year.

As a generic OData client, it should be used for "advanced" use cases that are not supported by the "typed" client.
A quick overview about the generic OData client would be the "Java SDK" [documentation](https://sap.github.io/cloud-sdk/docs/java/features/odata/generic-untyped-odata-client).

@marikaner , let's prioritise the generic client.

**Comment by jjtang1985** [comment]
Unfortunately, we will not work on this topic due to other priorities.
