### ISSUE TITLE
Cannot generate client consuming entity named "Service"

### ISSUE THREAD

**Issue by Jibbril** [SAP/cloud-sdk-js#3041]
**Describe the bug**
I am currently trying to upgrade from using the SAP Cloud SDK version 1.54.2 for javascript to version 2.10.0 and I am running into an issue. I'm looking to [generate an oData client](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client), and everything works as intended in the v1 SDK. However, in v2 there is a file called "service.ts" generated automatically when creating the client which is not there in v1. This causes an issue for me since one of the entities in the service I am consuming is named "Service" (capital S). Thus there is both a "service.ts" and a "Service.ts" generated in the client folder, which causes the generator to crash.

**To Reproduce**

1. Setup an odata v2 service with an exposed entity named "Service".
2. Fetch the edmx of the service. 
3. Use the fetched edmx to generate an odata client using the `generate-odata-client` command. 

**Expected behavior**
An odata client is generated in the specified output folder. 

**Used Versions:**

- node version: 16.17.1
- npm version: 8:15.0
- SAP Cloud SDK version: 2.10.0

**Log file**
The error message when the generator crashes: 

`error TS1149: File name '.../service.ts' differs from already included file name '.../Service.ts' only in casing.`

**Impact / Priority**
Upgrading to version 2 is quite important since v1 is no longer being supported. 

Affected development phase: Development

Impact: Impaired

Timeline: Ideally end of week, latest next week.

**Additional context**
I posted a question on the sap answers.com forums [here](https://answers.sap.com/questions/13750896/cannot-generate-client-consuming-entity-named-serv.html).

Image of the files being generated in the client folder: 
![image](https://user-images.githubusercontent.com/29061837/200838909-244b0c50-9cf2-406c-a0f0-ce86500dbf14.png)

Any help would be much appreciated! 

Best regards,
Jibbril

**Comment by jjtang1985** [comment]
Hi @Jibbril ,

Thanks for raising up.

Could you please share the edmx specification file so we can reproduce?

Best regards,
Junjie

**Comment by Jibbril** [comment]
I am unable to share these things due to secrecy issues, I have however created a small SAP CAP repo [here](https://github.com/Jibbril/sap-cloud-sdk-service-case-problem) showcasing the issue. Check the readme for instructions. 

Best regards,
Jibbril

**Comment by jjtang1985** [comment]
Hi @Jibbril ,

Understood.
Thanks for sharing the CAP model, which is useful.

We'll work on it soon and will update you.

FYI, we are working on the next major version update, I hope we can finish it next week, but I cannot make a promise.

**Comment by jjtang1985** [comment]
Hi @Jibbril ,

The fix was merged last week and you can test the `canary` version now.
We'll release a new stable version next week.

Please let me know, whether it works.
Best regards,
Junjie

**Comment by Jibbril** [comment]
Hello @jjtang1985,

I checked out the canary version and it seems to be working now. Looking forward to the stable version, thanks a lot!

Best Regards,
Jibbril

**Comment by Jibbril** [comment]
Hello @jjtang1985,

I checked out the canary version and it seems to be working now. Looking forward to the stable version, thanks a lot!

Best Regards,
Jibbril
