### ISSUE TITLE
LICENSE

### ISSUE THREAD

**Issue by luizcarlospedrosogomes** [SAP/cloud-sdk-js#3113]
Is the license description correct? Can't I use it in a productive environment?
Can't I use it in projects outside of SAP?

**Comment by jjtang1985** [comment]
Hi @luizcarlospedrosogomes ,

Thanks for raising up.

The license (Apache 2.0) is correct, as shown in this repository.
You can also find the same license information on the npm like this [example](https://www.npmjs.com/package/@sap-cloud-sdk/http-client) of our `http-client`.

Therefore, with this license:
- you can use it in a productive environemnt
- there is no restriction about inside/outside of SAP

The SAP Cloud SDK for JavaScript also released pre-generated clients (or known as VDMs) before like this [example](https://www.npmjs.com/package/@sap/cloud-sdk-vdm-business-partner-service).
These pre-generated clients have different licenses, as shown in the example page.
However, these packages have been deprecated and will not be maintained.

In case you have doubts about the license, you can always trust the information from npmjs.com.

Let me know, if you have questions.

Best,
Junjie

**Comment by luizcarlospedrosogomes** [comment]
@jjtang1985 thanks
 "This project depends on libraries licensed under the [SAP Developer license agreement](https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt). This limits the use of those dependencies to development purposes only."

Your answer deals with the first part of the licensing (Readme.md) but what about the second part? What does that mean?

**Comment by jjtang1985** [comment]
Hi @luizcarlospedrosogomes,

When you are asking a question regarding the "SAP Developer license agreement", I assume:
- you are not talking about the GitHub source code (Apache 2.0)
- you are not talking about the SDK Core packages on npm like `@sap-cloud-sdk/http-client` (Apache 2.0)
- **you are talking about the SDK regenerated pageasges (VDM) on npm like `@sap/cloud-sdk-vdm-business-partner-service` (SAP Developer license agreement)**

If so, as a developer, I cannot answer you immediately, as I'm not a legal expert, but I'll forward a message to the team and see how I can help.
@marikaner

**Comment by marikaner** [comment]
@luizcarlospedrosogomes Yes, you can use the SAP Cloud SDK in your productive project outside of SAP. I see how "development purposes only" can be confusing. What is meant is that we have dependencies, that you can not use for certain purposes as described in the [SAP Developer licence agreement](https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt). You can, however, use this for your applications.

SAP's APIs, that you find on APIHub are also published under the SAP Developer licence agreement. You are allowed to use them productively as well.

(Still, I am also not from the legal department, FYI ;) )

Hope that helps!

**Comment by jjtang1985** [comment]
Hi @luizcarlospedrosogomes ,

> news?

I hope @marikaner 's answer helps a bit.

Let me know, if you have questions.

**Comment by luizcarlospedrosogomes** [comment]
I had understood that there is a legal gap in licensing. But reviewing the answer again I realized that this has already been considered.
In summary, the fact that the readme.md indicates 02 licenses does not prevent me from considering only the Apache 2.0 license.

Right?

**Comment by marikaner** [comment]
Hey @luizcarlospedrosogomes,

I confirmed once more with legal to make absolutely sure and this is the statement:
> "SAP Cloud SDK for JavaScript" itself can be used freely under Apache 2.0 while any "libraries licensed under the SAP Developer License Agreement" can only be used according to the limitations of that license. Just because the project itself is under Apache 2.0 does not change the fact that other pieces may be more restricted.

I don't know what you are intending to do, therefore I find it very difficult to give you a clear yes or no. You can consume the SAP Cloud SDK under Apache 2.0. If you intend to do anything related to the dependencies that are not Apache 2.0, different regulations may apply.

**Comment by luizcarlospedrosogomes** [comment]
I will only use it in projects outside of SAP. As a service that communicates with another ERP (TOTVS). That kind of project. As if the lib were an open-source project and you could use it wherever you want, including large companies with billionaire revenues.

**Comment by xLexip** [comment]
Hey @jjtang1985 and @marikaner , 

I have a clarification question: How can this project be license under `APACHE-2.0` when the `SAP DEV. LICENSE AGREEMENT v3.1` is "non-sublicensable"? Doesn't that mean, that it restricts you from granting additional rights or permissions in this project that are not already granted by the original license? Especially, when `APACHE-2.0` grants general distribution (that is crucial for a commercial use of this cloud-sdk module in customer applications.) 


Quote from [SAP DEV. LICENSE AGREEMENT ](https://tools.eu1.hana.ondemand.com/developer-license-3_1.txt)at  2.a.b:

> You may not [...] provide or make the APIs, Tools or Software available to any third party

...and from 2.a.c:

> You may not [...] assign this Developer Agreement or give or transfer the APIs, Tools or Software or an interest in them to another individual or entity

In my opinion, it is a significant license conflict when [APACHE-2.0](https://github.com/SAP/cloud-sdk-js/blob/main/LICENSE) states: 

> [...] You may reproduce and distribute copies of the
      Work or Derivative Works thereof in any medium, with or without
      modifications, and in Source or Object form [...]

In view of these quotes, this project itself violates `SAP DEV. LICENSE AGREEMENT`, doesn't it? And we cannot use this module in applications for our customers without - at least indirectly - violating the license agreement. 

I would be very grateful if you help us understand this.

Thanks in advance and best regards
Lexip

**Comment by jjtang1985** [comment]
Hi @xLexip ,

Thanks for approaching us.

Maybe disclaimer first:
- Both @marikaner and myself are developers/POs of the SDK
- We might not be able to answer complicated legal questions
- We can forward your questions to our legal/license/Open Source Office etc. We will show you the answer from the colleagues, but feel free to contact them directly, if possible.

I got an answer from my colleague, about using dependencies under "SAP Developer License" directly in the SDK (under Apache 2.0). As we only ship SDK code to npmjs.com without containing the dependencies, this is not a problem.
Here is the original answer:
> your package only contains the Apache 2.0 code and you don’t sublicense anything. Npm automatically downloads the dependencies and neither Apache 2.0 nor the Dev License are violated.

> And we cannot use this module in applications for our customers without - at least indirectly - violating the license agreement.

I guess the previous messages from @marikaner should be clear for your questions:
- https://github.com/SAP/cloud-sdk-js/issues/3113#issuecomment-1328885847
- https://github.com/SAP/cloud-sdk-js/issues/3113#issuecomment-1346522490
Also, just FYI, we have lots of external customers/partners who are using the SDK for commercial use cases.

I hope it helps.
Best regards,
Junjie
