### ISSUE TITLE
Provide type definitions for all packages

### ISSUE THREAD

**Issue by brodo** [SAP/cloud-sdk-js#3343]
**Describe the solution you'd like**
`@sap/xsenv` and `@sap/xb-msg` (and probably others) do not come with Typescript type definitions. I would like you to provide some.

**Describe alternatives you've considered**
I am currently writing some myself, which is not ideal.

**Impact / Priority**

Getting started: I think a lot of people will just use other libraries when they see that the SAP library comes without type definitions because writing/generating the definitions yourself is tedious.

**Comment by florian-richter** [comment]
Hi @brodo,

our team is not responsible for the libraries you mentioned. Our team will not provide type definitions for other SAP libraries. Instead I reached out to the maintainers to inform them and will let you know how to contact them once I heard back.

Sorry that I can't be of more help!

**Comment by florian-richter** [comment]
Hey, I checked with the colleague behind xsenv. They are now aware of the issue, but you can open a formal request through ServiceNow with the component BC-XS-JS
