### ISSUE TITLE
Issue while runnning MBT build command in CAP project

### ISSUE THREAD

**Issue by Rohit52080** [SAP/cloud-sdk-js#3350]
While running the MBT build command in the CAP project in sap BAS, I am getting the error " Version 1 of SAP Cloud SDK is no longer maintained. Check the upgrade guide for switching to version 2: https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-2.
npm ERR! code E404"

Where do I have to make changes to make it work? I do not see any module in package.json. 
Please suggest

**Comment by florian-richter** [comment]
You are likely using an older version of CAP that has a dependency on the unsupported version 1 of the SAP Cloud SDK. You can find that information in the `package-lock.json` or by calling `npm ls PACKAGE_NAME` (replace PACKAGE_NAME with `@sap-cloud-sdk/core` or another impacted package name.

To resolve the issue, you will need to upgrade to CAP version 6.
