### ISSUE TITLE
Expose health endpoints

### ISSUE THREAD

**Issue by MartinPankraz** [SAP/cloud-sdk-js#3371]
Dear community,

how would you suggest to enable health check endpoints using the SDK? With the current feature scope a costly GET operation towards any object would be required. Would it be possible to add HEAD to your generator scope? Do you have other suggestions to address?

PaaS environments offer features like self-recovery etc. based on health-endpoints.

**Comment by tomfrenken** [comment]
Hey Martin,

To better understand your use case, this would refer to a use case where PaaS developers want to perform health checks (preferably `HEAD` as it's less costly), is that correct?

The benefit of a `GET` request with our typed clients is that we already type the response, with a HEAD request however you wouldn't receive a response body, therefore if you _only_ would perform health checks perhaps the typed client is a little overkill.

For this specific case, perhaps [our generic client](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/http-client) would be a better choice, where you can choose the specific method (like `get`/`post`/`head`).

Would this be sufficient for your use case, or do you already use the typed client and would need the `HEAD` operation in addition to the rest?

**Comment by MartinPankraz** [comment]
Hi Tom,

yes that is correct. The PaaS platforms often expose built-in functionality when pointed at the health endpoint of the app. Hence my request.

By no means is a typed client required for the HEAD operation, since no objects are called for. However, in my case I have a typed client for the OData request. So, in order to make the health check I need to add the generic client only for that purpose now taking additional dependency.

**Comment by jjtang1985** [comment]
Hi @MartinPankraz ,

Thanks for reaching out.

> for that purpose now taking additional dependency.

No, you'll **not** need any new dependencies.
The generic http client is documented [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/http-client) and the package is [here](https://www.npmjs.com/package/@sap-cloud-sdk/http-client)

This dependency is a transitive dependency if you use OData clients (see [package.json](https://github.com/SAP/cloud-sdk-js/blob/v2-main/packages/odata-v2/package.json#L41)) or OpenAPI clients (see [package.json](https://github.com/SAP/cloud-sdk-js/blob/v2-main/packages/openapi/package.json#L41)).

**Comment by MartinPankraz** [comment]
Choosing the generic client for the health checks now. Thanks for your insights :-)
