### ISSUE TITLE
OpenAPI SDK Generator Customisation/Extensibility Questions

### ISSUE THREAD

**Issue by uroslates** [SAP/cloud-sdk-js#3413]
Hello Colleagues,

First of all - kudos for your good work!

We from CX Team are considering usage of your OpenApi SDK generator library for our internal/external SDK generation. We have compiled a list of questions where we would really like to hear you opinions/feedback related to them, which might help us proceed further. 

We want to thank you in advance!

-----

Please find the list of questions below:

- Is Isomorphic API support on the radar?
  - Is Browser first support on the radar (so that no polyfills are required for the Browser)?
  - Is Edge support (on the radar)?
  - Is Tree Shakebility in ADR (support/plans/guidelines)
    - Any Plans for making the API thiner/lighter (for Browser/Edge)

- Recommendations for filtering out (excluding) parts of specification (reducing generated SDK codebase) (eg B2C out but leave B2B in SDK):
  - separating one spec in multiple Spec Files and ignore some spec by reducing input property
  - Spec tags based filtering (or similar) - Is there support 4 that already in generator (how)?

- Recommended way (examples) of replacing http client (connectivity layer/lib) implementation (per default Axios)
  - Support/Exposure of Axios interceptors (example) - (is this inteded to be replaced by middlewares)

- Templates Customisation support?
  - Recommendations for these (when needed)?
  - Plans to support overriding by providing externalised custom templates through generator command parameter?

- Auth workflows:
  - Are there exposed SDKs implementing auth flows obtaining JWT code utilities), or it’s counted as a clients responsibility?

- Best practices (recommendations)
  - for extending the JS SDK generator (eg. implementing custom Caching/Logging/ support in JS SDK)?

- Plugins support/examples (in JS SDK generator)?
  - Any exposed Extensions? (Examples/Guides around implementing JS SDK generator Extensions)?

- V3 (JS SDK) Release Plan?

Kind Regards,
Uros

**Comment by FrankEssenberger** [comment]
Regarding the axios question, we give you the request config  in the middleware and the function executing it in the middleware. So you could replace this which you own function as long it can work with the axios request config. This is possible since it contains usual things like url, headers and so on.

**Comment by uroslates** [comment]
Hi @jjtang1985 @FrankEssenberger ,


first of all thank you very much for your feedback!



> Unfortunately, I don't really get this question, typically could you please explain more about "Isomorphic API"?
  - Sorry I meant to say "Isomorphic JS SDK" - which you guys have in a way (but requiring polyfills for the Browser execution).

> To be honest, we are still discussing the frontend/browser support topic, and we are happy to know details of your use cases.
  - Context: Yes I was able to make the *generated SDK code work in the Browser* (by using a **set of polifills** below and additionally including `import "setimmediate";` within the loaded js). 
    - ```js config.resolve.fallback = {
      ...config.resolve.fallback,
      setImmediate: false,
      os: false,
      url: false,
      http: false,
      fs: false,
      path: false,
      assert: false,
      zlib: false,
      tls: false,
      net: false,
      constants: false,
      setimmediate: require.resolve('setimmediate'),
      util: require.resolve('util'),
      process: require.resolve('process/browser'),
      stream: require.resolve('stream-browserify'),
      buffer: require.resolve('buffer'),
      console: require.resolve('console-browserify'),
      crypto: require.resolve('crypto-browserify'),
      https: require.resolve('https-browserify'),
    };```
  - But **our goal is** providing an Isomorphic SDK that is *Browser first (meaning making it work in Browser W/O any polifills, and if really required than let the polifills be used on Node.js side)*. The reason behind this is that we have to make sure that **the Browser's code (the bundle size) is as minimal as possible** (improving Core Web Vitals)!
    - At the moment **having Polifils increases the Browser bundle sizes quite a bit**, even though *the generated SDK code itself is tree shakeable* (but polifilled code is not since its introduced by connectivity library and its dependencies). *So our question would be is there any plan of adressing this (making it polifill free on the Browser side by making adjustments in the implementation)?*

- Thanks for the hints on **using custom http client** (via [Middlewares](https://sap.github.io/cloud-sdk/docs/js/v3/features/middleware#example))


Thank you very much on your kind input & support!

**Comment by jjtang1985** [comment]
Hi @uroslates ,

I'm back to the second half.

Thank you for sharing your user stories of the browsers.
We'll have an internal discussion next week. FYI @marikaner .

> Templates Customisation support?
Recommendations for these (when needed)?
Plans to support overriding by providing externalised custom templates through generator command parameter?

Could you please share more details about the "templates"?
What "templates"? Templates of the generated clients?
Also, which potential customisation can be?

> Auth workflows:
Are there exposed SDKs implementing auth flows obtaining JWT code utilities), or it’s counted as a clients responsibility?

With the help of the generated OpenAPI client, you are able to execute (see [doc](https://sap.github.io/cloud-sdk/docs/js/features/openapi/execute-request#executing-a-request)) a request against a given destination.
As you mentioned the auth workflow, I assume you are talking about the destination service on BTP.
Please check the doc [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#destination-service) about the supported authentication types on BTP.
If the authentication type is supported, the SDK will fetch the auth token for you, and here is the sample code, where you just have to provide your destination name:
```
MyApi.myFunction().execute({ destinationName: 'myDestination' }); // when JWT is not needed
```
or
```
MyApi.myFunction().execute({ destinationName: 'myDestination' , jwt: 'yourJWT'}); // when JWT is needed
```

> Best practices (recommendations)
for extending the JS SDK generator (eg. implementing custom Caching/Logging/ support in JS SDK)?

The SDK uses "winston" under the hood for handling logging functionalities. We are aware this might be a problem for frontend (browser) use cases, so this is also part of the "frontend support" topic in the future (potential roadmap item). On the other hand, we will also re-verify the [cf-logging-lib](https://www.npmjs.com/package/cf-nodejs-logging-support). For the time being, unfortunately, no customisation is possible. Please create a feature request 😄 

Regarding the cache, could you please share your use cases?
We do have destination cache (see [doc](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination-cache)) and here is the customisation [doc](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination-cache#custom-destination-service-cache)

> Plugins support/examples (in JS SDK generator)?
Any exposed Extensions? (Examples/Guides around implementing JS SDK generator Extensions)?

Please describe more about the "plugins" and the "extensions".

I hope I did not miss any questions.

Best regards,
Junjie

**Comment by uroslates** [comment]
Hi team, thanks a lot for your answers.

As for the Templates:

> Could you please share more details about the "templates"?

> What "templates"? Templates of the generated clients?

> Also, which potential customisation can be?

  - I'll try giving our way of looking at things:
    - We really like the syntax you guys are imposing when generating SDKs (based on the spec). There might be a times when we would also like to be able to reuse the validation/parsing phase of the generator but customzie the generated output (through customization of externalized templates - similar to the way its achieved in OpenAPI Generators through `-t` option). 
    - The reasoning behind it might be (just as an example) auto-generating adapters targeting specific FE frameworks (like Angular rx adapters, React hooks,... or similar). These would be services or effects or whatever, where we would be able to wrap the generated SDK API methods and decorate or adapt them for easier usage within the targeted framework. In case U need more elaboated answer we might organise a meeting or suggest it as a feature in your repo.

> The SDK uses "winston" under the hood for handling logging functionalities. We are aware this might be a problem for frontend (browser) use cases, so this is also part of the "frontend support" topic in the future (potential roadmap item).
  - Yes that was exactly our main concern. Thanks a lot for giving us a heads up on that.
  
Regarding the cache, thanks a lot for the links!


Kind regards,
Uros

**Comment by jjtang1985** [comment]
I hope all the questions are answered, so I'll close the ticket.
