### ISSUE TITLE
Support  iss and userJwt Combination

### ISSUE THREAD

**Issue by FrankEssenberger** [SAP/cloud-sdk-js#3499]
Relates to [this public issue](https://github.com/SAP/cloud-sdk-js/issues/3067) or this [BLI](https://github.com/SAP/cloud-sdk-backlog/issues/984)

In their project @ww917352 they are doing the following:

- They have a refresh token
- They transform it to a JWT with user information using some stored client credentials - they could also use the destination service with `OAuth2RefereshToken` for that but this would mean one more call. So they do it directly
- Then they use this token to fetch a desination `executeHttpRequest({destinationName:'theirDest',jwt:'obtainedUserJwt'})
- However, they receive an error from the `@sap/xssec` library: 

> Jwt token with audience: [ 'uaa', 'sb-xsuaa!b30841' ] is not issued for these clientIds: [\n  'sb-uaa-action-runtime-service-xsappname!b43524',\n  'uaa-action-runtime-service-xsappname!b43524'\n].

This error comes from the fact, that we always try to get a service token for the given JWT. This was also an issue in the issue mentioned above. If they do the following:

- Get a client credentials grant token for the bound destination service (we call this provider service token in SDK code)
- Make a call to the destination service with
   -  `X-user-token` header their user token
   -  `authorization` the provider service token
- they get the destination with auth tokens exchanged as expected.

My initial idea to solve this issue would be the following:
- We implement the lazy token loading as mentioned in the issue above. 
- The `selectionStrategy: alwaysProvider` on the `executeHttpRequest({destinationName:'therDest', jwt:'ibtainedUserJwt', selectionStrategy: alwaysProvider})`

There could also be the option that we allow to specify some headers directly in the fetch options of the destination. Then you could even combine with the `iss` property so you get a service token for some tenant and provide the usertoken manually to have full flexibility:

```
executeHttpRequest({destinationName:'therDest', iss:'ibtainedUserJwt', 'X-user-header': somevalue})
```

**Comment by FrankEssenberger** [comment]
I thought about it a bit and currently we ignore the the `iss` options if the `jwt` is given in addition. However, we could allow to combine these such as:
- iss -> determines the service token (no validation via xssec library)
- jwt -> determines the X-user-tenant if the token flow requires it.

@ww917352 what do you think?

**Comment by FrankEssenberger** [comment]
I thought about it a bit and currently we ignore the the `iss` options if the `jwt` is given in addition. However, we could allow to combine these such as:
- iss -> determines the service token (no validation via xssec library)
- jwt -> determines the X-user-tenant if the token flow requires it.

@ww917352 what do you think?

**Comment by ww917352** [comment]
Yes, that is what I tried to suggest in our meeting. If both are provided, there is no need to fetch a service token from the user token, because it can be fetched using `iss`. In this case, we can get service token using `iss`, and set the user token `jwt` as the `X-user-token` header.

**Comment by ww917352** [comment]
@FrankEssenberger 

Hi Frank,

Any update on the plan to support this in V3? We are already using V3 now.

Thank you!

Cheers,
Wei

**Comment by marikaner** [comment]
The last PR to fix this was just merged. Now you should be able to use both `iss` and `jwt` in a manner that `iss` identifies the tenant when fetching destinations and `jwt` identifies the user (without validation). We will release a new productive version within this week, feel free try the canary version before to make sure it works as you expect it.
