### ISSUE TITLE
The 'url' property is not set for destination undefined which is mandatory if you use it as an 'HTTP destination

### ISSUE THREAD

**Issue by ptesny** [SAP/cloud-sdk-js#3625]
The following error message is thrown by `executeHttpRequest` method for a registered destination:
```
"The 'url' property is not set for destination undefined which is mandatory if you use it as an 'HTTP destination"
```

1. Create and register an inline destination definition:

https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#register-destination

```
const cloudSdkConnectivity = require('@sap-cloud-sdk/connectivity');

const poster = {
          name: "POSTER-DESTINATION",
          url: "https://poster.mydomain.com",
          forwardAuthToken: true
        };

await cloudSdkConnectivity.registerDestination(poster, {jwt: retrieveJwt(req) });

```
2. Retrieve the registered destination calling `getDestination` method:
```
  const destinationFetchOptions = 
      {
          destinationName: POSTER-DESTINATION",
          jwt: retrieveJwt(req),
          useCache: true,
      };

const destination = await cloudSdkConnectivity.getDestination(destinationFetchOptions);

```
and here goes the result of the above call:
```
[2023-03-07T07:32:28.416Z] [32mINFO[39m (register-destination): Successfully retrieved destination 'POSTER-DESTINATION' from registered destinations.
destination: {
"name": "POSTER-DESTINATION",
"url": "https://poster.mydomain.com",
"forwardAuthToken": true,
"authTokens": [
{
"value": "eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBzOi8vYXRlYW0uYXV0aGVudGljYXRpb24uc2FwLmhhbmEub25kZW1hbmQuY29tL3Rva2V
dRtbGkUZGSO_vj1_YA",
"expiresIn": "1678217546",
"error": null,
"http_header": {
"key": "Authorization",
"value": "Bearer eyJhbGciOiJSUzI1NiIsImprdSI6Imh0dHBzOi8vYXRlYW0uYXV0aGVudGljYXRpb24uc2FwLmhhbmEub25kZW1hbmQuY29tL3Rva2VudRtbGkUZGSO_vj1_YA"
},
"type": "Bearer"
}
]
}

Please notice the registered and then retrieved `POSTER-DESTINATION` has the `url` member se to the value of the business urlt!
```
4. execute the business function via the above destination:
```
const response = await httpClient.executeHttpRequest(
  {
    destination: "POSTER-DESTINATION"
    ,
    jwt: retrieveJwt(req)
  }
);
```

5. See the error payload
```
2023-03-07T07:32:28.420Z faas-srv:function /srv/poster The 'url' property is not set for destination undefined which is mandatory if you use it as an 'HTTP destination Error: The 'url' property is not set for destination undefined which is mandatory if you use it as an 'HTTP destination
at assertHttpDestination (/usr/src/app/function/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-service-types.js:11:15)
at /usr/src/app/function/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:85:46
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async main (/usr/src/app/function/handler.js:256:30) {
```

**Expected behavior**
According to the sdk documentation the `executeHttpRequest` method performs a call to `getDestination`;
And, as proven, it [ getDestination] can retrieve the destination definition;

Thus, the error message thrown by `executeHttpRequest` is beyond rational understanding.

**Used Versions:**

- node version via `node -v` 18.14.2
- npm version via `npm -v`.  9.x
- SAP Cloud SDK version you used as dependency : 3.0.1 but same is valid for 2.15

**Additional context**
https://answers.sap.com/questions/13673091/sap-cloud-sdk-javascript-destinationobjects-from-d.html

**Comment by ptesny** [comment]
Thus, in order to demonstrate my last assumption is a valid one I have repeated a call to `executeHttpRequest` this time by explicitly adding the required header as follows:

```
  const key = destination.authTokens[0].http_header.key;
  const value = destination.authTokens[0].http_header.value;
  const url = destination.url+req.query.path;
  var options = {
    method: 'get',
    url: url,
    timeout: 60*10000,
    headers: {}
  }
  options.headers[key] = value;

 const response = await httpClient.executeHttpRequest(
  destination
  ,
  options
);

```
on a side note the above call to `executeHttpRequest` could be replaced by the following one liner:
```
const response = await axios(options);
```

**Comment by deekshas8** [comment]
Hi @ptesny ,

I wrote a test following the steps you mentioned, and strangely I cannot reproduce this with v3 of the SDK. I will check this with my colleagues. 

With `forwardAuthToken` option, the token used to execute the request is sent to the destination, see [here](https://github.com/SAP/cloud-sdk-js/blob/c8169afa24f4633b1cd68ef93b90504246a7c3a0/packages/connectivity/src/scp-cf/destination/destination-from-registration.ts#L107). What is the Authentication type for the destination? The function only works if your target system accepts unchanged JWTs. For other auth types, using the destination service is recommended.

**Comment by ptesny** [comment]
Hi @deekshas8 , thanks for looking into this.

I have been using my code with either v3 or v2; (with the tick notation in the package.json)
The destination is the one from the top of the issue:
```
const poster = {
          name: "POSTER-DESTINATION",
          url: "https://poster.mydomain.com",
          forwardAuthToken: true
        };
```
the business url is that of a micro-service (any) that needs a valid oauth2 token ; or more precisely a valid jwt token;
The registration and susequntly fetching the registered destination work as expected.

What really fails is the call to `executeHttpRequest` with the registered destination name.

I hope that helps

**Comment by ptesny** [comment]
@deekshas8 , I added `setGlobalLogLevel('debug');` accordingly; and it does not add any additional information to the trace already reported in this issue;

**Comment by ptesny** [comment]
@marikaner; @deekshas8 ; 

Good news! I have found the root cause of this issue. 
A simple typing mistake: the parameter name in the call to `executeHttpRequest` must be a `destinationName` when passing a name of the destination; or otherwise it is `destination` is passing a destination object;

Thus the below code snippet does work:

```
const response = await httpClient.executeHttpRequest(
  {
    destinationName: "POSTER-DESTINATION"
    ,
    jwt: retrieveJwt(req)
  }
);
```
