### ISSUE TITLE
Migration to V3 -> issue with regenerating OData Client

### ISSUE THREAD

**Issue by lechnerc77** [SAP/cloud-sdk-js#3628]
**Describe the bug**

After upgrading to V3 of the SAP Cloud SDK, I try to regenerate the OData Client via CLI. To the best of my knowledge all adjustments in the project are made.
Executing the generation with the setup working in V2 fails with V3 as an error is raised that the configuration is invalid. 

**To Reproduce**

1. Clone the repository <https://github.com/lechnerc77/app-service-javascript-sap-cloud-sdk-quickstart>
2. Switch to branch `issue-46`
3. Navigate to the directory `src/api`
4. Execute a `npm i`
5. Execute the generation via:
   - Option1: `npx generate-odata-client --input service-specifications/ZAPI_BUSINESS_PARTNER.edmx --outputDir services -c service-specifications/config.json --clearOutputDir` => this will lead to the error `Unknown argument: API_BUSINESS_PARTNER` which is part of the configuration 
   - Option 2: npx generate-odata-client --input service-specifications/ZAPI_BUSINESS_PARTNER.edmx --outputDir services -c service-specifications --clearOutputDir` => this should pick up the config.json in the specified directory. It raises the error `Invalid JSON config file: service-specifications`

The configuration file is consistent with the one described [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client#generate-a-client-using-the-command-line-interface)

**Expected behavior**

Generation of the Client should be executed successfully.

**Screenshots**

**Used Versions:**

- node version via `node -v': v18.14.2
- npm version via `npm -v`: 9.5.1
- SAP Cloud SDK version you used as dependency: 3.0.1

**Code Examples**

See above (<https://github.com/lechnerc77/app-service-javascript-sap-cloud-sdk-quickstart/tree/issue-46/src/api>)

**Log file**

`--verbose` does not add anymore information than the error

**Impact / Priority**

Demo for DSAG Technologietage on 22nd of March 

**Additional context**

n/a

**Comment by deekshas8** [comment]
Hi @lechnerc77 ,

Thank you very much for your adoption of version 3. The example you pointed to [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client#generate-a-client-using-the-command-line-interface) is a bit outdated. Thanks for pointing it out. I will correct this. 

Please refer to our [Upgrade Guide](https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-3#use-optionsperservice-in-odata-client-generator) which shows the new format for the options for service file.

To fix the issue, update the `service-specifications/config.json` file manually to the new format (remove the old service options):
```
  "service-specifications/ZAPI_BUSINESS_PARTNER.edmx": {
    "packageName": "business-partner-service-1",
    "directoryName": "business-partner-service-1",
    "basePath": "/sap/opu/odata/sap/API_BUSINESS_PARTNER"
  }
```
 and re-run client generation using the command below:

`npx generate-odata-client --input service-specifications/ZAPI_BUSINESS_PARTNER.edmx --outputDir services --optionsPerService service-specifications/config.json --clearOutputDir`

Note: the correct option for specifying the service options is `--optionsPerService`. `-c` option is for providing path to a config file that contains generator options.

**Comment by lechnerc77** [comment]
You are right - looked at the right time in the wrong spot of the documentation. Thanks for the quick response and support!
