### ISSUE TITLE
SAP Cloud SDK @sap-cloud-sdk/mail-client is not able to send email to external email ids or Gmail id

### ISSUE THREAD

**Issue by preetisap** [SAP/cloud-sdk-js#3635]
Hi

We have one scenario in our project where we are facing one issue with @sap-cloud-sdk/mail-client.

We have followed below blog to send email from SAP CAPM project.

https://blogs.sap.com/2023/02/14/connecting-on-premise-mail-destination-using-sap-cloud-sdk-javascript-version-3-on-sap-cap/comment-page-1/#comment-663613

We are able to send emails successfully to the same organization's email id for which we have created destination. But when we are trying to send emails to any external email ids or Gmail id, we are not getting emails.
I want to send emails to external email ids with @sap-cloud-sdk/mail-client.

![image](https://user-images.githubusercontent.com/43028543/224078430-555e9e8b-4dc6-4d1a-8ead-cd0fb0414162.png)

Regards,
Preeti

**Comment by deekshas8** [comment]
Hi @preetisap ,

Based on this [answer to your post](https://answers.sap.com/answers/13842171/view.html), were you able to resolve your issue?

**Comment by deekshas8** [comment]
@preetisap 

I am closing this ticket. Please feel free to reopen if you're still facing any issue.
