### ISSUE TITLE
@sap-cloud-sdk/mail-client Proxy configuration undefined

### ISSUE THREAD

**Issue by davidescaranontt** [SAP/cloud-sdk-js#3636]
**Describe the bug**
Whenever calling an On-Premise MAIL Destination the mail-client module responds with a "proxy configuration undefined" error.

**To Reproduce**

1. Set up EMAIL Destination
2. Call the module with Node.JS
3. Check the application logs

**Expected behavior**
I expect an email to be sent.

**Screenshots**
![image](https://user-images.githubusercontent.com/127437501/224119350-0066b46f-5007-4bb1-89d6-4e7a200cb28a.png)
As you can see from this code here, the module checks for the proxy configuration.

![image](https://user-images.githubusercontent.com/127437501/224119473-e46662f5-5c6b-4c5d-88b6-de5fc7e4a50a.png)
Whenever the module retrieves the Destination information, the proxy configuration is missing from the code. I also would like to know which proxy configuration is the application looking for, given that the destination already is configured for an OnPremise systems. I am not aware of any additional properties regarding the proxy configuration.
**Used Versions:**
Latest

**Code Examples**
const mailService = require('@sap-cloud-sdk/mail-client');
   mailService.sendMail({ destinationName: 'MailServer' }, [{
                from: 'dummyemail@dummy.it'
                to: 'dummyreceiver@dummy.it',
                subject: 'Test',
                text: 'Dummy mail.'
            }]);

**Impact / Priority**
High, cannot develop functionality

**Comment by jjtang1985** [comment]
Hi @davidescaranontt ,

Thanks for approaching us.

Your code example looks fine.
The `proxyConfiguration` is missing from the `destination` object the SDK resolved, which might due to:
- wrong destination type. Could you please share your destination configuration one the BTP via a screenshot?
- missing service binding of the "connectivity service" (another BTP service, just like "destination service"), which is needed for OnPrem connectivity. Could you please share your the list of services bound to your application, via a screenshot?

Best regards,
Junjie

**Comment by davidescaranontt** [comment]
Hi @jjtang1985,
Thanks for the kind and fast reply.

Please take a look to this documentation I found.
https://help.sap.com/docs/CP_CONNECTIVITY/cca91383641e40ffbe03bdc78f00f681/e54cc8fbbb571014beb5caaf6aa31280.html?locale=en-US

![image](https://user-images.githubusercontent.com/127437501/224260025-ee585a09-8975-4df1-af56-0124d4882ef5.png)

Regardless, here's my destination and MTA.
![image](https://user-images.githubusercontent.com/127437501/224260225-9d32c0fe-c095-4827-a2d8-479267adc4ba.png)
![image](https://user-images.githubusercontent.com/127437501/224260696-8bba49c0-46da-4e54-93f7-177226578070.png)

**Comment by jjtang1985** [comment]
Hi @davidescaranontt 

> Please take a look to this documentation I found.

The documentation looks strange, and I'll talk to the connectivity colleagues.

The screenshot of the destination looks good, and I shared our end to end test destination below:
<img width="902" alt="2023-03-10_09-38-32" src="https://user-images.githubusercontent.com/33489572/224266536-f90c8661-3b5a-491a-bfa0-6eb74b2b7437.png">

I assume due to the documentation (maybe you are right, maybe it's outdated) of the connectivity service, currently there is no connectivity service binding for your application. Which will indeed trigger the  error message "proxy configuration undefined".

Here is a blog post about how to use the `@sap-cloud-sdk/mail-client` to OnPrem email server, shared by another user.
In the comment, other users also shared their successful stories.
Would you like to bind the connectivity service and have a quick test?
Of course, you have to set up the cloud connector, if you don't have.

Best regards,
Junjie

**Comment by davidescaranontt** [comment]
Hi @jjtang1985,
Thanks again for the support. Sorry, but I do not see any link about the blog post you mentioned in your previous comment. Can you make sure the link is working and visible in your comment?
Thank you!

**Comment by jjtang1985** [comment]
Sorry @davidescaranontt , for the missing link.
I fixed it in the original comment.

**Comment by davidescaranontt** [comment]
Hi @jjtang1985,

Alas, I already tried with that blog post but gave it a try again just to be sure. Same error. We initially tested this directly on the deployed CAP project, just to make sure there weren't any weird shenanigans going on with the bindings. 

![image](https://user-images.githubusercontent.com/127437501/224331023-bd037380-716e-4bc0-b318-9ccb22582909.png)

**Comment by deekshas8** [comment]
Hi @davidescaranontt ,

This is indeed a bug. The proxy configuration is not added to the destination object because of this check [here](https://github.com/SAP/cloud-sdk-js/blob/a78b2ac0226814d48d1fc43c79035c4cc6ebd999/packages/connectivity/src/scp-cf/destination/destination-from-service.ts#L224). We'll work on providing a fix. 

In the meanwhile, as a workaround, can you try to fetch the destination object and add the proxy configuration using `addProxyConfigurationOnPrem` function. Then use this destination in `sendMail`. For example:

```
 let destination = await getDestination({ destinationName: 'MailServer' });
 destination = await addProxyConfigurationOnPrem(destination!);

mailService.sendMail(destination, [{
from: '[dummyemail@dummy.it](mailto:dummyemail@dummy.it)'
to: '[dummyreceiver@dummy.it](mailto:dummyreceiver@dummy.it)',
subject: 'Test',
text: 'Dummy mail.'
}]);
```

Let me know if this helps.

**Comment by davidescaranontt** [comment]
Hi @deekshas8 ,

![image](https://user-images.githubusercontent.com/127437501/224649614-71ef0e2c-3945-4310-8a2c-79065f792c2e.png)
With this code I am getting no errors but no email is sent.

**Comment by davidescaranontt** [comment]
Hello @deekshas8  and @jjtang1985,

Have you had the chance of checking out the code that I've attached? It seems correct to me and it produces no errors that I'm aware of, however no email is being sent from the SMTP server.

Thank you!

**Comment by deekshas8** [comment]
Hi @davidescaranontt 

Sorry for the late response. 

The code looks correct to me. The SDK only creates the e-mail object and sends it to the SMTP server via the Cloud Connector. So if the email is being sent by the SDK, then the issue could be somewhere else. To confirm this, can you enable the debug logs? You would need to import `@sap-cloud-sdk/util` library and add `setGlobalLogLevel('debug')` as the first line in your code. 

If transport verify step is successful and no other errors are logged, then the problem can potentially lie with your Mail Server or the CC config.

**Comment by davidescaranontt** [comment]
Hi @deekshas8, here's my debug log.


[cds] - POST /mail/sendmail 
[2023-03-20T08:52:40.363Z] DEBUG    (env-destination-accessor): Attempting to retrieve destination from environment variable.
[2023-03-20T08:52:40.365Z] DEBUG    (env-destination-accessor): No environment variable set.
[2023-03-20T08:52:40.366Z] DEBUG    (environment-accessor): Only one XSUAA instance bound. This one is used: HBonificiCap!t125782
[2023-03-20T08:52:40.366Z] DEBUG    (register-destination): Could not retrieve 'MailServer' from registered destinations.
[2023-03-20T08:52:40.367Z] DEBUG    (destination-accessor-vcap): Attempting to retrieve destination from service binding.
[2023-03-20T08:52:40.367Z] DEBUG    (destination-accessor-vcap): Could not retrieve destination from service binding. If you are not using SAP Extension Factory, this information probably does not concern you. No service with the name: "MailServer" was found.
[2023-03-20T08:52:40.367Z] DEBUG    (destination-accessor-service): Attempting to retrieve destination from destination service.
[2023-03-20T08:52:40.368Z] DEBUG    (environment-accessor): Only one XSUAA instance bound. This one is used: HBonificiCap!t125782
[2023-03-20T08:52:40.504Z] DEBUG    (environment-accessor): Only one XSUAA instance bound. This one is used: HBonificiCap!t125782
[2023-03-20T08:52:40.506Z] DEBUG    (proxy-util): Tried to read https_proxy or HTTPS_PROXY from the environment variables. Value is http://127.0.0.1:8887.
[2023-03-20T08:52:40.507Z] DEBUG    (proxy-util): Tried to read https_proxy or HTTPS_PROXY from the environment variables. Value is http://127.0.0.1:8887.
[2023-03-20T08:52:40.507Z] DEBUG    (proxy-util): Proxy settings for https are found in environment variables.
[2023-03-20T08:52:40.507Z] DEBUG    (proxy-util): Tried to read https_proxy or HTTPS_PROXY from the environment variables. Value is http://127.0.0.1:8887.
[2023-03-20T08:52:40.508Z] DEBUG    (proxy-util): Used Proxy Configuration: {
  "host": "127.0.0.1",
  "protocol": "http",
  "port": 8887,
  "headers": {}
}.
[2023-03-20T08:52:40.514Z] DEBUG    (proxy-util): Tried to read https_proxy or HTTPS_PROXY from the environment variables. Value is http://127.0.0.1:8887.
[2023-03-20T08:52:40.514Z] DEBUG    (proxy-util): Tried to read https_proxy or HTTPS_PROXY from the environment variables. Value is http://127.0.0.1:8887.
[2023-03-20T08:52:40.515Z] DEBUG    (proxy-util): Proxy settings for https are found in environment variables.
[2023-03-20T08:52:40.515Z] DEBUG    (proxy-util): Tried to read https_proxy or HTTPS_PROXY from the environment variables. Value is http://127.0.0.1:8887.
[2023-03-20T08:52:40.515Z] DEBUG    (proxy-util): Used Proxy Configuration: {
  "host": "127.0.0.1",
  "protocol": "http",
  "port": 8887,
  "headers": {}
}.
[2023-03-20T08:52:40.841Z] DEBUG    (destination-accessor-service): Successfully retrieved destination from destination service.
[ERROR] read ECONNRESET

**Comment by davidescaranontt** [comment]
Hello @deekshas8 

I tried to send the email with the deployed application, and I have this piece of log that I couldn't see before on the BAS.

2023-03-20T10:28:09.660+0000 [APP/PROC/WEB/0] STDOUT {"custom_fields":{"messageContext":"mail-client","package":"mail-client"},"level":"debug","logger":"sap-cloud-sdk-logger","message":"Sending email 1/1...","msg":"Sending email 1/1...","timestamp":"2023-03-20T10:28:09.660Z","written_at":"2023-03-20T10:28:09.660Z","written_ts":1679308089660}
2023-03-20T10:28:39.668+0000 [APP/PROC/WEB/0] STDOUT {"custom_fields":{"messageContext":"mail-client","package":"mail-client"},"level":"debug","logger":"sap-cloud-sdk-logger","message":"The verification of the transport failed: Error: Greeting never received","msg":"The verification of the transport failed: Error: Greeting never received","timestamp":"2023-03-20T10:28:39.667Z","written_at":"2023-03-20T10:28:39.667Z","written_ts":1679308119667}

"Greeting never received". What could this mean?

**Comment by davidescaranontt** [comment]
Additionally, I get the [ERROR] The destination 'name: MailServer' does not contain user or password information as properties. The mail-client only supports basic authentication, so "user" and "password" are required.

If my destination is set to NoAuthentication. Currently, the SMTP server has no authentication, so to bypass this I had to use a dummy username and password. Is it possible to change this so that the mail-client also accepts No Authentication?

**Comment by deekshas8** [comment]
Hi @davidescaranontt ,

I looked into the error "Greeting never received", and there is an issue in the nodemailer socks proxy config in the SDK. We'll provide a fix soon and update you.

**Comment by davidescaranontt** [comment]
Hi @deekshas8,

I have taken all of the code inside your package and moved it to an external location within my project so that I could experiment on it. I have managed to remove the basic authentication part and so far it works (up until creaitng the socks connection). If the issue in the nodemailer socks proxy config is easily fixed with a few lines of code, could you please share them with me so that I can test it? I can just drop them in and see if they work.

**Comment by deekshas8** [comment]
You can see the changes in `createSocket` function in the [PR](https://github.com/SAP/cloud-sdk-js/pull/3647/files#diff-075160b9be9d694222c49ae90a1bb836b15874d7783fc345918f41f04b381057). The `_readableState` property needs to be set to true.

**Comment by davidescaranontt** [comment]
Hi @deekshas8,

I've installed the latest patch and this is the error I'm getting now.
[ERROR] self signed certificate in certificate chain


Can this be related to the fact that my destination is in basic authentication with dummy credentials? My SMTP server has no authentication, but the mail-client package doesn't seem to support no auth flow.

**Comment by deekshas8** [comment]
Hi @davidescaranontt ,

You can tell `nodemailer` to not check certificate trust by setting the `rejectUnauthorized` to `false`. Check our documentation [here](https://sap.github.io/cloud-sdk/docs/js/features/mail-client#configure-nodemailer) on how you can set it.

**Comment by deekshas8** [comment]
Hi @davidescaranontt,

Great to hear that the solution worked. I'll close this ticket.

You can now use the new version v3.0.2 of the [mail-client](https://www.npmjs.com/package/@sap-cloud-sdk/mail-client) was released yesterday. We are also planning to investigate whether to support OnPrem destinations with `NoAuthentication`.

**Comment by deekshas8** [comment]
Hi @davidescaranontt ,

With the latest release of v3.1.0, the SDK now supports On-Prem destinations with NoAuth.

**Comment by davidescaranontt** [comment]
Hi @deekshas8 
I installed 3.1.0 and changed my authentication to NoAuth but I still get the usual error of missing username and password. By rapidly checking the code I still see that the package checks for username and password regardless of auth method. Can you please check?

![image](https://user-images.githubusercontent.com/127437501/231165294-e6ed5213-f3a7-4061-9e88-d73fdae06353.png)
![image](https://user-images.githubusercontent.com/127437501/231165533-77f63735-dfe0-4d09-8b3a-03738ddfa918.png)

**Comment by deekshas8** [comment]
Hi @davidescaranontt ,

Apologies for the really late response. A small correction to my last comment, the support for On-Prem destinations with NoAuth was only extended for HTTP destinations, not MAIL. Sorry for the confusion.
