### ISSUE TITLE
ErrorWithCause: Generation of services failed.

### ISSUE THREAD

**Issue by Showkath** [SAP/cloud-sdk-js#3649]
Hi,

I am using BTP User Management API 

https://api.sap.com/api/PlatformAPI/overview
For this i followed steps mentioned in https://api.sap.com/api/PlatformAPI/cloud-sdk/JavaScript
with YAML File placed in resources folder

![image](https://user-images.githubusercontent.com/6544645/224726703-dff94be7-fef9-427a-a4d2-8444c6c3ceb1.png)

When i ran command 
`npx openapi-generator --input . --outputDir srv/src/generated -t `

I got below error 
Error : 
  at /home/user/projects/UserManagement/node_modules/@sap-cloud-sdk/openapi-generator/dist/cli.js:15:18
Caused by:
Error: Could not generate client. Errors: [
        Error: The service specification contains invalid schema names. Adjust the definition file or enable automatic name adjustment with `skipValidation`.
        Invalid names containing illegal characters: 'authorization.error','generic.error','method.error'
]
    at finishAll (/home/user/projects/UserManagement/node_modules/@sap-cloud-sdk/util/dist/promise.js:22:15)
    at async generateWithParsedOptions (/home/user/projects/UserManagement/node_modules/@sap-cloud-sdk/openapi-generator/dist/generator.js:58:9)

![image](https://user-images.githubusercontent.com/6544645/224726484-47928782-fb2e-4dc5-b97b-c263bc3c7569.png)

Kindly suggest ,
Showkath.

**Comment by tomfrenken** [comment]
Hey @Showkath, the letter `.` is an invalid character and is therefore causing errors with the 3 names which are listed in the error message.
As per the error message, either rename the 3 names or use the `skipValidation` option.

To check for invalid characters you can use the following RegEx: `/[.#@/"'*%]+/g`

**Comment by Showkath** [comment]
> Hey @Showkath, the letter `.` is an invalid character and is therefore causing errors in the 3 names which are listed in the error message. As per the error message, either rename the 3 names or use the `skipValidation` option.
> 
> To check for invalid characters you can use the following RegEx: `/[.#@/"'*%]+/g`

Just posting solution for others reference.

Thanks for explaining ,it means there are issue in YAML file . 
The other issue what i was facing [transpilation to JS,  -t or --transpil]
resolved with below command
`npx openapi-generator --input resources/service-specs --outputDir srv/src/generated --skipValidation -t -overwrite`

![image](https://user-images.githubusercontent.com/6544645/224991300-eacb7e23-6fff-42c8-8124-447f807c68b0.png)

Note  :  For first time u need to try 
npx openapi-generator --input resources/service-specs --outputDir srv/src/generated --skipValidation -t
