### ISSUE TITLE
Additional Headers and Query Parameters on Destinations

### ISSUE THREAD

**Issue by nlaenger** [SAP/cloud-sdk-js#3668]
Hi,

the query parameters for the destination are not work when we are using an SAP Approuter.

Dokumentation:
https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#additional-headers-and-query-parameters-on-destinations

URL.headers.HEADER_KEY for headers => Is working as documented
URL.queries.QUERY_KEY for query parameters => Does not change the targed URL at all.

I'm unsure if this issue is part of the cloud SDK (where this feature is documented) or if i have to raise an OSS ticket for the approuter (as described here: https://www.npmjs.com/package/@sap/approuter#getting-support)

regards
Norbert

**Comment by marikaner** [comment]
Hey @nlaenger,

the SAP Cloud SDK is not part of the SAP Approuter. If you are not using the SDK, you already pointed out the correct support channel, there is not much we can do. 
If you have an application, where you are using the SDK, could you share a minimal example with the incorrect behavior? This would help to identify the issue.

Regards,
Marika

**Comment by nlaenger** [comment]
Hi @marikaner ,

I can now confirm that with the cloud SDK everything works as explained in the documentation (HEADER + QUERY).
I will create an Ticket for the approuter.

thx for your feedback.

regards
Norbert
