### ISSUE TITLE
mTLS destination support broken or incomplete for BTP destinations

### ISSUE THREAD

**Issue by sebbae** [SAP/cloud-sdk-js#3719]
**Describe the bug**
Hi,

I have a scenario which requires destinations with mTLS-enabled token retrieval **and** mTLS-enabled access to the target API. The destination at subaccount level was created basically according to [this blog](https://blogs.sap.com/2022/07/28/sap-btp-security-how-to-use-mtls-with-destinations/) but with IAS instead of XSUAA.

The entered parameters seem correct as I can use them locally to get a proper token from the *tokenServiceUrl* via curl which I can pass on as Bearer token to my API at *URL*. Note, in both cases my scenario requires to pass on the mTLS key and certificate which are both contained in the *mykey.pem* certificate, which I created according to the above mentioned blog post.

The destination service response for the config is as follows:

```json
  {
    "Name": "mydestination",
    "Type": "HTTP",
    "URL": "https://myapi.stage.kyma.ondemand.com/",
    "Authentication": "OAuth2ClientCredentials",
    "ProxyType": "Internet",
    "tokenServiceURLType": "Dedicated",
    "tokenService.KeyStorePassword": "",
    "clientId": "999999999-460e-4d3a-9b1d-c85b0cff7f32",
    "clientSecret": "",
    "tokenServiceURL": "https://mytenant.accounts400.ondemand.com/oauth2/token",
    "tokenService.KeyStoreLocation": "certificate.pem"
  }
```

I consume the destination via CAP (@sap/cds 6.3.1 and @sap-cloud-sdk/http-client 3.0.1) and receive the following error:

```sh
Failed to build headers.
    at run (/Users/<redacted>/node_modules/@sap/cds/libx/_runtime/remote/utils/client.js:312:31)
    at processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async RemoteService.<anonymous> (/Users/<redacted>/node_modules/@sap/cds/libx/_runtime/remote/Service.js:234:20)
    at async next (/Users/<redacted>/node_modules/@sap/cds/lib/srv/srv-dispatch.js:75:17)
    at async RemoteService.handle (/Users/<redacted>/node_modules/@sap/cds/lib/srv/srv-dispatch.js:73:10)
    at async RemoteService.handle (/Users/<redacted>/node_modules/@sap/cds/libx/_runtime/remote/Service.js:265:22) {
  statusCode: 502,
  reason: {
    message: 'Error during request to remote service: \n' +
      'Failed to build headers. Caused by: The destination tried to provide authorization tokens but failed in all cases. This is most likely due to misconfiguration.\n' +
      'Original error messages:\n' +
      'Bad credentials',
    request: {
      method: 'GET',
      url: "/FlowProviders'",
      headers: { accept: 'application/json,text/plain' }
    },
    correlationId: '75a5c0cc-a00f-468c-a01f-1fed648d42c4'
  }
}
```

Through debugging, I figured that the returned destination from the destination service API performs a destination property parsing in *parseDestination()* which does not match/include *tokenService.KeyStoreLocation* and eventually leads to an unsuccessful token fetch:

https://github.com/SAP/cloud-sdk-js/blob/be04dafc2fdf27eba467206dcca23e760f96515c/packages/connectivity/src/scp-cf/destination/destination.ts#L398

I wonder now if destinations with mTLS-protected token endpoints are even supported? Or is there some misalignment currently between destination service (btw. I use internal canary) and the cloud sdk?

**To Reproduce**

1. Set up destination in BTP destination service with mTLS destination (e.g. using [the blog](https://blogs.sap.com/2022/07/28/sap-btp-security-how-to-use-mtls-with-destinations/))
2. Use cloud sdk to consume destination from destination service (https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#destination-service)
3. See error

**Expected behavior**

The destination should correctly handled to retrieve token from configured *Token Service URL* using OAuth2 Client Credentials flow with mTLS authentication using key and certificate from the configured *Token Service Key Store Location*.

Follow up call, i.e. the call to the actual configured API should be performed with the retrieved token (as Bearer) and also incl. mTLS, i.e. key and token.

**Screenshots**

![image](https://user-images.githubusercontent.com/2325250/227045687-09bfa418-622d-452e-b5e0-501b834dff4a.png)

**Used Versions:**

- @sap/cds 6.3.1
- @sap-cloud-sdk/http-client 3.0.1

**Comment by marikaner** [comment]
Hey @sebbae,

the token service URL is never used in the SAP Cloud SDK. This configuration only tells the destination service where to get the token from. It is the destination service that makes the request. The error message indicates, that "The destination tried to provide authorization tokens but failed in all cases." and the reason seems to be "Bad credentials".
Are you sure you are able to retrieve an auth token using mtls with the given certificate?

**Comment by ptesny** [comment]
Hello @sebbae , 
This is unlikely an issue with the cloud-sdk. 
Why?  Because the mTLS settings are to be applied to the token issuance endpoint `tokenServiceURL`. And the token issuance endpoint is called by a destination service itself (not by the cloud-sdk).

You can easily smoke-test your destination using the **dynamic_dest** route with from any SAP BTP sub-account.
You may refer to this blog of mine for a full bag of examples: https://blogs.sap.com/2023/03/20/destinations-routing-easy-with-sap-build-work-zone-standard-edition/

**Comment by sebbae** [comment]
Hello @ptesny, I checked the response from the destination service (`GET /destination-configuration/v1/destinations/mydestination`) manually, and indeed it get the following in the `authTokens` section:

```
{
  ...
  "authTokens": [
    {
      "type": "",
      "value": "",
      "error": "Bad credentials",
      "expires_in": "0"
    }
  ]
  ...
}
```
 
So it appears like an issue with the destination service. I still believe some support from the cloud-sdk would be required for the actual second part of my scenario, i.e. mTLS with key+cert not only for the token retrieval (handled by destination service) but also for the actual call to the configured target system, right?

**Comment by sebbae** [comment]
I have an update. So the issue was that I created the destination config from a template which contained an empty string for the `"clientSecret"`, which is actually not needed for the mTLS-enabled token endpoint. If this field is omitted, the destination service returns a proper token in the `"authTokens"` section.

So it should read:

```json
  {
    "Name": "mydestination",
    "Type": "HTTP",
    "URL": "https://myapi.stage.kyma.ondemand.com/",
    "Authentication": "OAuth2ClientCredentials",
    "ProxyType": "Internet",
    "tokenServiceURLType": "Dedicated",
    "tokenService.KeyStorePassword": "",
    "clientId": "999999999-460e-4d3a-9b1d-c85b0cff7f32",
    "tokenServiceURL": "https://mytenant.accounts400.ondemand.com/oauth2/token",
    "tokenService.KeyStoreLocation": "certificate.pem"
  }
```

In the end, however, my scenario is not yet fully complete as my API endpoint implements access token validation in form of the [Proof of Possession paradigm](https://emil-niroshan89.medium.com/proof-of-possession-access-tokens-23b9d85fe9d6). This means that the API endpoint must also be connected to via mTLS using the same certificate in addition to providing the Bearer access token.

So, this connection setup definitely requires some kind of alignment between Destination service for the configuration part and cloud-sdk for the execution.

This is apparently not in place yet but should hopefully on the roadmap. Hence, I close this ticket now but would be happy about any updates or reaching out in case you'd like to clarify the setup or would like to see an actual example.
