### ISSUE TITLE
Failed to build headers

### ISSUE THREAD

**Issue by Sandeep-Malhotra** [SAP/cloud-sdk-js#3764]
I am calling **executeHttpRequest** and got an error  "The destination tried to provide authorization tokens but failed in all cases.
				This is most likely due to misconfiguration.\nOriginal error messages:\nBad credentials"
```
let oResponse = await executeHttpRequest({
    destinationName: DESTINATION_NAME
}, {
    method: 'get',
    url: sUrl,
    responseType: "arraybuffer",
});
}
catch (oError) {
}
```
My BTP destination Authentication Type is OAuth2ClientCredentials.  I am using the destinations service in mta.yaml

`  - name:my-destination
    type: org.cloudfoundry.managed-service
    parameters:
      service: destination
      service-plan: lite`

Kindly let me know where am doing wrong

**Comment by tomfrenken** [comment]
Hi @Sandeep-Malhotra,

Are you certain the credentials maintained in the destination are the correct ones?
We have created a simple [debugging guide](https://sap.github.io/cloud-sdk/docs/js/troubleshooting) that could point you at the misconfiguration you are most likely having.

Please let me know if the debugging guide helped you, and if not, what new information you got through the guide.

**Comment by Sandeep-Malhotra** [comment]
Thanks, @tomfrenken  for your quick assistance. With the help of debugging guide I am able to find the root cause. Hence now resolved.

Thanks once again.
