### ISSUE TITLE
Create Request Builder Error 

### ISSUE THREAD

**Issue by iamitsharma03** [SAP/cloud-sdk-js#3776]
**Describe the bug**
While trying to create Sales Order in SAP S/4HANA System, I am using API_SALES_ORDER_SRV along with SAP Cloud SDK for javascript. I have generated the OData Client and tried to execute the Create API Call and it failed with the following error:

"TypeError: **Cannot read properties of undefined (reading 'data')**\n    at /Users/XXX/Dev/integration-service/node_modules/@sap-cloud-sdk/odata-common/dist/request-builder/create-request-builder-base.js:72:104\n    at processTicksAndRejections (node:internal/process/task_queues:96:5)\n    at async /Users/xxx/Dev/integration-service/utils/integration/salesOrder.js:37:21"

I have faced a similar issue with another OData Client for API_SALES_ORDER_SIMULATION_SRV.

**To Reproduce**

1. Generate OData client for API_SALES_ORDER_SRV.
2. Create payload using OData client, sample payload attached.
3. Execute the API Call using the following command:
    salesOrderApi.requestBuilder().create(soObj).execute(destination);

**Expected behavior**
API call should succeed with 201 or at least provide HTTP-related errors like 500 or 400.

**Screenshots**

**Used Versions:**

- node version via `node -v` 16.13.0
- npm version via `npm -v` 8.15.0
- SAP Cloud SDK version you used as dependency 1.54.2

**Code Examples**
Sales Order Payload

`{
    "salesOrderType": "OR",
    "salesOrganization": "1710",
    "distributionChannel": "10",
    "organizationDivision": "00",
    "soldToParty": "17100001",
    "creationDate": "2023-02-02T15:37:41.758Z",
    "createdByUser": "CB9980000027",
    "toPartner":
    [
        {
            "customer": "17100001",
            "partnerFunction": "SH",
            "ContactPerson": "Jane Doe",
            "toAddress":
            [
                {
                    "streetName": "Olympiadenlaan",
                    "houseNumber": "2",
                    "country": "BEL",
                    "region": "BRU",
                    "postalCode": "1140",
                    "cityName": "Evere"
                }
            ]
        }
    ],
    "toItem":
    [
        {
            "material": "TG11",
            "salesOrderItemCategory": "TAN",
            "salesOrderItemText": "Gasoline fuel injector for Honda Civic V",
            "netAmount": 7.88,
            "orderQuantityUnit": "EA",
            "transactionCurrency": "USD",
            "requestedQuantity": 1,
            "requestedQuantityUnit": "EA",
            "taxAmount": 2,
            "toPricingElement":
            [
                {
                    "conditionType": "PPR0",
                    "conditionRateValue": 7.88,
                    "conditionCurrency": "USD"
                }
            ],
            "toPartner":
            [
                {
                    "customer": "17100001",
                    "partnerFunction": "SH",
                    "ContactPerson": "Jane Doe",
                    "toAddress":
                    [
                        {
                            "streetName": "Olympiadenlaan",
                            "houseNumber": "2",
                            "country": "BEL",
                            "region": "BRU",
                            "postalCode": "1140",
                            "cityName": "Evere"
                        }
                    ]
                }
            ]
        }
    ]
}`

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**

Affected development phase: e.g. Release

Impact: e.g.  Blocked

Timeline: e.g. Go-Live is in 4 weeks.
![Screenshot 2023-04-10 at 11 35 14 AM](https://user-images.githubusercontent.com/41181359/230838246-d67c3cb9-9238-49b8-95f0-1e8ccea732ee.png)

**Additional context**

**Comment by deekshas8** [comment]
Hi @iamitsharma03 ,

The error seems to be because `response.data` is undefined, as seen in this [code](https://github.com/SAP/cloud-sdk-js/blob/8abbe7db40be92937c1b5ea4fba37da832ef283e/packages/odata-common/src/request-builder/create-request-builder-base.ts#L110). Can you try using `executeRaw(destination)` instead of `execute(destination)`. The function gives you the original response from the server, without any modifications. You can read more about it [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/execute-request#getting-the-raw-response-and-the-original-request)

Also, you mentioned you are using v1.54.2 of the SDK, but I can see `@sap-cloud-sdk/odata-common` in the logs which was released in v2. Please confirm which version you are using. The version 1 and 2 are deprecated and the best practice is to upgrade to version 3. Here you can find the [upgrade guide](https://sap.github.io/cloud-sdk/docs/js/guides/upgrade-to-version-3). Please let us know if you face any issues with the upgrade.

**Comment by deekshas8** [comment]
Hi @iamitsharma03 ,

Were you able to resolve your issue?

**Comment by deekshas8** [comment]
Closing this. Please reopen if you are still facing this issue
