### ISSUE TITLE
Unable to get destination from Subscriber with getDestinationFromDestinationService

### ISSUE THREAD

**Issue by crashmydev** [SAP/cloud-sdk-js#3832]
**Describe the bug**
Hi colleagues, 

we are developing a SAP standard product with **nodeJs** and **CAP v.6.7.0** on BTP CloudFoundry as a **multitenant** app.
We have just upgraded our version from @sap-cloud-sdk/core v.1.54.2 to @sap-cloud-sdk/connectivity v3.0.2. 

Now to the issue: we are using **getDestinationFromDestinationService** to retrieve a destination from the subscriber account. We first get a **jwt** with the client credentials of the bound destination service and the specific tenant id. 
Now we use this jwt as option parameter to do the call with above mentioned method. 
The error we are getting is the same as this issue #3050 . 

When we use this approach with the former version everything is working fine. I also decoded the jwt we are using and this looks fine, too. 

**Used Versions:**

- node version via `node -v`: 18.14.1
- npm version via `npm -v`: 9.3.1
- SAP Cloud SDK version you used as dependency: 3.0.2

**Impact / Priority**

We are currently testing the release and want to start developing for a new release soon. We have a workaround by using the **iss** option rather than the token. But ideally we want to stick with the token.  

Any help would be highly appreciated. 

Thanks and kind regards,
Tim Hollinger

**Comment by deekshas8** [comment]
Hi Tim,

You are right, we switched to `@sap/xssec` library in version 2.2.0 of the SDK for verification of the JWT, which was not the case before in v1.54.2. The `@sap/xssec` library has stricter checks for `audience` to meet some conditions. 

Coming to the error, you mentioned:

> We first get a jwt with the client credentials of the bound destination service and the specific tenant id.

This is the client credentials token used for calling the destination service. This is fetched by the SDK anyway in the [retrieveServiceToken](https://github.com/SAP/cloud-sdk-js/blob/782b9e37e6378ae6d607f4d6a0e26de89e6583cd/packages/connectivity/src/scp-cf/destination/get-subscriber-token.ts#L57) function. The `getDestinationFromDestinationService` expects a user JWT of the current request that is issued by the Approuter together with the XSUAA service. This user JWT should have the right audiences.

Does your application use the Approuter? Could you perhaps explain why you pass the destination service token to the method?

**Comment by crashmydev** [comment]
Hi @deekshas8 ,
thanks for clarifying. We are using the **iss** option now and as it is a background process I guess this is how we should use it. 
We were just curious if this is wanted behavior, because it worked in another way before the upgrade.
I will close the issue now.

**Comment by tonymathew17sap** [comment]
Hi @deekshas8 I'm facing the same issue [here](https://github.com/SAP/cloud-sdk-js/issues/4033). I tried adding iss and using serviceToken() as suggested above, but getting the same issue. Could you please help?
