### ISSUE TITLE
Failed to get CSRF token after upgrade to v3

### ISSUE THREAD

**Issue by thulium3** [SAP/cloud-sdk-js#3846]
**Describe the bug**
After upgrading my generated OData v2 client from v2 to v3, my create is not working any longer. I always get error 403, failed to get CSRF token.

**To Reproduce**
I execute following code:
`const { retrieveJwt } = require("@sap-cloud-sdk/connectivity");
const { ssfRequest } = require('./client/ssf-request');
const { postingRequestSetApi } = ssfRequest();
app.use(express.json({ limit: '50mb' }));

// create Ticket in SSF
app.post("/Posting", async function (req, res, next) {
  const posting = postingRequestSetApi.entityBuilder().fromJson(req.body);
  const myTicket = await postingRequestSetApi.requestBuilder()
    .create(posting)
    .execute({ destinationName: 'xxx', jwt: retrieveJwt(req) })
    .catch(err => {
      console.log('Error:', err.message);
      console.log('Cause:', err.cause?.message);
      console.log('Root cause:', err.rootCause?.message);
      next(err);
    });`
before upgrading it worked, now always getting the error.

**Expected behavior**
create still works.

**Screenshots**

**Used Versions:**

- node version via `node -v` v18.13.0
- npm version via `npm -v` v8.19.3
- SAP Cloud SDK version you used as dependency v3.1.1

**Code Examples**
`const { retrieveJwt } = require("@sap-cloud-sdk/connectivity");
const { ssfRequest } = require('./client/ssf-request');
const { postingRequestSetApi } = ssfRequest();
app.use(express.json({ limit: '50mb' }));

// create Ticket in SSF
app.post("/Posting", async function (req, res, next) {
  const posting = postingRequestSetApi.entityBuilder().fromJson(req.body);
  const myTicket = await postingRequestSetApi.requestBuilder()
    .create(posting)
    .execute({ destinationName: 'xxx', jwt: retrieveJwt(req) })
    .catch(err => {
      console.log('Error:', err.message);
      console.log('Cause:', err.cause?.message);
      console.log('Root cause:', err.rootCause?.message);
      next(err);
    });`

**Log file**

**Impact / Priority**

Cannot update my app.

Affected development phase: Production

Impact: Blocked

**Comment by tomfrenken** [comment]
Hi @thulium3,

without the error logs it's hard to tell what the root cause of your issue is, however after a brief investigation the `default` maximum length of header values seems to be 8KB, how exactly do you send the large attachment?
Is it in some header or part of the payload?
Additionally, the target system could have a limit on how big the payload through a POST request can be, however, from the status code & message you have shared, I would expect the issue to be related to the headers.

Could you share more detailed logs and also, if you set headers that exceed the maximum size of 8KB somewhere in your implementation?

**Comment by tomfrenken** [comment]
Additionally you mentioned that you started having this issue after upgrading to version 3 of the SAP Cloud SDK, does that mean that if you do the exact same request with a version 2 client, you don't receive any error?

**Comment by thulium3** [comment]
Hi Tom,
meanwhile I downgraded again to Cloud SDK v2, there it works again. The request should be the same. In a different module and a different OData service I use SDK v3 without a problem.

**Comment by thulium3** [comment]
Unfortunately the fix does not solve my issue. Regenerated my client with new fixed version but still I get error 403 instead of getting a CSRF token.

**Comment by thulium3** [comment]
after installing the fix I needed to fetch the csrf token via GET request manually, now it works:
`const myTicket = await postingRequestSetApi.requestBuilder()

    .create(posting)

    .middleware([csrf({ method: 'GET' })])

    .skipCsrfTokenFetching()

    .execute({ destinationName: 'xxx', jwt: retrieveJwt(req) })`
