### ISSUE TITLE
Failed to get CSRF token

### ISSUE THREAD

**Issue by krishraheja** [SAP/cloud-sdk-js#3869]
Hi Colleague,

During call of /rest/v2/rule-services Business Rules Service, I have set fetchCsrfToken: false in executeHttpRequest. I am doing this call with destination. Below is code snippet where I made the changes:

<img width="670" alt="image" src="https://github.com/SAP/cloud-sdk-js/assets/53295200/c2277b1e-b5fd-49e7-9916-e1d21dd267f7">

- node version 18.15.0
- npm version 9.5.1
- SAP Cloud SDK version 3.1.1

Please suggest how to fix this issue.

For further information, please contact me at our internal teams chat.

This issue is with version SDK version 2.15.0 as well.

Best Regards
Krishan Raheja

**Comment by krishraheja** [comment]
Hi Tom,

The issue is after setting fetchCsrfToken flag as false, SDK shouldn't call the logic to fetch the CSRF token. In logs, it is showing the result as "Failed to get CSRF token from  URL: /rest/v2/rule-services.". 

Also it dumps very lengthy logs regarding CSRF token, which is not helpful for us.

Best Regards
Krishan

**Comment by tomfrenken** [comment]
Hey @krishraheja,

After looking further into your implementation, you need to pass the fetchCsrfToken as a seperate object, as described in the [documentation](https://sap.github.io/cloud-sdk/docs/js/v2/features/connectivity/http-client#csrf-token-fetching), your call should look like the following:

```
promises.push(executeHttpRequest(brDestination, {
          url: process.env.RULE_SERVICE_ENDPOINT ? process.env.RULE_SERVICE_ENDPOINT
            : '/rest/v2/rule-services',
          method: 'post',
          data: rulePayloadArr[i]
        },
        {
          fetchCsrfToken: false
        }
```

**Comment by krishraheja** [comment]
Hi Tom,

It is working fine now.

Thanks for your support.

Best Regards
Krishan
