### ISSUE TITLE
Use destinations in multitenant application 

### ISSUE THREAD

**Issue by FedorSh-illumiti** [SAP/cloud-sdk-js#3880]
Hi. I have two subaccounts provider and a consumer. In the consumer cloud foundry is not activated. I cannot use destination when I'm using the consumer subaccount.
`const jwt = retrieveJwt(req);
await getAllDestinationsFromDestinationService({
                    jwt
                })
`
fails with the error "'Could not fetch client credentials token for service of type "destination" at the method 
this method also fails even thought it should take a destination from a provider
await getDestination({
                destinationName:'app-s4public',
                jwt,
                selectionStrategy: DestinationSelectionStrategies.alwaysProvider
            });

I am testing locally but the same is happening in a deployed version 

example:
###
GET {{apiEndpoint}}/catalog/Projects
Content-Type: application/json
Authorization: Bearer {{token}}

**mta file:**

`_schema-version: "3.1"
ID: fdc
description: Field Data Capture
version: 1.0.1
parameters:
  appname: fdc
  enable-parallel-deployments: true
  keep-existing-routes: true
  appl_suffix: "dev"
  category: "DEV-BETA"
build-parameters:
  before-all:
    - builder: custom
      commands:
        - npm install --production
        - npx -p @sap/cds-dk cds build --production
        - npm run build:cf
  after-all:
    - builder: custom
      commands:
        - npm install

modules:
  - name: fdc-srv
    type: nodejs
    path: gen/srv
    provides:
      - name: srv-api
        properties:
          srv-url: ${default-url}
          forwardAuthToken: true
    requires:
      - name: fdc-uaa
      - name: fdc-settings
      - name: fdc-registry
      - name: fdc-destination-service
      - name: app-api
        properties:
          APP_PROTOCOL: ~{protocol}
          APP_URI: ~{uri}

  - name: fdc-router
    type: approuter.nodejs
    path: router
    build-parameters:
      builder: custom
      commands:
        - npm install
        - npm run build:ts
    parameters:
      disk-quota: 256M
      memory: 256M
      keep-existing-routes: true
    properties:
      TENANT_HOST_PATTERN: "^(.*)-${default-uri}"
    provides:
      - name: app-api
        properties:
          protocol: ${protocol}
          uri: ${default-uri}
    requires:
      - name: fdc-uaa
      - name: fdc-registry
      - name: srv-api
        group: destinations
        properties:
          forwardAuthToken: true
          name: fdc-srv
          strictSSL: false
          url: ~{srv-url}

resources:
  - name: fdc-uaa
    type: org.cloudfoundry.managed-service
    parameters:
      path: ./xs-security.json
      service: xsuaa
      service-plan: application
  - name: fdc-settings
    type: org.cloudfoundry.existing-service

  - name: fdc-registry
    type: org.cloudfoundry.managed-service
    requires:
      - name: srv-api
      - name: fdc-uaa
    parameters:
      service: saas-registry
      service-plan: application
      service-name: fdc-registry
      config:
        xsappname: fdc
        appName: fdc-${appl_suffix}
        category: ${category}
        description: FDC
        displayName: FDC ${appl_suffix}
        appUrls:
          onSubscription: ~{srv-api/srv-url}/callback/v1.0/tenants/{tenantId}
          onSubscriptionAsync: false
          onUnSubscriptionAsync: false
          callbackTimeoutMillis: 300000

  - name: fdc-destination-service
    type: org.cloudfoundry.managed-service
    parameters:
      config:
        HTML5Runtime_enabled: false
        init_data:
          instance:
            existing_destinations_policy: update
            destinations:
              - Name: app-cfapi
                Description: CF Cloud Controller API
                URL: ${controller-url}
                Type: HTTP
                ProxyType: Internet
                Authentication: OAuth2Password
                tokenServiceURL: ${authorization-url}/oauth/token
                clientId: cf
                clientSecret:
                User: <SetValueInCockpit>
                Password: <SetValueInCockpit>

        version: 1.0.0
      service: destination
      service-name: fdc-destination-service
      service-plan: lite

**package.json**

{
  "name": "fdc",
  "version": "1.0.1",
  "description": "Field data capture",
  "license": "UNLICENSED",
  "private": true,
  "dependencies": {
    "@sap-cloud-sdk/http-client": "^3.1.1",
    "@sap-cloud-sdk/odata-v2": "^3.1.1",
    "@sap/cds": "^6.8.1"
   .....
   },

  "engines": {
    "node": ">=16"
  },
  "scripts": {
    "start": "cds run --production",
     .... 
  },
  "cds": {
    "requires": {
      "API_ENTERPRISE_PROJECT_SRV_0002": {
        "kind": "odata-v2",
        "model": "src/external/service-specifications/srv/external/API_ENTERPRISE_PROJECT_SRV_0002",
        "credentials": {
          "destination": "app-s4public"
        },
        "destinationOptions": {
          "selectionStrategy": "alwaysSubscriber"
        }

      },
      
    }
  }
}

**server.ts**

`
    app.get("/callback/v1.0/dependencies", function (req, res) {
        console.log('Retrive dependencies!!!');
        if (!req.authInfo.checkLocalScope('Callback')) {
            console.log('Forbidden: Dependencies requires Callback scope!');
            res.status(403).send('Forbidden');
            return;
        }
        let dependencies = [{
            'xsappname': services.dest.xsappname
        }];
        console.log('Dependencies:', dependencies);
        console.log('Retrive dependencies end!!!:',dependencies);

        res.status(200).json(dependencies);
    });
`
`
    app.get("/srv/subscriptions", function (req, res) {
        if (req.authInfo.checkScope('$XSAPPNAME.Administrator')) {
            lib.getSubscriptions(services.registry).then(
                function (result) {
                    res.status(200).json(result);
                },
                function (err) {
                    console.log(err.stack);
                    res.status(500).send(err.message);
                });
        } else {
            res.status(403).send('Forbidden');
        }
    });
`
`
app.get('/srv/destinations', async function (req, res) {
        console.log('Retrive destinations!!!');

        if (req.authInfo.checkScope('$XSAPPNAME.User')) {
            try {
                let res1 = await httpClient.executeHttpRequest(
                    {
                        destinationName: req.query.destination || '',
                        jwt: retrieveJwt(req)
                    },
                    {
                        method: 'GET',
                        url: req.query.path || '/'
                    }
                );
                res.status(200).json(res1.data);
                console.log('Retrive destinations!!!:', res1.data);
            } catch (err) {
                console.log(err.stack);
                res.status(500).send(err.message);
                console.log('Retrive destinations!!!:', err.message);
            }
        } else {
            res.status(403).send('Forbidden');
        }
        

    });
`

**Comment by deekshas8** [comment]
Hi @FedorSh-illumiti ,

Thanks for reaching out to us. The error seems to indicate that either the service credentials are incorrect or the XSUAA does not allow issuing a token for the destination service. For the latter, please check if the destination service is missing as a [dependency of your multitenant application](https://sap.github.io/cloud-sdk/docs/js/tutorials/multi-tenant-application).

You can also refer to our [troubleshooting guide](https://sap.github.io/cloud-sdk/docs/js/troubleshooting#get-destination-error) which points out possible reasons for errors in fetching a destination.
