### ISSUE TITLE
Error in OpenAPI client execute() method - getting "Unable to get access token for "destination" service. No service instance of type "destination" found."

### ISSUE THREAD

**Issue by tonymathew17sap** [SAP/cloud-sdk-js#3898]
**Describe the bug**

Error in OpenAPI client execute() method - getting "Unable to get access token for "destination" service. No service instance of type "destination" found."

Used Versions:
node version via node -v 18.16.0
SAP Cloud SDK version you used as dependency v3.0.1

**Additional context**
I have created an open api client. Getting the above error when I trigger .execute() method with a destination name. The destination is configured in BTP subaccount level.  

This is what I'm trying to do:

```ts
await MyApi.myFunction().execute({
  destinationName: 'destinationName',
});
```      
      
This is giving me the below error:
"Unable to get access token for "destination" service. No service instance of type "destination" found."
      
 This was working well until recently.

**Comment by deekshas8** [comment]
Hi @tonymathew17sap ,

The error seems to suggest that a binding to the destination service is missing. Can you confirm that your application is bound to a destination service instance? 

Could you also share the detailed log message with the error stack trace?

**Comment by tonymathew17sap** [comment]
Hi @deekshas8 , so my application is deployed in kyma and I have followed this link to consume destination service instance in my application: https://help.sap.com/docs/btp/sap-business-technology-platform/using-sap-btp-services-in-kyma-environment. 

Basically this is what I have done:
1. Created a service instance
2. Created a service binding

Please let me know if I have missed any steps to bind destination service to my application. 

These are the error logs that I'm getting:

Error: Unable to get access token for "destination" service. No service instance of type "destination" found.
    at resolveService (/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/environment-accessor.js:192:19)
    at serviceToken (/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/token-accessor.js:27:57)
    at getProviderServiceToken (/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/get-provider-token.js:12:61)
    at DestinationFromServiceRetriever.getDestinationFromDestinationService (/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-from-service.js:63:86)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async getDestination (/node_modules/@sap-cloud-sdk/connectivity/dist/scp-cf/destination/destination-accessor.js:72:10)
    at async OpenApiRequestBuilder.executeRaw (/node_modules/@sap-cloud-sdk/openapi/dist/openapi-request-builder.js:76:37)
    at async OpenApiRequestBuilder.execute (/node_modules/@sap-cloud-sdk/openapi/dist/openapi-request-builder.js:91:26)
    at async CasesService.getCaseById (/dist/cases/cases.service.js:19:34)

I get the following logs as well:

{"custom_fields":{"messageContext":"environment-accessor","package":"connectivity"},"level":"warn","logger":"sap-cloud-sdk-logger","message":"No services of type destination found! This might cause errors in other parts of the application.","msg":"No services of type destination found! This might cause errors in other parts of the application.","timestamp":"2023-05-31T10:43:52.136Z","written_at":"2023-05-31T10:43:52.136Z","written_ts":1685529832136}

Also, please note that until recently, even without creating any service instance/binding, cloud-sdk in my application was able to connect to destination just by passing the destinationName like this:

await MyApi.myFunction().execute({
destinationName: 'destinationName',
});

**Comment by tonymathew17sap** [comment]
> Hey @tonymathew17sap,
> 
> we are currently working on a guide specifically for Kyma, but for now, we only have a guide for Kubernetes, which should be mostly applicable to Kyma as well. Did you mount the created secrets into your application? Please check that you do this as described in this [guide](https://sap.github.io/cloud-sdk/docs/js/guides/kubernetes#deployment-configuration). Please share your `deployment.yml` to check if everything is correctly specified.

Hi @marikaner I did not mount the created secrets into my application. I have attached my deployment.yml(attached as .txt file)
[deployment.txt](https://github.com/SAP/cloud-sdk-js/files/11615925/deployment.txt)

Could you please tell me if there's any other steps involved other than creating service instance, service binding and mounting the secrets?

Also I'm unable to understand how cloud-sdk was able to connect to the destination earlier without any of these settings

**Comment by ptesny** [comment]
https://blogs.sap.com/2022/07/12/the-new-way-to-consume-service-bindings-on-kyma-runtime/

**Comment by marikaner** [comment]
Hey @tonymathew17sap, same for me, the SDK cannot connect to the destination without these settings. So there must have been some setup, maybe created by someone else?

**Comment by marikaner** [comment]
> https://blogs.sap.com/2022/07/12/the-new-way-to-consume-service-bindings-on-kyma-runtime/

This would work for Java, but probably won't for JavaScript.

**Comment by tonymathew17sap** [comment]
> https://blogs.sap.com/2022/07/12/the-new-way-to-consume-service-bindings-on-kyma-runtime/

This fixed the issue

**Comment by tomfrenken** [comment]
Hey @ptesny, thanks for supporting in solving the issue.
Interesting that `@sap/xsenv` now seems to support `SERVICE_BINDING_ROOT` as outlined in the guide you've linked, we didn't find any mention of it in their docs, but since it worked for you I suppose we can update our own guide as well.

**Comment by ptesny** [comment]
indeed, all the main sap libraries do support `SERVICE_BINDING_ROOT` paradigm; 
not sure why the externally facing documentation has not been updated so far...

PS. 
https://blogs.sap.com/2023/02/06/power-of-serverless-with-sap-btp-kyma-runtime.-secrets-mounted-as-volumes./
