### ISSUE TITLE
Resilience middlewares with executeHttpRequest do not seem to work

### ISSUE THREAD

**Issue by ptesny** [SAP/cloud-sdk-js#3941]
In a nutshell, I wanted to implement the default resilience middlewares with executeHttpRequest;
What I did is the following:

```
const { resilience } = require ('@sap-cloud-sdk/resilience');
const ResilienceOptions = {
  timeout: 300*1000, // 5 minutes in milliseconds
  circuitBreaker: false,
  retry: 10
};          
const [retry10,  timeout5min] =  resilience(ResilienceOptions);

console.log('resilience: ', resilience(ResilienceOptions));
```
next I add the middleware object to the options of the `executeHttpRequest` method

```
const url = req.query.path;
const jwt = retrieveJwt(req);

var params = new URLSearchParams();
params.append('Param', '{"OpportunityIds" : ["***********"],"MainOnly" : false}');

const options = {
      middleware: resilience(ResilienceOptions),
      method: 'post',
      url: url || '',
      timeout: ResilienceOptions.timeout,
      headers: {'Content-Type': 'application/x-www-form-urlencoded' },
      data : params
    }
console.log(options);

try {
  const response = await httpClient.executeHttpRequest(
    {
      destinationName: req.query.destination
      ,
      jwt: jwt
      ,
      useCache: true
    },
    options
  );
  results = JSON.stringify(response.data,0,2);
  console.log('executeHttpRequest:', results);

  return results;
  
} 
catch (err) {
  debug('/srv/harmony', err.message, err.stack, url, jwt);
  results = err.message;
}

```
The end result is that I do not see it this has any impact at all; What I mean is the code above works if the executeHttpRequest destination call works and there is no retry if the executeHttpRequest destination call fails.

It is like the timeout and retry middlewares were not taken into account. And the activated debug level logging does not offer any additional info...

For the sake of mental sanity I implemented the retry middleware manually using the same https://www.npmjs.com/package/async-retry that you rely upon internally. And guess what it does work....

@marikaner , @FrankEssenberger 
Do you see anything from the configuration point of view that may be required to activate the out-of-the-box resilience middlewares ? Or is it a bug (I've tested it with the latest version of cloud-sdk) ?

**Comment by ptesny** [comment]
OK. It looks like the middlewares do not kick in because:

https://github.com/SAP/cloud-sdk-js/blob/main/packages/http-client/src/http-client.ts#L416
```
Failed to build headers. ErrorWithCause: Failed to build headers.
at buildHeaders (/usr/src/app/function/node_modules/@sap-cloud-sdk/http-client/dist/http-client.js:296:15)
```
and my request is POST so the following will not execute:
https://github.com/SAP/cloud-sdk-js/blob/main/packages/http-client/src/http-client.ts#L98

**Comment by ptesny** [comment]
So now I put `{ middleware: resilience(ResilienceOptions) }, `  before `'options` in the call to `executeHttpRequest`, namely:

```
const options = {
      method: 'post',
      url: url || '',
      timeout: ResilienceOptions.timeout,
      headers: {'Content-Type': 'application/x-www-form-urlencoded' },
      data : params
    }
console.log(options);
```
```
try {
  const response = await httpClient.executeHttpRequest(
    {
      destinationName: req.query.destination
      ,
      jwt: jwt
      ,
      useCache: true
    },
    { middleware: resilience(ResilienceOptions) },
    options
  );
  return JSON.stringify(response.data,0,2);

} 
catch (err) {
  debug('/srv/harmony', err.message, err.stack, url, jwt);
  results = err.message;
}
```
and this time the middleware kicks in; 
However this ends up miserably retrying 10 times with the message at line: https://github.com/SAP/cloud-sdk-js/blob/main/packages/resilience/src/retry.ts#L46

Same is happening with the GET method....

**Comment by marikaner** [comment]
Hey @ptesny,

thanks you for sharing your insights so thoroughly. After digging a bit deeper with you together, it seems that the actual issue here is, that the resilience functionality is only applied to the target system and not for the destination fetch call.
This is intended. There is a default circuit breaker and timeout for the destination call, but you can enable retries by adding `retry: true` to the destination fetch options. This would add 3 retries to the destination fetch call.

In your code, this is what it would look like:
```js
const response = await httpClient.executeHttpRequest(
    {
      destinationName: req.query.destination
      ,
      jwt: jwt
      ,
      useCache: true
      ,
      retry: true
    },
    options
  );
```

I hope that helps.

**Comment by ptesny** [comment]
Hey @marikaner , thanks; indeed that has addressed to some extent the retry issue; 
As I needed a higher retry value I ended up implementing the retry logic manually;

As discussed, it could be better if the `retry` could be either be a boolean (with a default number of 3 retries) or an actual number of retries. Moreover that would be consistent with the retry definition used in the resilience middlewares.
