### ISSUE TITLE
Documentation about resilience of SAP BTP services ?

### ISSUE THREAD

**Issue by ptesny** [SAP/cloud-sdk-js#3942]
From the following slide it looks like retries for SAP BTP services need to be implemented by the user.
Still where it is documented on how to do it ? The existing resilience documentation seems to be covering the target system only ?

@marikaner , @FrankEssenberger , @deekshas8 
<img width="899" alt="image" src="https://github.com/SAP/cloud-sdk-js/assets/52403733/56d396d1-2a45-4d15-b59c-7d629288c27d">

**Comment by marikaner** [comment]
Hey Piotr, I believe this is what you're looking for: https://sap.github.io/cloud-sdk/docs/js/guides/resilience.

**Comment by ptesny** [comment]
Thx @marikaner ; that was a "loaded" question. I followed the above guide and watched your youtube recording but the application of resilience does not seem to work as described here: https://github.com/SAP/cloud-sdk-js/issues/3941
