### ISSUE TITLE
executeHttpRequest - forwardAuthToken is not working when destination is fetched from destination service instance

### ISSUE THREAD

**Issue by MarcusNotheis** [SAP/cloud-sdk-js#3979]
**Describe the bug**
This is a follow up issue to #3629. 
I think I found a bug when the destination is fetched from an instance-level destination service on cloud foundry. 
It looks like the jwt is not added as Authorization header because the `forwardAuthToken` property is not mapped to the top level part of the `destination` object but is part of `destination.originalProperties` in the `getMergedHeaders` function:

When placing a debugger at the following line:
https://github.com/SAP/cloud-sdk-js/blob/45e2490d2e42813ef495a5b0b19a16b849c6e28e/packages/http-client/src/http-client.ts#L258

then this is the `destination` object:

```json
{
  "originalProperties": {
    "Name": "my-destination",
    "Type": "HTTP",
    "URL": "URL_GOES_HERE",
    "Authentication": "NoAuthentication",
    "ProxyType": "Internet",
    "forwardAuthToken": "true"
  },
  "authTokens": [],
  "certificates": [],
  "name": "my-destination",
  "type": "HTTP",
  "url": "URL_GOES_HERE",
  "authentication": "NoAuthentication",
  "proxyType": "Internet",
  "isTrustingAllCertificates": false
}
```

**To Reproduce**

1. Set up instance-level destination on a CF destination service with `NoAuthentication` and `forwardAuthToken` to 
2. Execute: `executeHttpRequest({ destinationName: 'the-destination-name', jwt }, yourRequestConfig)`
3. Call fails with 401 because the `Authorization` header is not mapped

**Expected behavior**
The JWT should be mapped as Bearer token in the Authorization header

**Used Versions:**

- node version via `node -v`: 18.16.1
- npm version via `npm -v`: 9.5.1
- SAP Cloud SDK version you used as dependency: @sap-cloud-sdk/http-client@3.2.0

**Code Examples**
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information.

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**

Affected development phase: Production
Impact: Inconvenience. Workaround is to add the Authorization header manually.

**Comment by marikaner** [comment]
Hey @MarcusNotheis, thank you for reporting this. We are looking into it!

**Comment by marikaner** [comment]
Ok, after looking into this, I see that this is likely a very similar expectation as on this issue: https://github.com/SAP/cloud-sdk-js/issues/3634. Currently, the SDK does not consider any additional properties with regards to forwarding auth tokens from the destination service. It is only possible to forward tokens using destinations directly (basically if you have a URL without going through the destination service).
Can you sketch your use case, to help me understand your case better?
Also, I can see that you're using `forwardAuthToken` as an additional property on the destination. To my understanding there is also the additional property `HTML5.ForwardAuthToken`, which is meant to be used be the app router. We are now discussing, whether it is safe to assume that when using `HTML5.ForwardAuthToken` the token should also be forwarded in a backend application.

**Comment by MarcusNotheis** [comment]
Hi @marikaner 
sorry for the late reply. Our use case is currently migrating away from the app router to a NextJS based application where we want to access our backend services by forwarding the JWT from the UI Session.
As I was reusing the same destination as in the approuter (with `forwardAuthToken` set, but not `HTML5.forwardAuthToken`) I was under the impression that this should work with the CloudSDK for JS as well.

In addition to that, I also did some tests with the same destination in the Cloud SDK for Java, and there the JWT is forwarded to the destination target.

**Comment by marikaner** [comment]
Hey @MarcusNotheis, I am glad to let you know that we have implemented the token forwarding for all kinds of destinations now, you will find some more detailed documentation here soon: https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#forwarding-auth-tokens. (For a preview you can take a look at this [pull request](https://github.com/SAP/cloud-sdk/pull/1452/files)). You can use both `forwardAuthToken` and `HTML5.ForwardAuthToken` to activate this behavior.
