### ISSUE TITLE
OData V4 Client - POST request - wrong formatting for decimal values

### ISSUE THREAD

**Issue by geert-janklaps** [SAP/cloud-sdk-js#3999]
**Describe the bug**
When sending a POST request to an OData V4 API, decimal fields are wrongfully surrounded by quotes. This gets rejected by the server, as this is interpreted as a string value in stead of a number.

Example of resulting payload (OrderQuantity & NetPriceAmount) are wrongfully generated as string:

`{
  "PurchaseOrderType": "NB",
  "PurchaseOrder": "",
  "CompanyCode": "2580",
  "PurchasingOrganization": "2580",
  "PurchasingGroup": "002",
  "PaymentTerms": "0001",
  "IncotermsClassification": "FOB",
  "IncotermsLocation1": "test",
  "DocumentCurrency": "EUR",
  "Supplier": "25101002",
  "_PurchaseOrderItem": [
    {
      "PurchaseOrder": "",
      "PurchaseOrderItem": "10",
      "Material": "UNC08",
      "OrderQuantity": "10",
      "PurchaseOrderQuantityUnit": "KG",
      "Plant": "2580",
      "NetPriceAmount": "1000",
      "DocumentCurrency": "EUR"
    }
  ]
}`

**To Reproduce**
1. Generate a client for e.g. S/4HANA Cloud Purchase Order API (OData V4)
    https://api.sap.com/api/CE_PURCHASEORDER_0001/overview
2. Prepare a POST request using the entity builder (minimal setup header + item)
3. Execute a POST request
4. Server rejects the request

**Expected behavior**
Fields of type edm.decimal should not be surrounded by quotes in payloads to the server. 
Working payload (changed OrderQuantity & NetPriceAmount): 

`{
  "PurchaseOrder": "",
  "PurchaseOrderType": "NB",
  "CompanyCode": "2580",
  "PurchasingOrganization": "2580",
  "PurchasingGroup": "002",
  "Supplier": "25101002",
  "PaymentTerms": "0001",
  "IncotermsClassification": "FOB",
  "IncotermsLocation1": "tesing",
  "DocumentCurrency": "EUR",
  "_PurchaseOrderItem": [
    {
      "PurchaseOrder": "",
      "PurchaseOrderItem": 10,
      "Material": "UNC08",
      "OrderQuantity": 10,
      "PurchaseOrderQuantityUnit": "KG",
      "Plant": "2580",
      "NetPriceAmount": 1200,
      "DocumentCurrency": "EUR"
  }
  ]
}`

**Screenshots**
Generated request by SAP Cloud SDK
![cloud-sdk-odata-v4-issue](https://github.com/SAP/cloud-sdk-js/assets/2744548/845c7129-723b-4bb4-8c23-6b40d1023a2f)

Working request postman
![odata-v4-working-request](https://github.com/SAP/cloud-sdk-js/assets/2744548/a8c5d231-67f8-4471-8ac4-7dba731e634a)

**Used Versions:**

- node version: 16.19.0
- npm version: 8.19.3
- SAP Cloud SDK: 3.2.0

**Impact / Priority**

Affected development phase: Release

Impact: Blocked

Timeline: Go-Live is in 3 weeks.

**Comment by deekshas8** [comment]
Hi @geert-janklaps ,

Thank you for reaching out to us. We are aware of the issue with serialization of `Edm.Decimal` type and are working on it. I'll update you once we have a fix.

By default, the SDK serializes all Decimal values to type string. However, you can override this behavior using the Custom (De)serializers to ensure decimal values are serialized to number instead of string. 

Please refer to the documentation and usage [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/v4-client#customize-de-serialization). Let me know if that helps.

**Comment by deekshas8** [comment]
Hi @geert-janklaps ,

We fixed the issue in the latest `v3.5.0` release. We now serialize to `number` when values are within the safe integer range and strings, if not. Please reopen if you're still facing issues.
