### ISSUE TITLE
Edm.Decimal in OData v2 Client serializes into JSON number instead of string

### ISSUE THREAD

**Issue by mathewzile** [SAP/cloud-sdk-js#4044]
**Describe the bug**
Since v3.4.0 of @sap-cloud-sdk/odata-common (PR #4020), Edm.Decimal is being serialized into JSON Number format even for OData v2. From the [v2 specs](https://www.odata.org/documentation/odata-version-2-0/json-format/), it seems that JSON String is the expected format for Edm.Decimal. 

I currently have a custom OData v2 service in S4 being consumed in CAP JS and after the upgrade, the S4 OData started returning error when number is sent instead of strings for such properties:

**To Reproduce**

1. Generate a client from an S4 OData v2 API (eg. API_SALES_ORDER_SRV)
2. Execute a create request on an entity containing an Edm.Decimal property (eg. on salesOrderApi, passing salesOrder and accountingExchangeRate)
3. Confirm the request payload for the Edm.Decimal property is received in JSON number format instead of JSON string in S4
![image](https://github.com/SAP/cloud-sdk-js/assets/37588026/1161612b-f3ef-4105-8563-e6049319adfe)
4. See error in S4 response
![image](https://github.com/SAP/cloud-sdk-js/assets/37588026/b1855db9-dbb8-41f0-beea-8ee4bcba3a34)

**Expected behavior**
For OData v2, Edm.Decimal should be sent as string (with double quotes). For OData v4, current logic remains.

**Screenshots**
Error response from S4 can quickly be reproduced using Postman
![image](https://github.com/SAP/cloud-sdk-js/assets/37588026/4f50bd06-f819-4bc2-99e4-31736e36d1d2)

**Used Versions:**
- node v18.14.0
- npm 9.3.1
- SAP Cloud SDK v3.4.0

**Code Examples**
N/A

**Log file**
N/A

**Impact / Priority**
Low

Affected development phase: Development

Impact: Inconvenience

Timeline: N/A

**Additional context**
N/A

**Comment by marikaner** [comment]
Hey @mathewzile, thanks for reaching out. We will fix this as soon as possible.

**Comment by arunkrishnamoorthy** [comment]
@marikaner @mathewzile I am facing this issue while consuming API_MANAGE_TIMESHEET. Is there a workaround available for this issue.

**Comment by deekshas8** [comment]
Hi @mathewzile @arunkrishnamoorthy ,

We fixed the issue in the latest `v3.5.0` release. Please try it out.
