### ISSUE TITLE
401 Unauthorized error when calling OData V4 Service on S4 HANA On Premise

### ISSUE THREAD

**Issue by thisisevanfox** [SAP/cloud-sdk-js#4049]
Hi community,

we implemented an OData v4 service on a S4/HANA On Premise System and ran in a similar error like described [here](https://answers.sap.com/questions/13906168/s4hana-onpremise-odata-v4-service-is-not-accessibl.html). Since there isn't a solution to fix the issue described and we had some findings, we decided to open an issue here. 

Our On Premise system is connected via a cloud connector to our SAP BTP subaccount. When calling the OData v4 service via the `executeHttpRequest` function of the `@sap-cloud-sdk/http-client` module we get an 401 Unauthorized response.

When calling an OData v2 service on the same system we get an 200 OK response when running the same code only with another service path. 

Do we have to configure something on our S4/HANA system to "allow" calling an OData v4 service from outside? Or is something wrong with our destination in the BTP subaccount or is our implementation only valid for v2 services? Or is it a bug in the cloud-sdk?

We are calling the `http-client` like this:
```typescript
import * as httpClient from "@sap-cloud-sdk/http-client";

(...)

const destinationOptions = {
    "destinationName": "<MY_DESTINATION>",
    "isolationStrategy": "tenant",
    "jwt": "<MY_TOKEN>"
};

const requestOptions = {
    "url": "/sap/opu/odata4/mns/my_srv_v4/srvd/mns/my/0001/<MyEntity>", // v4 -- not working
    // "url": "/sap/opu/odata/MNS/MY_SRV_V2/<MyEntity>" // v2 -- working
    "method": "GET",
    "headers": {},
    "data": {},
    "params": {}
};

try {
	const response = await httpClient.executeHttpRequest(destinationOptions , requestOptions);
	(...)
} catch (error) {
	(...)
	// here we get the 401 Unauthorized when calling the v4 service
}
```

We debugged a bit in the node module and compared the request objects which are actually sent at this line of code:
![image](https://github.com/SAP/cloud-sdk-js/assets/43059689/ad7794d8-09c9-4b83-a875-9e5b94649e66)

The `req` object at this point looks exactly the same regardless which service we call.
OData v4 (which results in a 401 Unauthorized error):
```json
{
    "baseURL": "http://<VIRTUAL_HOST_FROM_CLOUDCONNECTOR>:<PORT>",
    "headers": {
        "authorization": "Basic <BASE64_USER_PASSWORD_FROM_DESTINATION>",
        "Proxy-Authorization": "Bearer <JWT_FROM_CONNECTIVITY_SERVICE>",
        "sap-client": "<SAP_CLIENT_OF_ADDITIONAL_PROPERTIES_FROM_DESTINATION>"
    },
    "params": {},
    "httpAgent": {
        "_events": {},
        "_eventsCount": 0,
        "timeout": null,
        "maxFreeSockets": 1,
        "maxSockets": 1,
        "maxTotalSockets": null,
        "sockets": {},
        "freeSockets": {},
        "requests": {},
        "options": {},
        "secureProxy": false,
        "proxy": {
            "host": "connectivityproxy.internal.cf.eu10.hana.ondemand.com",
            "protocol": "http",
            "port": 20003
        }
    },
    "url": "/sap/opu/odata4/mns/my_srv_v4/srvd/mns/my/0001/<MyEntity>",
    "method": "GET",
    "data": {}
}
```
OData v2 (successful):
```json
{
    "baseURL": "http://<VIRTUAL_HOST_FROM_CLOUDCONNECTOR>:<PORT>",
    "headers": {
        "authorization": "Basic <BASE64_USER_PASSWORD_FROM_DESTINATION>",
        "Proxy-Authorization": "Bearer <JWT_FROM_CONNECTIVITY_SERVICE>",
        "sap-client": "<SAP_CLIENT_OF_ADDITIONAL_PROPERTIES_FROM_DESTINATION>"
    },
    "params": {},
    "httpAgent": {
        "_events": {},
        "_eventsCount": 0,
        "timeout": null,
        "maxFreeSockets": 1,
        "maxSockets": 1,
        "maxTotalSockets": null,
        "sockets": {},
        "freeSockets": {},
        "requests": {},
        "options": {},
        "secureProxy": false,
        "proxy": {
            "host": "connectivityproxy.internal.cf.eu10.hana.ondemand.com",
            "protocol": "http",
            "port": 20003
        }
    },
    "url": "/sap/opu/odata/MNS/MY_SRV_V2/<MyEntity>",
    "method": "GET",
    "data": {}
}
```

The `Proxy-Authorization` Bearer token and the `authorization` string are identical in both requests.

In both requests the destination is fetched correctly from the BTP subaccount, so we could see the URI, username and password of the desired S4 HANA system:
![image](https://github.com/SAP/cloud-sdk-js/assets/43059689/dda65e86-0d0e-48a1-aed1-4e7b406e9627)

In the logs of our Cloud Connector we also see that the request to the S4/HANA system is "allowed":
![image](https://github.com/SAP/cloud-sdk-js/assets/43059689/1c6fc418-41a5-4ac0-b2f0-c8f6043b06b5)
... but at some point the 401 Unauthorized is thrown.

**Used Versions:**
@sap-cloud-sdk/http-client: 3.2.0
@sap/cds: 6.8.4
@sap/cds-compiler: 3.9.4
@sap/cds-dk: 6.8.3
@sap/cds-dk (global): 6.8.3
@sap/cds-foss: 4.0.2
@sap/cds-mtx: 2.6.4
@sap/hdi-deploy: 4.6.1
@sap/instance-manager: 3.5.3
Node.js: v18.16.0

Kind regards,
Johannes

**Comment by tomfrenken** [comment]
Hey @thisisevanfox,

from what I can tell the SAP Cloud SDK is doing the expected authentication flow, the fact that it's still throwing a 401 indicates you are doing something wrong on your end.

To narrow it down, you could try to [generate a client](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client) for your service with one of our generators.
If it also fails with one of these clients, it is definitely a setup issue, meaning you would have to change something, most likely in the hana.

Unfortunately, we're no HANA experts, therefore I would have to advise you to ask on answers.sap.com and follow up on the issue you've linked there.

**Comment by thisisevanfox** [comment]
Hi @tomfrenken,

we have reimported the certificates on our OnPremise system, now it works. Sorry for bothering you and thanks for the quick reply.

Kind regards,
Johannes
