### ISSUE TITLE
Support for FTP based destinations

### ISSUE THREAD

**Issue by ThomasSwolfs** [SAP/cloud-sdk-js#4055]
**Describe the solution you'd like**
An FTP destination implementation to read and write files to an FTP server.

**Describe alternatives you've considered**
Currently FTP connection needs to be done outside of the Cloud SDK. This could be integrated in the Cloud SDK with help of a library like ssh2-sftp-client.

**Comment by jjtang1985** [comment]
Hi @ThomasSwolfs ,

Thanks for reaching out.

Could you please share more details of the requirement?
For example, where would you host your FTP server?
Would it be an on-premise server, SaaS from a cloud provider, or maybe you deploy it on BTP?

Where would you deploy your application that consumes the FTP server?
Cloud Foundry? Kyma?

Are you using the SAP Cloud Integration?
If so, this [FTP adapter](https://help.sap.com/docs/cloud-integration/sap-cloud-integration/ftp-adapter) might be relevant?

**Comment by ThomasSwolfs** [comment]
Hi @jjtang1985 

In our specific context the FTP server is the one provided by SAP in SuccessFactors LMS. As the LMS API's are limited and SAP is not improving them, the FTP connectors are still a very popular way of communicating with LMS.

Our BTP applications are currently mainly hosted in Cloud Foundry.

In our case, SAP Cloud Integration is not used.

Currently we use the ssh2-sftp-client library directly in our project.

**Comment by jjtang1985** [comment]
Hi @ThomasSwolfs,

Sorry for my late response.
Thank you for sharing the background of this use case.
Unfortunately, this is the first time we hear this requirement, so I'm afraid that in the near future, we'll not be able to work on that.

Perhaps you can share your FTP specific requirement in the following platform:
- [Customer influence and adoption](https://www.sap.com/about/customer-involvement/influence-adopt.html)
- [Customer influence](https://influence.sap.com/sap/ino/#)

**Comment by jjtang1985** [comment]
I'll close this ticket, as this is out of the SDK scope.
