### ISSUE TITLE
Typescript transpilation with target ES2022 results in different payload

### ISSUE THREAD

**Issue by geert-janklaps** [SAP/cloud-sdk-js#4074]
**Describe the bug**
We recently switched our project from node v16 to v18 and are using the latest SAP Cloud SDK (3.4.0).
Our project uses the best practice @tsconfig/node18 as base for our tsconfig files (extends mechnism), previously we used @tsconfig/node16.

The problem arises when the target is set to ES2022, for some reason the payload of the same code changes and includes all fields instead of only the fields set in the program. (CREATE request)
Due to the fact each unset value now contains null as a value the request is rejected by the server. (null is not excepted in each field)

**To Reproduce**

1. Generate a cloud sdk library for e.g. Sales Order Simulate (S/4HANA Cloud SDK)
2. Create a sample program setting a few fields
3. Create a tsconfig file with target set to ES2021
4. Test the program and check the payload generated
5. Change the tsconfig file and set target to ES2022
6. Test the program and check the payload generated (will be different from previous sample)

**Expected behavior**
The payload should only contain the fields which are set using the request builder.

**Screenshots**
Example payload with ES2021 (working):
![target-ES2021](https://github.com/SAP/cloud-sdk-js/assets/2744548/30f590cd-1616-49ea-a156-f4c9e8bb099e)

Example payload with ES2022 (rejected):
![target-ES2022](https://github.com/SAP/cloud-sdk-js/assets/2744548/67f813a9-2034-4f81-97d0-c29dff2b35cb)

**Used Versions:**

- node version: 18.14.2 (Business Application Studio)
- npm version: 9.5.0 (Business Application Studio)
- SAP Cloud SDK version: 3.4.0

**Impact / Priority**

Affected development phase: Development

Impact: Inconvenience

**Additional context**

**Comment by deekshas8** [comment]
Hi @geert-janklaps ,

Thank you for raising this. I have created a backlog item to support this. We will update you when this is available.

**Comment by deekshas8** [comment]
Hi @geert-janklaps, the fix is part of the newly released v3.7.0. Please give it a try.
