### ISSUE TITLE
@sap-cloud-sdk/mail-client  - SocksClientError: read ECONNRESET

### ISSUE THREAD

**Issue by vdevExplorer** [SAP/cloud-sdk-js#4146]
I am trying to call an On-Premise MAIL Destination the mail-client module responds with  SocksClientError: read ECONNRESET

Complete Error:

SocksClientError: read ECONNRESET
    at SocksClient.closeSocket (/home/user/projects/jobaction/node_modules/socks/build/client/socksclient.js:390:32)
    at SocksClient.onErrorHandler (/home/user/projects/jobaction/node_modules/socks/build/client/socksclient.js:363:14)
    at Socket.onError (/home/user/projects/jobaction/node_modules/socks/build/client/socksclient.js:225:38)
    at Object.onceWrapper (node:events:628:26)
    at Socket.emit (node:events:513:28)
    at emitErrorNT (node:internal/streams/destroy:151:8)
    at emitErrorCloseNT (node:internal/streams/destroy:116:3)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21) {
  options: {
    proxy: {
      host: 'connectivityproxy.internal.cf.us10.hana.ondemand.com',
      port: 20004,
      type: 5,
      custom_auth_method: 128,
      custom_auth_request_handler: [Function: custom_auth_request_handler],
      custom_auth_response_size: 2,
      custom_auth_response_handler: [AsyncFunction: customAuthResponseHandler]
    },
    command: 'connect',
    destination: { host: 'smtptest', port: 5525 }
  }
}

Example Code:

const { sendMail } = require("@sap-cloud-sdk/mail-client");
sendMail({ destinationName: "mail_destination" }, {
      to: test@gmail.com,
      text: 'Test Mail'
      subject: "test mail"
      },
      {
        tls: {
          rejectUnauthorized: false
        } 
      } )

I binded connectivity service, destination service, xsuaa service to test hybrid from BAS.

Any pointers in resolving the error would be appreciated.

Thanks,

**Comment by jjtang1985** [comment]
Here are some additional messages from the author.

> I asked a question in the cloud sdk repo.I am not sure if I am missing any config, I tried everything . The mail is working if the MAIL destination is INTERNET
> the issue is with the onpremise MAIL destination

> There is only one cloud connector associated with the subaccount where we are developing the app.
> the cloud connector is linked to multiple subaccounts. (One subaccount has Integration Suite, the other sub account is for App dev)
> from Integration Suite, we can send emails to to same Destination.

**Comment by marikaner** [comment]
Hey @vdevExplorer,

I will try to reproduce this issue, could you however explain the setup with integration suite, where this works in a bit more detail? Maybe this will reveal some hints.

**Comment by jjtang1985** [comment]
Thank you @vdevExplorer for your updates.
Happy to hear that it worked.

BTW, what is the "hybrid mode"?
It would be very helpful, if you can share more details?
Is it about this CAP [Hybrid testing](https://cap.cloud.sap/docs/advanced/hybrid-testing)?

**Comment by vdevExplorer** [comment]
yes it is CAP Hybrid tesiting. I tried to test locally by binding the services before I deploy the app the BTP  and I encountered the issue on connection refused. I will submit a ticket to BTP connectivity service team aswell.

**Comment by mr-flannery** [comment]
Hi @vdevExplorer , sorry for only getting back to you now.

As far as I'm aware, the connectivity service is not reachable from outside the BTP network, which explains why it's working when deployed, but not from BAS. Whether or not this should work from BAS or not I do not know, but to my understanding, BAS is whom you should ask about this.

I will close the ticket. Should you find out that there is indeed an issue with the Cloud SDK, feel free to reopen or create a new ticket.

**Comment by eliasfelipedasilva** [comment]
I tried to connect to an oracle host via socks, but the socks connection is closing as reported above. Here's the implementation:


`class ConnectivitySocks {
  #jwtCache;
  #socket;
  #connectivityCredentials;
  #remoteHost;
  #remotePort;

  constructor(remoteHost, remotePort) {
    xsenv.loadEnv();
    this.#connectivityCredentials = xsenv.serviceCredentials({ tag: 'connectivity' });
    if (!this.#connectivityCredentials) {
      throw Error('No connectivity credentials provided (local: not supported, SAP BTP: check binding)');
    }
    this.#jwtCache = {
      expiration: 0,
      jwt: undefined,
    };
    this.#remoteHost = remoteHost;
    this.#remotePort = remotePort;
    this.#createSocket();
  }

  async #connectivityToken() {
    return new Promise((resolve, reject) => {
      log('Renewing the new connectivity access token');
      https.get(
        `${this.#connectivityCredentials.token_service_url}/oauth/token?grant_type=client_credentials&response_type=token`,
        {
          headers: {
            Authorization: `Basic ${Buffer.from(`${this.#connectivityCredentials.clientid}:${this.#connectivityCredentials.clientsecret}`).toString('base64')}`,
          },
        },
        (res) => {
          const data = [];
          res.on('data', (chunk) => data.push(chunk));
          res.on('end', () => {
            let r = JSON.parse(data.join(''));
            this.#jwtCache.expiration = Date.now() + (r.expires_in - 60) * 1000;
            this.#jwtCache.jwt = r.access_token;
            resolve(r.access_token);
          });
        }
      ).on('error', (err) => {
        reject('Error while getting connectivity JWT: ' + err.message);
      });
    });
  }

  async #generateSocksClientOptions() {
    let jwt = Date.now() > this.#jwtCache.expiration ? await this.#connectivityToken() : this.#jwtCache.jwt;

    let logAuthMessage = function (authStatusByte) {
      if (socksAuthMessages.length < authStatusByte - 1) {
        log('ERROR: Unknown SOCKS5 auth flow error.');
      } else {
        log(socksAuthMessages[authStatusByte]);
      }
    };

    let sLocationBase64 ='';
    let iJWTLength = Buffer.byteLength(jwt, 'utf8');
    let iLocationLength = Buffer.byteLength(sLocationBase64, 'utf8');
    let xJWTLengthBuffer = Buffer.alloc(4);
    xJWTLengthBuffer.writeInt32BE(iJWTLength);
    let xLocationLengthBuffer = Buffer.alloc(1);
    xLocationLengthBuffer.writeInt8(iLocationLength);
    return {
      proxy: {
        host: this.#connectivityCredentials.onpremise_proxy_host,
        port: parseInt(this.#connectivityCredentials.onpremise_socks5_proxy_port),
        type: 5,
        custom_auth_method: 0x80,
        custom_auth_request_handler: async () => {
          return Buffer.concat([
            Buffer.from([0x01]), // Authentication method version - currently 1
            xJWTLengthBuffer, // Length of the JWT
            Buffer.from(jwt), // The actual value of the JWT in its encoded form
            xLocationLengthBuffer, // Length of the Cloud Connector location ID (0 if no Cloud Connector location ID is used)
            Buffer.from(sLocationBase64), // The value of the Cloud Connector location ID in base64-encoded form
          ]);
        },
        custom_auth_response_size: 2,
        custom_auth_response_handler: async (data) => {
          logAuthMessage(data[1]);
          return data[1] === 0x00;
        },
      },
      command: 'connect',
      destination: {
        host: 'exacc04-scan.aroeira.corp',
        port: 1521,
      },
    };
  }

  async #createSocket() {
    this.#socket = new net.Socket();
    this.#socket.setKeepAlive(true, 60 * 60 * 1000); // TODO: no effect because BTP ends first
    this.#socket.setTimeout(60 * 60 * 1000); // TODO: no effect because BTP ends first

    const connectSocksSocket = () => {
      this.#socket.connect(this.#connectivityCredentials.onpremise_socks5_proxy_port, this.#connectivityCredentials.onpremise_proxy_host, async () => {
        let options = await this.#generateSocksClientOptions();
        let socksClient = new SocksClient(options);
        socksClient.connect(this.#socket);
      });
    };

    this.#socket.on('close', () => {
      log('Connection closed, reconnecting...');
      connectSocksSocket();
    });
    this.#socket.on('error', (e) => {
      log('Socket error: ', e.code);
    });
    this.#socket.on('end', () => {
      log('Socket ended by BTP');
    });
    this.#socket.on('ready', () => {
      log('Socket ready');
    });
    this.#socket.on('timeout', () => {
      log('Socket timeout due to inactivity');
    });
    this.#socket.on('connect', () => {
      log('Socket connected');
    });

    connectSocksSocket();
  }

  getSocket() {
    return this.#socket;
  }
}

module.exports.ConnectivitySocks = ConnectivitySocks;
`


And
  const proxySocket = proxy.getSocket();
  
  Is there any documentation on how to connect to a host in the cloud connector via nodejs cloud foundry ?



A
