### ISSUE TITLE
how to pass iasToXsuaaTokenExchange as false for IAS usage (defaults to true) 

### ISSUE THREAD

**Issue by JanPfenning** [SAP/cloud-sdk-js#4156]
We use the BTP destination-service to retrieve the url of the target service.
Via cds.connect.to('destination-name') cap does plenty of calls in the background and lands in the function getDestinationFromDestinationService (in destination-from-service.js).
The first clause here calls shouldExchangeToken which is a function in identity-service.js.
Here the issue arises. The flag iasToXsuaaTokenExchange defaults to true but we need it to be set to false, since were using ias. 
but we cant manage to find a way to do this.
For reference: we also opened an [internal issue on the CAP side](https://github.tools.sap/cap/issues/issues/14500) but they told us to reach out to you guys. maybe that is something you should fix together because IAS integration will be growing importance

**Comment by marikaner** [comment]
As discussed in person, the underlying issue a bit different and resolved internally. The answer to the actual question is, just pass `iasToXsuaaTokenExchange: false` in the destination fetch options 😊
