### ISSUE TITLE
Unable to call an external API using @sap-cloud-sdk/http-client

### ISSUE THREAD

**Issue by manoj5783sap** [SAP/cloud-sdk-js#4197]
Hi All,
Whenever i try to call an external api using @sap-cloud-sdk/http-client, i get this below error: HTTP 405 Method Not Allowed.
I am accessing the application from BTP and i am running the url directly without a destination(thought will get this working with a direct url coz i wasnt able to get the reference of the destination. A problem to solve for later). 
I am running a POST method coz the API would accept only POST and i am able to execute it successfully from Postman with a POST call.
Please help.

Thanks,
Manoj

**Comment by tomfrenken** [comment]
Hey @manoj5783sap,

please share your code, otherwise, we can't help you.

**Comment by manoj5783sap** [comment]
Hi,
Thanks for your reply.
                                                                                                 const response = await executeHttpRequest({
      method: 'POST',
      url: "https://myurl",
      data: 
      {
        "queryIdentifier": "API_ECS_Webservice_3",
        "top": 100
      },
      headers: {
        "Authorization": "Bearer ea893ccfa219c34afe962788e4907c",
        "Content-Type": "application/json" 
      }
    });

This is the code i am using. 
This is a simple code which i took it from the sdk itself to call an external api without a destination.

Thanks,
Manoj

**Comment by marikaner** [comment]
Hey @manoj5783sap,

the first parameter of `executeHttpRequest()` is the destination, the second is the request config. So I assume, what you want is this:

```ts
  const response = await executeHttpRequest({ url: "https://myurl" }, {
      method: 'POST',
      data: 
      {
        "queryIdentifier": "API_ECS_Webservice_3",
        "top": 100
      },
      headers: {
        "Authorization": "Bearer ea893ccfa219c34afe962788e4907c",
        "Content-Type": "application/json" 
      }
    });
```

Let me know it this helps!
