### ISSUE TITLE
ProxyConfiguration not respected in @sap-cloud-sdk/connectivity@3.7.0

### ISSUE THREAD

**Issue by muellinho** [SAP/cloud-sdk-js#4210]
Hi,

I think I found the following bug:

**Describe the bug**
When using the package @sap-cloud-sdk/connectivity in version 3.7.0 I noticed, that requests to an on-Premise system (through the cloud connector) were not resolved correctly.

The package doesn't take the proxy settings from destinations into account.
When the request was executed I was confronted with the error message: "ENOTFOUND onPremise System-Id".
<br>

**To Reproduce**
To reproduce the behaviour it should be enough to try to consume an onPremise Service through the use of the destination / connectivity service.
<br>

**Expected behavior**
The proxy settings from the destinations configuration should be taken into account.
<br>

**Screenshots**
I compared an earlier version of my application with the new one and found the following code snippets that show the problem.

**@sap-cloud-sdk/connectivity@3.5.0**

**Function getAgentConfig:**
In the following picture you can see that the `destination` with the proxy settings and an empty `certificateOptions` object is passed to the proxyAgent function.

![image](https://github.com/SAP/cloud-sdk-js/assets/23531536/35e532e0-20b2-4e63-a0e7-879812118ea9)

**Function proxyAgent:**
In here you can see at line 176-181 that an `agentConfig` object is created which takes in the `proxyConfiguration`.
The `agentConfig` object is then used to create a `proxyAgent` later.

![image](https://github.com/SAP/cloud-sdk-js/assets/23531536/fd373f06-057d-432e-9eee-9cfd26e3d76f)

<br>

**@sap-cloud-sdk/connectivity@3.7.0**

**Function getAgentConfig**
In the following picture we can see that the code changed a little, but it still passes the `destination` with proxySettings and an empty `certificateOptions` object to the `createAgent` function.

![image](https://github.com/SAP/cloud-sdk-js/assets/23531536/1a259c86-30b7-4423-87df-f3c4cccf46db)

**Function createAgent**
In the createAgent function however, we can see that the destination is only used to evaluate if we need an https or http Agent.
To create the agent, only the empty `options` (`certificateOptions`) object is respected.
This causes the resulting agent to not be a proxyAgent.

![image](https://github.com/SAP/cloud-sdk-js/assets/23531536/f1bc09af-294a-4b38-a154-2701b475275f)
<br>

**Used Versions:**
@sap-cloud-sdk/connectivity@3.7.0

I think the bug was introduced however with version 3.6.0 (see [release Notes](https://sap.github.io/cloud-sdk/docs/js/release-notes#360-core-modules---october-02-2023))
<br>

**Impact / Priority**
The impact on my project is, that I can only use an older build of my application, since I don't use @sap-cloud-sdk/connectivity directly.
Instead I'm only using @sap-cloud-sdk/http-client@3.1.1, but this package depends on the connectivity package with the semver: `^3.1.1` which causes to load the package with the bug described above.
<br>

Affected development phase: Release

Impact: Impaired

Timeline: Go-Live is in a couple of weeks.

If you need further info, feel free to reach out

Best regards
Jan

**Comment by muellinho** [comment]
**UPDATE:**

I analyzed my project a little further and it seems that there actually isn't a bug in `@sap-cloud-sdk/connectivity@3.7.0`

I noticed, that in my package.json I refer to `@sap-cloud-sdk/http-client@3.1.1` (notice that no ^ is used).
The `http-client` package in turn uses `connectivity` with `^3.1.1`.

Since I pinned my version to 3.1.1 but the package itself doesn't pin the version of the `connectivity` package, during installation I ended up with:

@sap-cloud-sdk/http-client: 3.1.1
@sap-cloud-sdk/connectivity: 3.7.0

These two in combination are incompatible, since the http-client @3.1.1 doesn't have this line yet:
![image](https://github.com/SAP/cloud-sdk-js/assets/23531536/db5ff817-33e7-412d-b007-ab03a34d0c88)

I'm not sure however if this is something that needs to be fixed or not, so I'm leaving this open for now.

Best regards

**Comment by marikaner** [comment]
Hey @muellinho, thank you for your thorough investigation. It seems that we accidentally introduced a breaking change in version 3.6.0. We discussed this extensively and whether we should fix this to make it backwards compatible. We have quite a simple, but ugly fix in on SDK side in mind. However, this issue is quite easy to fix for users as well, by just updating the version to 3.6.0 or higher.
Therefore my proposal is the following: We will add a compatibility note on this issue, stating that users should update to the latest version, but we won't fix it for now. If this issue pops up again we will reconsider fixing it for backwards compatibility.

Is that an ok solution for you?

I apologize for the inconvenience!

**Comment by muellinho** [comment]
Hey @marikaner,

yes that's fine for me.
I already updated my project to use compatible versions of the two packages :)

Thanks

**Comment by marikaner** [comment]
Thank you!
