### ISSUE TITLE
Auth tokens for Destination of authentication type oAuth2UserTokenExchange is not fetched

### ISSUE THREAD

**Issue by ferrari997** [SAP/cloud-sdk-js#4213]
**Describe the bug**
While fetching the details of destination of authentication type `OAuth2UserTokenExchange`, authTokens array doesn't contain the  valid auth token needed for connecting to the system mentioned in the destination.
Instead, this is fetched in destination details 
```"authTokens": [
        {
            "type": "",
            "value": "",
            "error": "Retrieval of OAuthToken failed due to: Unable to fetch refresh token from the specified token service URL. Response was: Insufficient scope for this resource",
            "expires_in": "0"
        }
    ]
```

**To Reproduce**
Add a destination of authentication type oAuth2UserTokenExchange in the cockpit
try to fetch the above destination using getDestination method by passing auth token(of grant type authorization_code) as jwt in the destination fetch options

I'm using cloud-sdk-java version 4.12.0 and cloud-sdk-js 3.1.0 in my apps

Difference I've noticed while fetching destination of authentication type oAuth2UserTokenExchange is:

-First step, both SDKs fetch client credentials token(using credentials details of "destination" service). And then use this token to make /destinations/{​dest_name}​ GET API request. In both SDKs, this request fetches all the details of the destination except for the authTokens

-In the next step, both SDKs try to fetch the destination details again by exchanging user token but take different approaches.
cloud-sdk-js - again makes a call to /destinations/{​dest_name}​ GET API. This time, it sends client credential token(generated in the first step) as Authorization header and user token(passed from my app, through destinationFetchOptions parameter to getDestination method) as X-user-token header. But this call again fails to fetch the complete destination details(authTokens not fetched)
cloud-sdk-java - makes a call to {​destination services's authentication url}​/oauth/token, with parameters
![MicrosoftTeams-image (4)](https://github.com/SAP/cloud-sdk-js/assets/37513770/d910d0da-40d0-421d-884d-1f7805b15680)    
here, client id and secret are from credentials of destination service and  value for assertion parameter is the user token from my app. With the jwt token generated from this call, SDK again makes a call to /destinations/{​dest_name}​ GET API which fetches all the details of the destination

One more thing I've noticed is, 
If I pass the jwt token generated in the above call to /destinations/{​dest_name}​ GET API as X-user-token header and client credentials token as authorization header, i'll get complete destination details.

Question: for using cloud-sdk-js, do we have to genearate jwt token(like how it is generated in coud-sdk-java) and then pass it as jwt in the destinationFetchOptions
Or
Is it a bug at cloud-sdk-js

- Customers are not able to use destination of authentication type oAuth2UserTokenExchange because of this
- Affected development phase: Production
- Impact: Blocked
- Timeline: already live

**Comment by marikaner** [comment]
Hey @ferrari997, I checked what is happening here and what the Java SDK is doing and as of now, I have the impression that either I am lacking information or this is a bug in the destination service. According to the [documentation](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/exchanging-user-jwts-via-oauth2usertokenexchange-destinations) the token exchange should happen automatically in the destination service and this is what we are leveraging by sending the `x-user-token` header. This does clearly not happen in your case.
I can also see that the Java SDK has different [options](https://sap.github.io/cloud-sdk/docs/java/features/connectivity/destination-service#token-exchange-options) and I believe that your token automatically falls into the category `LOOKUP_THEN_EXCHANGE`, but I wonder why.
Do you use a token that was not issued by XSUAA? Do you have any other indicators that could help me reproduce this - do you have multiple XSUAA instances? Our E2E tests cover `OAuth2UserTokenExchange` and give me a valid auth token, so there must be some significant difference.

**Comment by ferrari997** [comment]
Hi @marikaner, 
To answer your questions: 
Yes, in java sdk our case follows LOOKUP_THEN_EXCHANGE strategy as it was the default strategy used in 4.12.0
We use the token issued by XSUAA and application uses single XSUAA instance

**Comment by ferrari997** [comment]
Hi @marikaner,
May I know if there was any update on this?

**Comment by mr-flannery** [comment]
Hi @ferrari997, could you please share the payload of the jwt that you're passing to the SDK when fetching the destination?

**Comment by ferrari997** [comment]
Hi @marikaner, @mr-flannery ,
some more details about the issue, If it helps:
we have provider-subscriber subaccount setup(Customers subscribing to SAP process automation service)
When a request comes from subscriber account, 
we call getDestination method of cloud-sdk-js with the destinationFetchOption,
{ 
destinationName: destination_name, 
selectionStrategy: DestinationSelectionStrategies.alwaysProvider, 
jwt: request.headers.authorization.split(" ")[1] 
}
Here jwt would contain the token sent in the authorization header of the request from subscriber subaccount. This token doesn't have uaa.user scope. If this token is passed as X-user-token header we won't get complete destination details.

getAuthTokenForOAuth2UserBasedTokenExchanges - In this method, 

`if (this.subscriberToken.serviceJwt &&
            (0, tenant_1.isIdenticalTenant)(this.subscriberToken.userJwt.decoded, this.providerServiceToken.decoded)) {
            logger.debug(`UserExchange flow started without user exchange token for destination ${destinationName} of the provider account.`);
            return {
                authHeaderJwt: await (0, token_accessor_1.jwtBearerToken)(this.subscriberToken.userJwt.encoded, getDestinationService())
            };
        }`
This part of the code generates an user token that has uaa.user scope. But this is not executed for our token.

**Comment by ferrari997** [comment]
@mr-flannery, here is the payload of the jwt that gets passed to SDK

{
  "jti": "4413b7941b624b53b090db98ca80bc46",
  "ext_attr": {
    "enhancer": "XSUAA",
    "subaccountid": "312266ae-1ca5-46cb-b68b-d5e2dfc5195e",
    "zdn": "spa-registry-dev-consumer-eu",
    "oidcIssuer": "https://accounts.sap.com"
  },
  "xs.user.attributes": {},
  "cnf": {
    "x5t#S256": "ZxXwW7IObiIzJYFY7BJf9aPClpyn_aTEnk9YhQ4qsro"
  },
  "xs.system.attributes": {
    "xs.rolecollections": [
      "Subaccount Service Administrator",
      "ProcessAutomationAdmin (1)",
      "ProcessParticipant",
      "ProcessAutomationDeveloper",
      "Subaccount Viewer",
      "Cloud Connector Administrator",
      "ProcessAutomationParticipant (1)",
      "ProcessAutomationParticipant",
      "Destination Administrator",
      "ProcessAutomationAdmin",
      "Subaccount Administrator",
      "Connectivity and Destination Administrator",
      "ProcessParticipant (1)",
      "ProcessAutomationDeveloper (1)"
    ]
  },
  "given_name": "Hemanth",
  "family_name": "Shetty M",
  "sub": "aa9b023f-7952-48d1-b29b-a7e9551c4e67",
  "scope": [
    "applicationdevelopment!b31014.Developer",
    "ap-lcnc-store-uaa!t31014.store-submit",
    "openid",
    "applicationdevelopment!b31014.Administrator",
    "ap-lcnc-store-uaa!t31014.store-retrieve"
  ],
  "client_id": "sb-applicationdevelopment!b31014",
  "cid": "sb-applicationdevelopment!b31014",
  "azp": "sb-applicationdevelopment!b31014",
  "grant_type": "authorization_code",
  "user_id": "aa9b023f-7952-48d1-b29b-a7e9551c4e67",
  "origin": "sap.default",
  "user_name": "hemanth.shetty.m@sap.com",
  "email": "hemanth.shetty.m@sap.com",
  "auth_time": 1698982542,
  "rev_sig": "87f2c3a3",
  "iat": 1698983122,
  "exp": 1699026322,
  "iss": "https://spa-registry-dev-consumer-eu.authentication.sap.hana.ondemand.com/oauth/token",
  "zid": "699037e7-2b46-497a-a6c4-76b6e5873449",
  "aud": [
    "applicationdevelopment!b31014",
    "sb-applicationdevelopment!b31014",
    "openid",
    "ap-lcnc-store-uaa!t31014"
  ]
}

**Comment by marikaner** [comment]
Hey @ferrari997,

this is very interesting and should help us get closer to the root cause.
In your case the following is not fulfilled:
```ts
if (
      this.subscriberToken.serviceJwt &&
      isIdenticalTenant(
        this.subscriberToken.userJwt.decoded,
        this.providerServiceToken.decoded
      )
    )
```

To better understand let's talk about those tokens:
1. `providerServiceToken`: This is a service token for the destination service, that was retrieved without using a JWT. It belongs to the provider tenant.
2. `subscriberToken.userJwt`: This is the token that you pass to your application. It belongs to the subscriber tenant. In your case (provider only) it should be the provider tenant.
3. `subscriberToken.serviceJwt`: This is a service token that was retrieved using the `subscriberToken.userJwt`. It belongs to the subscriber tenant, which in your case should be identical with the provider tenant.

In your case, I would expect this resolves to `true` (First scenario in this [documentation](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/exchanging-user-jwts-via-oauth2usertokenexchange-destinations)).
As it doesn't I assume either
a) the user token you are getting in your application does not belong to the provider tenant and then the behavior is different (also see documentation).
or b) the`subscriberToken.serviceJwt` could not be retrieved for some reason (but I doubt that).

Can you check those two things? For a) just compare the `zid`s in the `subscriberToken.userJwt` and the `providerServiceToken`.

Thank you for your collaboration!

**Comment by marikaner** [comment]
@ferrari997 Oooops, I just noticed that you mentioned that you're doing this from the **subscriber** account, so no wonder why it is not entering this if clause. No need to check. My bad.
We're looking into whether we can reproduce a case with empty `xs.user.attributes` to better understand the issue.

**Comment by ferrari997** [comment]
@marikaner My bad, I had mentioned selectionStrategy as DestinationSelectionStrategies.alwaysProvider. But it will be set as alwaysSubscriber.
zid in tokens **this.subscriberToken.userJwt.decoded** and  **this.providerServiceToken.decoded** are different

**Comment by ferrari997** [comment]
The token passed to SDK didn't have the uaa.user scope, token exchange wasn't happening because of this.
Things started working after scope was added to a role-template in the xsuaa service configuration
