### ISSUE TITLE
Support OData V4 Batch Request with "Resource path relative to the batch request URI."

### ISSUE THREAD

**Issue by cschuerings** [SAP/cloud-sdk-js#4293]
**Is your feature request related to a problem? Please describe.**
When using OData V4 Batch Requests with a custom RAP service, we encounter an issue where the request is rejected with the error message "Die Data-Services-Anforderung wurde wegen einer deformierten Syntax nicht verstanden." (The data services request was not understood due to a malformed syntax.)
Upon troubleshooting, we discovered that this issue is caused by the resource path in the batch payload.

Both `POST /Entity` and `POST <absolute_Path/Entity>` are rejected, while `POST Entity` works but is not supported by the SDK. Related documention [Configure Subrequest Serialization](https://sap.github.io/cloud-sdk/docs/js/features/odata/v4-client#configure-subrequest-serialization).

The [OData specification](https://docs.oasis-open.org/odata/odata/v4.01/csprd02/part1-protocol/odata-v4.01-csprd02-part1-protocol.html#sec_MultipartBatchRequestBody) provides an example (Example 97) that demonstrates how the entity should be addressed.

**Describe the solution you'd like**
To address this issue, we suggest enhancing the `batch-request-serializer.ts` [getUrl method](https://github.com/SAP/cloud-sdk-js/blob/66b8bef46a64eefa6dfbddf1e44fbcc1996aa681/packages/odata-common/src/request-builder/batch/batch-request-serializer.ts#L93) to support relative paths without leading slashes.

**Describe alternatives you've considered**
An alternative would be to manually build the Batch request body and use the `executeHttpRequest`.

**Impact / Priority**

Affected development phase: Development

Impact: Impaired

Timeline: N/A

**Additional context**

**Comment by tomfrenken** [comment]
Hey @cschuerings,

thanks again for your nice contribution, I'll add some additional documentation to our docs repository and will create a release by the end of the week so that you can use the fix ASAP :)
