### ISSUE TITLE
how do use the SAP BTP connectivity service to call an SMTP server within a CAP application?

### ISSUE THREAD

**Issue by eliugonzalez86** [SAP/cloud-sdk-js#4331]
Hi Everyone,
I have created a destination service and a connectivity service for my CAP application and bound them in BAS through the "env" file. but when I call the sendmail function from the SDK I get an error that says "read ECONNRESET" " So I kindly ask your help on how to test the destination and the connectivity service from a CAP application
best regards

**Comment by deekshas8** [comment]
Hi @eliugonzalez86 ,

What version of the sap-cloud-sdk are you currently using? I am assuming you have a MAIL On-prem destination, can you also share what the destination object looks like? 

We have a [troubleshooting guide](https://sap.github.io/cloud-sdk/docs/js/troubleshooting#connectivity-issue) that you can refer to for debugging the destination service/connectivity issues. Let us know if that helps.

**Comment by eliugonzalez86** [comment]
Hi @deekshas8 ,
thank you very much for your response, I followed the troubleshooting guide and as you can see in the image below the CAP application does find the destination even with the connectivity proxy values
![image](https://github.com/SAP/cloud-sdk-js/assets/96129216/b0d23866-61b1-49d0-ad7b-798a8073f5f9)

I have the following destination:
![image](https://github.com/SAP/cloud-sdk-js/assets/96129216/f55c5e30-c9fd-4eed-9715-c616206ff15b)

and this cloud connector is configured as follows:
![image](https://github.com/SAP/cloud-sdk-js/assets/96129216/6c192876-2a93-4b98-b913-0d4ecc05d6e4)

These are the cloud SDK versions I'm using and declare in my package.json:
        "@sap-cloud-sdk/connectivity": "^3.8.1",
        "@sap-cloud-sdk/http-client": "^3.8.1",
        "@sap-cloud-sdk/mail-client": "^3.6.0",

![image](https://github.com/SAP/cloud-sdk-js/assets/96129216/b2c88ec6-4663-48fa-b081-00eef915ee88)


The problem is when I try to send an email using mail-client along with the destination :( 
if you something else please let me know.
I hope to hear from you soon
best regards

**Comment by deekshas8** [comment]
Hi @eliugonzalez86 ,

Can you upgrade your `@sap-cloud-sdk/mail-client` version to [v3.8.0](https://github.com/SAP/cloud-sdk-js/releases/tag/v3.8.0). We recently added support for `Location ID` starting this version.

**Comment by eliugonzalez86** [comment]
Hi @deekshas8,
I updated the @sap-cloud-sdk/mail-client version and the error is still the same :( 
![image](https://github.com/SAP/cloud-sdk-js/assets/96129216/7474f82c-cd04-4c46-bbac-f3b5196dffa5)
any other tip would be appreciated
best regards

**Comment by mr-flannery** [comment]
Hi @eliugonzalez86 ,

We double-checked our code again, and it turns out you cannot use Mail destinations with authType `NoAuthentication`. In other words you need to change the authentication type to e.g. `BasicAuthentication` and provide credentials. This should have been checked before the request is sent and a corresponding error should have been logged. Not sure why this worked as intended here.

Best regards,
Dennis

**Comment by mr-flannery** [comment]
Hi again @eliugonzalez86,

@deekshas8 made me aware that you're running in BAS. As far as we're aware, the connectivity service is not reachable from BAS. Could you please try deploying your application and see if that makes a difference?

**Comment by eliugonzalez86** [comment]
Hi @mr-flannery and @deekshas8 ,
yes, after deploying the application in btp and adjusting the destination adding user and password it worked :), then the problem is in the BAS proxy to use the destinations created in BTP. specially the email type, because the http type works.
best regards

**Comment by mr-flannery** [comment]
Happy to hear it worked!

**Comment by aartsingh** [comment]
Hi, Can you share the properties used in destination with type MAIL?

**Comment by eliugonzalez86** [comment]
> Hi, Can you share the properties used in destination with type MAIL?

Hi @aartsingh  yes, here's how I created the destination type MAIL for my CAP proyect
