### ISSUE TITLE
Pass "additional Properties" to Destination-Service on destination-retrieval

### ISSUE THREAD

**Issue by JanPfenning** [SAP/cloud-sdk-js#4349]
We have a use-case in which we need to set an individual header for each of our microservice when communicating with eachother.
We are using CAP - which internally uses the cloud-sdk to retrieve destinations via a mapping defined in the package.json.
It is cumbersum to add this header to every single request manually so we would like to set it once (e.g. in the destination mapping part in the package.json so it takes effect on getting the destination).
Setting these Static headers does work but appearently only in the UI and only for all users of a destination, meaning that a user of the destination cannot customize how they want to use it any further.
(Of course as soon as this is implemented in the cloud-sdk CAP has to implement this reading from the package.json and forwarding it to the call of the cloud-sdk too)

It may also come in handy to not only set these values hard-coded in the package.json but setting it at runtime if the value is dynamic (e.g. some ids?). So on retrieval of the destination from the destination-service one could add the properties at runtime to make it even mroe flexible.

For now we have a single wrapper function for all our inter-service-calls which adds this header in a hacky way...
We also considered creating a new destination for every combination of header-values we need but this gets cumbersome very quick

Our solution does work - however it is still a workaround and adds plenty of technical dept to our project

**Comment by marikaner** [comment]
Hey @JanPfenning, I think I have a broad understanding of your request, but could you please make an example of how you would expect this to look like. That would help me understand your requirements better.

**Comment by jjtang1985** [comment]
Hi @JanPfenning , we did not hear you for a while, so I'll close the ticket.

Please share more details as requested [here](https://github.com/SAP/cloud-sdk-js/issues/4349#issuecomment-1854356920) and reopen the ticket.
Thank you very much for your understanding.
