### ISSUE TITLE
Unable to extract request URI: Illegal character in query at index 93

### ISSUE THREAD

**Issue by cbsmerveguel** [SAP/cloud-sdk-js#4374]
Dear experts,

We have upgraded below package versions due to the security note 3411067. However, after the upgrade, we realized that our function import batch calls are not reaching to the SAP backend system and we are ending up getting below dump at our CAP service. We found out "@sap-cloud-sdk/http-client" upgrade to 3.9.0 is the cause of the issue (previously it was "^2.x.x".

**body: 'Unable to extract request URI: Illegal character in query at index 93: xxxx://xxx:xxxxx/sap/opu/odata/sap/xxx_xxxxxx_xxxxxxxxxx_xxx/getRepairModules?ProductData=%27{%22Products%22:[{%22MATNR%22:%22TESTP%22,%22WERKS%22:%221951%22,%22PLNNR%22:%22500%22,%22PLNAL%22:%2201%22}]}%27'**

**"@sap-cloud-sdk/http-client" : "^3.9.0",
"@sap/approuter": "^14.4.3",
"@sap/xssec": "^3.6.0",**

We appreciate for any help, since issue also currently occurs at our Productive environment.

Best,
Merve

**Comment by marikaner** [comment]
Hey @cbsmerveguel, can you share what the string was in the old version? I think there might be a problem with the encoding, because index 93 will probably be the first `%27`.

**Comment by mr-flannery** [comment]
could you please also share a code snippet of the code that procudes this error as well as a stacktrace?

**Comment by jjtang1985** [comment]
I will close this ticket, due to the missing information.
@cbsmerveguel, feel free to reopen and answer the questions.
