### ISSUE TITLE
Cannot find the user-provided destination service when calling executeHttpRequest

### ISSUE THREAD

**Issue by ZacharyChang** [SAP/cloud-sdk-js#4411]
**Is your feature request related to a problem? Please describe.**
We have a CAP Nodejs application using @sap-cloud-sdk/connectivity deployed to BTP CF environment. The application has bound serveral **user-provided** services, including destination. When we try to call the destination with executeHttpRequest(@sap-cloud-sdk/http-client), the application runtime cannot find the related service. After some debug in the code, I found out that the code looked like this(v3.9.0):
```javascript
// @sap-cloud-sdk/connectivity/dist/scp-cf/environment-accessor/service-bindings.js
function getServiceBinding(service) {
    const services = xsenv.filterServices({ label: service });
    ...
}
```
From my understanding, the sdk is looking for the service which has the label 'destination'. But in our case, the label of the user-provided service is always 'user-provided'.

**Describe the solution you'd like**
I expect to make the user-provided service supported. I think it would be okay if it can resolve the service which has the `tag`. For example, I tested with this implemention and it was working.
```javascript
function replaceGetServiceBinding(service) {
  let services = [];
  services = xsenv.filterServices({ tag: service });
  if (!services.length) {
      services = xsenv.filterServices({ label: service });
  }
  ...
}
```

**Describe alternatives you've considered**
None

**Impact / Priority**

Affected development phase: Development

Impact: Impaired

Timeline: Go-Live is in 4 weeks.

**Additional context**
* I got the information from other developer that the Java Cloud SDK already handles user-provided service with `tag`.
* related code yet known from my test:
  ** @sap-cloud-sdk/connectivity/dist/scp-cf/environment-accessor/service-bindings getServiceBindings
  ** @sap-cloud-sdk/connectivity/dist/scp-cf/environment-accessor/service-bindings getServiceBinding

**Comment by deekshas8** [comment]
Hi @ZacharyChang ,

Thankyou for raising this. I'll create a backlog item for this and update you once the feature is available.

**Comment by mr-flannery** [comment]
Hi @ZacharyChang ,

I took a look at your request and was having some questions. 

In your suggested implementation, you're first checking by tag (i.e. the new behavior) and then by label (the old behavior):

```
function replaceGetServiceBinding(service) {
  let services = [];
  services = xsenv.filterServices({ tag: service });
  if (!services.length) {
      services = xsenv.filterServices({ label: service });
  }
  ...
}
```

This could break existing users, since they might have a service with label `xyz` and a different service with tag `xyz`. In this scenario, the function would return a different service instance than before. 

Would it also work for you if we first checked for label and then for tag?

**Comment by ZacharyChang** [comment]
Hi @mr-flannery , I think it is okay if firstly checking with label. Maybe the label `xyz` should have higher priority than tag `xyz`. For our case it should work as well because we only have user-provided service.

**Comment by mr-flannery** [comment]
Hi @ZacharyChang , we had some discussions about this internally and had some questions about your use case. Could you please provide some more detail of what it is your trying to achieve, what your code looks like, and why it requires a user-provided destination (instead of binding a service instance directly)?

**Comment by ZacharyChang** [comment]
Hi @mr-flannery , this is the background of our case:
1. Firstly we developed the CAP nodejs application in subaccount A, including the features which needs calling the destination service. With cloud-sdk-js lib, it was working good.
2. Then due to some technical reason, we need to deploy the same application to another subaccount B. But for the services we don't want to re-create the related services. Instead, we want to reuse the services in subaccount A, as we don't want to maintain the configurations like destination in both sides.
3. Then we found a way: we created the service keys in the service instance of subaccount A, then for the application in subaccount B, we created the user-provided services and bound them to the application.
4. The application in subaccount B was working, except the feature calling the destination service. The reason from my investigation was due to the service lookup in the cloud-sdk-js.

Anyway, we made this feature work with the code sharing in the description. But I would expect this can be achieved by the sdk itself. Also it would be fine if the API can provide the option to find the services with `tag`. Hope this answers your question.

Regards,
Zachary

**Comment by mr-flannery** [comment]
Hi @ZacharyChang ,

thanks for the input, that clears it up. Just to make sure, could you please provide the code snippet with the SDK function call that triggers this error?

Also, does "Anyway, we made this feature work with the code sharing in the description." mean you found a workaround or that the code provided above _would_ solve it, _if_ it was in the SDK?

**Comment by ZacharyChang** [comment]
Hi @mr-flannery , this is the code when this error was triggered:
```javascript
const path = `/odata/v2/API_MMT_MASTER/CustomerCommunicationApis?$filter=apiID eq 'CPIOperations'`;
    let communication_apis_res;
    let destinationName
    try {
        communication_apis_res = await executeHttpRequest({
            destinationName: Destination.API_MMT_MASTER,
            selectionStrategy: alwaysProvider,
            jwt: token,
        }, {
            url: path,
            method: 'get',
        });
        logger.debug('communication_apis_res:', communication_apis_res)
    } catch (error) {
        logger.error('getDestinationName fail', error.message)
        logger.debug('GET_CONFIGURATION_FAILED  path:/odata/v2/API_MMT_MASTER/CustomerCommunicationApis:', error)
    }
```
The screenshot of this error:
![image](https://github.com/SAP/cloud-sdk-js/assets/8346727/9630f629-6ef4-49b4-8045-a5977dfe2f04)

As for the workaround, I wrote another file to overwrite the original way before cds server started. For your reference, I put the file(js) into attachment.
[patchGetServiceBinding.txt](https://github.com/SAP/cloud-sdk-js/files/14720673/patchGetServiceBinding.txt)

**Comment by mr-flannery** [comment]
Hi @ZacharyChang ,

thanks for the information. After talking to the CAP team and looking at your use case more closely, we have decided not to implement this. While I can understand why you have chosen this workaround, it's not a feature that the underlying platform promotes or supports, and therefore not something that we want to support in the SDK.

I understand that this is inconvenient for you. While you've found a workaround already, please be aware that is probably not the most stable workaround. If I were you, I'd reconsider if the technical reasons for hosting the same application twice cannot be resolved somehow. Other than that, you could consider writing a separate application that replicates destinations from subaccount A to subaccount B, or providing the credentials to your application at startup and manually patching them into `process.env.VCAP_APPLICATIONS`.

Best regards,
Dennis
