### ISSUE TITLE
Unable to retrieve destination properties in mail-client

### ISSUE THREAD

**Issue by PPG-BrianChan** [SAP/cloud-sdk-js#4425]
Dear experts,

We are attempting to send mails using the mail-client package. However,Mail destination information required such as host and port cannot be retrieved during execution.
This is because in the source code https://github.com/SAP/cloud-sdk-js/blob/main/packages/mail-client/src/mail-client.ts#L54-L69, it is retrieving the values from "originalProperties", but in reality there is an additional property "destinationConfiguration" encapsulating the values.

**To Reproduce**
1. Set up ...
Configure a mail destination in subaccount with mail.host, mail.port and other required information in additional properties. A sample we used is https://help.sap.com/docs/build-process-automation/sap-build-process-automation/configuring-smtp-mail-destination?version=Cloud

Prepare a CAP project and include the mail-client package.
Pass the destination name into the function "sendMail" along with simple mail config.

2. Execute
Execute CAP project in hybrid testing or deployed mode.

3. Confirm
Error message will be caught.

Error will be logged as attached in screenshots.

**Screenshots**
Error log:
<img width="701" alt="image" src="https://github.com/SAP/cloud-sdk-js/assets/101160883/71760511-3d99-41bf-8194-ea4e5930f444">
Destination Configurations:
<img width="576" alt="Destination configurations" src="https://github.com/SAP/cloud-sdk-js/assets/101160883/23c8b7f2-cdd7-466b-b646-e191fb50c1eb">

**Used Versions:**
- node version via `node -v` : v18.14.2
- npm version via `npm -v` : 9.5.0
- SAP Cloud SDK version you used as dependency:
- "@sap-cloud-sdk/connectivity": "^3.10.0",
   "@sap-cloud-sdk/mail-client": "^3.10.0",
   "@sap/cds": "^7",
   "@sap/xssec": "^3",

**Impact / Priority**
We intend of making use the same package in all applications that will be sending mails but currently have to resort to a custom solution.

Affected development phase: Development

Impact: Impaired

**Additional context**
A similar issue is raised in the comment of the blog https://blogs.sap.com/2023/02/14/connecting-on-premise-mail-destination-using-sap-cloud-sdk-javascript-version-3-on-sap-cap/
FYI the same destination can be used by SBPA.

**Comment by deekshas8** [comment]
Hi @PPG-BrianChan ,

Thanks for raising this. I was able to reproduce this. I'll create a ticket for this in our backlog and update you once we have a fix.

**Comment by FlorianFechterTCon** [comment]
Hey @deekshas8,

we ran into the same issue. 
So we would like to know if there is a "roadmap" when this'll be solved?

Greetings

**Comment by softproviding-Devendrp** [comment]
Hey @deekshas8 ,

I am attempting to send mails using the destination mail service. But I am facing the same error as mentioned by others in the thread. 

Kindly suggest me if there is a workaround to fix this issue.

Thanks and Regards,
Paran

**Comment by jjtang1985** [comment]
This is not planned.
