### ISSUE TITLE
@sap/cloud-sdk-vdm-purchase-order-service with deprecated PO oData API ?

### ISSUE THREAD

**Issue by jl-de** [SAP/cloud-sdk-js#4442]
Dear Experts,

We are currently using @sap/cloud-sdk-vdm-purchase-order-service (https://help.sap.com/doc/96ad709a1b7e41f3804fa5040bc83167/1.0/en-US/modules/_sap_cloud_sdk_vdm_purchase_order_service.html) in our custom app, which contains the OData VDM for the Purchase Order Service of SAP S/4HANA Cloud. However, this Purchase Order Service (https://api.sap.com/api/API_PURCHASEORDER_PROCESS_SRV/overview) is getting deprecated now. According to the SAP's statement, the new purchase order api V4 (https://api.sap.com/api/CE_PURCHASEORDER_0001/overview) should be used.

Does this impact our usage of @sap/cloud-sdk-vdm-purchase-order-service ? Would the @sap/cloud-sdk-vdm-purchase-order-service automatically handle the new api in the background, or do we need to use another new library from cloud sdk now ?

We would like to know whether we would need to switch to a new library or the current library @sap/cloud-sdk-vdm-purchase-order-service will handle the new v4 api automatically ?

Many thanks.

Best Regards,

**Comment by mr-flannery** [comment]
Hi Jie Lin,

we have stopped shipping pre-generated client packages (@sap/cloud-sdk-vdm-somthing) with version 3 of the Cloud SDK for JS. For future version of the OData API, you will need to generate your own client as described here: https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client

Best regards,
Dennis
