### ISSUE TITLE
Why does the OpenAPI generator add a Record<string, any> to types?

### ISSUE THREAD

**Issue by sven-petersen** [SAP/cloud-sdk-js#4477]
Assuming the following OpenAPI spec

```yaml
openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
paths:
  /pet:
    put:
      operationId: updatePet
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pet"
```

the open API generator will generate this type definiton for the `Pet` schema:

```ts
export type Pet =
  | {
      id?: number;
      name: string;
    }
  | Record<string, any>;
```

I would like to understand the rational behind adding `Record<string, any>`. For example this will have the side effect that even the properties `id` and `name` are of type `any` because the `any`-type in `Record<string, any>` is wider then the type `number`/`string`. This also creates further issues if the project uses strict typescript rules regarding the usage of `any`. E.g. doing an assignment like `const foo = response.name` it will raise the `Unsafe assignment of an any value` error.

```ts
const response = await openApiClient.DefaultApi.updatePet({
  id: 123,
  name: "super dog",
}).execute({ url: "foo.com " });

const idontexist = response.idontexist // ✅  gives the correct error that this prop does not exist
const name = response.name; // ❌ is of type "any" but should be "string"
const id = response.id; // ❌ is of type "any" but should be "number | undefined"
```

Is this behavior intended? If so would it make sense to make it configurable to not add the generic `Record<...>`-type?

**Comment by marikaner** [comment]
Hey @sven-petersen, I will take a closer look at this. It is definitely not intended that the types of your properties have type `any`. From a quick glance, I can't tell you the ratio behind this decision, I have a suspicion though and will investigate it.

**Comment by marikaner** [comment]
Ok, so the reason this is there at all is that we want to allow to have additional properties, if not stated otherwise in the spec ( aka .`additionalProperties: false`). However, I assume we merely confused `|` and `&`. With the latter you should get correct types. I implemented and tested this here: https://github.com/SAP/cloud-sdk-js/pull/4479.

Once this is merged, we will release a new version soon.
