### ISSUE TITLE
OpenAPI generator - parameters in header are not added to the client

### ISSUE THREAD

**Issue by sven-petersen** [SAP/cloud-sdk-js#4484]
**Describe the bug**

Parameters in headers (`in: header`) cannot be passed to the generated OpenAPI client.

**To Reproduce**

Generate an OpenAPI client for the following schema:

```yaml
openapi: 3.0.3
info:
  title: Swagger Petstore - OpenAPI 3.0
  version: 1.0.11
paths:
  /pet:
    post:
      operationId: updatePet
      parameters:
        - $ref: "#/components/parameters/SomeParameterInHeader"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Pet"
        required: true
      responses:
        "200":
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Pet"
components:
  schemas:
    Pet:
      required:
        - name
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
  requestBodies:
    Pet:
      description: Pet object that needs to be added to the store
      content:
        application/json:
          schema:
            $ref: "#/components/schemas/Pet"
  parameters:
    SomeParameterInHeader:
      name: header-param
      in: header
      required: true
      schema:
        type: string
      examples:
        example1:
          value: 11111111-2222-3333-4444-555555555555

```

Check if the header parameter `header-param` can be set in the generated client.

**Expected behavior**

The parameter in the header ( `header-param`) can be passed as parameter to the generated client somewhere like so:

```ts
import * as myApi from "./gen/ckms-common-api/index.js";
myApi.DefaultApi.updatePet({
  name: "my dog",
  "header-param": "11111111-2222-3333-4444-555555555555"
});
```

**Used Versions:**

- node version: v20.11.0
- npm version: 10.2.4
- SAP Cloud SDK version: @sap-cloud-sdk/openapi-generator@3.12.0

**Impact / Priority**

Affected development phase: Development

**Additional context**

Current workaround is to manually set the headers using
```ts
import * as myApi from "./gen/ckms-common-api/index.js";
myApi.DefaultApi.updatePet({
  name: "my dog",
})
  .addCustomHeaders({
    headerParam: "11111111-2222-3333-4444-555555555555",
  })
```

**Comment by jjtang1985** [comment]
Hi @sven-petersen ,

Thanks for raising up.
Using custom headers is the recommended way for passing header parameters for the time being.

I'll leave this ticket open and re-evaluate it later (e.g., the workaround does not work).

Best regards,
Junjie

**Comment by sven-petersen** [comment]
This was implemented with https://sap.github.io/cloud-sdk/docs/js/release-notes#improvements-1 / aa0b849
