### ISSUE TITLE
Incorrect Warning Log for Instance Destinations

### ISSUE THREAD

**Issue by chuckberrry** [SAP/cloud-sdk-js#4501]
**Describe the bug**
When starting a Cloud SDK application, the system always checks whether there is a destination with the same name at the destination instance and sub-account level.
However, the warning log also appears if there is only one destination at instance level and not at sub-account level.

The log is displayed as follows:
WARN     (destination-selection-strategies): Found destinations named '`<destination-name>`' for both, the destination service instance and subaccount. Using instance destination.

**To Reproduce**
Create a destination at the destination instance level without defining it at the sub-account level.

I debugged the Cloud SDK coding and the misbehavior seems to be in the following function (destination-service.js)

```js
async function fetchDestinationWithoutTokenRetrieval(destinationName, destinationServiceUri, serviceToken) {
    const targetUri = `${(0, util_1.removeTrailingSlashes)(destinationServiceUri)}/destination-configuration/v1/destinations/${destinationName}?$skipTokenRetrieval=true`;
    try {
        const response = await callDestinationEndpoint({ uri: targetUri, tenantId: getTenantFromTokens(serviceToken) }, { Authorization: `Bearer ${serviceToken}` });
        const destination = (0, destination_1.parseDestination)(response.data.destinationConfiguration);
        return {
            instance: response.data.owner?.InstanceId ? [destination] : [],
            subaccount: response.data.owner?.SubaccountId ? [destination] : []
        };
    }
    catch (err) {
        if (err.response?.status === 404 &&
            err.response?.data?.ErrorMessage ===
                'Configuration with the specified name was not found') {
            return {
                instance: [],
                subaccount: []
            };
        }
        throw new util_1.ErrorWithCause(`Failed to fetch destination.${errorMessageFromResponse(err)}`, err);
    }
}
````

The return statement checks whether the destination is an instance or subaccount destination.
However, the response of the CF endpoint ``/destination-configuration/v1/destinations/`` always returns a subaccountId, even for instance destinations.
Therefore, both the instance and subaccount properties are returned with the same destination object for destinations that are only available at instance level, causing the warning log.

**Expected behavior**
No warning log should be printed.

**Used Versions:**

node version via node -v
v18.18.0
npm version via npm -v
9.8.1
SAP Cloud SDK version you used as dependency
3.12.0

**Comment by marikaner** [comment]
Hey @chuckberrry  this was fixed in version 13.12.1.
