### ISSUE TITLE
TypeScript invalid with TS compilerOptions "noImplicitOverride": true

### ISSUE THREAD

**Issue by GoWale** [SAP/cloud-sdk-js#4576]
**Describe the bug**
Generated TypeScript files are not valid when setting ```"noImplicitOverride": true``` in tsconfig.json

**To Reproduce**
git clone https://github.com/GoWale/issue-cloud_sdk-odatav4.git
npm i

1. Set up ...  start the cap server via npm run start
2. Execute ... npm run sdk_gen_client (with the running server providing the EDMX)
3. See error now you should see the typescript complains in the console

**Expected behavior**
generated typescript should support "noImplicitOverride"

**Used Versions:**

- node version v20.10.0
- npm version 10.2.5
- SAP Cloud SDK version you used as dependency
 "@sap-cloud-sdk/generator": "^3.12.1",

**Impact / Priority**

low / medium: we can add the override by hand or remove the typescript validation

Affected development phase: Development / CI/CD

**Comment by deekshas8** [comment]
Hi @GoWale,
This config setting is currently not supported. I'll create a ticket to update our client generators.

**Comment by jjtang1985** [comment]
Hi @deekshas8, it seems we solved this issue with this PR #4687.
Could you please confirm?

**Comment by deekshas8** [comment]
Closing as this was already fixed in v3.16.0.
