### ISSUE TITLE
SAP CAP with Event Mesh - Error: JWT with audience is not issued for clientIds

### ISSUE THREAD

**Issue by Beniseeger** [SAP/cloud-sdk-js#4623]
**Describe the bug**
As described in this SAP Community ticket here: 
https://community.sap.com/t5/technology-q-a/sap-cap-with-event-mesh-error-jwt-with-audience-is-not-issued-for-clientids/qaq-p/13661962/comment-id/4824628/emcs_t/S2h8ZW1haWx8dG9waWNfc3Vic2NyaXB0aW9ufExVUU45RlY2TVVTQjVOfDEzNjYyMDEyfFNVQlNDUklQVElPTlN8aEs#M4824628  
we are facing issues when integrating the event mesh with SAP CAP. 

The issue seems to be in the xssec library and its validators. I therefore opened a ticket for SAP directly, but they told me to raise my issue for the cloud sdk. 

**To Reproduce**

1. Set up a basic CAP application
2. Connect the Application to the Event Mesh using the documentation here: https://cap.cloud.sap/docs/guides/messaging/event-mesh
3. Deploy the application to cloud foundry 
4. An error appears that says:

Error: Jwt token with audience: [ "here the event mesh client id is shown", uaa ] is not issued for these clientIds: [ here our srv application is shown ]

ERR at returnError (/home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:308:25)

ERR at /home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:392:36

**Expected behavior**
The event mesh should be bound to the service and the service should listen to events. 

**Used Versions:**

- node version: v18.16.0
- npm version: v9.5.1
- xssec version: 3.6.1
- SAP Cloud SDK version you used as dependency
    "@sap-cloud-sdk/http-client": "^3.3.0",
    "@sap-cloud-sdk/resilience": "^3.3.0",

**Code Examples**
See the ticket I provided above. 

**Impact / Priority**

Event mesh cannot be integrated into the application. After deployment, the application does not start anymore

Affected development phase: Development

Impact: Blocked

**Comment by Beniseeger** [comment]
Hello @deekshas8 , 
the error does not appear when my application runs, it appears when I try to deploy the application. In my mta.yml I defined that the event mesh should be bound to my Server and during this setup in the deployment the error occurs like mentioned in the ticket. So its not really a code snippet I created but during the deployment. 
During the deployment the following logs are the relevant one for the error (Before that the app is just started):
`2024-04-10T09: 09: 46.46+0200 [APP/PROC/WEB/0
] OUT {
    "level": "info",
    "logger": "enterprise-messaging-http",
    "timestamp": "2024-04-10T07:09:46.459Z",
    "layer": "cds",
    "component_type": "application",
    "container_id": "",
    "component_id": "432d617c-dac0-4c09-9ae6-0d59e916cc78",
    "component_name": "my-app",
    "component_instance": 0,
    "source_instance": 0,
    "organization_name": "myorg",
    "organization_id": "",
    "space_name": "Space",
    "space_id": "",
    "msg": "Delete webhook {\n  webhook: 'eu10/cool/namespace/subaccounts',\n  queue: 'eu10/cool/namespace/subaccounts'\n}",
    "type": "log"
}
2024-04-10T09: 09: 47.53+0200 [APP/PROC/WEB/0
] OUT {
    "level": "info",
    "logger": "enterprise-messaging-http",
    "timestamp": "2024-04-10T07:09:47.528Z",
    "layer": "cds",
    "component_type": "application",
    "container_id": "",
    "component_id": "432d617c-dac0-4c09-9ae6-0d59e916cc78",
    "component_name": "my-app",
    "component_instance": 0,
    "source_instance": 0,
    "organization_name": "myorg",
    "organization_id": "",
    "space_name": "Space",
    "space_id": "",
    "msg": "Create webhook {\n  webhook: 'eu10/cool/namespace/subaccounts',\n  queue: 'eu10/cool/namespace/subaccounts'\n}",
    "type": "log"
}

2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR Error: Jwt token with audience: [
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR 'sb-default-superLoongID-clone!b161949|xbem-service-broker-!b1234',
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR 'uaa'
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR ] is not issued for these clientIds: [
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR 'mySRVClientId'
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR ].
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR at returnError (/home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:308:25)
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR at /home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:392:36
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR at TokenInfo.<anonymous> (/home/vcap/deps/0/node_modules/@sap/xssec/lib/tokeninfo.js:152:24)
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR at /home/vcap/deps/0/node_modules/jsonwebtoken/verify.js:261:12
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR at verificationKeySupplier (/home/vcap/deps/0/node_modules/@sap/xssec/lib/validator.js:346:28)
    2024-04-10T09:09:47.94+0200 [APP/PROC/WEB/0] ERR at process.processTicksAndRejections (node:internal/process/task_queues:95:5)`

**Comment by deekshas8** [comment]
Hi @Beniseeger ,

This is probably then a setup issue with CAP, and likely not related to the SDK. I would suggest to raise an issue here in the [CAP repository](https://github.tools.sap/cap/issues/issues).

**Comment by Beniseeger** [comment]
Hi @deekshas8 , 
I also believe that this might be more an issue of the communication between CAP and the @sap/xssec package, but I cannot find a repo to for these. I also cannot access your link. Therefore I opened a ticket for SAP support and they redirected me here 😅
Are there open repos where such issues can be raised?

**Comment by deekshas8** [comment]
Sorry wrong link. You can check out their [resources pages](https://cap.cloud.sap/docs/resources/#resources-and-support) for information on how to get support.
