### ISSUE TITLE
Unexpected backslash has been added to request URI when using `csrf=true` in SAP CAP Project

### ISSUE THREAD

**Issue by saphongjunqian** [SAP/cloud-sdk-js#4624]
**Describe the bug**
It is a follow-up issue from https://github.tools.sap/cap/issues/issues/1535.

When setting `csrf = true` and access an OData service on SAP Gateway server, it will send out a `HEAD` request with the URL added a backslash, it leads to an error in SAP S/4 server side.

Please refer to the URL for detail.

**Expected behavior**
The HEAD request shall keep the origin URL with adding backslash.

**Screenshots**
![image](https://github.com/SAP/cloud-sdk-js/assets/162257924/8a86f782-e412-4469-ba3d-e001850d7c35)

**Used Versions:**

|:---------------------- | ----------- |
| Node.js | v18.18.2 |
| @sap/cds | 7.6.1 |
| @sap/cds-compiler | 4.4.2 |
| @sap/cds-dk | -- missing |
| @sap/cds-dk (global) | 7.5.1 |
| @sap/eslint-plugin-cds | 2.6.4 |
| @sap/cds-mtxs | 1.14.2 |

**Comment by deekshas8** [comment]
Hi @saphongjunqian ,

Based on the information and related ticket you have shared, I cannot determine how this relates to the SAP Cloud SDK. 
Are you using any SAP Cloud SDK dependencies? If yes, then please share some code snippet/logs of what you are trying to do.

**Comment by saphongjunqian** [comment]
Hi @deekshas8 ,

Thank you for your reply.
If you click on the original issue, it is recommend by SAPCAP team to raise this issue to SAP Cloud SDK team. I have no clue how SAP CAP relies on SAP Cloud SDK team.

Thank you.
Best regards, Hongjun

**Comment by deekshas8** [comment]
Hi @saphongjunqian,

I clicked the original issue and it seems to be unrelated to this one.
Regarding the behavior when fetching csrf tokens for non-GET requests, the SDK makes two requests, one with `/` and one without. The reason for this is explained [here](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/csrf#default-behaviour)

**Comment by saphongjunqian** [comment]
Hi @deekshas8 ,

Thank you very much, the link helps a lot.
I closed this incident for now.

Thanks again.
Best regards, Hongju
