### ISSUE TITLE
setBasePath in open api client

### ISSUE THREAD

**Issue by lovis-ff** [SAP/cloud-sdk-js#4646]
Hi,

I did use the odata client generated via `generate-odata-client` but tried now to switch to the open api client generated via `openapi-generator` because I had problems with the type conversions. 
On the odata client requestBuilder there was a `setBasePath` function. This is not available on the open api client. The documentation does also not state anything about it for the open api client.
How do I properly set the basePath on the open api client?

**Comment by mr-flannery** [comment]
Hi @lovis-ff ,

we currently do not have such a function for the code generated with the OpenAPI generator. Could you provide more details on what problem you're facing?

Best regards,
Dennis

**Comment by lovis-ff** [comment]
Hi and thanks for the quick response.
I do have to call a custom base path for the api endpoints that is deviating from the standard one. For the odata client this was clear, for the OpenApi client it is not clear to me how to do this.

**Comment by mr-flannery** [comment]
Ok so I understand this as: usually, you would call the under `host.com/path/from/the/spec`, but you need to call it under `host.com/CUSTOM/path/from/the/spec`?

If my understanding is correct, can you try using a custom destination for this specific API call and add the path there? 

This is obviously a workaround, not a proper solution, but I'd like to understand if this would solve the problem for now.

**Comment by lovis-ff** [comment]
Thanks @mr-flannery that works indeed.

**Comment by mr-flannery** [comment]
Glad to hear that! I added backlog item for `setBasePath` in OpenAPI-generated code. I will close this ticket.

**Comment by KavithaSiva** [comment]
Hi @lovis-ff,

From version `3.25.0`, you can now regenerate your clients by giving a `basePath` in `options-per-service.json` to prepend the custom base path to the API path parameter for every request.

Or use the `setBasePath` before executing a request, which allows prepending the base path to the API path parameter for that single request.
