### ISSUE TITLE
Error while generating the OData client for IntegrationContent OData API

### ISSUE THREAD

**Issue by sagarbansal106** [SAP/cloud-sdk-js#4662]
**Describe the bug**
While generating the OData client using the SDK generator for the IntegrationContent API, I am getting error of 'Duplicate Identifier'.

**To Reproduce**

1. Download the EDMX file from https://api.sap.com/api/IntegrationContent/overview and place it in the resources folder.
2. Install SAP Cloud SDK Generator.
3. Run the command npx generate-odata-client --input resources/service-specs --outputDir src/generated --skipValidation --overwrite
4. Generation of Odata client fails
5. See error

**Expected behavior**
The client generation should be completed successfully without any errors.

**Screenshots**
![image](https://github.com/SAP/cloud-sdk-js/assets/30744226/1db5ce51-6df3-4a88-b6c3-e796ba4a9cc5)

**Used Versions:**

- node version via `node -v` : v18.14.2
- npm version via `npm -v` : 9.5.0
- SAP Cloud SDK version you used as dependency : ^3.14.0

**Code Examples**
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information.

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**

Affected development phase: Development

Impact: Blocked

Timeline: Go-Live is in 4 weeks.

**Additional context**

**Comment by Johannes-Schneider** [comment]
Hi @sagarbansal106,

it looks like the service specification has a duplicated entry in it's `EntityContainer`:

```xml 
<EntitySet Name="IntegrationRuntimeArtifacts" EntityType="com.sap.hci.api.IntegrationRuntimeArtifact"/>
```

The line above appears twice, once in line 386 and once again in line 404.
If I remove the second occurrence, everything seems to work as expected.

So as a workaround, you could manually edit the specification.
Additionally, I suggest that you reach out to the service maintainers and ask them to fix their specification file.

Hope that helps!

Best regards,
Johannes

**Comment by deekshas8** [comment]
Closing this as workaround provided. Please open another issue if you are still facing any issue related to the SDK.
