### ISSUE TITLE
Breaking changes from @sap/xssec v4 impacting connectivity service

### ISSUE THREAD

**Issue by fleischr** [SAP/cloud-sdk-js#4704]
**Describe the bug**
Breaking changes in @sap/xssec v4 are not yet compatible with the latest release of connectivity service

**To Reproduce**
Use latest version of connectivity service (3.15.0) and install/update @sap/xssec to latest release (4.0.0)
Connectivity service uses xssec version 3.6.1 as dependency 
Conflicts in versions and breaking changes in xssec 4.0.0 causes the app backend not to start

**Expected behavior**
Should be able to support latest 4.0 build of xssec in future update of cloud sdk (presumably version 4.0?)
Need some clarity if it will be possible at that time to keep using xssec v 3.6.1 or if similar breaking changes are to be required in SDK as well.

**Used Versions:**
Latest release: SAP cloud sdk connectivity service

**Code Examples**
run ```npm list @sap/xssec``` in a given project
**Impact / Priority**

Current workaround is to postpone xssec version 4.0.0 update

**Comment by fleischr** [comment]
see https://www.npmjs.com/package/@sap/xssec

**Comment by jjtang1985** [comment]
Hi @fleischr ,

Thanks for reaching out.
Could you please share the error messages, when starting the app, so we can try to reproduce?

Also, could you please also share the xssec function that you need, so we know your use cases better?

Thank you.

**Comment by marikaner** [comment]
Hey @fleischr could you point out the exact issues that you are encountering? We would like to upgrade to v4, however with your comment's I am worried that this might be a breaking change, but I don't see a reason for it to be breaking. Is it possible that this is an issue in your setup?

**Comment by finkmanAtSap** [comment]
Hi @fleischr, we (authors of @sap/xssec) would also be interested in an error stack that shows what is causing the app to crash, so we can work on a solution.
Please provide as much information from [this list](https://github.wdf.sap.corp/CPSecurity/node-xs2sec#how-to-get-support) as you can.
Thanks,
Manuel

**Comment by marikaner** [comment]
Hey @fleischr, we are in the process of upgrading to xssec version 4 and due to inactivity on this ticket, I will go ahead and close it.
