### ISSUE TITLE
Add query to request

### ISSUE THREAD

**Issue by QuentinSieweAGI** [SAP/cloud-sdk-js#4723]
Hello,

i am currently working on a scenario where we use S/4 Hana Cloud Data on a multitenancy SaaS project. I want to know if there is a solution out of the box to forward the incoming query (previously `service.run(req.query)` to the destination service using `getDestination()` or `executeHttpRequest()`.

When i try to send the request without any URL parameters (e.g. "/A_Products") it is working fine but when adding any parameters (e.g. "/A_Products?$count=true") the destination service is rejecting the request with a 400 response code.

Any help on this?

**Comment by Florin1335BP** [comment]
Hey, since you're getting a 400, are you sure that's not an oData v2 endpoint, in which case you should use $inlinecount?

**Comment by deekshas8** [comment]
Hi @QuentinSieweAGI ,

What query parameters you add to your odata service request is unrelated to the call to `destinationService`, so I did not entirely get what you mean there. 
Could you share some code snippet and the complete error logs?

**Comment by jjtang1985** [comment]
Hi @QuentinSieweAGI ,

Thanks for approaching.

> service.run(req.query)

Could you please share more content of the code example above?
It looks like CAP integration, but I'm not sure.

Are you using SAP Cloud SDK directly?
If yes, what's the relevant code snippets?

Best regards,
Junjie

**Comment by deekshas8** [comment]
Hi @QuentinSieweAGI , were you able to resolve the issue? If not, could you provide some more details.

**Comment by jjtang1985** [comment]
I'll close this ticket, as there are no updates.
Please feel free to reopen.
