### ISSUE TITLE
JS - retry Resilience - Return the original error

### ISSUE THREAD

**Issue by aboccassiniavvale** [SAP/cloud-sdk-js#4789]
Hi experts,

i was trying to implement the "retry" resilience with "executeHttpRequest" method.
Following the example of that implementation:
![image](https://github.com/SAP/cloud-sdk-js/assets/144323043/53960897-b382-48db-bb42-64d7f29a6369)

Testing the error behaviour, I realised that the message that is propagated to the 'catch' is the 'retry' message: 'Request failed with status code 400':
![image](https://github.com/SAP/cloud-sdk-js/assets/144323043/b991a877-921c-47ec-8688-d3fac2f32d7e)

My question is: is it possible to return the original error message received from the server and which triggered the 'retry' logic?

In this way it would be possible to return a 'talking' (the original) message for logging purposes. Instead, with the 'retry' message ("Request failed with status code 400"), it is impossible to make it clear what the real error was.

Thank you, 
Alessandro

**Comment by deekshas8** [comment]
Hi @aboccassiniavvale ,

Thanks for raising this. I agree this would be an improvement to what is currently returned. I will open a ticket to add more info about the cause of the error.
