### ISSUE TITLE
Angular 17+

### ISSUE THREAD

**Issue by nile4000** [SAP/cloud-sdk-js#4825]
Since Angular 17+ isn't using webpack anymore, is there a way to use your Angular Workaround for esbuild/vite?

**Comment by jjtang1985** [comment]
Thank you, @nile4000 for raising up.

Unfortunately, using SAP Cloud SDK for frontend use cases is not recommended. ([documentation](https://sap.github.io/cloud-sdk/docs/js/guides/browser))

We will not provide support for this.

Best regards,
Junjie
