### ISSUE TITLE
executeHttpRequest with destination ClientCertificateAuthentication locally in BAS

### ISSUE THREAD

**Issue by aboccassiniavvale** [SAP/cloud-sdk-js#4836]
Good morning,

i was trying to call a subaccount destination with ClientCertificateAuthentication authentication type.
![image](https://github.com/user-attachments/assets/9d369f7b-18bb-4199-bcea-3f65978f37d0)

Additional Properties:
forwardAuthCertificates: true
HTML5.DynamicDestination: true
HTML5.ForwardAuthCertificates: true
WebIDEEnabled: true
WebIDESystem: test_cred

In my CAP application in NodeJS im using executeHttpRequest :
![image](https://github.com/user-attachments/assets/bb1192f9-53d4-46ce-aa47-c01fdc1dfe93)

If I run locally my CAP in BAS i receive a 401 error. If i deploy the same code works fine.

How can i execute the same http request also in my BAS environment?

Context: im calling the redential Store API with "Mutual TLS Authentication" type.

**Comment by tomfrenken** [comment]
If the workaround did not fix your issue, feel free to re-open it.
