### ISSUE TITLE
Cannot use openapi-generator for Build process SDK generation: 'Some names are not unique after formatting'

### ISSUE THREAD

**Issue by Zahlii** [SAP/cloud-sdk-js#4896]
**Describe the bug**

Downloading specification from SAP Business Accelerator Hub and running openapi-generator fails to produce SDk.

**To Reproduce**

1. Download spec from https://api.sap.com/api/SPA_Workflow_Runtime/cloud-sdk/JavaScript
2. Copy file to resources/service-specs
3. Run npx openapi-generator --input resources/service-specs --outputDir srv/btp-services

**Expected behavior**
SDK is generated and usable.

**Used Versions:**

node -v
v20.12.2

npm -v
10.5.0

"@sap-cloud-sdk/openapi-generator": "^3.17.0",

**Code Examples**
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information.

**Log file**
```
[2024-08-07T12:41:28.458Z] INFO     (cli): Parsing args...
[2024-08-07T12:41:28.516Z] INFO     (openapi-generator): Finished generation. Don't forget to add @sap-cloud-sdk/openapi to your dependencies.
[2024-08-07T12:41:28.516Z] ERROR    (cli): ErrorWithCause: Generation of services failed.
    at /Users/xx/PycharmProjects/cockpit-ng/node_modules/@sap-cloud-sdk/openapi-generator/dist/cli.js:15:18
Caused by:
Error: Could not generate client. Errors: [
        Error: Some names are not unique after formatting.
        Formatted name: 'updateV1WorkflowInstancesContextByWorkflowInstanceId', original names: 'updateV1WorkflowInstancesContextByWorkflowInstanceId', 'updateV1WorkflowInstancesContextByWorkflowInstanceId'.
]
    at finishAll (/Users/xx/PycharmProjects/cockpit-ng/node_modules/@sap-cloud-sdk/util/dist/promise.js:19:15)
    at async generateWithParsedOptions (/Users/xx/PycharmProjects/cockpit-ng/node_modules/@sap-cloud-sdk/openapi-generator/dist/generator.js:59:9)
```

**Impact / Priority**

Affected development phase: Development
Impact: Impaired

**Comment by tomfrenken** [comment]
Hi @Zahlii,

as the log already indicates, the issue here is not with the SDK, but rather with the spec files with seems to have errors.
Please approach the service owner to update and fix the issue in their API.

In the meantime, you can use the `--skipValidation` flag as documented [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client#options).
