### ISSUE TITLE
SDk library ->@sap-cloud-sdk/http-client

### ISSUE THREAD

**Issue by zarar1210** [SAP/cloud-sdk-js#4949]
We are using Cloud SDk library ->@sap-cloud-sdk/http-client - npm (npmjs.com) and it function executeHttpRequest to send request to convergent mediation system(On premise ) via cloud connector .The connectivity is made using Destination which is mainatained in BTP subaccount.

Issue : when we send request to Microservice on particular endpoint. Cloud connector logs shows three requests being fired at the same time even though we send the request once.

```js
const { executeHttpRequest } = require('@sap-cloud-sdk/http-client');
const express = require('express'); const app = express();
app.use(express.json());

app.post('/xyz', async (req, res) => {
   try {
       async function callPostApi(req, destination) {
           const response = await executeHttpRequest(
               {
                   destinationName: destination,
               },
               {
                   method: 'POST',
                   url: req.url,
                   data: req.body,
                   maxContentLength: Infinity,
                   maxBodyLength: Infinity,
                   headers: {
                       "Content-Type": "application/json"
                   },
               }
           );
           return response.data;
       }
       const responseData = await callPostApi(req, "Destination Name");
       res.status(200).send(responseData);

   } catch (error) {
       console.error('Error:', error);
       res.status(500).send({ message: "An error occurred", error });
   } });
```

**Comment by tomfrenken** [comment]
Hi @zarar1210,

The way you are using the SAP Cloud SDK seems correct, however, the cause of your issue is improbable to be the SDK.
Without knowing the rest of your setup it is hard to judge, I would advice you to attach a remote debugger to your application, we have some documentation on this [here](https://sap.github.io/cloud-sdk/docs/js/guides/remote-debugging#attach-a-local-debugger).

I would assume that you are executing `executeHttpRequest` three times due to some malfunction in your setup, therefore you could simply create breakpoint at `await executeHttpRequest`.

Please let me know if this already helped you in finding the cause.

**Comment by zarar1210** [comment]
Hi @tomfrenken 

const { executeHttpRequest } = require('@sap-cloud-sdk/http-client');
const express = require('express'); 
const app = express();
app.use(express.json());

app.post('/xyz', async (req, res) => {
   try {
       async function callPostApi(req, destination) {
           const response = await executeHttpRequest(
               {
                   destinationName: "TEST",
               },
               {
                   method: 'POST',
                   url: req.url,
                   data: req.body,
                   maxContentLength: Infinity,
                   maxBodyLength: Infinity,
                   headers: {
                       "Content-Type": "application/json"
                   },
               }
           );
           return response.data;
       }
       const responseData = await callPostApi(req, "Destination Name");
       res.status(200).send(responseData);

   } catch (error) {
       console.error('Error:', error);
       res.status(500).send({ message: "An error occurred", error });
   } });

This is the final code , Currently I'm using SAP BAS, How I can debug in SAP Business Application Studio?, Please share me if any document is available for this .

**Comment by tomfrenken** [comment]
Hi @zarar1210 your code looks overall functional (although defining the function within the try catch block seems rather weird to me).

I found this [blog post for BAS](https://community.sap.com/t5/technology-blogs-by-sap/set-up-remote-debugging-to-diagnose-cap-applications-node-js-stack-at/ba-p/13515376#attaching-debugger), it seems like the steps involved are very similar / identical.

**Comment by marikaner** [comment]
@zarar1210, can you check whether these requests are CSRF token fetching requests? For POST this is done automatically, you can turn it off as described here: https://sap.github.io/cloud-sdk/docs/js/features/connectivity/http-client#csrf-token-fetching

**Comment by zarar1210** [comment]
Hi @marikaner , Issue resolved now for POST using this
            {
                fetchCsrfToken: false
            }

What about GET method ?  No need to add above code ?

**Comment by tomfrenken** [comment]
No, as you can also see in the references docs:
> It is not available for GET requests.
