### ISSUE TITLE
CDS add data type inference not working

### ISSUE THREAD

**Issue by GoldSucc** [SAP/cloud-sdk-js#4950]
**Describe the bug**
When adding data via CLI `cds add data` it fails with Unknown type undefined (com.sap.learning.BookPrice) in 'com.sap.learning.Books:price'

**To Reproduce**

1. Use this schema for CAP app: entity Books {
    key ID          : UUID;
        title       : String(255);
        genre       : Genre;
        publCountry : String(3);
        stock       : NoOfBooks;
        price       : {
            currency : String(3);
            amount   : Decimal;
        };
        isHardcover : Boolean;
}

type Price {
    currency : String(3);
    amount   : Decimal;
}

2. `cds add data`
3. Error -  Unknown type undefined (com.sap.learning.BookPrice) in 'com.sap.learning.Books:price'
  Skipping db/data/com.sap.learning-Authors.csv
  Skipping db/data/com.sap.learning-Books.csv

**Expected behavior**
Type should be inferred correctly and CSV head generated

**Used Versions:**

- node version via `node -v`: v22.3.0
- npm version via `npm -v`: 10.8.1
- SAP Cloud SDK version you used as dependency `  "dependencies": {
    "@sap/cds": "^8",
    "@sap/cds-hana": "^2.0.0",
    "express": "^4"
  },
`

**Code Examples**
`entity Books {
    key ID          : UUID;
        title       : String(255);
        genre       : Genre;
        publCountry : String(3);
        stock       : NoOfBooks;
        price       : {
            currency : String(3);
            amount   : Decimal;
        };
        isHardcover : Boolean;
}

type Price {
    currency : String(3);
    amount   : Decimal;
}
`

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**
High

Affected development phase: e.g. Getting Started

Impact: ?? (in discovery phase)

Timeline: 1 week.

**Comment by tomfrenken** [comment]
Hi @GoldSucc,

you didn't describe any issue that relates to the SAP Cloud SDK, your dependencies don't even include the SAP Cloud SDK, therefore I assume you opened this issue for the wrong component.

If you can point out any issue with the SAP Cloud SDK, feel free to re-open the issue and add the context.

**Comment by GoldSucc** [comment]
@tomfrenken Posted it here because didn't find any other cds public repo except sap samples repo. would be grateful if you suggest where can I post this issue. issue is SAP CAP related, cds CLI.

**Comment by tomfrenken** [comment]
@GoldSucc I recommend opening a SNOW issue with the BC-XS-CDX-NJS component.
