### ISSUE TITLE
Not able to connect to SAP ECC from CAPM application

### ISSUE THREAD

**Issue by ragavr41** [SAP/cloud-sdk-js#4982]
Hi,

We have a CAPM application, from which we call a OData service to fetch some details using cds.connect in service.

_But we were getting "Error during request to remote service: \ngetaddrinfo ENOTFOUND pg1" error._

So, we updated the SAP Cloud SDK version from 3.2 to 3.6 and now we getting the getting the below error.

_Error during request to remote service: (0 , internal_1.getTenantIdWithFallback) is not a function_

Please help us resolving this.

Regards,
Ragav

**Comment by tomfrenken** [comment]
Hi Ragav, you must keep all cloud sdk dependency versions in sync, otherwise, they will break.
We also recommend upgrading to the latest version, as we do not support outdated ones.

**Comment by tomfrenken** [comment]
Hi @hasanciftci26, the function was removed, however, this error can only occur if you do not keep the SDK dependencies aligned, no package of version 3.20.0 is calling the removed function.
