### ISSUE TITLE
Impossible to pass custom headers in BTP Destination

### ISSUE THREAD

**Issue by aspirio187** [SAP/cloud-sdk-js#5061]
**Describe the bug**

One of the API I needed to use was only accepting application/json content type, which resulted in a 406 error every time I was making a call because the Accept header in the default underlying axios instance in CAP is `application/json,text/plain`.

So I followed the different guides to modify the headers for a BTP Destination and it seems like nothing is working.

**Supposed solutions**

I added the following property on the destination: `URL.headers.Accept` (I tried lower case 'A' and uppercase, there is no difference).

![image](https://github.com/user-attachments/assets/09f6b31e-c0f3-42ec-9cd7-04516fd1d0b8)

So this is as recommended in the documentation [using-services#use-destinations-with-node-js](https://cap.cloud.sap/docs/guides/using-services#use-destinations-with-node-js). The documentation mentions that:

_If you want to configure additional headers for the HTTP request to the system behind the destination, for example an Application Interface Register (AIR) header, you can specify such headers in the destination definition itself using the property [URL.headers.<header-key>](https://help.sap.com/docs/CP_CONNECTIVITY/cca91383641e40ffbe03bdc78f00f681/4e1d742a3d45472d83b411e141729795.html?q=URL.headers)._

This feature is available in UI5 using the approuter, like mentioned in this KBA [3341287 - URL.headers.<header-name> property in BTP destination doesn't work for UI5 application with standalone approuter](https://me.sap.com/notes/3341287/E)

I maybe misunderstood the previous quote, so that it can't overwrite existing headers. But later, on the same page, there is another solution to pass custom headers to the destination [Configure Application Defined Destinations in Node.js
](https://cap.cloud.sap/docs/guides/using-services#configure-application-defined-destinations-in-node-js).

This is a solution for _application defined destinations_, but I'd presume that it would also be picked up by the classic way of using a BTP defined destination.

**Actual workaround**

The only way I found to pass custom headers during an API call, is to use the `send()` method, instead of using the classis `get(),post()...`

```javascript
const connectedDestination = await cds.connect.to('[DESTINATION_NAME]')

const oResult = await connectedDestination.send({
  query: 'POST /[ENDPOINT_TO_WHICH_I_MAKE_THE_CALL]',
  data: oPayload,
  headers: {
    Accept: '*/*',
  },
})
```

**To Reproduce**

1. Set up a simple SAP CAP application
2.1 Create a destination in BTP with an additional **URL.headers.Accept: */*** property

![image](https://github.com/user-attachments/assets/09f6b31e-c0f3-42ec-9cd7-04516fd1d0b8)

2.2 Add the custom header directly in the destination defintion:

```json
    "DESTINATION_NAME": {
      "kind": "rest",
      "credentials": {
        "destination": "DESTINATION_NAME_IN_BTP",
        "requestTimeout": 100000,
        "headers": {
          "Accept": "*/*"
        }
      },
      "destinationOptions": {
        "useCache": true
      }
    },
```
3. Use a tool like BeeCeptor to create mock API and analyze incoming data
4. In CAP, connect to the destination and make an API call to the destination using one of the default CRUD function:

```javascript
    const mock = await cds.connect.to('MOCK_DESTINATION')

    await mock.get('/')
```

4.1 Adding the property in BTP Destination doesn't change the `accept` header key/value

```json
{
  "user-agent": "axios/1.7.4",
  "accept": "application/json,text/plain",
  "accept-encoding": "gzip, compress, deflate, br",
  "x-forwarded-for": "IP_ADDRESS",
  "x-forwarded-host": "issue-report.free.beeceptor.com",
  "x-forwarded-proto": "https"
}
```
4.2 Adding the headers in the destination definition (`.cdsrc,json` file) doesn't change the `accept` header key/value

```json
{
  "user-agent": "axios/1.7.4",
  "accept": "application/json,text/plain",
  "accept-encoding": "gzip, compress, deflate, br",
  "x-forwarded-for": "94.110.18.7",
  "x-forwarded-host": "issue-report.free.beeceptor.com",
  "x-forwarded-proto": "https"
}
```

6. Modify the `.get()` to the following code:

```javascript
await mock.send({
      query: 'GET /',
      headers: {
        Accept: '*/*',
      },
    })
```

8. Confirm that the request headers now contains `Accept: */*`

```json
{
  "user-agent": "axios/1.7.4",
  "accept": "*/*",
  "accept-encoding": "gzip, compress, deflate, br",
  "x-forwarded-for": "94.110.18.7",
  "x-forwarded-host": "issue-report.free.beeceptor.com",
  "x-forwarded-proto": "https"
}
```

**Expected behavior**
Setting the header value in the Destination in BTP should do the job like for the approuter.

**Screenshots**

**Used Versions:**

- node version `v20.15.0`
- npm version `10.7.0`
- SAP Cloud SDK version you used as dependency 

```bash
@cap-js/cds-types: 0.2.0
@sap/cds: 7.9.4
@sap/cds-compiler: 4.9.6
@sap/cds-dk (global): 7.9.6
@sap/cds-fiori: 1.2.7
@sap/cds-foss: 5.0.1
@sap/cds-mtxs: 1.18.2
@sap/cds-odata-v2-adapter-proxy: 1.9.21
@sap/eslint-plugin-cds: 3.0.4
Node.js: v20.15.0
home: /.../backend/node_modules/@sap/cds
....srv: 1.0.0
```

**Code Examples**
If applicable, add code snippets as examples to help explain your problem. Please remove sensitive information.

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**

_Big Impact_: Even though there is a "solution", it would be beneficials to have it mentioned as the only way to pass custom headers in a API call

Affected development phase: Development

Impact: Inconvenience

Timeline: Go-Live is in 2 months

**Additional context**

**Comment by marikaner** [comment]
Hey @aspirio187, it seems to me that you are using CAP and not the SAP Cloud SDK directly. Therefore I would like to ask you to open an issue with CAP. Otherwise please provide a reproducible example where you use the SAP Cloud SDK, so that debugging is easier for us. 

The SAP Cloud SDK for JS does support additional headers from destinations ([docs](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destinations#additional-headers-and-query-parameters-on-destinations)). However all our tests with regards to this pass, so I would need a few more information to go on with this.
