### ISSUE TITLE
how to trace http request when call the executeHttpRequest function

### ISSUE THREAD

**Issue by linjpg** [SAP/cloud-sdk-js#5119]
how to trace http request when call the executeHttpRequest function
const response = await executeHttpRequest(
  {
    url: `https://example.com`
  },
  {
    method: 'post'
  },
  {
    fetchCsrfToken: false
  }
);

**Comment by tomfrenken** [comment]
Hi @linjpg,

we do not offer any out-of-the-box functionality for tracing.
You can either add [middleware](https://sap.github.io/cloud-sdk/docs/js/features/middleware) that logs all events or use a [logger](https://sap.github.io/cloud-sdk/docs/js/features/logging) on the components you want to trace.
