### ISSUE TITLE
Entity Builder fromJson not working for non-top-level navigation properties

### ISSUE THREAD

**Issue by sippsolutions** [SAP/cloud-sdk-js#5180]
**Describe the bug**
When trying to use `fromJson` with navigation properties it works perfectly if they are only assigned on the top level item (example: root>toItem). Nested navigationProperties (example: root>toItem>toScheduleLine) do not work, the entity builder does not have the functions assigned at that moment.

**To Reproduce**

1. Use this example JSON:
```
{
  salesOrderType: 'OR',
  salesOrderTypeInternalCode: 'TA',
  salesOrganization: '1010',
  distributionChannel: '10',
  organizationDivision: '00',
  soldToParty: '10100003',
  purchaseOrderByCustomer: 'PO-GROUP-88',
  salesOrderDate: Moment<2024-11-24T00:00:00+01:00>,
  pricingDate: Moment<2024-11-24T00:00:00+01:00>,
  requestedDeliveryDate: Moment<2024-11-24T00:00:00+01:00>,
  shippingCondition: '01',
  completeDeliveryIsDefined: true,
  toItem: [
    {
      salesOrder: '10',
      salesOrderItem: '10',
      material: 'TG11',
      requestedQuantity: '100',
      requestedQuantityUnit: 'PC',
      toScheduleLine: [
        {
          salesOrder: '10',
          salesOrderItem: '10',
          scheduleLine: '1',
          requestedDeliveryDate: Moment<2024-11-24T00:00:00+01:00>,
          confirmedDeliveryDate: null,
          orderQuantityUnit: 'PC',
          scheduleLineOrderQuantity: '100'
        }
      ]
    }
  ]
}
```
2. Try to build the entity with fromJson: `salesOrderApi.entityBuilder().fromJson(data);`
3. A warning is displayed: `WARN  (entity-builder): Field name "toScheduleLine" is already existing in "SalesOrderItem" and thus cannot be defined as custom field. `

`toItem` works perfectly (top-level navigation property on `SalesOrder` API), but `toScheduleLine` on the `SalesOrderItem` Entity does not work as `toScheduleLine` is not assigned as a function.

**Expected behavior**
Nested navigation properties get assigned correctly.

**Used Versions:**

- node version v20.18.0
- npm version via `npm -v` 10.8.2
- SAP Cloud SDK version you used as dependency `"@sap-cloud-sdk/generator": "^3.22.2",`

**Code example**

```
const util = require('util');
const {apiSalesOrder} = require('../../../services/API_SALES_ORDER/service.js');

async function sendData(params, data, preProcessed) {
    const destination = {
        name: 'xxx',
        url: 'xxx',
        username: 'xxx',
        password: 'xxx',
    }
    process.env.destinations = JSON.stringify([destination]);

    const {salesOrderApi} = apiSalesOrder();
    const salesOrderEntity = salesOrderApi.entityBuilder().fromJson(data);

    salesOrderApi
        .requestBuilder()
        .create(salesOrderEntity)
        .execute({destinationName: 'xxx'})
        .then((data) => {
            console.log(data);
        });

    return {
        success: true
    }
}

module.exports = {
    sendData
}
```
(use data json object from above)

**Comment by deekshas8** [comment]
Hi @sippsolutions ,

We are aware of this issue. We do a [lazy init](https://github.com/SAP/cloud-sdk-js/blob/f76da306088050ab10a90622b45fe46cc3d04d6e/test-packages/test-services-odata-v2/test-service/service.ts#L176) of 2nd level navigation properties. This is the reason why they don't get initialized.

As a workaround, can you destructure the nested apis as well (even if you don't use them). This ensures that the nested navigation properties are also initialized. An example would be :

`const { salesOrderApi, salesOrderItemApi, salesOrderScheduleLineApi } = apiSalesOrder();`

**Comment by sippsolutions** [comment]
@deekshas8 Thank you, the workaround works well!

**Comment by deekshas8** [comment]
Hi @sippsolutions , that's great. I will close this ticket as we have https://github.com/SAP/cloud-sdk-js/issues/3538 to track the issue.
