### ISSUE TITLE
OpenAPI generator ignores the `basePath` field

### ISSUE THREAD

**Issue by lorenzofratus-syscons** [SAP/cloud-sdk-js#5189]
I'm trying to generate a client for an API from SAP Business Accelerator Hub ([link](https://api.sap.com/api/sapdme_plant_workcenter_v2/overview)).

The production URL for said API is of type `https://api.{regionHost}/workcenter/v2` but I want to connect using an existing BTP destination with URL `https://api.{regionHost}` (I plan to use multiple APIs and I don't want to manage many different destinations pointing at basically the same target).

My idea was to set the `basePath` to `/workcenter/v2` using the `options-per-service.json` file since, as far as I know, is [a thing](https://sap.github.io/cloud-sdk/docs/js/features/odata/generate-client#generate-a-client-using-the-command-line-interface) for OData clients, while it is not mentioned in the [documentation](https://sap.github.io/cloud-sdk/docs/js/features/openapi/generate-client#generate-a-client-using-the-command-line-interface) for OpenAPI clients.

However, this didn't produce any change in the generated clients. I even tried changing the `basePath` in the root of the OpenAPI specification from `/` to `/workcenter/v2` but no difference.

I would have expected the generator to prepend the base path to the actual paths defined in the specification.

I couldn't find any way to set a custom base path without having to manually edit the generated clients. In the meantime I will use a different destination for this, but I would appreciate any suggestion on how to improve the situation.

Thanks!

**Comment by KavithaSiva** [comment]
Hi @lorenzofratus-syscons,

We have implemented this feature request in version `3.25.0`. 

You can now regenerate your clients by giving a `basePath` in `options-per-service.json` to prepend the custom base path to the API path parameter for every request.

Or use the `setBasePath` before executing a request, which allows prepending the base path to the API path parameter for that single request.
