### ISSUE TITLE
Failed to call CPI destination endpoint using executeHttpRequest in multitenant cap background job

### ISSUE THREAD

**Issue by sikander-kamra** [SAP/cloud-sdk-js#5202]
**Describe the bug**
I am trying to call CPI endpoint via destination of subscriber subaccount in multitenant cap application's background job. It is a 'GET' call but is getting failed with error "ERROR occurred in background job: Cannot read properties of undefined (reading 'toLowerCase')","stacktrace":["TypeError: Cannot read properties of undefined (reading 'toLowerCase')","at needsCsrfToken (/home/vcap/app/node_modules/@sap-cloud-sdk/http-client/dist/csrf-token-middleware.js:37:30)""

Ideally it should execute the call and give result.

**Expected behavior**
Ideally it should execute the call and give result.

**Screenshots**

<img width="663" alt="DestinationConfig" src="https://github.com/user-attachments/assets/0616ba06-2a17-4032-b335-5fde6d6acf92">
<img width="567" alt="Console Logs" src="https://github.com/user-attachments/assets/53990d0f-88b0-4461-8e0f-8fac4d1dbb61">
<img width="323" alt="Snippet" src="https://github.com/user-attachments/assets/21b6c911-d17e-4476-8d6f-85b6df149a71">
<img width="336" alt="Cloud SDK Error" src="https://github.com/user-attachments/assets/983b47aa-22d3-4c31-8fb1-97cdc8632d2a">

**Used Versions:**

- node version v20.12.0
- npm version 10.5.0
- SAP Cloud SDK version you used as dependency
 "@sap-cloud-sdk/connectivity": "^3.23.0",
    "@sap-cloud-sdk/http-client": "^3.8.1",
    "@sap-cloud-sdk/mail-client": "^3.15.0",
    "@sap-cloud-sdk/odata-v2": "^3.20.0",
    "@sap-cloud-sdk/util": "^3.8.1",

**Code Examples**
Code snippet for background job:

```js
let job = cds.spawn({every:3000, iFlowId: iFlowId, taskId: taskId , destination : destination, nodeKey: nodeKey, commitId: commitId, subdomain:subdomain}, this.backgroundTaskWithId.bind(this));
```

Code snippet for job execution:

```js
async backgroundTaskWithId(){
        var cpi = await cds.connect.to("IntegrationContent");
        cpi.destination = cds.context.destination;
        let taskId = cds.context.taskId;
        let iFlowId = cds.context.iFlowId;
        let nodeKey = cds.context.nodeKey;
        let commitId = cds.context.commitId;
        let subdomain = cds.context.subdomain;
        let deploymentStatus = await this._getDeploymentStatus(taskId,cpi,subdomain);
}

async **_getDeploymentStatus**(taskId,cpi, subdomain) {
      console.log("Inside _getDeploymentStat: "+subdomain);
      console.log("Destination: "+ cpi.destination);
      console.log("TaskId: "+taskId);
	  let iss = 'https://'+subdomain+'.localhost:8080/uaa/oauth/token';
	  **let deploymentStatus = await executeHttpRequest(**                                               // ERROR
		{ 
		   destinationName: cpi.destination,
		   iss: iss 
		},
		{ 
		   url: `BuildAndDeployStatus('${taskId}')`,
		   headers: { 
		   "Content-Type" : "application/json"
		 }
		}
	  );
	  console.log(deploymentStatus);
        return deploymentStatus.Status
    },
```

**Log file**
Screenshot attached

**Impact / Priority**

Impact: e.g. Blocked

Timeline: e.g. Go-Live is in 4 weeks.

**Comment by ZhongpinWang** [comment]
Hi @sikander-kamra , 

When calling `executeHttpRequest` with `requestConfig`, you always need to define the `method` property.

```js
let deploymentStatus = await executeHttpRequest(
  { 
    destinationName: cpi.destination,
      iss: iss 
  },
  { 
    url: `BuildAndDeployStatus('${taskId}')`,
    headers: { 
      "Content-Type" : "application/json"
    },
    method: "..." // Method is missing
  }
);
```

Feel free to re-open this issue if the problem still persists.
