### ISSUE TITLE
"XsuaaService is missing the properties certurl inside its credentials" error after upgrading @sap-cloud-sdk/connectivity to 3.20.0

### ISSUE THREAD

**Issue by infosail** [SAP/cloud-sdk-js#5213]
**Describe the bug**
After we upgraded the Cloud SDK (specifically @sap-cloud-sdk/connectivity, @sap-cloud-sdk/http-client, @sap-cloud-sdk/util) from 3.11.0 to 3.20.0 in our application, the getDestinationFromDestinationService() seems to break for S4 on-premise destinations, which are configured with SAML authentication. 

It throws an error of "Could not fetch client credentials token for service of type connectivity: XsuaaService is missing the properties certurl inside its credentials for: fetch token via certificate authentication." I also tried upgrading @sap/xssec from 3.6.1 to 4.2.0, but I still got the same error.

Please refer to the [errors.log](https://github.com/user-attachments/files/17914206/errors.log) for detailed stack.

**To Reproduce**

1. Set up ...
2. Execute ...
3. Confirm ...

**Expected behavior**
The getDestinationFromDestinationService() returns a promise without throwing errors.

**Screenshots**
<img width="1036" alt="error stack" src="https://github.com/user-attachments/assets/a35452b2-ff73-4782-9c78-47bdc7e61368">

**Used Versions:**

- node version 16.14.0
- npm version 8.3.1
- SAP Cloud SDK version you used as dependency 3.20.0

**Code Examples**
Please see the code snippet here 
<img width="675" alt="code" src="https://github.com/user-attachments/assets/19ca47ba-3d8a-4059-ac48-0ae3b892d22b">

**Log file**
If applicable, add your log file or related error message. Again, please remove your sensitive information.

**Impact / Priority**

Affected development phase: Release

Impact: Impaired

Timeline: new release in four weeks.

**Additional context**

**Comment by ZhongpinWang** [comment]
Hi @infosail ,

Thanks for reaching out. It looks like the underlying `@sap/xssec` cannot get the token for connectivity service because the `certificate` property is defined, but not `certurl`.

I checked the current implementation for `XsuaaService.js` from `@sap/xssec`:

```js
async getTokenUrl(grant_type, options = {}) {
        const { tenant } = options;

        let baseUrl;
        if (tenant) {
            this.validateCredentials("build token fetch URL for custom tenant subdomain", "uaadomain");
            const uaaDomain = this.credentials.certificate ? this.credentials.uaadomain.replace("authentication.", "authentication.cert.") : this.credentials.uaadomain;
            baseUrl = `${HTTPS_SCHEME}${tenant}.${uaaDomain}`;
        } else {
            if (this.credentials.certificate) { // `certificate` is defined
                this.validateCredentials("fetch token via certificate authentication", "certurl");
                baseUrl = this.credentials.certurl;
            } else {
                this.validateCredentials("fetch token via client secret authentication", "url");
                baseUrl = this.credentials.url;
            }
        }

        return new URL(this.endpoints.token, baseUrl);
    }
```

Could you please share the structure of your credential for connectivity service by removing the actual values? I will contact xssec team for this issue.

**Comment by finkmanAtSap** [comment]
Hi,

It is not possible to fetch client credentials tokens with certificate/key from the `url` property. The `certurl` property is required for this. The `url` property only works for client-secret based credentials.

If I understand correctly, your Xsuaa service credentials are supplied by connectivity service. I assume they only forward a hand-picked set of properties from the full credentials object. Please open a ticket there to have this fixed and the certurl supplied.

Best,
Manuel from the @sap/xssec maintainers

**Comment by deekshas8** [comment]
Hi @infosail , please refer to the reply from Manuel. I'll close this ticket.

**Comment by infosail** [comment]
@deekshas8 The Connectivity Service colleague Ivan Penev told me that the "connectivity_proxy" plan does not include the "certurl" property like the "lite" plan but this is intentional. He wants Cloud SDK team to provide more details about the consumption of the "connectivity_proxy" plan in the new versions. But he couldn't find your SNOW component - in the past it was "XX-S4C-SDK". Could you please provide your component? Otherwise, we may have to continue to use this thread for tracking.
