### ISSUE TITLE
getByKey is appending the key name in the GET Call

### ISSUE THREAD

**Issue by singhc00** [SAP/cloud-sdk-js#5292]
### Describe the Bug

Hi

It appears that odata-v2 client does not respect the OpenAPI.json from the api hub. We are using API Management which allows certain endpoints based on the OpenAPI.json file.

I am trying to use Sales Quotation (A2X) and based on the OpenAPI.json, it only allows /A_SalesQuotation('{SalesQuotation}'). When I try to fetch the Sales Quotation using .requestBuilder().getByKey({salesQuotation}), it tries to make an HTTP call as /A_SalesQuotation(SalesQuotation='{SalesQuotation}'). This is not a valid URL because it does not exist in OpenAPI.json.

### Steps to Reproduce

I am trying to use Sales Quotation (A2X) and based on the OpenAPI.json, it only allows /A_SalesQuotation('{SalesQuotation}'). When I try to fetch the Sales Quotation using .requestBuilder().getByKey({salesQuotation}), it tries to make an HTTP call as /A_SalesQuotation(SalesQuotation='{SalesQuotation}'). This is not a valid URL because it does not exist in OpenAPI.json.

### Expected Behavior

It should not use the key name for the GET request if OpenAPI.json from API Hub does not have it.

### Used Versions

- Node version via `node -v`: ...
- NPM version via `npm -v: ...
- SAP Cloud SDK version: ...
- For CAP users, CAP version: ...

### Affected Development Phase

Getting Started

### Impact

No Impact

**Comment by ZhongpinWang** [comment]
Hi @singhc00 ,

First of all, I assume you are using OData V2 generator with edmx file, not OpenAPI generator. 

According to [OData documentation for key predicate](https://www.odata.org/documentation/odata-version-2-0/uri-conventions/#:~:text=KeyPredicate%3A%20A%20predicate%20that%20identifies,stated%20using%20name%2Fvalue%20pairs.):

> If the Entry has a single key Property the predicate **may** include only the value of the key Property.

If the service side implements the OData standard correctly, it should also support a request with a single key name in it.

Check the OData reference service. Both of the following requests work:

```txt
GET https://services.odata.org/TripPinRESTierService/People('russellwhyte')
GET https://services.odata.org/TripPinRESTierService/People(UserName='russellwhyte')
```

As a workaround, you can

- use [http-client](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/http-client) to construct the request manually
- OR use `getAll()` with `filter()`, which constructs the url with `$filter` and will be filtered by the server side, not by SDK.

**Comment by ZhongpinWang** [comment]
I will close this issue for now. If you see it otherwise, feel free to re-open it with some additional information like the server response and error logs.
