### ISSUE TITLE
Deprecation of @sap-cloud-sdk/mail-client, what is the alternative?

### ISSUE THREAD

**Issue by devhirsbrunnerm** [SAP/cloud-sdk-js#5298]
Hi, 
i just saw that the @sap-cloud-sdk/mail-client is deprecated. Is there an alternative to it or did SAP just drop support for it? What was the reason it was deprecated?

I found this reference as a reason: [https://github.com/SAP/ai-sdk-js-backlog/issues/169](https://github.com/SAP/ai-sdk-js-backlog/issues/169) but am getting a 404 error. I would guess this is an internal repo.

Thanks for clarifying!

Cheers
Marco Hirsbrunner

**Comment by jjtang1985** [comment]
Thank you, @devhirsbrunnerm for raising this up.

We deprecated the mail client from SAP Cloud SDK, which is purely from the SDK perspective.
You can still use the mail destination from BTP and here is the BTP documentation for [using the TCP protocol for cloud applications](https://help.sap.com/docs/connectivity/sap-btp-connectivity-cf/using-tcp-protocol-for-cloud-applications?locale=en-US).

As an alternative, you can use the SDK for getting a mail destination, and send the mail by your own.
This can be done e.g., by reading the BTP documentation above or copy/paste the existing SDK code.

The usage statistics also indicated that this is not a major feature that most SDK users used.

BTW, the link you shared was an internal repo.

**Comment by T1mey** [comment]
@jjtang1985 
I found the package very helpful and used it in some projects. Is there any chance that SAP provides a migration path?
