### ISSUE TITLE
Support more than two schemas

### ISSUE THREAD

**Issue by AndreasHae** [SAP/cloud-sdk-js#569]
The parser throws an error when passing an EDMX file with more than 2 schemas. Is there any specific reason why that's the case? If there are only 2 schemas, they seem to get merged. Shouldn't that be possible for more than 2 schemas as well?

Here's the relevant code:
https://github.com/SAP/cloud-sdk/blob/master/packages/generator/src/edmx-parser/edmx-file-reader.ts#L60

**Comment by jjtang1985** [comment]
Hi @AndreasHae , thank you for approaching us 😃 

your feature request is added to our backlog and will be discussed in the refinement.

I have some additional questions below:
- Could you please provide us the `.edmx` file example with 2+ schemas, if possible?
- Where (e.g., [SAP API Business Hub](https://api.sap.com)) did you get this `.edmx` file for which system (e.g., S/4, SuccessFactors or some other odata system).
- OData version? v2 or v4?
- Is it a very urgent requirement?

Thank you.

**Comment by AndreasHae** [comment]
Hi @jjtang1985, thanks for the quick response.

I cannot provide the actual EDMX file, but its structure resembles this:

```xml
<?xml version="1.0" encoding="utf-8"?>
<edmx:Edmx Version="4.0"
  xmlns:edmx="http://docs.oasis-open.org/odata/ns/edmx">
  <edmx:DataServices>
    <Schema Namespace="Company.Product.Namespace1"
      xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="...">...</EntityType>
    </Schema>
    <Schema Namespace="Company.Product.Namespace2"
      xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="...">...</EntityType>
    </Schema>
    <Schema Namespace="Company.Product.Namespace3"
      xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="...">...</EntityType>
    </Schema>
    <Schema Namespace="Company.Product.Namespace4"
      xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityType Name="...">...</EntityType>
    </Schema>
    <Schema Namespace="Company.Product.Enums"
      xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EnumType Name="...">...</EnumType>
      <EnumType Name="...">...</EnumType>
      <EnumType Name="...">...</EnumType>
    <Schema Namespace="Default"
      xmlns="http://docs.oasis-open.org/odata/ns/edm">
      <EntityContainer Name="Container">
        <EntitySet Name="..." EntityType="Company.Product.Namespace1..." />
        <EntitySet Name="..." EntityType="Company.Product.Namespace2..." />
        <EntitySet Name="..." EntityType="Company.Product.Namespace3..." />
        <EntitySet Name="..." EntityType="Company.Product.Namespace4..." />
      </EntityContainer>
    </Schema>
  </edmx:DataServices>
</edmx:Edmx>
```

I got the response from a custom-built .NET service using the Microsoft.AspNet.OData library.

The OData version is 4.0.

The requirement is not that urgent, but from what I've seen this should be simple to implement (just remove the if-statement I linked in my first comment).

**Comment by marikaner** [comment]
@AndreasHae, please note that this repository has been moved and the link to this issue has changed.

**Comment by jjtang1985** [comment]
Hi @AndreasHae , the [version `1.33.0`](https://github.com/SAP/cloud-sdk-js/releases) has been released, which supports using multiple schemas. Please try it and let me know whether it solves your issue.

**Comment by jjtang1985** [comment]
Hi @AndreasHae , I'm going to close this ticket since it has not been updated for 8 days.

**Comment by jjtang1985** [comment]
Hi @AndreasHae, I'll close this ticket. Please reopen if you still have questions.
