### ISSUE TITLE
Batch request fails with CAP

### ISSUE THREAD

**Issue by meakgoz2** [SAP/cloud-sdk-js#605]
**Describe the bug**
I am using the "SDK's Generator for JavaScript" to generate OData client for a service generated by using CAP (following this [blog](https://developers.sap.com/tutorials/cloudsdk-js-generator.html) post).
After I change the default service path from `VALUE_IS_UNDEFINED` to my service path (`/sitn-admin-srv`) I could use all the operations without any problem.
However, when I use the batch request (following this [blog](https://developers.sap.com/tutorials/cloudsdk-js-odata-batch-changeset.html) post), the request has reached to the server fine, but I got warnings in the server side;  
`[2020-10-19T13:35:50.287Z | WARNING | 1854218]: 'sitn' is not an entity set, a singleton, an action import, or a function import`   
where my service path is `sitn-admin-srv`. 

When I set the `_defaultServicePath` to empty string in the entity level (file is `SituationTemplateMetaData.ts`), then batch request works fine, but of course all the single operations are being made to the root level and I get 404 errors for the single operations.

Maybe the batch request concatenates the default service path twice? Or am I doing something wrong?

**To Reproduce**
1. Get any OData service (like bookshop app)
2. Generate client library using the generator
3. Change the default paths in generated files
    `export const defaultSitnAdminSrvServicePath = '/<serice-path>';` in `BatchRequest.ts` and `static _defaultServicePath = '/<service-path>';` in `<entity>.ts` 
4. Single requests will work, but batch request will get a warning like above.
5. Leave the service path empty in the entity file, batch request will work but the single requests will get 404.

I can also provide you my code, or collabrate further if there is a need.

**Used Versions:**
 - node version via `node -v`: v12.16.0
 - npm version via `npm -v`: 6.13.7
 - SAP Cloud SDK version you used as dependency: `-- @sap-cloud-sdk/core@1.30.0
- Cli: `-- @sap-cloud-sdk/cli@0.1.12

**Comment by artemkovalyov** [comment]
Hi, @meakgoz2 

We'll take a look into this and get back to you soon. Thanks for the detailed but report. cc @marikaner 

Best,
Artem

**Comment by marikaner** [comment]
Hey @meakgoz2,

according to the batch specification endpoints that accept batch should allow to set subrequest paths that are absolute, relative to the service or relative to the entity set. The SDK sets the subrequest path relative to the service by default, but CAP currently only accepts paths relative to the entity set. We provide an additional configuration option that you can use to diverge from this default behaviour.

Try:
```ts
batch(...).withSubRequestType('relativeToEntity')
```

I hope that helps, we will add documentation on this soon.

**Comment by meakgoz2** [comment]
Hi Marika, 
Thank you for the information. I have solved my problem using `.withCustomServicePath('/admin')` but will use your suggestion from now on.
Feel free to close this issue in your convenience (e.g., after the documentation change).

**Comment by marikaner** [comment]
Hey @meakgoz2,

that was also my initial solution when I realized that this issue exists. ;) I will update this ticket with a link to the documentation, once it is done!

**Comment by marikaner** [comment]
@meakgoz2, please note that this repository has been moved and the link to this issue has changed.

**Comment by marikaner** [comment]
Hey @meakgoz2, we have added this to our documentation [here](https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v4-type-safe-client-for-javascript-typescript#configure-subrequest-serialization).
