### ISSUE TITLE
Disable csrf fetch request

### ISSUE THREAD

**Issue by meakgoz2** [SAP/cloud-sdk-js#606]
**Is your feature request related to a problem? Please describe.**
I am using the sdk as an OData client for my CAP project. I do not have CSRF protection in my backend as it is not meant for users to do browsing. I assume there is no need for csrf protection when two apps talks to each other?

So it would be very nice if there was a configuration to disable the token fetching request that is sent before each request. When there are so many requests, this is even creating problems with destination service. Issuing lots of request creates a connection problem.

I checked the documentation and tutorials, unfortunately could not find any clue to do this.
Hope this description is good enoug.

**Comment by artemkovalyov** [comment]
Hi @meakgoz2,

Thanks for reporting your issue. Yes, we normally do a pre-flight to fetch CSRF, most of the services implement this. We'll take a look and come back with ideas about suppressing it or other possible solutions.

Best,
Artem

**Comment by artemkovalyov** [comment]
Hi @meakgoz2 ,

There's no workaround out of the box. We added this to the backlog to provide a flexibility of suppression of CSRF token retrieval. 

Can you please let us know how urgent or blocking this fix is for you? What's the state of your service? Having many competing items we have to prioritize this.

We'll keep you posted on the progress.

Thanks,
Artem

**Comment by meakgoz2** [comment]
Hi Artem,

Although it would be nice to have feature, this can be low prio as it does not block us (rather slowing our service a bit).
Thanks for keeping me up to date.

Regards,
Emin.

**Comment by marikaner** [comment]
@meakgoz2, please note that this repository has been moved and the link to this issue has changed.

**Comment by jjtang1985** [comment]
Hi all,
now you are able to skip fetching the csrf token by using our new feature.
Here is an example:
```ts
 BusinessPartner.requestBuilder()
   .update(businessPartner)
   .skipCsrfTokenFetching();
 ```
Please note, the feature is currently available in the `canary` version and will be released in the next minor version.

I'll close this ticket.
Please feel free to re-open, if you have questions.

**Comment by jjtang1985** [comment]
Hi all,
Please use the new version [1.42.0](https://github.com/SAP/cloud-sdk-js/releases), which contains this feature.
