### ISSUE TITLE
Cloud SDK serialization issue

### ISSUE THREAD

**Issue by FrankEssenberger** [SAP/cloud-sdk-js#698]
Issue on answers.sap.com:
https://answers.sap.com/questions/13187137/cloud-sdk-serialization-issue-1.html

**Comment by marikaner** [comment]
From my first investigation I think there is a discrepancy between the given metadata and generated odata client. If this is not the case, we are stripping `_Code` from the names of navigation properties.

**Comment by marikaner** [comment]
The user deleted the question.
