### ISSUE TITLE
Support entity type as parameter/return type for function/action import

### ISSUE THREAD

**Issue by jjtang1985** [SAP/cloud-sdk-js#707]
When using the generator with an SAP Business One Edmx file, the following error message is shown:

```
Tries to get a action/function parameter with type SAPB1.Document which is not a Edm type.
```
because currently the sdk does not support entity type as parameter for function/action import.

AC:
- [x] The generator should not fail when detecting unsupported function/action import. Ignoring such cases might be a quick win.
- [ ] Support entity type as parameter/return type for function/action import

cloud sdk version: 1.31.1-22d161e0.22
odata version: v4

**Comment by marikaner** [comment]
This feature was requested here as well: https://answers.sap.com/questions/13229704/unsupported-function-or-action-import-parameter.html

**Comment by jjtang1985** [comment]
It turns out that all the function imports with entity parameters occurred in the SAP Business One metadata file are bound function. Therefore, the feature request implicitly goes to the direction that contains the bound function/action.
@artemkovalyov

**Comment by marikaner** [comment]
As there was no further activity on this, I will close it for now. We will keep it in our backlog with low priority.

**Comment by marikaner** [comment]
BTW, @thekevinbrown, did you try running the generator after some of the fixes we provided? Entity types as return types are now supported, but adding support for parameters would result in a bigger deal, we plan to postpone this until there is bigger demand. However, generation should not fail for those anymore.

**Comment by thekevinbrown** [comment]
No, I ended up just hand coding entity files and a client to match our needed schema, as it had to be done quickly.

**Comment by marikaner** [comment]
Thank you for the info!

**Comment by andretrump** [comment]
> It turns out that all the function imports with entity parameters occurred in the SAP Business One metadata file are bound function. Therefore, the feature request implicitly goes to the direction that contains the bound function/action. @artemkovalyov

Hi colleagues, I am currently working in a customer project where we require this feature since we need to call bound actions  quite frequently. Until now we called them through the HTTP client as a workaround but now we also need to bundle them in batch requests which is quite cumbersome without a high-level API. Are there any plans to implement this?

**Comment by BovineJoni** [comment]
Hi, yes it would be really nice if bound actions/functions would be supported by the sdk generator.
Actually I don't understand that SAP is waiting for a bigger demand. Right now all bound actions/functions of OData APIs (which are quite a lot) cannot get used by the recommended procedure (which is the use of the SDK generator). This applies to Node.js. I don't know if the Java implementation can handle this - but customers either have one of the two, not both. To me this sounds more like an incompleteness or unfinished work, than some special features needed by too few people. Please put it on the roadmap asap.

**Comment by jjtang1985** [comment]
Hi all,

Thanks for your comments.

> Until now we called them through the HTTP client as a workaround but now we also need to bundle them in batch requests which is quite cumbersome without a high-level API. Are there any plans to implement this?

Using the HTTP client is the recommended workaround, which should work but I agree, it makes the consumption more complicated.

To make it more transparent, the current priority of the SAP Cloud SDK is to support AI use cases. (new [repository](https://github.com/SAP/ai-sdk-js))
From the current plan, I guess we will not work on this for the next 6 months.

Thank you very much for your understanding.
Best regards,
Junjie

**Comment by qby-ankul** [comment]
Hi @jjtang1985 even though my origin issue https://github.com/SAP/cloud-sdk-js/issues/4543 is an unbound operation, we keep coming across this post in the hope that this feature will be implemented soon.

If I read the SCN correctly, it was already in development in january 21
> This is a known issue and we're working on it now. I assume we should be able to handle this soon.
