### ISSUE TITLE
Generator: Deprecated nested dependencies

### ISSUE THREAD

**Issue by ja-ne** [SAP/cloud-sdk-js#734]
Npm warns about two deprecated packages associated with @sap/edm-converters which is a dependency of @sap-cloud-sdk/generator:

```
npm WARN deprecated request@2.88.0: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
```

Is there something that can be done about this?

I know this may not be the most suitable place for this question but the only one I could think of since I could not find contact information for @sap/edm-converters.

Thanks in advance.

**Comment by marikaner** [comment]
Hey @ja-ne 

I can forward your request to the colleagues who work on the edm-converters. I will let you know if there is anything planning with regards to this.

**Comment by ja-ne** [comment]
That's good, many thanks.

**Comment by marikaner** [comment]
Hey @ja-ne,

I heard back from the colleagues. They are aware of the replacement need and will take it into consideration. It is possible that this will take a while though as they are considering other changes along this.

I hope that helps!

**Comment by ja-ne** [comment]
Thanks for the update.
