### ISSUE TITLE
New version (1.32.0) of @sap-cloud-sdk/core does not export `executeHttpRequest` function anymore

### ISSUE THREAD

**Issue by johannes-vogel** [SAP/cloud-sdk-js#741]
**Describe the bug**
Hi colleagues,

when installing the newest version (1.32.0) of the `@sap-cloud-sdk/core` package, the functions of the `http-client` module are not exported anymore.

We rely on the `executeHttpRequest` method which was exported until `1.31.0`.
I did not find any related entry in the changelog and also the [documentation](https://sap.github.io/cloud-sdk/api/1.32.0/modules/sap_cloud_sdk_core#executehttprequest) suggests that this function should still be available. 

When looking at https://github.com/SAP/cloud-sdk-js/blob/v1.32.0/packages/core/src/index.ts, I can also see that it is not exported anymore.

**To Reproduce**
1. Install `@sap-cloud-sdk/core` in any node.js project.
2. `require('@sap-cloud-sdk/core').executeHttpRequest`  is not defined

**Expected behavior**
I'd expect the function to still be available.

**Comment by marikaner** [comment]
Hey @johannes-vogel,

this should not have happened, I will check this and release a new version as soon as possible. Thanks for reporting!

**Comment by johannes-vogel** [comment]
Hi @marikaner,

thanks for your quick support 👍

**Comment by marikaner** [comment]
Hey @johannes-vogel, we have released a new version 1.32.1 that should fix this problem. Sorry for the inconvenience. I'll go ahead and close this issue.

**Comment by johannes-vogel** [comment]
@marikaner I can confirm, that it is working again!
