### ISSUE TITLE
Error using sap-cloud-sdk with vue.js (process.on is not a function)

### ISSUE THREAD

**Issue by nexzgg** [SAP/cloud-sdk-js#759]
Hey guys,
I'm currently evaluating several odata-clients for vue.js and encountered the following problem using the cloud-sdk for js.

My test-repository:
https://github.com/nexzgg/vue3-typescript 

The Problem:
I generated my odata-client from an odata-metadata.xml (like u can see in the picture)
![image](https://user-images.githubusercontent.com/53438585/100732577-31b21a00-33cd-11eb-8dea-51645e11ac0e.png)

Afterwards i tried to show some data within a table.
![image](https://user-images.githubusercontent.com/53438585/100754845-d2173700-33eb-11eb-84bb-de3473659930.png)

The Problem is, i always run into this error.
![image](https://user-images.githubusercontent.com/53438585/100732779-805fb400-33cd-11eb-9dca-504ca5f25893.png)

I found out that the node-module "node-libs-browser" is used somewhere in the backround from cloud-sdk-logger.js and process.on is not defined here.
![image](https://user-images.githubusercontent.com/53438585/100733111-f82dde80-33cd-11eb-9057-4e47486e6066.png)

Am i doing something wrong or is this a bug?

Kind regards,
Julian.

**Comment by marikaner** [comment]
Hey @nexzgg,

thanks for reporting this. This might be a bug in the underlying library. I have never seen this error before, so I will have to take some time to investigate this. Maybe in the mean time you might want to try [this workaround](https://sap.github.io/cloud-sdk/docs/js/guides/sdk-in-browser#workaround) but for `vue` and `process`, although I am not sure that this will work. I will come back to you once I had a closer look.

**Comment by nexzgg** [comment]
Hey @marikaner,

i will try this out. Thanks so far.

**Comment by nexzgg** [comment]
Hey @marikaner,

this Workaround worked for me. I added the webpack config to my vue.config.js.
![image](https://user-images.githubusercontent.com/53438585/100754448-6765fb80-33eb-11eb-9b7d-cfef6fa9ce7d.png)

I had also problems with "setImmediate", so i added this too.

**Comment by marikaner** [comment]
Thanks for letting me know!

**Comment by FrankEssenberger** [comment]
As discussed with @marikaner I close the issue since we have already backlog items for the follow up tasks to do a proper fix.
