### ISSUE TITLE
Deep create request fails with error

### ISSUE THREAD

**Issue by jjtang1985** [SAP/cloud-sdk-js#768]

**Comment by FrankEssenberger** [comment]
This issue is just a place holder for an issue created in the internal repo.

**Comment by marikaner** [comment]
Documentation was improved.

**Comment by jjtang1985** [comment]
https://sap.github.io/cloud-sdk/docs/js/features/odata/use-odata-v4-type-safe-client-for-javascript-typescript#deep-create
