### ISSUE TITLE
How-To consume Destinations outside of my CF space using CAP

### ISSUE THREAD

**Issue by JohannesRu** [SAP/cloud-sdk-js#778]
Hello colleagues,

We are from SAP Graph and use CAP4 library to connect to S4 systems utilising the Cloud SDK
(See: https://cap.cloud.sap/docs/guides/services#rest-and-odata).

In the documentation we see how we can achieve this for CAP4 applications running in the same CF space where the sub accounts Destination Service is accessible. 
cds.connect.to(‘my.external.service’)

In our scenario, we are hosting a SaaS application in a Kubernetes Cluster hosted on Google Cloud Platform. Hence we need to consume the Destination Service from outside. Our application does have access to Destination Service URL as well as the credentials required.

Previously, in a CAP3 set-up that did not contain the Cloud SDK, we achieved the desired behaviour by fetching the Destination data programatically and then continued with the access via CAP.

Is this case supported by Cloud SDK and furthermore, can we make use of it when using Cloud SDK indirectly via CAP4? 

Would be great to exchange on the use-case and hear from you how we can best achieve this.
Looking forward

Johannes (D056754)
PO, SAP Graph

**Comment by jjtang1985** [comment]
Hi Johannes,

thanks for approaching us.

In addition to the [destination service](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/destination-js-sdk), which is a CF specific service, the SDK also provides the [generic HTTP client](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/generic-http-client), which might be helpful in your case.

AFAIK, the CAP is using this function [`executeHttpRequest(destination, requestConfig)`](https://sap.github.io/cloud-sdk/api/1.32.1/modules/sap_cloud_sdk_core#executehttprequest) as the connectivity service from the SDK. You can either user this API directly from the SDK or implicitly from the CAP.

To consume directly, given that you would like to connect to GCP, you'll have to provide e.g., the url and credential information in the [destination object](https://sap.github.io/cloud-sdk/api/1.32.1/interfaces/sap_cloud_sdk_core.destination) being the first parameter of the function `executeHttpRequest(destination, requestConfig)`.

I don't have deep knowledge about how you configure the destination with CAP, I recommend that you can approach CAP colleagues [here](https://github.wdf.sap.corp/cap/issues/issues).

I hope this answers your question.
Please let me know, if you have further questions.

Best regards,
Junjie

**Comment by jjtang1985** [comment]
Hi @JohannesRu , 
I'll close this ticket, if you don't have further questions?

**Comment by jjtang1985** [comment]
I close this ticket for now. Please reopen it when necessary.
