### ISSUE TITLE
BAPI/RFC support -- call S/4HANA on-premise BAPI from CAPM app

### ISSUE THREAD

**Issue by sumit-kundu** [SAP/cloud-sdk-js#780]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by FrankEssenberger** [comment]
Hello summit-kundu,

I think I got your feature request from the title, but the next time it would be nice if you could put also a bit more context to the issue description.

Currently we do not support a typed client for BAPI/RFC calls and I am afraid we can not offer this in the near future. What you can use is the [executeHttpReques](https://sap.github.io/cloud-sdk/docs/js/features/connectivity/generic-http-client) method of the SDK. 

This gives you at least the connectivity from the SDK so you do not have to bother about the could connector and so on. You have then to pass the payload to the BAPI/RFC wihtout type safety as plain XML/JSON.

I hope this helps.

Best
Frank

**Comment by artemkovalyov** [comment]
Hi @sumit-kundu,

Besides our generic HTTP client that you could leverage as described by Frank, we're not going to implement BAPI ins JS SDK.
You can consider Java as there we still have enough convenience for BAPI/RFC calls. Check this material for reference: https://sap.github.io/cloud-sdk/docs/java/features/bapi-and-rfc/bapi-and-rfc-overview/

Best,
Artem
