### ISSUE TITLE
CLOUD SDK JS 1.0 - risk assessment for vulnerability (medium) in axios-0.19.2.tgz

### ISSUE THREAD

**Issue by AnnaDez** [SAP/cloud-sdk-js#812]
Dear Colleagues,
 
we are from ERP for SME and are building one of the consumer applications of the Cloud SDK JS (Using "@sap-cloud-sdk/core": "^**1.30.0**") component
and the WhiteSource scan result for our BAF core component ([package.json](https://github.wdf.sap.corp/BIG/x4/blob/dev/package.json)) shows a vulnerability in axios-0.19.2.tgz 
(Path: https://saas.whitesourcesoftware.com/Wss/WSS.html#!libraryVulnerabilities;uuid=811031a9-bfee-44c0-bd1f-1aec280d4bed;project=2366016;orgToken=74cbbb27-f32c-474e-bb6b-d99fbffddee4).
 
Could you do us a small favor by writing my a short feedback when the risk assessment (hopefully false positive ;) ) for this vulnerability will be done or providing further details? (currently we will continue to use the 1.30.0 version of the component)

![_thumb_77439](https://user-images.githubusercontent.com/75968284/102046787-569a8a00-3ddc-11eb-9d01-085301bf2ff2.png)
![_thumb_77438](https://user-images.githubusercontent.com/75968284/102046795-5a2e1100-3ddc-11eb-90c0-655b69a5d79a.png)
![image-2020-12-02-06-52-24-170](https://user-images.githubusercontent.com/75968284/102047297-4d5ded00-3ddd-11eb-89e3-646f12d2a612.png)

Thanks!
Best, 
Anna

**Comment by FrankEssenberger** [comment]
Hi Anna,

thanks for opening an issue. We use the following version of `axios` in our package.json: 
``` 
    "axios": "^0.21.0"
```

The modifier `^` means that minor and path versions are automatically increased if available when you do a fresh `npm i`. So once the axios fixed the issue and released a new version the error will disappear. You can have a look at this issue:

https://github.com/axios/axios/pull/3410

So once they release 0.21.1 the error will be fixed I think.

**Comment by FrankEssenberger** [comment]
So I would close the issue here because the fix from axios is already on the way.

**Comment by jjtang1985** [comment]
https://github.com/SAP/cloud-sdk-js/pull/890
