### ISSUE TITLE
Custom field in navigation of deep create possible?

### ISSUE THREAD

**Issue by stefania-santimbrean** [SAP/cloud-sdk-js#849]
Hello,

I am doing a deep create using SAP Cloud SDK and in the navigation entity I have a custom field which is not saved.

Before `PurchaseOrder.requestBuilder().create(purchaseOrder).execute(dest);` is executed if I do `purchaseOrder.toPurchaseOrderItem[0].getCustomFields()` I can see my custom field. But when I check the Purchase Order in the SAP S/4HANA Cloud system it's not there.

It works if I create PurchaseOrderItem. I can see that the custom field is saved.

Could you please tell me if this functionality is supported or if I'm missing something? If there is already an issue/question which covers this scenario, please point me in the right direction. 

Thank you,
Best regards,
Stefania

**Comment by marikaner** [comment]
Hey @stefania-santimbrean,

I tried to reproduce this and found that this in fact is a bug in our serialization. I will let you know once this is fixed.

Regards,
Marika

**Comment by stefania-santimbrean** [comment]
Hello @marikaner ,

Thanks for taking a look at the issue!

Do you happen to know when the fix might be available? A general timeframe? I am asking so I know if to wait for the fix or try workarounds.

Best regards,
Stefania

**Comment by marikaner** [comment]
Hey @stefania-santimbrean,

this is no promise, but we have discussed a possibility of making a new release this week. It depends a bit on how many changes will need to be done on the PR I opened. I will let you know as soon as I know more.

**Comment by stefania-santimbrean** [comment]
Hello @marikaner ,

Thank you so much for the support!!

One more question on the topic: What about batch mode? Are the custom fields in the navigation entity supported when using batch mode?

I tried to use batch mode and the custom field is not saved. Will your fix also solve this in batch mode?

Best regards and thank you again,
Stefania

**Comment by marikaner** [comment]
Hey @stefania-santimbrean,

we provided a fix in version 1.35.0 of the SDK. This should also solve the same issue in batch mode. Let me know in case you still encounter issues. I will go ahead and close this issue for now.

**Comment by stefania-santimbrean** [comment]
@marikaner thank you! Deep create works with custom fields now perfectly!
