### ISSUE TITLE
Cannot create entity due to "`entity.getCustomFields` is not a function

### ISSUE THREAD

**Issue by marikaner** [SAP/cloud-sdk-js#931]
**Describe the bug**
When creating a custom client and executing create requests the error above occurs, while this has worked before.

**Comment by marikaner** [comment]
Requested previous and current version from user.

**Comment by blaart** [comment]
hi I have the same problem (for me first time using this). I use v1.37.0.
I get this on this call on the .create:
await OrderSet
      .requestBuilder()
      .create(orderSet)
      .execute(..)

**Comment by marikaner** [comment]
Thanks @blaart, we will investigate this and try to solve it as soon as possible. Does your `orderSet` instance contain navigation properties?

**Comment by blaart** [comment]
Thanks, @marikaner, the orderSet has several navigation properties (some in an array)

**Comment by blaart** [comment]
Same problem with .update by the way

**Comment by ja-ne** [comment]
Hi, I can reproduce this for versions >1.34.0 as well. Is there a workaround other than leaving out navigation properties (I've only tested with array navigation properties)?

Thanks in advance.

**Comment by marikaner** [comment]
Hey @blaart and @ja-ne,

I am on it, but I am currently unable to reproduce this problem, therefore I am also not able to give you any good advice for a workaround (maybe stay with a version < 1.34).

Could you please provide a small example on how you are building the entity that you want to create?

**Comment by marikaner** [comment]
Ok, I just confirmed a suspicion.

It seems that you are not building the entities as intended, with the entity builder:

```ts
const navProperty = SomeNavProperty().builder().someProperty('navProperty').build();
const myEntity = MyEntity.builder().someNavProperty(navProperty).build();
```

Instead are trying to use an object:
```ts
const myEntity = {
  someNavProperty: {
    someProperty: 'navProperty'
  }
};
```

Is this possible? If yes, can you give me a bit more context why you are doing it this way? It seems that this is not a single case, therefore I would be interested, whether we could / should improve our usability here.

**Comment by ja-ne** [comment]
Hi @marikaner,
thanks for the quick response.

You are right, I do not use the entity builder as you described but the `.fromJson` method of the parent entity.

For example:
```
//entityJson comes from somewhere else
const entityJson = {
  firstProperty: 'firstValue',
  toNavigationProperty: [{
      "navigationProperty": 'value'
    }]
};
const entity: MyEntity= MyEntity.builder().fromJson(entityJson);
```

Using the entity builders of both the entity "MyEntity" and the navigation property "toNavigationProperty" as you suggested the error 'entity.getCustomFields is not a function' does not occur.

I use the `.fromJson` method because

- I wrote a generic method to handle many different entities and
- the entities including their navigation properties come from somewhere else so I do not know which (optional) properties will be there

**Comment by blaart** [comment]
Hi @marikaner, 
I did not use the builder for the navigation properties either. When I do so, I do indeed no longer get the error. 
Thanks for your answer, it helped me a lot. For usability: would be nice to get a nice error when the navigation properties are not of the right type.
Regards, 
Peter

**Comment by marikaner** [comment]
Hello @ja-ne,

the `fromJson` method was fixed. The fix will be available with the next release. In case you encounter any further issues, let me know.

**Comment by ja-ne** [comment]
Hi @marikaner,

thanks, I'll soon test it.
