### ISSUE TITLE
Calling external Services from local environment in BAS SDK / SAP Delivered Support

### ISSUE THREAD

**Issue by jjtang1985** [SAP/cloud-sdk-js#949]
https://support.wdf.sap.corp/sap(bD1lbiZjPTAwMSZkPW1pbiZpPTE=)/bc/bsp/sap/crm_ui_start/default.htm?saprole=ZCSSINTPROCE&crm-object-type=CRM_SRQM_INCIDENT&crm-object-keyname=OBJECT_GUID&crm-object-value=0090FAE68F161EDB98A872897223A10A

**Comment by FrankEssenberger** [comment]
I have tested it E2E and you can connect to an onPrem system via BAS connectivity proxy with basic and even principal propagation. I adjusted also the guide to show how this is done:

https://sap.github.io/cloud-sdk/docs/js/guides/bas-external-system#principal-propagation
